# Per-Day Sampled Scatter Decoding Orchestrator — Patient Speech

Combines the per-day structure of `scat_classifier_sampled_nocv_filtered_speech_per_day.ipynb`
with the patient-speech filtering of `scat_classifier_sampled_nocv_filtered_patient_speech.ipynb`.

Words must pass **both** criteria:
1. **Quality-filtered** (`{patient}_word_df_filtered.csv`)
2. **Patient-speaking** (`{patient}_transcripts_annotated.csv` — LR-ASD marks segment as patient speech)

One SLURM job is submitted per *(patient, date, resample)* triplet.  
Outputs land in `{vad_root}/{patient}/standard_decoding_analysis/scat_xgboost_sampled_norm_patient_per_day/{date}/`.

**`REUSE_PATIENT_CONSENSUS = True`** (default): borrows hyperparameters from the already-finished
patient-level run (`scat_xgboost_sampled_norm_filtered_patient`) and skips the 3-resample hyper-search per day,
going straight to the 20-resample fixed-params stage.  
Set to `False` to run the full two-phase search independently for each day.

### 1. Imports

In [1]:
import json
import subprocess
from pathlib import Path

import dill as pickle
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)

### 2. Configuration

In [2]:
# ── Paths ─────────────────────────────────────────────────────────────────────────────────
PATIENTS    = ['YEY', 'YEZ', 'YFA', 'YFB', 'YFC', 'YFD', 'YFE', 'YFF', 'YFG',
               'YFI', 'YFK', 'YFL', 'YFM', 'YFN', 'YFP', 'YFQ', 'YFR', 'YFT', 'YFU', 'YFV']

VAD_ROOT    = Path('/mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new')
LEGACY_ROOT = Path('/mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_out')

BASE_RUN_NAME         = 'scat_xgboost_sampled_norm_patient_per_day'
PATIENT_CONSENSUS_RUN = 'scat_xgboost_sampled_norm_filtered_patient'   # source of borrowed params

CLUSTER_PREDS_OVERRIDE = {}
FRS_PATH_OVERRIDE      = {}

# ── Day-partition settings ────────────────────────────────────────────────────────────────
LOCAL_TZ           = 'America/Chicago'
ACTIVE_HOURS_START = 9
ACTIVE_HOURS_END   = 23
MIN_WORDS_PER_DAY  = 200

# ── Two-phase strategy ────────────────────────────────────────────────────────────────────
# True  → skip per-day hyperparameter search; borrow consensus from the patient-level run
# False → run full 3+17 pipeline independently per day
REUSE_PATIENT_CONSENSUS = False

N_RESAMPLES  = 20
FIRST_STAGE  = [0, 1, 2]
SECOND_STAGE = list(range(3, N_RESAMPLES))
SEED_STRIDE  = 42

PYTHON_BIN  = '/scratch/tahaismail424/miniforge3/envs/speech_247_env/bin/python3'
WORKER_PATH = Path('/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!'
                   '/standard_decoding_analysis/scat_classifier_worker.py')

PARTITION = 'Universal'
QOS       = 'big_batch_tier'
CPUS      = 8
MEM       = '40G'
TIME      = '48:00:00'

TEST_SIZE    = 0.2
SEARCH_ITERS = 40
CV_SPLITS    = 4
N_SHUFFLES   = 50
SCORING      = 'f1_macro'
PERM_METRIC  = 'f1_macro'

print('patients:', PATIENTS)
print('worker:', WORKER_PATH)
print(f'active hours: {ACTIVE_HOURS_START}:00 – {ACTIVE_HOURS_END}:00 {LOCAL_TZ}')
print(f'reuse patient consensus: {REUSE_PATIENT_CONSENSUS}')

patients: ['YEY', 'YEZ', 'YFA', 'YFB', 'YFC', 'YFD', 'YFE', 'YFF', 'YFG', 'YFI', 'YFK', 'YFL', 'YFM', 'YFN', 'YFP', 'YFQ', 'YFR', 'YFT', 'YFU', 'YFV']
worker: /scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py
active hours: 9:00 – 23:00 America/Chicago
reuse patient consensus: False

### 3. Compute & Save Per-Day Patient-Speech Word Indices Per Patient

In [3]:
def compute_day_indices(patient: str) -> 'dict[str, Path]':
    """
    Load quality-filtered word df, intersect with patient-speaking segments,
    group by local calendar date within active hours, and save one .npy index
    file per day.  Returns {date_str: path}.
    """
    patient_root  = VAD_ROOT / patient
    filtered_csv  = patient_root / f'{patient}_word_df_filtered.csv'
    annotated_csv = patient_root / f'{patient}_transcripts_annotated.csv'

    if not filtered_csv.exists():
        print(f'  [{patient}] missing {filtered_csv.name}')
        return {}
    if not annotated_csv.exists():
        print(f'  [{patient}] missing {annotated_csv.name} — run add_video_diarization_df.ipynb first')
        return {}

    df           = pd.read_csv(filtered_csv, usecols=['original_word_idx', 'utc_word_start'])
    annotated_df = pd.read_csv(annotated_csv, index_col=0)

    patient_speaking = annotated_df['patient_speaking'].astype(bool)
    df['patient_speaking'] = patient_speaking.reindex(df['original_word_idx']).values
    df = df[df['patient_speaking'] == True].copy()

    if df.empty:
        print(f'  [{patient}] no patient-speaking words after quality filter')
        return {}

    df['utc_word_start'] = pd.to_datetime(df['utc_word_start'], utc=True)
    df['local_dt'] = df['utc_word_start'].dt.tz_convert(LOCAL_TZ)
    df['hour']     = df['local_dt'].dt.hour
    df['date_str'] = df['local_dt'].dt.strftime('%Y-%m-%d')

    active = df[(df['hour'] >= ACTIVE_HOURS_START) & (df['hour'] < ACTIVE_HOURS_END)]

    day_paths = {}
    for date_str, grp in active.groupby('date_str'):
        if len(grp) < MIN_WORDS_PER_DAY:
            print(f'  [{patient}] {date_str}: only {len(grp)} patient-speech words — skipping')
            continue
        idx_dir  = patient_root / 'standard_decoding_analysis' / BASE_RUN_NAME / date_str
        idx_dir.mkdir(parents=True, exist_ok=True)
        idx_path = idx_dir / f'{patient}_{date_str}_word_idx.npy'
        word_idx = grp['original_word_idx'].values.astype(np.int64)
        np.save(idx_path, word_idx)
        day_paths[date_str] = idx_path
        print(f'  [{patient}] {date_str}: {len(word_idx):,} patient-speech words → {idx_path.name}')

    return day_paths


print(f'Computing per-day patient-speech word indices for {len(PATIENTS)} patients...\n')
patient_day_idx_paths = {}
for patient in PATIENTS:
    day_paths = compute_day_indices(patient)
    if day_paths:
        patient_day_idx_paths[patient] = day_paths

total_pairs = sum(len(v) for v in patient_day_idx_paths.values())
print(f'\nTotal (patient, day) pairs ready: {total_pairs}')

Computing per-day patient-speech word indices for 20 patients...

  [YEY] missing YEY_transcripts_annotated.csv — run add_video_diarization_df.ipynb first
  [YEZ] missing YEZ_transcripts_annotated.csv — run add_video_diarization_df.ipynb first
  [YFA] missing YFA_transcripts_annotated.csv — run add_video_diarization_df.ipynb first
  [YFB] missing YFB_transcripts_annotated.csv — run add_video_diarization_df.ipynb first
  [YFC] 2024-07-20: 693 patient-speech words → YFC_2024-07-20_word_idx.npy
  [YFC] 2024-07-21: 1,963 patient-speech words → YFC_2024-07-21_word_idx.npy
  [YFC] 2024-07-22: 2,265 patient-speech words → YFC_2024-07-22_word_idx.npy
  [YFC] 2024-07-23: 2,427 patient-speech words → YFC_2024-07-23_word_idx.npy
  [YFC] 2024-07-24: 3,959 patient-speech words → YFC_2024-07-24_word_idx.npy
  [YFC] 2024-07-25: 4,340 patient-speech words → YFC_2024-07-25_word_idx.npy
  [YFC] 2024-07-26: 1,641 patient-speech words → YFC_2024-07-26_word_idx.npy
  [YFD] 2024-07-30: 209 patient-speech words → YFD_2024-07-30_word_idx.npy
  [YFD] 2024-07-31: only 184 patient-speech words — skipping
  [YFD] 2024-08-01: 1,213 patient-speech words → YFD_2024-08-01_word_idx.npy
  [YFD] 2024-08-02: 5,275 patient-speech words → YFD_2024-08-02_word_idx.npy
  [YFD] 2024-08-03: 7,090 patient-speech words → YFD_2024-08-03_word_idx.npy
  [YFE] 2024-08-13: 514 patient-speech words → YFE_2024-08-13_word_idx.npy
  [YFE] 2024-08-14: 1,184 patient-speech words → YFE_2024-08-14_word_idx.npy
  [YFE] 2024-08-15: 387 patient-speech words → YFE_2024-08-15_word_idx.npy
  [YFE] 2024-08-16: 1,742 patient-speech words → YFE_2024-08-16_word_idx.npy
  [YFF] 2024-08-21: 549 patient-speech words → YFF_2024-08-21_word_idx.npy
  [YFF] 2024-08-22: 252 patient-speech words → YFF_2024-08-22_word_idx.npy
  [YFF] 2024-08-23: 3,755 patient-speech words → YFF_2024-08-23_word_idx.npy
  [YFF] 2024-08-24: 1,616 patient-speech words → YFF_2024-08-24_word_idx.npy
  [YFF] 2024-08-25: 672 patient-speech words → YFF_2024-08-25_word_idx.npy
  [YFF] 2024-08-26: 1,400 patient-speech words → YFF_2024-08-26_word_idx.npy
  [YFF] 2024-08-27: 990 patient-speech words → YFF_2024-08-27_word_idx.npy
  [YFF] 2024-08-28: 1,508 patient-speech words → YFF_2024-08-28_word_idx.npy
  [YFG] 2024-09-25: only 12 patient-speech words — skipping
  [YFG] 2024-09-26: only 8 patient-speech words — skipping
  [YFG] 2024-09-27: only 9 patient-speech words — skipping
  [YFI] 2024-10-15: only 85 patient-speech words — skipping
  [YFI] 2024-10-16: 1,782 patient-speech words → YFI_2024-10-16_word_idx.npy
  [YFI] 2024-10-17: only 111 patient-speech words — skipping
  [YFI] 2024-10-18: 645 patient-speech words → YFI_2024-10-18_word_idx.npy
  [YFI] 2024-10-19: 1,071 patient-speech words → YFI_2024-10-19_word_idx.npy
  [YFI] 2024-10-20: 1,289 patient-speech words → YFI_2024-10-20_word_idx.npy
  [YFI] 2024-10-21: 847 patient-speech words → YFI_2024-10-21_word_idx.npy
  [YFK] 2025-02-12: 251 patient-speech words → YFK_2025-02-12_word_idx.npy
  [YFK] 2025-02-13: 8,232 patient-speech words → YFK_2025-02-13_word_idx.npy
  [YFK] 2025-02-14: only 53 patient-speech words — skipping
  [YFK] 2025-02-15: only 8 patient-speech words — skipping
  [YFL] missing YFL_transcripts_annotated.csv — run add_video_diarization_df.ipynb first
  [YFM] 2025-03-11: only 90 patient-speech words — skipping
  [YFM] 2025-03-12: only 69 patient-speech words — skipping
  [YFM] 2025-03-13: 1,436 patient-speech words → YFM_2025-03-13_word_idx.npy
  [YFM] 2025-03-15: only 20 patient-speech words — skipping
  [YFM] 2025-03-18: only 14 patient-speech words — skipping
  [YFN] 2025-04-01: only 8 patient-speech words — skipping
  [YFN] 2025-04-04: only 4 patient-speech words — skipping
  [YFN] 2025-04-05: only 6 patient-speech words — skipping
  [YFP] 2025-05-06: 316 patient-speech words → YFP_2025-05-06_word_idx.npy
  [YFP] 2025-05-07: 3,936 patient-speech words → YFP_2025-05-07_word_idx.npy
  [YFP] 2025-05-08: 929 patient-speech words → YFP_2025-05-08_word_idx.npy
  [YFP] 2025-05-09: 627 patient-speech words → YFP_2025-05-09_word_idx.npy
  [YFP] 2025-05-10: 898 patient-speech words → YFP_2025-05-10_word_idx.npy
  [YFP] 2025-05-11: 245 patient-speech words → YFP_2025-05-11_word_idx.npy
  [YFP] 2025-05-12: 2,035 patient-speech words → YFP_2025-05-12_word_idx.npy
  [YFP] 2025-05-13: only 105 patient-speech words — skipping
  [YFP] 2025-05-14: only 145 patient-speech words — skipping
  [YFP] 2025-05-15: only 26 patient-speech words — skipping
  [YFP] 2025-05-16: 495 patient-speech words → YFP_2025-05-16_word_idx.npy
  [YFQ] 2025-06-14: 3,337 patient-speech words → YFQ_2025-06-14_word_idx.npy
  [YFQ] 2025-06-15: 376 patient-speech words → YFQ_2025-06-15_word_idx.npy
  [YFQ] 2025-06-16: only 177 patient-speech words — skipping
  [YFQ] 2025-06-17: 241 patient-speech words → YFQ_2025-06-17_word_idx.npy
  [YFQ] 2025-06-18: 1,165 patient-speech words → YFQ_2025-06-18_word_idx.npy
  [YFR] 2025-07-01: 425 patient-speech words → YFR_2025-07-01_word_idx.npy
  [YFR] 2025-07-02: 1,189 patient-speech words → YFR_2025-07-02_word_idx.npy
  [YFR] 2025-07-03: only 126 patient-speech words — skipping
  [YFR] 2025-07-04: only 149 patient-speech words — skipping
  [YFR] 2025-07-05: 368 patient-speech words → YFR_2025-07-05_word_idx.npy
  [YFR] 2025-07-06: only 121 patient-speech words — skipping
  [YFR] 2025-07-07: only 69 patient-speech words — skipping
  [YFT] 2025-07-29: 4,723 patient-speech words → YFT_2025-07-29_word_idx.npy
  [YFT] 2025-07-30: 11,471 patient-speech words → YFT_2025-07-30_word_idx.npy
  [YFT] 2025-07-31: 3,352 patient-speech words → YFT_2025-07-31_word_idx.npy
  [YFT] 2025-08-01: only 60 patient-speech words — skipping
  [YFT] 2025-08-02: 384 patient-speech words → YFT_2025-08-02_word_idx.npy
  [YFT] 2025-08-03: only 8 patient-speech words — skipping
  [YFU] 2025-12-09: only 17 patient-speech words — skipping
  [YFU] 2025-12-10: 201 patient-speech words → YFU_2025-12-10_word_idx.npy
  [YFU] 2025-12-11: only 46 patient-speech words — skipping
  [YFU] 2025-12-12: 205 patient-speech words → YFU_2025-12-12_word_idx.npy
  [YFU] 2025-12-13: 384 patient-speech words → YFU_2025-12-13_word_idx.npy
  [YFU] 2025-12-14: 863 patient-speech words → YFU_2025-12-14_word_idx.npy
  [YFU] 2025-12-15: 647 patient-speech words → YFU_2025-12-15_word_idx.npy
  [YFU] 2025-12-16: 250 patient-speech words → YFU_2025-12-16_word_idx.npy
  [YFU] 2025-12-17: 238 patient-speech words → YFU_2025-12-17_word_idx.npy
  [YFU] 2025-12-18: 216 patient-speech words → YFU_2025-12-18_word_idx.npy
  [YFV] 2026-02-17: 491 patient-speech words → YFV_2026-02-17_word_idx.npy
  [YFV] 2026-02-18: only 59 patient-speech words — skipping
  [YFV] 2026-02-19: 303 patient-speech words → YFV_2026-02-19_word_idx.npy
  [YFV] 2026-02-20: 8,279 patient-speech words → YFV_2026-02-20_word_idx.npy

Total (patient, day) pairs ready: 61

### 4. Path Resolution & Consensus-Params Helpers

In [4]:
def first_existing(paths):
    for p in paths:
        if p is not None and Path(p).exists():
            return Path(p)
    return None


def resolve_patient_neural_inputs(patient: str) -> dict:
    root = VAD_ROOT / patient
    cluster_override = CLUSTER_PREDS_OVERRIDE.get(patient)
    frs_override     = FRS_PATH_OVERRIDE.get(patient)

    new_clusters = first_existing([root / 'embeddings' / 'semantic_cluster_predictions.npy'])
    new_frs = first_existing([
        root / 'neural_embeddings' / 'word_frs.npy',
        root / 'all_convo_recording' / 'word_avg_frs.npy',
    ])
    legacy_frs = first_existing([LEGACY_ROOT / patient / 'all_convo_recording' / 'word_avg_frs.npy'])

    if cluster_override is not None or frs_override is not None:
        cluster_preds_path = first_existing([cluster_override, new_clusters])
        frs_path           = first_existing([frs_override, new_frs, legacy_frs])
    elif new_clusters is not None and new_frs is not None:
        cluster_preds_path = new_clusters
        frs_path           = new_frs
    else:
        cluster_preds_path = None
        frs_path           = None

    return {'cluster_preds_path': cluster_preds_path, 'frs_path': frs_path}


def patient_consensus_path(patient: str) -> 'Path | None':
    """Return existing consensus params from the base patient-level run, if present."""
    p = VAD_ROOT / patient / 'standard_decoding_analysis' / PATIENT_CONSENSUS_RUN / 'consensus_best_params.json'
    return p if p.exists() else None


def choose_consensus_params(param_options: list) -> dict:
    params = dict(param_options[0])
    params['max_depth']        = int(np.min([p['max_depth'] for p in param_options]))
    params['min_child_weight'] = int(np.max([p['min_child_weight'] for p in param_options]))
    params['gamma']            = float(np.max([p['gamma'] for p in param_options]))
    params['reg_lambda']       = float(np.max([p['reg_lambda'] for p in param_options]))
    params['reg_alpha']        = float(np.max([p['reg_alpha'] for p in param_options]))
    params['subsample']        = float(np.median([p['subsample'] for p in param_options]))
    params['colsample_bytree'] = float(np.median([p['colsample_bytree'] for p in param_options]))
    params['learning_rate']    = float(np.median([p['learning_rate'] for p in param_options]))
    params['n_estimators']     = int(np.median([p['n_estimators'] for p in param_options]))
    params['tree_method'] = 'hist'
    params['device'] = 'cpu'
    params.pop('predictor', None)
    params.pop('use_label_encoder', None)
    return params

### 5. Build Status Table

In [5]:
def resample_paths(out_root: Path, r: int) -> dict:
    return {
        'pkl':              out_root / f'scat_sampled_resample_{r}_.pkl',
        'summary_json':     out_root / f'summary_resample_{r}.json',
        'best_params_json': out_root / f'best_params_resample_{r}.json',
        'success':          out_root / f'resample_{r}_SUCCESS',
        'error':            out_root / f'resample_{r}_error.txt',
    }


def build_status_df() -> pd.DataFrame:
    rows = []
    for patient in PATIENTS:
        neural = resolve_patient_neural_inputs(patient)
        day_idx_map = patient_day_idx_paths.get(patient, {})
        borrowed_consensus = patient_consensus_path(patient) if REUSE_PATIENT_CONSENSUS else None

        for date_str, word_idx_path in day_idx_map.items():
            out_root = VAD_ROOT / patient / 'standard_decoding_analysis' / BASE_RUN_NAME / date_str
            out_root.mkdir(parents=True, exist_ok=True)
            consensus_json = out_root / 'consensus_best_params.json'
            has_inputs = (neural['cluster_preds_path'] is not None
                         and neural['frs_path'] is not None)

            # When reusing patient consensus, copy it into the day output dir if not there yet
            if REUSE_PATIENT_CONSENSUS and borrowed_consensus is not None and not consensus_json.exists():
                consensus_json.write_text(borrowed_consensus.read_text())

            consensus_ready = consensus_json.exists()

            if REUSE_PATIENT_CONSENSUS:
                effective_first_stage  = []
                effective_second_stage = list(range(N_RESAMPLES))
            else:
                effective_first_stage  = FIRST_STAGE
                effective_second_stage = SECOND_STAGE

            first_three_done = all(
                (out_root / f'resample_{r}_SUCCESS').exists()
                for r in effective_first_stage
            ) if effective_first_stage else True

            for r in range(N_RESAMPLES):
                paths = resample_paths(out_root, r)
                rows.append({
                    'patient':             patient,
                    'date':                date_str,
                    'resample_idx':        r,
                    'stage':               'hyperparam' if r in effective_first_stage else 'fixed',
                    'seed':                r * SEED_STRIDE,
                    'cluster_preds_path':  neural['cluster_preds_path'],
                    'frs_path':            neural['frs_path'],
                    'word_idx_path':       word_idx_path,
                    'has_inputs':          has_inputs,
                    'out_root':            out_root,
                    'consensus_json':      consensus_json,
                    'consensus_ready':     consensus_ready,
                    'first_three_done':    first_three_done,
                    'pkl_path':            paths['pkl'],
                    'summary_json':        paths['summary_json'],
                    'best_params_json':    paths['best_params_json'],
                    'success_path':        paths['success'],
                    'error_path':          paths['error'],
                    'has_pkl':             paths['pkl'].exists(),
                    'has_success':         paths['success'].exists(),
                    'has_error':           paths['error'].exists(),
                    'ready_phase1':        (has_inputs and r in effective_first_stage
                                          and not paths['success'].exists()),
                    'ready_phase2':        (has_inputs and r in effective_second_stage
                                          and first_three_done and consensus_ready
                                          and not paths['success'].exists()),
                })
    return pd.DataFrame(rows).sort_values(['patient', 'date', 'resample_idx']).reset_index(drop=True)


status_df = build_status_df()
print(f'total rows (patient × day × resample): {len(status_df)}')
print(f'has inputs:      {int(status_df["has_inputs"].sum())}')
print(f'consensus ready: {int(status_df["consensus_ready"].sum())}')
print(f'completed:       {int(status_df["has_success"].sum())}')
print(f'errors:          {int(status_df["has_error"].sum())}')
print(f'ready_phase1:    {int(status_df["ready_phase1"].sum())}')
print(f'ready_phase2:    {int(status_df["ready_phase2"].sum())}')
status_df[['patient','date','resample_idx','stage','has_inputs','consensus_ready',
           'has_success','has_error','ready_phase1','ready_phase2']].head(40)

total rows (patient × day × resample): 1220
has inputs:      1220
consensus ready: 0
completed:       84
errors:          99
ready_phase1:    99
ready_phase2:    0

,patient,date,resample_idx,stage,has_inputs,consensus_ready,has_success,has_error,ready_phase1,ready_phase2
0,YFC,2024-07-20,0,hyperparam,True,False,False,True,True,False
1,YFC,2024-07-20,1,hyperparam,True,False,False,True,True,False
2,YFC,2024-07-20,2,hyperparam,True,False,False,True,True,False
3,YFC,2024-07-20,3,fixed,True,False,False,False,False,False
4,YFC,2024-07-20,4,fixed,True,False,False,False,False,False
5,YFC,2024-07-20,5,fixed,True,False,False,False,False,False
6,YFC,2024-07-20,6,fixed,True,False,False,False,False,False
7,YFC,2024-07-20,7,fixed,True,False,False,False,False,False
8,YFC,2024-07-20,8,fixed,True,False,False,False,False,False
9,YFC,2024-07-20,9,fixed,True,False,False,False,False,False
10,YFC,2024-07-20,10,fixed,True,False,False,False,False,False
11,YFC,2024-07-20,11,fixed,True,False,False,False,False,False
12,YFC,2024-07-20,12,fixed,True,False,False,False,False,False
13,YFC,2024-07-20,13,fixed,True,False,False,False,False,False
14,YFC,2024-07-20,14,fixed,True,False,False,False,False,False
15,YFC,2024-07-20,15,fixed,True,False,False,False,False,False
16,YFC,2024-07-20,16,fixed,True,False,False,False,False,False
17,YFC,2024-07-20,17,fixed,True,False,False,False,False,False
18,YFC,2024-07-20,18,fixed,True,False,False,False,False,False
19,YFC,2024-07-20,19,fixed,True,False,False,False,False,False
20,YFC,2024-07-21,0,hyperparam,True,False,True,False,False,False
21,YFC,2024-07-21,1,hyperparam,True,False,True,False,False,False
22,YFC,2024-07-21,2,hyperparam,True,False,True,False,False,False
23,YFC,2024-07-21,3,fixed,True,False,False,False,False,False
24,YFC,2024-07-21,4,fixed,True,False,False,False,False,False
25,YFC,2024-07-21,5,fixed,True,False,False,False,False,False
26,YFC,2024-07-21,6,fixed,True,False,False,False,False,False
27,YFC,2024-07-21,7,fixed,True,False,False,False,False,False
28,YFC,2024-07-21,8,fixed,True,False,False,False,False,False
29,YFC,2024-07-21,9,fixed,True,False,False,False,False,False
30,YFC,2024-07-21,10,fixed,True,False,False,False,False,False
31,YFC,2024-07-21,11,fixed,True,False,False,False,False,False
32,YFC,2024-07-21,12,fixed,True,False,False,False,False,False
33,YFC,2024-07-21,13,fixed,True,False,False,False,False,False
34,YFC,2024-07-21,14,fixed,True,False,False,False,False,False
35,YFC,2024-07-21,15,fixed,True,False,False,False,False,False
36,YFC,2024-07-21,16,fixed,True,False,False,False,False,False
37,YFC,2024-07-21,17,fixed,True,False,False,False,False,False
38,YFC,2024-07-21,18,fixed,True,False,False,False,False,False
39,YFC,2024-07-21,19,fixed,True,False,False,False,False,False

### 6. Patient × Day Input Summary

In [6]:
pair_df = (
    status_df.drop_duplicates(subset=['patient', 'date'])
    [['patient', 'date', 'has_inputs', 'consensus_ready', 'cluster_preds_path', 'frs_path', 'word_idx_path']]
    .sort_values(['patient', 'date'])
    .reset_index(drop=True)
)
print(f'{len(pair_df)} (patient, day) pairs')
display(pair_df)

61 (patient, day) pairs

,patient,date,has_inputs,consensus_ready,cluster_preds_path,frs_path,word_idx_path
0,YFC,2024-07-20,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
1,YFC,2024-07-21,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
2,YFC,2024-07-22,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
3,YFC,2024-07-23,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
4,YFC,2024-07-24,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
5,YFC,2024-07-25,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
6,YFC,2024-07-26,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
7,YFD,2024-07-30,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
8,YFD,2024-08-01,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
9,YFD,2024-08-02,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
10,YFD,2024-08-03,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
11,YFE,2024-08-13,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
12,YFE,2024-08-14,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
13,YFE,2024-08-15,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
14,YFE,2024-08-16,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
15,YFF,2024-08-21,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
16,YFF,2024-08-22,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
17,YFF,2024-08-23,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
18,YFF,2024-08-24,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
19,YFF,2024-08-25,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
20,YFF,2024-08-26,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
21,YFF,2024-08-27,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
22,YFF,2024-08-28,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
23,YFI,2024-10-16,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
24,YFI,2024-10-18,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
25,YFI,2024-10-19,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
26,YFI,2024-10-20,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
27,YFI,2024-10-21,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
28,YFK,2025-02-12,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
29,YFK,2025-02-13,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
30,YFM,2025-03-13,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
31,YFP,2025-05-06,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
32,YFP,2025-05-07,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
33,YFP,2025-05-08,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
34,YFP,2025-05-09,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
35,YFP,2025-05-10,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
36,YFP,2025-05-11,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
37,YFP,2025-05-12,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
38,YFP,2025-05-16,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
39,YFQ,2025-06-14,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
40,YFQ,2025-06-15,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
41,YFQ,2025-06-17,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
42,YFQ,2025-06-18,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
43,YFR,2025-07-01,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
44,YFR,2025-07-02,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
45,YFR,2025-07-05,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
46,YFT,2025-07-29,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
47,YFT,2025-07-30,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
48,YFT,2025-07-31,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
49,YFT,2025-08-02,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
50,YFU,2025-12-10,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
51,YFU,2025-12-12,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
52,YFU,2025-12-13,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
53,YFU,2025-12-14,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
54,YFU,2025-12-15,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
55,YFU,2025-12-16,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
56,YFU,2025-12-17,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
57,YFU,2025-12-18,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
58,YFV,2026-02-17,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
59,YFV,2026-02-19,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
60,YFV,2026-02-20,True,False,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...

### 7a. Submit Phase-1 Jobs  
*(Only runs if `REUSE_PATIENT_CONSENSUS = False`; otherwise `ready_phase1` is always empty.)*

In [7]:
DRY_RUN = False

submitted = []
failed    = []

for _, row in status_df[status_df['ready_phase1']].iterrows():
    patient  = row['patient']
    date_str = row['date']
    r        = int(row['resample_idx'])
    logs_dir    = row['out_root'] / 'slurm_logs'
    scripts_dir = row['out_root'] / 'slurm_scripts'
    logs_dir.mkdir(parents=True, exist_ok=True)
    scripts_dir.mkdir(parents=True, exist_ok=True)

    word_idx_arg = f'--word-idx-path "{row["word_idx_path"]}"' if row['word_idx_path'] else ''
    sbatch_text = f"""#!/bin/bash
#SBATCH --job-name=scat_pspd_{patient}_{date_str}_{r}
#SBATCH --partition={PARTITION}
#SBATCH --qos={QOS}
#SBATCH --cpus-per-task={CPUS}
#SBATCH --mem={MEM}
#SBATCH --time={TIME}
#SBATCH --output={logs_dir}/{patient}_{date_str}_r{r}_%j.out
#SBATCH --error={logs_dir}/{patient}_{date_str}_r{r}_%j.err

set -eo pipefail
echo "HOSTNAME: $(hostname)"
echo "START: $(date)"
echo "PATIENT: {patient}"
echo "DATE: {date_str}"
echo "RESAMPLE: {r}"

{PYTHON_BIN} {WORKER_PATH} \\
  --patient {patient} \\
  --resample-idx {r} \\
  --cluster-preds-path "{row['cluster_preds_path']}" \\
  --frs-path "{row['frs_path']}" \\
  --out-dir "{row['out_root']}" \\
  {word_idx_arg} \\
  --test-size {TEST_SIZE} \\
  --n-iter {SEARCH_ITERS} \\
  --cv-splits {CV_SPLITS} \\
  --n-shuffles {N_SHUFFLES} \\
  --seed-stride {SEED_STRIDE} \\
  --n-jobs {CPUS * 2} \\
  --scoring {SCORING} \\
  --perm-metric {PERM_METRIC}

echo "END: $(date)"
"""
    sbatch_path = scripts_dir / f'{patient}_{date_str}_resample_{r}.sbatch'
    sbatch_path.write_text(sbatch_text)

    if DRY_RUN:
        submitted.append((patient, date_str, r, 'dry-run'))
        print(f'dry-run: {patient} {date_str} r={r}')
    else:
        try:
            res = subprocess.run(['sbatch', str(sbatch_path)], capture_output=True, text=True, check=True)
            submitted.append((patient, date_str, r, res.stdout.strip()))
            print(f'submitted: {patient} {date_str} r={r} -> {res.stdout.strip()}')
        except subprocess.CalledProcessError as exc:
            failed.append((patient, date_str, r, exc.stderr.strip()))
            print(f'FAILED: {patient} {date_str} r={r}\n{exc.stderr}')

print(f'phase-1 submitted={len(submitted)}, failed={len(failed)}')

submitted: YFC 2024-07-20 r=0 -> Submitted batch job 295621
submitted: YFC 2024-07-20 r=1 -> Submitted batch job 295622
submitted: YFC 2024-07-20 r=2 -> Submitted batch job 295623
submitted: YFD 2024-07-30 r=0 -> Submitted batch job 295624
submitted: YFD 2024-07-30 r=1 -> Submitted batch job 295625
submitted: YFD 2024-07-30 r=2 -> Submitted batch job 295626
submitted: YFE 2024-08-13 r=0 -> Submitted batch job 295627
submitted: YFE 2024-08-13 r=1 -> Submitted batch job 295628
submitted: YFE 2024-08-13 r=2 -> Submitted batch job 295629
submitted: YFE 2024-08-14 r=0 -> Submitted batch job 295630
submitted: YFE 2024-08-14 r=1 -> Submitted batch job 295631
submitted: YFE 2024-08-14 r=2 -> Submitted batch job 295632
submitted: YFE 2024-08-15 r=0 -> Submitted batch job 295633
submitted: YFE 2024-08-15 r=1 -> Submitted batch job 295634
submitted: YFE 2024-08-15 r=2 -> Submitted batch job 295635
submitted: YFF 2024-08-21 r=0 -> Submitted batch job 295636
submitted: YFF 2024-08-21 r=1 -> Submitted batch job 295637
submitted: YFF 2024-08-21 r=2 -> Submitted batch job 295638
submitted: YFF 2024-08-22 r=0 -> Submitted batch job 295639
submitted: YFF 2024-08-22 r=1 -> Submitted batch job 295640
submitted: YFF 2024-08-22 r=2 -> Submitted batch job 295641
submitted: YFF 2024-08-25 r=0 -> Submitted batch job 295642
submitted: YFF 2024-08-25 r=1 -> Submitted batch job 295643
submitted: YFF 2024-08-25 r=2 -> Submitted batch job 295644
submitted: YFI 2024-10-18 r=0 -> Submitted batch job 295645
submitted: YFI 2024-10-18 r=1 -> Submitted batch job 295646
submitted: YFI 2024-10-18 r=2 -> Submitted batch job 295647
submitted: YFI 2024-10-19 r=0 -> Submitted batch job 295648
submitted: YFI 2024-10-19 r=1 -> Submitted batch job 295649
submitted: YFI 2024-10-19 r=2 -> Submitted batch job 295650
submitted: YFI 2024-10-20 r=0 -> Submitted batch job 295651
submitted: YFI 2024-10-20 r=1 -> Submitted batch job 295652
submitted: YFI 2024-10-20 r=2 -> Submitted batch job 295653
submitted: YFI 2024-10-21 r=0 -> Submitted batch job 295654
submitted: YFI 2024-10-21 r=1 -> Submitted batch job 295655
submitted: YFI 2024-10-21 r=2 -> Submitted batch job 295656
submitted: YFK 2025-02-12 r=0 -> Submitted batch job 295657
submitted: YFK 2025-02-12 r=1 -> Submitted batch job 295658
submitted: YFK 2025-02-12 r=2 -> Submitted batch job 295659
submitted: YFP 2025-05-08 r=0 -> Submitted batch job 295660
submitted: YFP 2025-05-08 r=1 -> Submitted batch job 295661
submitted: YFP 2025-05-08 r=2 -> Submitted batch job 295662
submitted: YFP 2025-05-09 r=0 -> Submitted batch job 295663
submitted: YFP 2025-05-09 r=1 -> Submitted batch job 295664
submitted: YFP 2025-05-09 r=2 -> Submitted batch job 295665
submitted: YFP 2025-05-10 r=0 -> Submitted batch job 295666
submitted: YFP 2025-05-10 r=1 -> Submitted batch job 295667
submitted: YFP 2025-05-10 r=2 -> Submitted batch job 295668
submitted: YFP 2025-05-11 r=0 -> Submitted batch job 295669
submitted: YFP 2025-05-11 r=1 -> Submitted batch job 295670
submitted: YFP 2025-05-11 r=2 -> Submitted batch job 295671
submitted: YFP 2025-05-12 r=0 -> Submitted batch job 295672
submitted: YFP 2025-05-12 r=1 -> Submitted batch job 295673
submitted: YFP 2025-05-12 r=2 -> Submitted batch job 295674
submitted: YFP 2025-05-16 r=0 -> Submitted batch job 295675
submitted: YFP 2025-05-16 r=1 -> Submitted batch job 295676
submitted: YFP 2025-05-16 r=2 -> Submitted batch job 295677
submitted: YFQ 2025-06-15 r=0 -> Submitted batch job 295678
submitted: YFQ 2025-06-15 r=1 -> Submitted batch job 295679
submitted: YFQ 2025-06-15 r=2 -> Submitted batch job 295680
submitted: YFQ 2025-06-17 r=0 -> Submitted batch job 295681
submitted: YFQ 2025-06-17 r=1 -> Submitted batch job 295682
submitted: YFQ 2025-06-17 r=2 -> Submitted batch job 295683
submitted: YFR 2025-07-01 r=0 -> Submitted batch job 295684
submitted: YFR 2025-07-01 r=1 -> Submitted batch job 295685
submitted: YFR 2025-07-01 r=2 -> Submitted batch job 295686
submitted: YFR 2025-07-02 r=0 -> Submitted batch job 295687
submitted: YFR 2025-07-02 r=1 -> Submitted batch job 295688
submitted: YFR 2025-07-02 r=2 -> Submitted batch job 295689
submitted: YFR 2025-07-05 r=0 -> Submitted batch job 295690
submitted: YFR 2025-07-05 r=1 -> Submitted batch job 295691
submitted: YFR 2025-07-05 r=2 -> Submitted batch job 295692
submitted: YFU 2025-12-10 r=0 -> Submitted batch job 295693
submitted: YFU 2025-12-10 r=1 -> Submitted batch job 295694
submitted: YFU 2025-12-10 r=2 -> Submitted batch job 295695
submitted: YFU 2025-12-12 r=0 -> Submitted batch job 295696
submitted: YFU 2025-12-12 r=1 -> Submitted batch job 295697
submitted: YFU 2025-12-12 r=2 -> Submitted batch job 295698
submitted: YFU 2025-12-13 r=0 -> Submitted batch job 295699
submitted: YFU 2025-12-13 r=1 -> Submitted batch job 295700
submitted: YFU 2025-12-13 r=2 -> Submitted batch job 295701
submitted: YFU 2025-12-15 r=0 -> Submitted batch job 295702
submitted: YFU 2025-12-15 r=1 -> Submitted batch job 295703
submitted: YFU 2025-12-15 r=2 -> Submitted batch job 295704
submitted: YFU 2025-12-16 r=0 -> Submitted batch job 295705
submitted: YFU 2025-12-16 r=1 -> Submitted batch job 295706
submitted: YFU 2025-12-16 r=2 -> Submitted batch job 295707
submitted: YFU 2025-12-17 r=0 -> Submitted batch job 295708
submitted: YFU 2025-12-17 r=1 -> Submitted batch job 295709
submitted: YFU 2025-12-17 r=2 -> Submitted batch job 295710
submitted: YFU 2025-12-18 r=0 -> Submitted batch job 295711
submitted: YFU 2025-12-18 r=1 -> Submitted batch job 295712
submitted: YFU 2025-12-18 r=2 -> Submitted batch job 295713
submitted: YFV 2026-02-17 r=0 -> Submitted batch job 295714
submitted: YFV 2026-02-17 r=1 -> Submitted batch job 295715
submitted: YFV 2026-02-17 r=2 -> Submitted batch job 295716
submitted: YFV 2026-02-19 r=0 -> Submitted batch job 295717
submitted: YFV 2026-02-19 r=1 -> Submitted batch job 295718
submitted: YFV 2026-02-19 r=2 -> Submitted batch job 295719
phase-1 submitted=99, failed=0

### 7b. Build Per-Day Consensus Params  
*(Only needed if `REUSE_PATIENT_CONSENSUS = False`; otherwise consensus was copied in the status step.)*

In [8]:
if not REUSE_PATIENT_CONSENSUS:
    built   = []
    blocked = []
    for (patient, date_str), grp in status_df.groupby(['patient', 'date']):
        out_root       = grp.iloc[0]['out_root']
        consensus_json = grp.iloc[0]['consensus_json']
        if consensus_json.exists():
            print(f'consensus already exists: {patient} {date_str}')
            continue
        first_three = grp[grp['resample_idx'].isin(FIRST_STAGE)]
        if not bool(first_three['has_success'].all()):
            blocked.append((patient, date_str))
            continue
        param_options = []
        for r in FIRST_STAGE:
            path = out_root / f'best_params_resample_{r}.json'
            param_options.append(json.loads(path.read_text()))
        consensus = choose_consensus_params(param_options)
        consensus_json.write_text(json.dumps(consensus, indent=2))
        built.append((patient, date_str))
        print(f'built consensus: {patient} {date_str}')
    print('built:', len(built), '  blocked:', len(blocked))
else:
    print('REUSE_PATIENT_CONSENSUS=True — consensus already copied during status build.')

built consensus: YFC 2024-07-21
built consensus: YFC 2024-07-22
built consensus: YFC 2024-07-23
built consensus: YFC 2024-07-24
built consensus: YFC 2024-07-25
built consensus: YFC 2024-07-26
built consensus: YFD 2024-08-01
built consensus: YFD 2024-08-02
built consensus: YFD 2024-08-03
built consensus: YFE 2024-08-16
built consensus: YFF 2024-08-23
built consensus: YFF 2024-08-24
built consensus: YFF 2024-08-26
built consensus: YFF 2024-08-27
built consensus: YFF 2024-08-28
built consensus: YFI 2024-10-16
built consensus: YFK 2025-02-13
built consensus: YFM 2025-03-13
built consensus: YFP 2025-05-06
built consensus: YFP 2025-05-07
built consensus: YFQ 2025-06-14
built consensus: YFQ 2025-06-18
built consensus: YFT 2025-07-29
built consensus: YFT 2025-07-30
built consensus: YFT 2025-07-31
built consensus: YFT 2025-08-02
built consensus: YFU 2025-12-14
built consensus: YFV 2026-02-20
built: 28   blocked: 33

### 7c. Submit Phase-2 (Fixed-Params) Jobs

In [9]:
DRY_RUN = False

# Refresh status after any consensus files were written
status_df = build_status_df()

submitted = []
failed    = []

for _, row in status_df[status_df['ready_phase2']].iterrows():
    patient  = row['patient']
    date_str = row['date']
    r        = int(row['resample_idx'])
    logs_dir    = row['out_root'] / 'slurm_logs'
    scripts_dir = row['out_root'] / 'slurm_scripts'
    logs_dir.mkdir(parents=True, exist_ok=True)
    scripts_dir.mkdir(parents=True, exist_ok=True)

    word_idx_arg = f'--word-idx-path "{row["word_idx_path"]}"' if row['word_idx_path'] else ''
    sbatch_text = f"""#!/bin/bash
#SBATCH --job-name=scat_pspd_{patient}_{date_str}_{r}
#SBATCH --partition={PARTITION}
#SBATCH --qos={QOS}
#SBATCH --cpus-per-task={CPUS}
#SBATCH --mem={MEM}
#SBATCH --time={TIME}
#SBATCH --output={logs_dir}/{patient}_{date_str}_r{r}_%j.out
#SBATCH --error={logs_dir}/{patient}_{date_str}_r{r}_%j.err

set -eo pipefail
echo "HOSTNAME: $(hostname)"
echo "START: $(date)"
echo "PATIENT: {patient}"
echo "DATE: {date_str}"
echo "RESAMPLE: {r}"

{PYTHON_BIN} {WORKER_PATH} \\
  --patient {patient} \\
  --resample-idx {r} \\
  --cluster-preds-path "{row['cluster_preds_path']}" \\
  --frs-path "{row['frs_path']}" \\
  --out-dir "{row['out_root']}" \\
  --params-json "{row['consensus_json']}" \\
  {word_idx_arg} \\
  --test-size {TEST_SIZE} \\
  --n-iter {SEARCH_ITERS} \\
  --cv-splits {CV_SPLITS} \\
  --n-shuffles {N_SHUFFLES} \\
  --seed-stride {SEED_STRIDE} \\
  --n-jobs {CPUS * 2} \\
  --scoring {SCORING} \\
  --perm-metric {PERM_METRIC}

echo "END: $(date)"
"""
    sbatch_path = scripts_dir / f'{patient}_{date_str}_resample_{r}.sbatch'
    sbatch_path.write_text(sbatch_text)

    if DRY_RUN:
        submitted.append((patient, date_str, r, 'dry-run'))
        print(f'dry-run: {patient} {date_str} r={r}')
    else:
        try:
            res = subprocess.run(['sbatch', str(sbatch_path)], capture_output=True, text=True, check=True)
            submitted.append((patient, date_str, r, res.stdout.strip()))
            print(f'submitted: {patient} {date_str} r={r} -> {res.stdout.strip()}')
        except subprocess.CalledProcessError as exc:
            failed.append((patient, date_str, r, exc.stderr.strip()))
            print(f'FAILED: {patient} {date_str} r={r}\n{exc.stderr}')

print(f'phase-2 submitted={len(submitted)}, failed={len(failed)}')

submitted: YFC 2024-07-21 r=3 -> Submitted batch job 295720
submitted: YFC 2024-07-21 r=4 -> Submitted batch job 295721
submitted: YFC 2024-07-21 r=5 -> Submitted batch job 295722
submitted: YFC 2024-07-21 r=6 -> Submitted batch job 295723
submitted: YFC 2024-07-21 r=7 -> Submitted batch job 295724
submitted: YFC 2024-07-21 r=8 -> Submitted batch job 295725
submitted: YFC 2024-07-21 r=9 -> Submitted batch job 295726
submitted: YFC 2024-07-21 r=10 -> Submitted batch job 295727
submitted: YFC 2024-07-21 r=11 -> Submitted batch job 295728
submitted: YFC 2024-07-21 r=12 -> Submitted batch job 295729
submitted: YFC 2024-07-21 r=13 -> Submitted batch job 295730
submitted: YFC 2024-07-21 r=14 -> Submitted batch job 295731
submitted: YFC 2024-07-21 r=15 -> Submitted batch job 295732
submitted: YFC 2024-07-21 r=16 -> Submitted batch job 295733
submitted: YFC 2024-07-21 r=17 -> Submitted batch job 295734
submitted: YFC 2024-07-21 r=18 -> Submitted batch job 295735
submitted: YFC 2024-07-21 r=19 -> Submitted batch job 295736
submitted: YFC 2024-07-22 r=3 -> Submitted batch job 295737
submitted: YFC 2024-07-22 r=4 -> Submitted batch job 295738
submitted: YFC 2024-07-22 r=5 -> Submitted batch job 295739
submitted: YFC 2024-07-22 r=6 -> Submitted batch job 295740
submitted: YFC 2024-07-22 r=7 -> Submitted batch job 295741
submitted: YFC 2024-07-22 r=8 -> Submitted batch job 295742
submitted: YFC 2024-07-22 r=9 -> Submitted batch job 295743
submitted: YFC 2024-07-22 r=10 -> Submitted batch job 295744
submitted: YFC 2024-07-22 r=11 -> Submitted batch job 295745
submitted: YFC 2024-07-22 r=12 -> Submitted batch job 295746
submitted: YFC 2024-07-22 r=13 -> Submitted batch job 295747
submitted: YFC 2024-07-22 r=14 -> Submitted batch job 295748
submitted: YFC 2024-07-22 r=15 -> Submitted batch job 295749
submitted: YFC 2024-07-22 r=16 -> Submitted batch job 295750
submitted: YFC 2024-07-22 r=17 -> Submitted batch job 295751
submitted: YFC 2024-07-22 r=18 -> Submitted batch job 295752
submitted: YFC 2024-07-22 r=19 -> Submitted batch job 295753
submitted: YFC 2024-07-23 r=3 -> Submitted batch job 295754
submitted: YFC 2024-07-23 r=4 -> Submitted batch job 295755
submitted: YFC 2024-07-23 r=5 -> Submitted batch job 295756
submitted: YFC 2024-07-23 r=6 -> Submitted batch job 295757
submitted: YFC 2024-07-23 r=7 -> Submitted batch job 295758
submitted: YFC 2024-07-23 r=8 -> Submitted batch job 295759
submitted: YFC 2024-07-23 r=9 -> Submitted batch job 295760
submitted: YFC 2024-07-23 r=10 -> Submitted batch job 295761
submitted: YFC 2024-07-23 r=11 -> Submitted batch job 295762
submitted: YFC 2024-07-23 r=12 -> Submitted batch job 295763
submitted: YFC 2024-07-23 r=13 -> Submitted batch job 295764
submitted: YFC 2024-07-23 r=14 -> Submitted batch job 295765
submitted: YFC 2024-07-23 r=15 -> Submitted batch job 295766
submitted: YFC 2024-07-23 r=16 -> Submitted batch job 295767
submitted: YFC 2024-07-23 r=17 -> Submitted batch job 295768
submitted: YFC 2024-07-23 r=18 -> Submitted batch job 295769
submitted: YFC 2024-07-23 r=19 -> Submitted batch job 295770
submitted: YFC 2024-07-24 r=3 -> Submitted batch job 295771
submitted: YFC 2024-07-24 r=4 -> Submitted batch job 295772
submitted: YFC 2024-07-24 r=5 -> Submitted batch job 295773
submitted: YFC 2024-07-24 r=6 -> Submitted batch job 295774
submitted: YFC 2024-07-24 r=7 -> Submitted batch job 295775
submitted: YFC 2024-07-24 r=8 -> Submitted batch job 295776
submitted: YFC 2024-07-24 r=9 -> Submitted batch job 295777
submitted: YFC 2024-07-24 r=10 -> Submitted batch job 295778
submitted: YFC 2024-07-24 r=11 -> Submitted batch job 295779
submitted: YFC 2024-07-24 r=12 -> Submitted batch job 295780
submitted: YFC 2024-07-24 r=13 -> Submitted batch job 295781
submitted: YFC 2024-07-24 r=14 -> Submitted batch job 295782
submitted: YFC 2024-07-24 r=15 -> Submitted batch job 295783
submitted: YFC 2024-07-24 r=16 -> Submitted batch job 295784
submitted: YFC 2024-07-24 r=17 -> Submitted batch job 295785
submitted: YFC 2024-07-24 r=18 -> Submitted batch job 295786
submitted: YFC 2024-07-24 r=19 -> Submitted batch job 295787
submitted: YFC 2024-07-25 r=3 -> Submitted batch job 295788
submitted: YFC 2024-07-25 r=4 -> Submitted batch job 295789
submitted: YFC 2024-07-25 r=5 -> Submitted batch job 295790
submitted: YFC 2024-07-25 r=6 -> Submitted batch job 295791
submitted: YFC 2024-07-25 r=7 -> Submitted batch job 295792
submitted: YFC 2024-07-25 r=8 -> Submitted batch job 295793
submitted: YFC 2024-07-25 r=9 -> Submitted batch job 295794
submitted: YFC 2024-07-25 r=10 -> Submitted batch job 295795
submitted: YFC 2024-07-25 r=11 -> Submitted batch job 295796
submitted: YFC 2024-07-25 r=12 -> Submitted batch job 295797
submitted: YFC 2024-07-25 r=13 -> Submitted batch job 295798
submitted: YFC 2024-07-25 r=14 -> Submitted batch job 295799
submitted: YFC 2024-07-25 r=15 -> Submitted batch job 295800
submitted: YFC 2024-07-25 r=16 -> Submitted batch job 295801
submitted: YFC 2024-07-25 r=17 -> Submitted batch job 295802
submitted: YFC 2024-07-25 r=18 -> Submitted batch job 295803
submitted: YFC 2024-07-25 r=19 -> Submitted batch job 295804
submitted: YFC 2024-07-26 r=3 -> Submitted batch job 295805
submitted: YFC 2024-07-26 r=4 -> Submitted batch job 295806
submitted: YFC 2024-07-26 r=5 -> Submitted batch job 295807
submitted: YFC 2024-07-26 r=6 -> Submitted batch job 295808
submitted: YFC 2024-07-26 r=7 -> Submitted batch job 295809
submitted: YFC 2024-07-26 r=8 -> Submitted batch job 295810
submitted: YFC 2024-07-26 r=9 -> Submitted batch job 295811
submitted: YFC 2024-07-26 r=10 -> Submitted batch job 295812
submitted: YFC 2024-07-26 r=11 -> Submitted batch job 295813
submitted: YFC 2024-07-26 r=12 -> Submitted batch job 295814
submitted: YFC 2024-07-26 r=13 -> Submitted batch job 295815
submitted: YFC 2024-07-26 r=14 -> Submitted batch job 295816
submitted: YFC 2024-07-26 r=15 -> Submitted batch job 295817
submitted: YFC 2024-07-26 r=16 -> Submitted batch job 295818
submitted: YFC 2024-07-26 r=17 -> Submitted batch job 295819
submitted: YFC 2024-07-26 r=18 -> Submitted batch job 295820
submitted: YFC 2024-07-26 r=19 -> Submitted batch job 295821
submitted: YFD 2024-08-01 r=3 -> Submitted batch job 295822
submitted: YFD 2024-08-01 r=4 -> Submitted batch job 295823
submitted: YFD 2024-08-01 r=5 -> Submitted batch job 295824
submitted: YFD 2024-08-01 r=6 -> Submitted batch job 295825
submitted: YFD 2024-08-01 r=7 -> Submitted batch job 295826
submitted: YFD 2024-08-01 r=8 -> Submitted batch job 295827
submitted: YFD 2024-08-01 r=9 -> Submitted batch job 295828
submitted: YFD 2024-08-01 r=10 -> Submitted batch job 295829
submitted: YFD 2024-08-01 r=11 -> Submitted batch job 295830
submitted: YFD 2024-08-01 r=12 -> Submitted batch job 295831
submitted: YFD 2024-08-01 r=13 -> Submitted batch job 295832
submitted: YFD 2024-08-01 r=14 -> Submitted batch job 295833
submitted: YFD 2024-08-01 r=15 -> Submitted batch job 295834
submitted: YFD 2024-08-01 r=16 -> Submitted batch job 295835
submitted: YFD 2024-08-01 r=17 -> Submitted batch job 295836
submitted: YFD 2024-08-01 r=18 -> Submitted batch job 295837
submitted: YFD 2024-08-01 r=19 -> Submitted batch job 295838
submitted: YFD 2024-08-02 r=3 -> Submitted batch job 295839
submitted: YFD 2024-08-02 r=4 -> Submitted batch job 295840
submitted: YFD 2024-08-02 r=5 -> Submitted batch job 295841
submitted: YFD 2024-08-02 r=6 -> Submitted batch job 295842
submitted: YFD 2024-08-02 r=7 -> Submitted batch job 295843
submitted: YFD 2024-08-02 r=8 -> Submitted batch job 295844
submitted: YFD 2024-08-02 r=9 -> Submitted batch job 295845
submitted: YFD 2024-08-02 r=10 -> Submitted batch job 295846
submitted: YFD 2024-08-02 r=11 -> Submitted batch job 295847
submitted: YFD 2024-08-02 r=12 -> Submitted batch job 295848
submitted: YFD 2024-08-02 r=13 -> Submitted batch job 295849
submitted: YFD 2024-08-02 r=14 -> Submitted batch job 295850
submitted: YFD 2024-08-02 r=15 -> Submitted batch job 295851
submitted: YFD 2024-08-02 r=16 -> Submitted batch job 295852
submitted: YFD 2024-08-02 r=17 -> Submitted batch job 295853
submitted: YFD 2024-08-02 r=18 -> Submitted batch job 295854
submitted: YFD 2024-08-02 r=19 -> Submitted batch job 295855
submitted: YFD 2024-08-03 r=3 -> Submitted batch job 295856
submitted: YFD 2024-08-03 r=4 -> Submitted batch job 295857
submitted: YFD 2024-08-03 r=5 -> Submitted batch job 295858
submitted: YFD 2024-08-03 r=6 -> Submitted batch job 295859
submitted: YFD 2024-08-03 r=7 -> Submitted batch job 295860
submitted: YFD 2024-08-03 r=8 -> Submitted batch job 295861
submitted: YFD 2024-08-03 r=9 -> Submitted batch job 295862
submitted: YFD 2024-08-03 r=10 -> Submitted batch job 295863
submitted: YFD 2024-08-03 r=11 -> Submitted batch job 295864
submitted: YFD 2024-08-03 r=12 -> Submitted batch job 295865
submitted: YFD 2024-08-03 r=13 -> Submitted batch job 295866
submitted: YFD 2024-08-03 r=14 -> Submitted batch job 295867
submitted: YFD 2024-08-03 r=15 -> Submitted batch job 295868
submitted: YFD 2024-08-03 r=16 -> Submitted batch job 295869
submitted: YFD 2024-08-03 r=17 -> Submitted batch job 295870
submitted: YFD 2024-08-03 r=18 -> Submitted batch job 295871
submitted: YFD 2024-08-03 r=19 -> Submitted batch job 295872
submitted: YFE 2024-08-16 r=3 -> Submitted batch job 295873
submitted: YFE 2024-08-16 r=4 -> Submitted batch job 295874
submitted: YFE 2024-08-16 r=5 -> Submitted batch job 295875
submitted: YFE 2024-08-16 r=6 -> Submitted batch job 295876
submitted: YFE 2024-08-16 r=7 -> Submitted batch job 295877
submitted: YFE 2024-08-16 r=8 -> Submitted batch job 295878
submitted: YFE 2024-08-16 r=9 -> Submitted batch job 295879
submitted: YFE 2024-08-16 r=10 -> Submitted batch job 295880
submitted: YFE 2024-08-16 r=11 -> Submitted batch job 295881
submitted: YFE 2024-08-16 r=12 -> Submitted batch job 295882
submitted: YFE 2024-08-16 r=13 -> Submitted batch job 295883
submitted: YFE 2024-08-16 r=14 -> Submitted batch job 295884
submitted: YFE 2024-08-16 r=15 -> Submitted batch job 295885
submitted: YFE 2024-08-16 r=16 -> Submitted batch job 295886
submitted: YFE 2024-08-16 r=17 -> Submitted batch job 295887
submitted: YFE 2024-08-16 r=18 -> Submitted batch job 295888
submitted: YFE 2024-08-16 r=19 -> Submitted batch job 295889
submitted: YFF 2024-08-23 r=3 -> Submitted batch job 295890
submitted: YFF 2024-08-23 r=4 -> Submitted batch job 295891
submitted: YFF 2024-08-23 r=5 -> Submitted batch job 295892
submitted: YFF 2024-08-23 r=6 -> Submitted batch job 295893
submitted: YFF 2024-08-23 r=7 -> Submitted batch job 295894
submitted: YFF 2024-08-23 r=8 -> Submitted batch job 295895
submitted: YFF 2024-08-23 r=9 -> Submitted batch job 295896
submitted: YFF 2024-08-23 r=10 -> Submitted batch job 295897
submitted: YFF 2024-08-23 r=11 -> Submitted batch job 295898
submitted: YFF 2024-08-23 r=12 -> Submitted batch job 295899
submitted: YFF 2024-08-23 r=13 -> Submitted batch job 295900
submitted: YFF 2024-08-23 r=14 -> Submitted batch job 295901
submitted: YFF 2024-08-23 r=15 -> Submitted batch job 295902
submitted: YFF 2024-08-23 r=16 -> Submitted batch job 295903
submitted: YFF 2024-08-23 r=17 -> Submitted batch job 295904
submitted: YFF 2024-08-23 r=18 -> Submitted batch job 295905
submitted: YFF 2024-08-23 r=19 -> Submitted batch job 295906
submitted: YFF 2024-08-24 r=3 -> Submitted batch job 295907
submitted: YFF 2024-08-24 r=4 -> Submitted batch job 295908
submitted: YFF 2024-08-24 r=5 -> Submitted batch job 295909
submitted: YFF 2024-08-24 r=6 -> Submitted batch job 295910
submitted: YFF 2024-08-24 r=7 -> Submitted batch job 295911
submitted: YFF 2024-08-24 r=8 -> Submitted batch job 295912
submitted: YFF 2024-08-24 r=9 -> Submitted batch job 295913
submitted: YFF 2024-08-24 r=10 -> Submitted batch job 295914
submitted: YFF 2024-08-24 r=11 -> Submitted batch job 295915
submitted: YFF 2024-08-24 r=12 -> Submitted batch job 295916
submitted: YFF 2024-08-24 r=13 -> Submitted batch job 295917
submitted: YFF 2024-08-24 r=14 -> Submitted batch job 295918
submitted: YFF 2024-08-24 r=15 -> Submitted batch job 295919
submitted: YFF 2024-08-24 r=16 -> Submitted batch job 295920
submitted: YFF 2024-08-24 r=17 -> Submitted batch job 295921
submitted: YFF 2024-08-24 r=18 -> Submitted batch job 295922
submitted: YFF 2024-08-24 r=19 -> Submitted batch job 295923
submitted: YFF 2024-08-26 r=3 -> Submitted batch job 295924
submitted: YFF 2024-08-26 r=4 -> Submitted batch job 295925
submitted: YFF 2024-08-26 r=5 -> Submitted batch job 295926
submitted: YFF 2024-08-26 r=6 -> Submitted batch job 295927
submitted: YFF 2024-08-26 r=7 -> Submitted batch job 295928
submitted: YFF 2024-08-26 r=8 -> Submitted batch job 295929
submitted: YFF 2024-08-26 r=9 -> Submitted batch job 295930
submitted: YFF 2024-08-26 r=10 -> Submitted batch job 295931
submitted: YFF 2024-08-26 r=11 -> Submitted batch job 295932
submitted: YFF 2024-08-26 r=12 -> Submitted batch job 295933
submitted: YFF 2024-08-26 r=13 -> Submitted batch job 295934
submitted: YFF 2024-08-26 r=14 -> Submitted batch job 295935
submitted: YFF 2024-08-26 r=15 -> Submitted batch job 295936
submitted: YFF 2024-08-26 r=16 -> Submitted batch job 295937
submitted: YFF 2024-08-26 r=17 -> Submitted batch job 295938
submitted: YFF 2024-08-26 r=18 -> Submitted batch job 295939
submitted: YFF 2024-08-26 r=19 -> Submitted batch job 295940
submitted: YFF 2024-08-27 r=3 -> Submitted batch job 295941
submitted: YFF 2024-08-27 r=4 -> Submitted batch job 295942
submitted: YFF 2024-08-27 r=5 -> Submitted batch job 295943
submitted: YFF 2024-08-27 r=6 -> Submitted batch job 295944
submitted: YFF 2024-08-27 r=7 -> Submitted batch job 295945
submitted: YFF 2024-08-27 r=8 -> Submitted batch job 295946
submitted: YFF 2024-08-27 r=9 -> Submitted batch job 295947
submitted: YFF 2024-08-27 r=10 -> Submitted batch job 295948
submitted: YFF 2024-08-27 r=11 -> Submitted batch job 295949
submitted: YFF 2024-08-27 r=12 -> Submitted batch job 295950
submitted: YFF 2024-08-27 r=13 -> Submitted batch job 295951
submitted: YFF 2024-08-27 r=14 -> Submitted batch job 295952
submitted: YFF 2024-08-27 r=15 -> Submitted batch job 295953
submitted: YFF 2024-08-27 r=16 -> Submitted batch job 295954
submitted: YFF 2024-08-27 r=17 -> Submitted batch job 295955
submitted: YFF 2024-08-27 r=18 -> Submitted batch job 295956
submitted: YFF 2024-08-27 r=19 -> Submitted batch job 295957
submitted: YFF 2024-08-28 r=3 -> Submitted batch job 295958
submitted: YFF 2024-08-28 r=4 -> Submitted batch job 295959
submitted: YFF 2024-08-28 r=5 -> Submitted batch job 295960
submitted: YFF 2024-08-28 r=6 -> Submitted batch job 295961
submitted: YFF 2024-08-28 r=7 -> Submitted batch job 295962
submitted: YFF 2024-08-28 r=8 -> Submitted batch job 295963
submitted: YFF 2024-08-28 r=9 -> Submitted batch job 295964
submitted: YFF 2024-08-28 r=10 -> Submitted batch job 295965
submitted: YFF 2024-08-28 r=11 -> Submitted batch job 295966
submitted: YFF 2024-08-28 r=12 -> Submitted batch job 295967
submitted: YFF 2024-08-28 r=13 -> Submitted batch job 295968
submitted: YFF 2024-08-28 r=14 -> Submitted batch job 295969
submitted: YFF 2024-08-28 r=15 -> Submitted batch job 295970
submitted: YFF 2024-08-28 r=16 -> Submitted batch job 295971
submitted: YFF 2024-08-28 r=17 -> Submitted batch job 295972
submitted: YFF 2024-08-28 r=18 -> Submitted batch job 295973
submitted: YFF 2024-08-28 r=19 -> Submitted batch job 295974
submitted: YFI 2024-10-16 r=3 -> Submitted batch job 295975
submitted: YFI 2024-10-16 r=4 -> Submitted batch job 295976
submitted: YFI 2024-10-16 r=5 -> Submitted batch job 295977
submitted: YFI 2024-10-16 r=6 -> Submitted batch job 295978
submitted: YFI 2024-10-16 r=7 -> Submitted batch job 295979
submitted: YFI 2024-10-16 r=8 -> Submitted batch job 295980
submitted: YFI 2024-10-16 r=9 -> Submitted batch job 295981
submitted: YFI 2024-10-16 r=10 -> Submitted batch job 295982
submitted: YFI 2024-10-16 r=11 -> Submitted batch job 295983
submitted: YFI 2024-10-16 r=12 -> Submitted batch job 295984
submitted: YFI 2024-10-16 r=13 -> Submitted batch job 295985
submitted: YFI 2024-10-16 r=14 -> Submitted batch job 295986
submitted: YFI 2024-10-16 r=15 -> Submitted batch job 295987
submitted: YFI 2024-10-16 r=16 -> Submitted batch job 295988
submitted: YFI 2024-10-16 r=17 -> Submitted batch job 295989
submitted: YFI 2024-10-16 r=18 -> Submitted batch job 295990
submitted: YFI 2024-10-16 r=19 -> Submitted batch job 295991
submitted: YFK 2025-02-13 r=3 -> Submitted batch job 295992
submitted: YFK 2025-02-13 r=4 -> Submitted batch job 295993
submitted: YFK 2025-02-13 r=5 -> Submitted batch job 295994
submitted: YFK 2025-02-13 r=6 -> Submitted batch job 295995
submitted: YFK 2025-02-13 r=7 -> Submitted batch job 295996
submitted: YFK 2025-02-13 r=8 -> Submitted batch job 295997
submitted: YFK 2025-02-13 r=9 -> Submitted batch job 295998
submitted: YFK 2025-02-13 r=10 -> Submitted batch job 295999
submitted: YFK 2025-02-13 r=11 -> Submitted batch job 296000
submitted: YFK 2025-02-13 r=12 -> Submitted batch job 296001
submitted: YFK 2025-02-13 r=13 -> Submitted batch job 296002
submitted: YFK 2025-02-13 r=14 -> Submitted batch job 296003
submitted: YFK 2025-02-13 r=15 -> Submitted batch job 296004
submitted: YFK 2025-02-13 r=16 -> Submitted batch job 296005
submitted: YFK 2025-02-13 r=17 -> Submitted batch job 296006
submitted: YFK 2025-02-13 r=18 -> Submitted batch job 296007
submitted: YFK 2025-02-13 r=19 -> Submitted batch job 296008
submitted: YFM 2025-03-13 r=3 -> Submitted batch job 296009
submitted: YFM 2025-03-13 r=4 -> Submitted batch job 296010
submitted: YFM 2025-03-13 r=5 -> Submitted batch job 296011
submitted: YFM 2025-03-13 r=6 -> Submitted batch job 296012
submitted: YFM 2025-03-13 r=7 -> Submitted batch job 296013
submitted: YFM 2025-03-13 r=8 -> Submitted batch job 296014
submitted: YFM 2025-03-13 r=9 -> Submitted batch job 296015
submitted: YFM 2025-03-13 r=10 -> Submitted batch job 296016
submitted: YFM 2025-03-13 r=11 -> Submitted batch job 296017
submitted: YFM 2025-03-13 r=12 -> Submitted batch job 296018
submitted: YFM 2025-03-13 r=13 -> Submitted batch job 296019
submitted: YFM 2025-03-13 r=14 -> Submitted batch job 296020
submitted: YFM 2025-03-13 r=15 -> Submitted batch job 296021
submitted: YFM 2025-03-13 r=16 -> Submitted batch job 296022
submitted: YFM 2025-03-13 r=17 -> Submitted batch job 296023
submitted: YFM 2025-03-13 r=18 -> Submitted batch job 296024
submitted: YFM 2025-03-13 r=19 -> Submitted batch job 296025
submitted: YFP 2025-05-06 r=3 -> Submitted batch job 296026
submitted: YFP 2025-05-06 r=4 -> Submitted batch job 296027
submitted: YFP 2025-05-06 r=5 -> Submitted batch job 296028
submitted: YFP 2025-05-06 r=6 -> Submitted batch job 296029
submitted: YFP 2025-05-06 r=7 -> Submitted batch job 296030
submitted: YFP 2025-05-06 r=8 -> Submitted batch job 296031
submitted: YFP 2025-05-06 r=9 -> Submitted batch job 296032
submitted: YFP 2025-05-06 r=10 -> Submitted batch job 296033
submitted: YFP 2025-05-06 r=11 -> Submitted batch job 296034
submitted: YFP 2025-05-06 r=12 -> Submitted batch job 296035
submitted: YFP 2025-05-06 r=13 -> Submitted batch job 296036
submitted: YFP 2025-05-06 r=14 -> Submitted batch job 296037
submitted: YFP 2025-05-06 r=15 -> Submitted batch job 296038
submitted: YFP 2025-05-06 r=16 -> Submitted batch job 296039
submitted: YFP 2025-05-06 r=17 -> Submitted batch job 296040
submitted: YFP 2025-05-06 r=18 -> Submitted batch job 296041
submitted: YFP 2025-05-06 r=19 -> Submitted batch job 296042
submitted: YFP 2025-05-07 r=3 -> Submitted batch job 296043
submitted: YFP 2025-05-07 r=4 -> Submitted batch job 296044
submitted: YFP 2025-05-07 r=5 -> Submitted batch job 296045
submitted: YFP 2025-05-07 r=6 -> Submitted batch job 296046
submitted: YFP 2025-05-07 r=7 -> Submitted batch job 296047
submitted: YFP 2025-05-07 r=8 -> Submitted batch job 296048
submitted: YFP 2025-05-07 r=9 -> Submitted batch job 296049

### 8. Check Status

In [ ]:
status_df = build_status_df()
pair_progress = (
    status_df.groupby(['patient', 'date'])
    .agg(
        total=('resample_idx', 'count'),
        done=('has_success', 'sum'),
        errors=('has_error', 'sum'),
    )
    .reset_index()
)
pair_progress['pct'] = (pair_progress['done'] / pair_progress['total'] * 100).round(0).astype(int)
print(f'Overall: {int(status_df["has_success"].sum())} / {len(status_df)} resamples done')
display(pair_progress)

### 9. Inspect Errors

In [ ]:
error_rows = status_df[status_df['has_error']].copy()
print(f'resamples with error files: {len(error_rows)}')
for _, row in error_rows.head(10).iterrows():
    print('=' * 100)
    print(row['patient'], row['date'], f'r={row["resample_idx"]}')
    print(row['error_path'].read_text()[:4000])

### 10. Aggregate Results Per (Patient, Day)

In [ ]:
for (patient, date_str), grp in status_df.groupby(['patient', 'date']):
    if not bool(grp['has_success'].all()):
        print(f'skipping {patient} {date_str}: not all resamples finished')
        continue

    out_root     = grp.iloc[0]['out_root']
    summary_rows = []
    aggregate    = {}
    for r in range(N_RESAMPLES):
        with open(out_root / f'summary_resample_{r}.json') as f:
            summary_rows.append(json.load(f))
        with open(out_root / f'scat_sampled_resample_{r}_.pkl', 'rb') as f:
            aggregate[f'resample_{r}'] = pickle.load(f)

    summary_df = pd.DataFrame(summary_rows).sort_values('resample_idx').reset_index(drop=True)
    agg_csv = out_root / 'scat_sampled_all_resamples.csv'
    agg_pkl = out_root / 'scat_sampled_all_resamples.pkl'
    summary_df.to_csv(agg_csv, index=False)
    with open(agg_pkl, 'wb') as f:
        pickle.dump(aggregate, f)
    print(f'aggregated {patient} {date_str} -> {agg_csv}')
    display(summary_df)