# Per-Day Sampled Scatter Decoding Orchestrator — Quality-Filtered Speech

Identical to `scat_classifier_sampled_nocv_filtered_speech.ipynb` but restricted to
words spoken within a single calendar day during **active hours** (default 09:00–23:00 local time).

One SLURM job is submitted per *(patient, date, resample)* triplet.  
Outputs land in `{vad_root}/{patient}/standard_decoding_analysis/{BASE_RUN_NAME}/{date}/`.

**`REUSE_PATIENT_CONSENSUS = True`** (default): borrows hyperparameters from the already-finished
patient-level run (`scat_xgboost_sampled_norm_filtered`) and skips the 3-resample hyper-search per day,
going straight to the 20-resample fixed-params stage.  
Set to `False` to run the full two-phase search independently for each day.

### 1. Imports

In [1]:
import json
import subprocess
from pathlib import Path

import dill as pickle
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)

### 2. Configuration

In [2]:
# ── Paths ─────────────────────────────────────────────────────────────────────
PATIENTS    = ['YEY', 'YEZ', 'YFA', 'YFB', 'YFC', 'YFD', 'YFE', 'YFF', 'YFG',
               'YFI', 'YFK', 'YFL', 'YFM', 'YFN', 'YFP', 'YFQ', 'YFR', 'YFT', 'YFU', 'YFV']

VAD_ROOT    = Path('/mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new')
LEGACY_ROOT = Path('/mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_out')

BASE_RUN_NAME          = 'scat_xgboost_sampled_norm_filtered_per_day'
PATIENT_CONSENSUS_RUN  = 'scat_xgboost_sampled_norm_filtered'   # source of borrowed params

CLUSTER_PREDS_OVERRIDE = {}
FRS_PATH_OVERRIDE      = {}

# ── Day-partition settings ────────────────────────────────────────────────────
LOCAL_TZ           = 'America/Chicago'
ACTIVE_HOURS_START = 9
ACTIVE_HOURS_END   = 23
MIN_WORDS_PER_DAY  = 200

# ── Two-phase strategy ────────────────────────────────────────────────────────
# True  → skip per-day hyperparameter search; borrow consensus from the patient-level run
# False → run full 3+17 pipeline independently per day
REUSE_PATIENT_CONSENSUS = False

N_RESAMPLES  = 20
FIRST_STAGE  = [0, 1, 2]
SECOND_STAGE = list(range(3, N_RESAMPLES))
SEED_STRIDE  = 42

PYTHON_BIN  = '/scratch/tahaismail424/miniforge3/envs/speech_247_env/bin/python3'
WORKER_PATH = Path('/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!'
                   '/standard_decoding_analysis/scat_classifier_worker.py')

PARTITION = 'Universal'
QOS       = 'big_batch_tier'
CPUS      = 8
MEM       = '40G'
TIME      = '48:00:00'

TEST_SIZE    = 0.2
SEARCH_ITERS = 40
CV_SPLITS    = 4
N_SHUFFLES   = 50
SCORING      = 'f1_macro'
PERM_METRIC  = 'f1_macro'

print('patients:', PATIENTS)
print('worker:', WORKER_PATH)
print(f'active hours: {ACTIVE_HOURS_START}:00 – {ACTIVE_HOURS_END}:00 {LOCAL_TZ}')
print(f'reuse patient consensus: {REUSE_PATIENT_CONSENSUS}')

patients: ['YEY', 'YEZ', 'YFA', 'YFB', 'YFC', 'YFD', 'YFE', 'YFF', 'YFG', 'YFI', 'YFK', 'YFL', 'YFM', 'YFN', 'YFP', 'YFQ', 'YFR', 'YFT', 'YFU', 'YFV']
worker: /scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py
active hours: 9:00 – 23:00 America/Chicago
reuse patient consensus: False

### 3. Compute & Save Per-Day Word Indices Per Patient

In [3]:
def compute_day_indices(patient: str) -> 'dict[str, Path]':
    patient_root = VAD_ROOT / patient
    filtered_csv = patient_root / f'{patient}_word_df_filtered.csv'

    if not filtered_csv.exists():
        print(f'  [{patient}] missing {filtered_csv.name}')
        return {}

    df = pd.read_csv(filtered_csv, usecols=['original_word_idx', 'utc_word_start'])
    df['utc_word_start'] = pd.to_datetime(df['utc_word_start'], utc=True)
    df['local_dt'] = df['utc_word_start'].dt.tz_convert(LOCAL_TZ)
    df['hour']     = df['local_dt'].dt.hour
    df['date_str'] = df['local_dt'].dt.strftime('%Y-%m-%d')

    active = df[(df['hour'] >= ACTIVE_HOURS_START) & (df['hour'] < ACTIVE_HOURS_END)]

    day_paths = {}
    for date_str, grp in active.groupby('date_str'):
        if len(grp) < MIN_WORDS_PER_DAY:
            print(f'  [{patient}] {date_str}: only {len(grp)} words — skipping')
            continue
        idx_dir  = patient_root / 'standard_decoding_analysis' / BASE_RUN_NAME / date_str
        idx_dir.mkdir(parents=True, exist_ok=True)
        idx_path = idx_dir / f'{patient}_{date_str}_word_idx.npy'
        word_idx = grp['original_word_idx'].values.astype(np.int64)
        np.save(idx_path, word_idx)
        day_paths[date_str] = idx_path
        print(f'  [{patient}] {date_str}: {len(word_idx):,} words → {idx_path.name}')

    return day_paths


print(f'Computing per-day word indices for {len(PATIENTS)} patients...\n')
patient_day_idx_paths = {}
for patient in PATIENTS:
    day_paths = compute_day_indices(patient)
    if day_paths:
        patient_day_idx_paths[patient] = day_paths

total_pairs = sum(len(v) for v in patient_day_idx_paths.values())
print(f'\nTotal (patient, day) pairs ready: {total_pairs}')

Computing per-day word indices for 20 patients...

  [YEY] 2024-04-01: 16,510 words → YEY_2024-04-01_word_idx.npy
  [YEY] 2024-04-02: 23,841 words → YEY_2024-04-02_word_idx.npy
  [YEZ] 2024-04-09: 6,698 words → YEZ_2024-04-09_word_idx.npy
  [YEZ] 2024-04-10: 16,464 words → YEZ_2024-04-10_word_idx.npy
  [YEZ] 2024-04-11: 1,584 words → YEZ_2024-04-11_word_idx.npy
  [YEZ] 2024-04-12: 7,996 words → YEZ_2024-04-12_word_idx.npy
  [YEZ] 2024-04-14: 18,298 words → YEZ_2024-04-14_word_idx.npy
  [YEZ] 2024-04-15: 14,595 words → YEZ_2024-04-15_word_idx.npy
  [YFA] 2024-04-23: 18,729 words → YFA_2024-04-23_word_idx.npy
  [YFA] 2024-04-24: 58,808 words → YFA_2024-04-24_word_idx.npy
  [YFA] 2024-04-25: 48,473 words → YFA_2024-04-25_word_idx.npy
  [YFA] 2024-04-26: 36,215 words → YFA_2024-04-26_word_idx.npy
  [YFA] 2024-04-27: 66,950 words → YFA_2024-04-27_word_idx.npy
  [YFA] 2024-04-28: 43,939 words → YFA_2024-04-28_word_idx.npy
  [YFA] 2024-04-29: 54,695 words → YFA_2024-04-29_word_idx.npy
  [YFA] 2024-04-30: 44,142 words → YFA_2024-04-30_word_idx.npy
  [YFA] 2024-05-01: 3,076 words → YFA_2024-05-01_word_idx.npy
  [YFB] 2024-05-02: 4,630 words → YFB_2024-05-02_word_idx.npy
  [YFB] 2024-05-03: 10,842 words → YFB_2024-05-03_word_idx.npy
  [YFB] 2024-05-04: 14,858 words → YFB_2024-05-04_word_idx.npy
  [YFB] 2024-05-05: 18,712 words → YFB_2024-05-05_word_idx.npy
  [YFB] 2024-05-06: 10,860 words → YFB_2024-05-06_word_idx.npy
  [YFB] 2024-05-07: 14,859 words → YFB_2024-05-07_word_idx.npy
  [YFB] 2024-05-08: 11,793 words → YFB_2024-05-08_word_idx.npy
  [YFB] 2024-05-09: 14,559 words → YFB_2024-05-09_word_idx.npy
  [YFB] 2024-05-10: 11,566 words → YFB_2024-05-10_word_idx.npy
  [YFC] 2024-07-18: 824 words → YFC_2024-07-18_word_idx.npy
  [YFC] 2024-07-19: 9,261 words → YFC_2024-07-19_word_idx.npy
  [YFC] 2024-07-20: 42,455 words → YFC_2024-07-20_word_idx.npy
  [YFC] 2024-07-21: 41,226 words → YFC_2024-07-21_word_idx.npy
  [YFC] 2024-07-22: 21,408 words → YFC_2024-07-22_word_idx.npy
  [YFC] 2024-07-23: 26,845 words → YFC_2024-07-23_word_idx.npy
  [YFC] 2024-07-24: 37,000 words → YFC_2024-07-24_word_idx.npy
  [YFC] 2024-07-25: 36,170 words → YFC_2024-07-25_word_idx.npy
  [YFC] 2024-07-26: 21,091 words → YFC_2024-07-26_word_idx.npy
  [YFD] 2024-07-29: 3,625 words → YFD_2024-07-29_word_idx.npy
  [YFD] 2024-07-30: 57,151 words → YFD_2024-07-30_word_idx.npy
  [YFD] 2024-07-31: 36,664 words → YFD_2024-07-31_word_idx.npy
  [YFD] 2024-08-01: 28,494 words → YFD_2024-08-01_word_idx.npy
  [YFD] 2024-08-02: 36,990 words → YFD_2024-08-02_word_idx.npy
  [YFD] 2024-08-03: 38,221 words → YFD_2024-08-03_word_idx.npy
  [YFE] 2024-08-13: 10,502 words → YFE_2024-08-13_word_idx.npy
  [YFE] 2024-08-14: 25,070 words → YFE_2024-08-14_word_idx.npy
  [YFE] 2024-08-15: 67,303 words → YFE_2024-08-15_word_idx.npy
  [YFE] 2024-08-16: 41,956 words → YFE_2024-08-16_word_idx.npy
  [YFF] 2024-08-20: 2,174 words → YFF_2024-08-20_word_idx.npy
  [YFF] 2024-08-21: 28,934 words → YFF_2024-08-21_word_idx.npy
  [YFF] 2024-08-22: 18,915 words → YFF_2024-08-22_word_idx.npy
  [YFF] 2024-08-23: 38,000 words → YFF_2024-08-23_word_idx.npy
  [YFF] 2024-08-24: 28,150 words → YFF_2024-08-24_word_idx.npy
  [YFF] 2024-08-25: 16,441 words → YFF_2024-08-25_word_idx.npy
  [YFF] 2024-08-26: 8,552 words → YFF_2024-08-26_word_idx.npy
  [YFF] 2024-08-27: 19,545 words → YFF_2024-08-27_word_idx.npy
  [YFF] 2024-08-28: 32,806 words → YFF_2024-08-28_word_idx.npy
  [YFF] 2024-08-29: 9,081 words → YFF_2024-08-29_word_idx.npy
  [YFG] 2024-09-23: 1,653 words → YFG_2024-09-23_word_idx.npy
  [YFG] 2024-09-24: 6,444 words → YFG_2024-09-24_word_idx.npy
  [YFG] 2024-09-25: 18,917 words → YFG_2024-09-25_word_idx.npy
  [YFG] 2024-09-26: 13,855 words → YFG_2024-09-26_word_idx.npy
  [YFG] 2024-09-27: 2,382 words → YFG_2024-09-27_word_idx.npy
  [YFI] 2024-10-15: 4,550 words → YFI_2024-10-15_word_idx.npy
  [YFI] 2024-10-16: 17,138 words → YFI_2024-10-16_word_idx.npy
  [YFI] 2024-10-17: 16,573 words → YFI_2024-10-17_word_idx.npy
  [YFI] 2024-10-18: 21,692 words → YFI_2024-10-18_word_idx.npy
  [YFI] 2024-10-19: 32,679 words → YFI_2024-10-19_word_idx.npy
  [YFI] 2024-10-20: 22,175 words → YFI_2024-10-20_word_idx.npy
  [YFI] 2024-10-21: 6,247 words → YFI_2024-10-21_word_idx.npy
  [YFK] 2025-02-10: 1,497 words → YFK_2025-02-10_word_idx.npy
  [YFK] 2025-02-11: 13,139 words → YFK_2025-02-11_word_idx.npy
  [YFK] 2025-02-12: 52,050 words → YFK_2025-02-12_word_idx.npy
  [YFK] 2025-02-13: 56,075 words → YFK_2025-02-13_word_idx.npy
  [YFK] 2025-02-14: 39,192 words → YFK_2025-02-14_word_idx.npy
  [YFK] 2025-02-15: 45,775 words → YFK_2025-02-15_word_idx.npy
  [YFK] 2025-02-16: 26,858 words → YFK_2025-02-16_word_idx.npy
  [YFK] 2025-02-17: 27,766 words → YFK_2025-02-17_word_idx.npy
  [YFK] 2025-02-18: 34,803 words → YFK_2025-02-18_word_idx.npy
  [YFK] 2025-02-19: only 11 words — skipping
  [YFL] 2025-02-24: only 1 words — skipping
  [YFL] 2025-02-25: only 26 words — skipping
  [YFL] 2025-02-26: only 52 words — skipping
  [YFL] 2025-02-27: only 18 words — skipping
  [YFL] 2025-02-28: 7,263 words → YFL_2025-02-28_word_idx.npy
  [YFL] 2025-03-01: 7,569 words → YFL_2025-03-01_word_idx.npy
  [YFL] 2025-03-02: 5,457 words → YFL_2025-03-02_word_idx.npy
  [YFL] 2025-03-03: 31,239 words → YFL_2025-03-03_word_idx.npy
  [YFL] 2025-03-04: 19,735 words → YFL_2025-03-04_word_idx.npy
  [YFL] 2025-03-05: 7,042 words → YFL_2025-03-05_word_idx.npy
  [YFL] 2025-03-06: 3,198 words → YFL_2025-03-06_word_idx.npy
  [YFM] 2025-03-10: 949 words → YFM_2025-03-10_word_idx.npy
  [YFM] 2025-03-11: 13,693 words → YFM_2025-03-11_word_idx.npy
  [YFM] 2025-03-12: 17,076 words → YFM_2025-03-12_word_idx.npy
  [YFM] 2025-03-13: 22,725 words → YFM_2025-03-13_word_idx.npy
  [YFM] 2025-03-14: 37,799 words → YFM_2025-03-14_word_idx.npy
  [YFM] 2025-03-15: 17,705 words → YFM_2025-03-15_word_idx.npy
  [YFM] 2025-03-16: only 28 words — skipping
  [YFM] 2025-03-17: 47,384 words → YFM_2025-03-17_word_idx.npy
  [YFM] 2025-03-18: 21,529 words → YFM_2025-03-18_word_idx.npy
  [YFM] 2025-03-19: 12,787 words → YFM_2025-03-19_word_idx.npy
  [YFN] 2025-03-31: 5,369 words → YFN_2025-03-31_word_idx.npy
  [YFN] 2025-04-01: 28,844 words → YFN_2025-04-01_word_idx.npy
  [YFN] 2025-04-02: 40,584 words → YFN_2025-04-02_word_idx.npy
  [YFN] 2025-04-03: 43,876 words → YFN_2025-04-03_word_idx.npy
  [YFN] 2025-04-04: 33,770 words → YFN_2025-04-04_word_idx.npy
  [YFN] 2025-04-05: 30,049 words → YFN_2025-04-05_word_idx.npy
  [YFN] 2025-04-06: 28,131 words → YFN_2025-04-06_word_idx.npy
  [YFP] 2025-05-06: 9,667 words → YFP_2025-05-06_word_idx.npy
  [YFP] 2025-05-07: 33,731 words → YFP_2025-05-07_word_idx.npy
  [YFP] 2025-05-08: 21,778 words → YFP_2025-05-08_word_idx.npy
  [YFP] 2025-05-09: 29,320 words → YFP_2025-05-09_word_idx.npy
  [YFP] 2025-05-10: 20,906 words → YFP_2025-05-10_word_idx.npy
  [YFP] 2025-05-11: 23,683 words → YFP_2025-05-11_word_idx.npy
  [YFP] 2025-05-12: 49,693 words → YFP_2025-05-12_word_idx.npy
  [YFP] 2025-05-13: 14,710 words → YFP_2025-05-13_word_idx.npy
  [YFP] 2025-05-14: 40,642 words → YFP_2025-05-14_word_idx.npy
  [YFP] 2025-05-15: 23,662 words → YFP_2025-05-15_word_idx.npy
  [YFP] 2025-05-16: 20,024 words → YFP_2025-05-16_word_idx.npy
  [YFQ] 2025-06-14: 28,326 words → YFQ_2025-06-14_word_idx.npy
  [YFQ] 2025-06-15: 26,051 words → YFQ_2025-06-15_word_idx.npy
  [YFQ] 2025-06-16: 32,858 words → YFQ_2025-06-16_word_idx.npy
  [YFQ] 2025-06-17: 14,240 words → YFQ_2025-06-17_word_idx.npy
  [YFQ] 2025-06-18: 28,154 words → YFQ_2025-06-18_word_idx.npy
  [YFQ] 2025-06-19: 5,820 words → YFQ_2025-06-19_word_idx.npy
  [YFR] 2025-06-30: 754 words → YFR_2025-06-30_word_idx.npy
  [YFR] 2025-07-01: 18,576 words → YFR_2025-07-01_word_idx.npy
  [YFR] 2025-07-02: 36,139 words → YFR_2025-07-02_word_idx.npy
  [YFR] 2025-07-03: 10,223 words → YFR_2025-07-03_word_idx.npy
  [YFR] 2025-07-04: 17,865 words → YFR_2025-07-04_word_idx.npy
  [YFR] 2025-07-05: 21,419 words → YFR_2025-07-05_word_idx.npy
  [YFR] 2025-07-06: 46,819 words → YFR_2025-07-06_word_idx.npy
  [YFR] 2025-07-07: 7,370 words → YFR_2025-07-07_word_idx.npy
  [YFT] 2025-07-28: 13,981 words → YFT_2025-07-28_word_idx.npy
  [YFT] 2025-07-29: 43,049 words → YFT_2025-07-29_word_idx.npy
  [YFT] 2025-07-30: 75,770 words → YFT_2025-07-30_word_idx.npy
  [YFT] 2025-07-31: 47,012 words → YFT_2025-07-31_word_idx.npy
  [YFT] 2025-08-01: 52,810 words → YFT_2025-08-01_word_idx.npy
  [YFT] 2025-08-02: 66,610 words → YFT_2025-08-02_word_idx.npy
  [YFT] 2025-08-03: 74,948 words → YFT_2025-08-03_word_idx.npy
  [YFT] 2025-08-04: 8,869 words → YFT_2025-08-04_word_idx.npy
  [YFU] 2025-12-08: 1,453 words → YFU_2025-12-08_word_idx.npy
  [YFU] 2025-12-09: 6,769 words → YFU_2025-12-09_word_idx.npy
  [YFU] 2025-12-10: 6,819 words → YFU_2025-12-10_word_idx.npy
  [YFU] 2025-12-11: 42,300 words → YFU_2025-12-11_word_idx.npy
  [YFU] 2025-12-12: 33,763 words → YFU_2025-12-12_word_idx.npy
  [YFU] 2025-12-13: 74,133 words → YFU_2025-12-13_word_idx.npy
  [YFU] 2025-12-14: 35,244 words → YFU_2025-12-14_word_idx.npy
  [YFU] 2025-12-15: 44,675 words → YFU_2025-12-15_word_idx.npy
  [YFU] 2025-12-16: 43,521 words → YFU_2025-12-16_word_idx.npy
  [YFU] 2025-12-17: 36,235 words → YFU_2025-12-17_word_idx.npy
  [YFU] 2025-12-18: 16,053 words → YFU_2025-12-18_word_idx.npy
  [YFV] 2026-02-17: 17,708 words → YFV_2026-02-17_word_idx.npy
  [YFV] 2026-02-18: 13,530 words → YFV_2026-02-18_word_idx.npy
  [YFV] 2026-02-19: 32,670 words → YFV_2026-02-19_word_idx.npy
  [YFV] 2026-02-20: 42,700 words → YFV_2026-02-20_word_idx.npy

Total (patient, day) pairs ready: 147

### 4. Path Resolution & Consensus-Params Helpers

In [4]:
def first_existing(paths):
    for p in paths:
        if p is not None and Path(p).exists():
            return Path(p)
    return None


def resolve_patient_neural_inputs(patient: str) -> dict:
    root = VAD_ROOT / patient
    cluster_override = CLUSTER_PREDS_OVERRIDE.get(patient)
    frs_override     = FRS_PATH_OVERRIDE.get(patient)

    new_clusters = first_existing([root / 'embeddings' / 'semantic_cluster_predictions.npy'])
    new_frs = first_existing([
        root / 'neural_embeddings' / 'word_frs.npy',
        root / 'all_convo_recording' / 'word_avg_frs.npy',
    ])
    legacy_frs = first_existing([LEGACY_ROOT / patient / 'all_convo_recording' / 'word_avg_frs.npy'])

    if cluster_override is not None or frs_override is not None:
        cluster_preds_path = first_existing([cluster_override, new_clusters])
        frs_path           = first_existing([frs_override, new_frs, legacy_frs])
    elif new_clusters is not None and new_frs is not None:
        cluster_preds_path = new_clusters
        frs_path           = new_frs
    else:
        cluster_preds_path = None
        frs_path           = None

    return {'cluster_preds_path': cluster_preds_path, 'frs_path': frs_path}


def patient_consensus_path(patient: str) -> 'Path | None':
    """Return existing consensus params from the base patient-level run, if present."""
    p = VAD_ROOT / patient / 'standard_decoding_analysis' / PATIENT_CONSENSUS_RUN / 'consensus_best_params.json'
    return p if p.exists() else None


def choose_consensus_params(param_options: list) -> dict:
    params = dict(param_options[0])
    params['max_depth']        = int(np.min([p['max_depth'] for p in param_options]))
    params['min_child_weight'] = int(np.max([p['min_child_weight'] for p in param_options]))
    params['gamma']            = float(np.max([p['gamma'] for p in param_options]))
    params['reg_lambda']       = float(np.max([p['reg_lambda'] for p in param_options]))
    params['reg_alpha']        = float(np.max([p['reg_alpha'] for p in param_options]))
    params['subsample']        = float(np.median([p['subsample'] for p in param_options]))
    params['colsample_bytree'] = float(np.median([p['colsample_bytree'] for p in param_options]))
    params['learning_rate']    = float(np.median([p['learning_rate'] for p in param_options]))
    params['n_estimators']     = int(np.median([p['n_estimators'] for p in param_options]))
    params['tree_method'] = 'hist'
    params['device'] = 'cpu'
    params.pop('predictor', None)
    params.pop('use_label_encoder', None)
    return params

### 5. Build Status Table

In [5]:
def resample_paths(out_root: Path, r: int) -> dict:
    return {
        'pkl':              out_root / f'scat_sampled_resample_{r}_.pkl',
        'summary_json':     out_root / f'summary_resample_{r}.json',
        'best_params_json': out_root / f'best_params_resample_{r}.json',
        'success':          out_root / f'resample_{r}_SUCCESS',
        'error':            out_root / f'resample_{r}_error.txt',
    }


def build_status_df() -> pd.DataFrame:
    rows = []
    for patient in PATIENTS:
        neural = resolve_patient_neural_inputs(patient)
        day_idx_map = patient_day_idx_paths.get(patient, {})
        borrowed_consensus = patient_consensus_path(patient) if REUSE_PATIENT_CONSENSUS else None

        for date_str, word_idx_path in day_idx_map.items():
            out_root = VAD_ROOT / patient / 'standard_decoding_analysis' / BASE_RUN_NAME / date_str
            out_root.mkdir(parents=True, exist_ok=True)
            consensus_json = out_root / 'consensus_best_params.json'
            has_inputs = (neural['cluster_preds_path'] is not None
                         and neural['frs_path'] is not None)

            # When reusing patient consensus, copy it into the day output dir if not there yet
            if REUSE_PATIENT_CONSENSUS and borrowed_consensus is not None and not consensus_json.exists():
                consensus_json.write_text(borrowed_consensus.read_text())

            consensus_ready = consensus_json.exists()

            # Which resamples to run:
            # - REUSE_PATIENT_CONSENSUS=True  → all 20 go directly to fixed-params stage
            # - REUSE_PATIENT_CONSENSUS=False → normal 3+17 flow
            if REUSE_PATIENT_CONSENSUS:
                effective_first_stage  = []
                effective_second_stage = list(range(N_RESAMPLES))
            else:
                effective_first_stage  = FIRST_STAGE
                effective_second_stage = SECOND_STAGE

            first_three_done = all(
                (out_root / f'resample_{r}_SUCCESS').exists()
                for r in effective_first_stage
            ) if effective_first_stage else True

            for r in range(N_RESAMPLES):
                paths = resample_paths(out_root, r)
                rows.append({
                    'patient':             patient,
                    'date':                date_str,
                    'resample_idx':        r,
                    'stage':               'hyperparam' if r in effective_first_stage else 'fixed',
                    'seed':                r * SEED_STRIDE,
                    'cluster_preds_path':  neural['cluster_preds_path'],
                    'frs_path':            neural['frs_path'],
                    'word_idx_path':       word_idx_path,
                    'has_inputs':          has_inputs,
                    'out_root':            out_root,
                    'consensus_json':      consensus_json,
                    'consensus_ready':     consensus_ready,
                    'first_three_done':    first_three_done,
                    'pkl_path':            paths['pkl'],
                    'summary_json':        paths['summary_json'],
                    'best_params_json':    paths['best_params_json'],
                    'success_path':        paths['success'],
                    'error_path':          paths['error'],
                    'has_pkl':             paths['pkl'].exists(),
                    'has_success':         paths['success'].exists(),
                    'has_error':           paths['error'].exists(),
                    'ready_phase1':        (has_inputs and r in effective_first_stage
                                          and not paths['success'].exists()),
                    'ready_phase2':        (has_inputs and r in effective_second_stage
                                          and first_three_done and consensus_ready
                                          and not paths['success'].exists()),
                })
    return pd.DataFrame(rows).sort_values(['patient', 'date', 'resample_idx']).reset_index(drop=True)


status_df = build_status_df()
print(f'total rows (patient × day × resample): {len(status_df)}')
print(f'has inputs:      {int(status_df["has_inputs"].sum())}')
print(f'consensus ready: {int(status_df["consensus_ready"].sum())}')
print(f'completed:       {int(status_df["has_success"].sum())}')
print(f'errors:          {int(status_df["has_error"].sum())}')
print(f'ready_phase1:    {int(status_df["ready_phase1"].sum())}')
print(f'ready_phase2:    {int(status_df["ready_phase2"].sum())}')
status_df[['patient','date','resample_idx','stage','has_inputs','consensus_ready',
           'has_success','has_error','ready_phase1','ready_phase2']].head(40)

total rows (patient × day × resample): 2940
has inputs:      2940
consensus ready: 2940
completed:       2900
errors:          6
ready_phase1:    6
ready_phase2:    0

,patient,date,resample_idx,stage,has_inputs,consensus_ready,has_success,has_error,ready_phase1,ready_phase2
0,YEY,2024-04-01,0,hyperparam,True,True,True,False,False,False
1,YEY,2024-04-01,1,hyperparam,True,True,True,False,False,False
2,YEY,2024-04-01,2,hyperparam,True,True,True,False,False,False
3,YEY,2024-04-01,3,fixed,True,True,True,False,False,False
4,YEY,2024-04-01,4,fixed,True,True,True,False,False,False
5,YEY,2024-04-01,5,fixed,True,True,True,False,False,False
6,YEY,2024-04-01,6,fixed,True,True,True,False,False,False
7,YEY,2024-04-01,7,fixed,True,True,True,False,False,False
8,YEY,2024-04-01,8,fixed,True,True,True,False,False,False
9,YEY,2024-04-01,9,fixed,True,True,True,False,False,False
10,YEY,2024-04-01,10,fixed,True,True,True,False,False,False
11,YEY,2024-04-01,11,fixed,True,True,True,False,False,False
12,YEY,2024-04-01,12,fixed,True,True,True,False,False,False
13,YEY,2024-04-01,13,fixed,True,True,True,False,False,False
14,YEY,2024-04-01,14,fixed,True,True,True,False,False,False
15,YEY,2024-04-01,15,fixed,True,True,True,False,False,False
16,YEY,2024-04-01,16,fixed,True,True,True,False,False,False
17,YEY,2024-04-01,17,fixed,True,True,True,False,False,False
18,YEY,2024-04-01,18,fixed,True,True,True,False,False,False
19,YEY,2024-04-01,19,fixed,True,True,True,False,False,False
20,YEY,2024-04-02,0,hyperparam,True,True,True,False,False,False
21,YEY,2024-04-02,1,hyperparam,True,True,True,False,False,False
22,YEY,2024-04-02,2,hyperparam,True,True,True,False,False,False
23,YEY,2024-04-02,3,fixed,True,True,True,False,False,False
24,YEY,2024-04-02,4,fixed,True,True,True,False,False,False
25,YEY,2024-04-02,5,fixed,True,True,True,False,False,False
26,YEY,2024-04-02,6,fixed,True,True,True,False,False,False
27,YEY,2024-04-02,7,fixed,True,True,True,False,False,False
28,YEY,2024-04-02,8,fixed,True,True,True,False,False,False
29,YEY,2024-04-02,9,fixed,True,True,True,False,False,False
30,YEY,2024-04-02,10,fixed,True,True,True,False,False,False
31,YEY,2024-04-02,11,fixed,True,True,True,False,False,False
32,YEY,2024-04-02,12,fixed,True,True,True,False,False,False
33,YEY,2024-04-02,13,fixed,True,True,True,False,False,False
34,YEY,2024-04-02,14,fixed,True,True,True,False,False,False
35,YEY,2024-04-02,15,fixed,True,True,True,False,False,False
36,YEY,2024-04-02,16,fixed,True,True,True,False,False,False
37,YEY,2024-04-02,17,fixed,True,True,True,False,False,False
38,YEY,2024-04-02,18,fixed,True,True,True,False,False,False
39,YEY,2024-04-02,19,fixed,True,True,True,False,False,False

### 6. Patient × Day Input Summary

In [6]:
pair_df = (
    status_df.drop_duplicates(subset=['patient', 'date'])
    [['patient', 'date', 'has_inputs', 'consensus_ready', 'cluster_preds_path', 'frs_path', 'word_idx_path']]
    .sort_values(['patient', 'date'])
    .reset_index(drop=True)
)
print(f'{len(pair_df)} (patient, day) pairs')
display(pair_df)

147 (patient, day) pairs

,patient,date,has_inputs,consensus_ready,cluster_preds_path,frs_path,word_idx_path
0,YEY,2024-04-01,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
1,YEY,2024-04-02,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
2,YEZ,2024-04-09,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
3,YEZ,2024-04-10,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
4,YEZ,2024-04-11,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
5,YEZ,2024-04-12,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
6,YEZ,2024-04-14,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
7,YEZ,2024-04-15,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
8,YFA,2024-04-23,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
9,YFA,2024-04-24,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
10,YFA,2024-04-25,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
11,YFA,2024-04-26,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
12,YFA,2024-04-27,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
13,YFA,2024-04-28,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
14,YFA,2024-04-29,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
15,YFA,2024-04-30,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
16,YFA,2024-05-01,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
17,YFB,2024-05-02,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
18,YFB,2024-05-03,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
19,YFB,2024-05-04,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
20,YFB,2024-05-05,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
21,YFB,2024-05-06,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
22,YFB,2024-05-07,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
23,YFB,2024-05-08,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
24,YFB,2024-05-09,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
25,YFB,2024-05-10,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
26,YFC,2024-07-18,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
27,YFC,2024-07-19,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
28,YFC,2024-07-20,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
29,YFC,2024-07-21,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
30,YFC,2024-07-22,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
31,YFC,2024-07-23,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
32,YFC,2024-07-24,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
33,YFC,2024-07-25,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
34,YFC,2024-07-26,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
35,YFD,2024-07-29,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
36,YFD,2024-07-30,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
37,YFD,2024-07-31,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
38,YFD,2024-08-01,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
39,YFD,2024-08-02,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
40,YFD,2024-08-03,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
41,YFE,2024-08-13,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
42,YFE,2024-08-14,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
43,YFE,2024-08-15,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
44,YFE,2024-08-16,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
45,YFF,2024-08-20,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
46,YFF,2024-08-21,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
47,YFF,2024-08-22,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
48,YFF,2024-08-23,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
49,YFF,2024-08-24,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
50,YFF,2024-08-25,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
51,YFF,2024-08-26,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
52,YFF,2024-08-27,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
53,YFF,2024-08-28,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
54,YFF,2024-08-29,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
55,YFG,2024-09-23,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
56,YFG,2024-09-24,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
57,YFG,2024-09-25,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
58,YFG,2024-09-26,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
59,YFG,2024-09-27,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
60,YFI,2024-10-15,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
61,YFI,2024-10-16,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
62,YFI,2024-10-17,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
63,YFI,2024-10-18,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
64,YFI,2024-10-19,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
65,YFI,2024-10-20,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
66,YFI,2024-10-21,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
67,YFK,2025-02-10,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
68,YFK,2025-02-11,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
69,YFK,2025-02-12,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
70,YFK,2025-02-13,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
71,YFK,2025-02-14,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
72,YFK,2025-02-15,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
73,YFK,2025-02-16,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
74,YFK,2025-02-17,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
75,YFK,2025-02-18,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
76,YFL,2025-02-28,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
77,YFL,2025-03-01,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
78,YFL,2025-03-02,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
79,YFL,2025-03-03,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
80,YFL,2025-03-04,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
81,YFL,2025-03-05,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
82,YFL,2025-03-06,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
83,YFM,2025-03-10,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
84,YFM,2025-03-11,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
85,YFM,2025-03-12,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
86,YFM,2025-03-13,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
87,YFM,2025-03-14,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
88,YFM,2025-03-15,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
89,YFM,2025-03-17,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
90,YFM,2025-03-18,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
91,YFM,2025-03-19,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
92,YFN,2025-03-31,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
93,YFN,2025-04-01,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
94,YFN,2025-04-02,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
95,YFN,2025-04-03,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
96,YFN,2025-04-04,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
97,YFN,2025-04-05,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
98,YFN,2025-04-06,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
99,YFP,2025-05-06,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
100,YFP,2025-05-07,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
101,YFP,2025-05-08,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
102,YFP,2025-05-09,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
103,YFP,2025-05-10,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
104,YFP,2025-05-11,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
105,YFP,2025-05-12,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
106,YFP,2025-05-13,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
107,YFP,2025-05-14,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
108,YFP,2025-05-15,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
109,YFP,2025-05-16,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...
110,YFQ,2025-06-14,True,True,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...,/mnt/labworlds/Hayden/Hayden_Lab/speech_247/va...

### 7a. Submit Phase-1 Jobs  
*(Only runs if `REUSE_PATIENT_CONSENSUS = False`; otherwise `ready_phase1` is always empty.)*

In [7]:
DRY_RUN = False

submitted = []
failed    = []

for _, row in status_df[status_df['ready_phase1']].iterrows():
    patient  = row['patient']
    date_str = row['date']
    r        = int(row['resample_idx'])
    logs_dir    = row['out_root'] / 'slurm_logs'
    scripts_dir = row['out_root'] / 'slurm_scripts'
    logs_dir.mkdir(parents=True, exist_ok=True)
    scripts_dir.mkdir(parents=True, exist_ok=True)

    word_idx_arg = f'--word-idx-path "{row["word_idx_path"]}"' if row['word_idx_path'] else ''
    sbatch_text = f"""#!/bin/bash
#SBATCH --job-name=scat_pd_{patient}_{date_str}_{r}
#SBATCH --partition={PARTITION}
#SBATCH --qos={QOS}
#SBATCH --cpus-per-task={CPUS}
#SBATCH --mem={MEM}
#SBATCH --time={TIME}
#SBATCH --output={logs_dir}/{patient}_{date_str}_r{r}_%j.out
#SBATCH --error={logs_dir}/{patient}_{date_str}_r{r}_%j.err

set -eo pipefail
echo "HOSTNAME: $(hostname)"
echo "START: $(date)"
echo "PATIENT: {patient}"
echo "DATE: {date_str}"
echo "RESAMPLE: {r}"

{PYTHON_BIN} {WORKER_PATH} \\
  --patient {patient} \\
  --resample-idx {r} \\
  --cluster-preds-path "{row['cluster_preds_path']}" \\
  --frs-path "{row['frs_path']}" \\
  --out-dir "{row['out_root']}" \\
  {word_idx_arg} \\
  --test-size {TEST_SIZE} \\
  --n-iter {SEARCH_ITERS} \\
  --cv-splits {CV_SPLITS} \\
  --n-shuffles {N_SHUFFLES} \\
  --seed-stride {SEED_STRIDE} \\
  --n-jobs {CPUS * 2} \\
  --scoring {SCORING} \\
  --perm-metric {PERM_METRIC}

echo "END: $(date)"
"""
    sbatch_path = scripts_dir / f'{patient}_{date_str}_resample_{r}.sbatch'
    sbatch_path.write_text(sbatch_text)

    if DRY_RUN:
        submitted.append((patient, date_str, r, 'dry-run'))
        print(f'dry-run: {patient} {date_str} r={r}')
    else:
        try:
            res = subprocess.run(['sbatch', str(sbatch_path)], capture_output=True, text=True, check=True)
            submitted.append((patient, date_str, r, res.stdout.strip()))
            print(f'submitted: {patient} {date_str} r={r} -> {res.stdout.strip()}')
        except subprocess.CalledProcessError as exc:
            failed.append((patient, date_str, r, exc.stderr.strip()))
            print(f'FAILED: {patient} {date_str} r={r}\n{exc.stderr}')

print(f'phase-1 submitted={len(submitted)}, failed={len(failed)}')

submitted: YFG 2024-09-23 r=0 -> Submitted batch job 274401
submitted: YFG 2024-09-23 r=1 -> Submitted batch job 274402
submitted: YFG 2024-09-23 r=2 -> Submitted batch job 274403
submitted: YFR 2025-06-30 r=0 -> Submitted batch job 274404
submitted: YFR 2025-06-30 r=1 -> Submitted batch job 274405
submitted: YFR 2025-06-30 r=2 -> Submitted batch job 274406
phase-1 submitted=6, failed=0

### 7b. Build Per-Day Consensus Params  
*(Only needed if `REUSE_PATIENT_CONSENSUS = False`; otherwise consensus was copied in the status step.)*

In [8]:
if not REUSE_PATIENT_CONSENSUS:
    built   = []
    blocked = []
    for (patient, date_str), grp in status_df.groupby(['patient', 'date']):
        out_root       = grp.iloc[0]['out_root']
        consensus_json = grp.iloc[0]['consensus_json']
        if consensus_json.exists():
            print(f'consensus already exists: {patient} {date_str}')
            continue
        first_three = grp[grp['resample_idx'].isin(FIRST_STAGE)]
        if not bool(first_three['has_success'].all()):
            blocked.append((patient, date_str))
            continue
        param_options = []
        for r in FIRST_STAGE:
            path = out_root / f'best_params_resample_{r}.json'
            param_options.append(json.loads(path.read_text()))
        consensus = choose_consensus_params(param_options)
        consensus_json.write_text(json.dumps(consensus, indent=2))
        built.append((patient, date_str))
        print(f'built consensus: {patient} {date_str}')
    print('built:', len(built), '  blocked:', len(blocked))
else:
    print('REUSE_PATIENT_CONSENSUS=True — consensus already copied during status build.')

consensus already exists: YEY 2024-04-01
consensus already exists: YEY 2024-04-02
consensus already exists: YEZ 2024-04-09
consensus already exists: YEZ 2024-04-10
consensus already exists: YEZ 2024-04-11
consensus already exists: YEZ 2024-04-12
consensus already exists: YEZ 2024-04-14
consensus already exists: YEZ 2024-04-15
consensus already exists: YFA 2024-04-23
consensus already exists: YFA 2024-04-24
consensus already exists: YFA 2024-04-25
consensus already exists: YFA 2024-04-26
consensus already exists: YFA 2024-04-27
consensus already exists: YFA 2024-04-28
consensus already exists: YFA 2024-04-29
consensus already exists: YFA 2024-04-30
consensus already exists: YFA 2024-05-01
consensus already exists: YFB 2024-05-02
consensus already exists: YFB 2024-05-03
consensus already exists: YFB 2024-05-04
consensus already exists: YFB 2024-05-05
consensus already exists: YFB 2024-05-06
consensus already exists: YFB 2024-05-07
consensus already exists: YFB 2024-05-08
consensus already exists: YFB 2024-05-09
consensus already exists: YFB 2024-05-10
consensus already exists: YFC 2024-07-18
consensus already exists: YFC 2024-07-19
consensus already exists: YFC 2024-07-20
consensus already exists: YFC 2024-07-21
consensus already exists: YFC 2024-07-22
consensus already exists: YFC 2024-07-23
consensus already exists: YFC 2024-07-24
consensus already exists: YFC 2024-07-25
consensus already exists: YFC 2024-07-26
consensus already exists: YFD 2024-07-29
consensus already exists: YFD 2024-07-30
consensus already exists: YFD 2024-07-31
consensus already exists: YFD 2024-08-01
consensus already exists: YFD 2024-08-02
consensus already exists: YFD 2024-08-03
consensus already exists: YFE 2024-08-13
consensus already exists: YFE 2024-08-14
consensus already exists: YFE 2024-08-15
consensus already exists: YFE 2024-08-16
consensus already exists: YFF 2024-08-20
consensus already exists: YFF 2024-08-21
consensus already exists: YFF 2024-08-22
consensus already exists: YFF 2024-08-23
consensus already exists: YFF 2024-08-24
consensus already exists: YFF 2024-08-25
consensus already exists: YFF 2024-08-26
consensus already exists: YFF 2024-08-27
consensus already exists: YFF 2024-08-28
consensus already exists: YFF 2024-08-29
consensus already exists: YFG 2024-09-23
consensus already exists: YFG 2024-09-24
consensus already exists: YFG 2024-09-25
consensus already exists: YFG 2024-09-26
consensus already exists: YFG 2024-09-27
consensus already exists: YFI 2024-10-15
consensus already exists: YFI 2024-10-16
consensus already exists: YFI 2024-10-17
consensus already exists: YFI 2024-10-18
consensus already exists: YFI 2024-10-19
consensus already exists: YFI 2024-10-20
consensus already exists: YFI 2024-10-21
consensus already exists: YFK 2025-02-10
consensus already exists: YFK 2025-02-11
consensus already exists: YFK 2025-02-12
consensus already exists: YFK 2025-02-13
consensus already exists: YFK 2025-02-14
consensus already exists: YFK 2025-02-15
consensus already exists: YFK 2025-02-16
consensus already exists: YFK 2025-02-17
consensus already exists: YFK 2025-02-18
consensus already exists: YFL 2025-02-28
consensus already exists: YFL 2025-03-01
consensus already exists: YFL 2025-03-02
consensus already exists: YFL 2025-03-03
consensus already exists: YFL 2025-03-04
consensus already exists: YFL 2025-03-05
consensus already exists: YFL 2025-03-06
consensus already exists: YFM 2025-03-10
consensus already exists: YFM 2025-03-11
consensus already exists: YFM 2025-03-12
consensus already exists: YFM 2025-03-13
consensus already exists: YFM 2025-03-14
consensus already exists: YFM 2025-03-15
consensus already exists: YFM 2025-03-17
consensus already exists: YFM 2025-03-18
consensus already exists: YFM 2025-03-19
consensus already exists: YFN 2025-03-31
consensus already exists: YFN 2025-04-01
consensus already exists: YFN 2025-04-02
consensus already exists: YFN 2025-04-03
consensus already exists: YFN 2025-04-04
consensus already exists: YFN 2025-04-05
consensus already exists: YFN 2025-04-06
consensus already exists: YFP 2025-05-06
consensus already exists: YFP 2025-05-07
consensus already exists: YFP 2025-05-08
consensus already exists: YFP 2025-05-09
consensus already exists: YFP 2025-05-10
consensus already exists: YFP 2025-05-11
consensus already exists: YFP 2025-05-12
consensus already exists: YFP 2025-05-13
consensus already exists: YFP 2025-05-14
consensus already exists: YFP 2025-05-15
consensus already exists: YFP 2025-05-16
consensus already exists: YFQ 2025-06-14
consensus already exists: YFQ 2025-06-15
consensus already exists: YFQ 2025-06-16
consensus already exists: YFQ 2025-06-17
consensus already exists: YFQ 2025-06-18
consensus already exists: YFQ 2025-06-19
consensus already exists: YFR 2025-06-30
consensus already exists: YFR 2025-07-01
consensus already exists: YFR 2025-07-02
consensus already exists: YFR 2025-07-03
consensus already exists: YFR 2025-07-04
consensus already exists: YFR 2025-07-05
consensus already exists: YFR 2025-07-06
consensus already exists: YFR 2025-07-07
consensus already exists: YFT 2025-07-28
consensus already exists: YFT 2025-07-29
consensus already exists: YFT 2025-07-30
consensus already exists: YFT 2025-07-31
consensus already exists: YFT 2025-08-01
consensus already exists: YFT 2025-08-02
consensus already exists: YFT 2025-08-03
consensus already exists: YFT 2025-08-04
consensus already exists: YFU 2025-12-08
consensus already exists: YFU 2025-12-09
consensus already exists: YFU 2025-12-10
consensus already exists: YFU 2025-12-11
consensus already exists: YFU 2025-12-12
consensus already exists: YFU 2025-12-13
consensus already exists: YFU 2025-12-14
consensus already exists: YFU 2025-12-15
consensus already exists: YFU 2025-12-16
consensus already exists: YFU 2025-12-17
consensus already exists: YFU 2025-12-18
consensus already exists: YFV 2026-02-17
consensus already exists: YFV 2026-02-18
consensus already exists: YFV 2026-02-19
consensus already exists: YFV 2026-02-20
built: 0   blocked: 0

### 7c. Submit Phase-2 (Fixed-Params) Jobs

In [9]:
DRY_RUN = False

# Refresh status after any consensus files were written
status_df = build_status_df()

submitted = []
failed    = []

for _, row in status_df[status_df['ready_phase2']].iterrows():
    patient  = row['patient']
    date_str = row['date']
    r        = int(row['resample_idx'])
    logs_dir    = row['out_root'] / 'slurm_logs'
    scripts_dir = row['out_root'] / 'slurm_scripts'
    logs_dir.mkdir(parents=True, exist_ok=True)
    scripts_dir.mkdir(parents=True, exist_ok=True)

    word_idx_arg = f'--word-idx-path "{row["word_idx_path"]}"' if row['word_idx_path'] else ''
    sbatch_text = f"""#!/bin/bash
#SBATCH --job-name=scat_pd_{patient}_{date_str}_{r}
#SBATCH --partition={PARTITION}
#SBATCH --qos={QOS}
#SBATCH --cpus-per-task={CPUS}
#SBATCH --mem={MEM}
#SBATCH --time={TIME}
#SBATCH --output={logs_dir}/{patient}_{date_str}_r{r}_%j.out
#SBATCH --error={logs_dir}/{patient}_{date_str}_r{r}_%j.err

set -eo pipefail
echo "HOSTNAME: $(hostname)"
echo "START: $(date)"
echo "PATIENT: {patient}"
echo "DATE: {date_str}"
echo "RESAMPLE: {r}"

{PYTHON_BIN} {WORKER_PATH} \\
  --patient {patient} \\
  --resample-idx {r} \\
  --cluster-preds-path "{row['cluster_preds_path']}" \\
  --frs-path "{row['frs_path']}" \\
  --out-dir "{row['out_root']}" \\
  --params-json "{row['consensus_json']}" \\
  {word_idx_arg} \\
  --test-size {TEST_SIZE} \\
  --n-iter {SEARCH_ITERS} \\
  --cv-splits {CV_SPLITS} \\
  --n-shuffles {N_SHUFFLES} \\
  --seed-stride {SEED_STRIDE} \\
  --n-jobs {CPUS * 2} \\
  --scoring {SCORING} \\
  --perm-metric {PERM_METRIC}

echo "END: $(date)"
"""
    sbatch_path = scripts_dir / f'{patient}_{date_str}_resample_{r}.sbatch'
    sbatch_path.write_text(sbatch_text)

    if DRY_RUN:
        submitted.append((patient, date_str, r, 'dry-run'))
        print(f'dry-run: {patient} {date_str} r={r}')
    else:
        try:
            res = subprocess.run(['sbatch', str(sbatch_path)], capture_output=True, text=True, check=True)
            submitted.append((patient, date_str, r, res.stdout.strip()))
            print(f'submitted: {patient} {date_str} r={r} -> {res.stdout.strip()}')
        except subprocess.CalledProcessError as exc:
            failed.append((patient, date_str, r, exc.stderr.strip()))
            print(f'FAILED: {patient} {date_str} r={r}\n{exc.stderr}')

print(f'phase-2 submitted={len(submitted)}, failed={len(failed)}')

phase-2 submitted=0, failed=0

### 8. Check Status

In [10]:
status_df = build_status_df()
pair_progress = (
    status_df.groupby(['patient', 'date'])
    .agg(
        total=('resample_idx', 'count'),
        done=('has_success', 'sum'),
        errors=('has_error', 'sum'),
    )
    .reset_index()
)
pair_progress['pct'] = (pair_progress['done'] / pair_progress['total'] * 100).round(0).astype(int)
print(f'Overall: {int(status_df["has_success"].sum())} / {len(status_df)} resamples done')
display(pair_progress)

Overall: 2900 / 2940 resamples done

    patient        date  total  done  errors  pct
0       YEY  2024-04-01     20    20       0  100
1       YEY  2024-04-02     20    20       0  100
2       YEZ  2024-04-09     20    20       0  100
3       YEZ  2024-04-10     20    20       0  100
4       YEZ  2024-04-11     20    20       0  100
5       YEZ  2024-04-12     20    20       0  100
6       YEZ  2024-04-14     20    20       0  100
7       YEZ  2024-04-15     20    20       0  100
8       YFA  2024-04-23     20    20       0  100
9       YFA  2024-04-24     20    20       0  100
10      YFA  2024-04-25     20    20       0  100
11      YFA  2024-04-26     20    20       0  100
12      YFA  2024-04-27     20    20       0  100
13      YFA  2024-04-28     20    20       0  100
14      YFA  2024-04-29     20    20       0  100
15      YFA  2024-04-30     20    20       0  100
16      YFA  2024-05-01     20    20       0  100
17      YFB  2024-05-02     20    20       0  100
18      YFB  2024-05-03     20    20       0  100
19      YFB  2024-05-04     20    20       0  100
20      YFB  2024-05-05     20    20       0  100
21      YFB  2024-05-06     20    20       0  100
22      YFB  2024-05-07     20    20       0  100
23      YFB  2024-05-08     20    20       0  100
24      YFB  2024-05-09     20    20       0  100
25      YFB  2024-05-10     20    20       0  100
26      YFC  2024-07-18     20    20       0  100
27      YFC  2024-07-19     20    20       0  100
28      YFC  2024-07-20     20    20       0  100
29      YFC  2024-07-21     20    20       0  100
30      YFC  2024-07-22     20    20       0  100
31      YFC  2024-07-23     20    20       0  100
32      YFC  2024-07-24     20    20       0  100
33      YFC  2024-07-25     20    20       0  100
34      YFC  2024-07-26     20    20       0  100
35      YFD  2024-07-29     20    20       0  100
36      YFD  2024-07-30     20    20       0  100
37      YFD  2024-07-31     20    20       0  100
38      YFD  2024-08-01     20    20       0  100
39      YFD  2024-08-02     20    20       0  100
40      YFD  2024-08-03     20    20       0  100
41      YFE  2024-08-13     20    20       0  100
42      YFE  2024-08-14     20    20       0  100
43      YFE  2024-08-15     20    20       0  100
44      YFE  2024-08-16     20    20       0  100
45      YFF  2024-08-20     20    20       0  100
46      YFF  2024-08-21     20    20       0  100
47      YFF  2024-08-22     20    20       0  100
48      YFF  2024-08-23     20    20       0  100
49      YFF  2024-08-24     20    20       0  100
50      YFF  2024-08-25     20    20       0  100
51      YFF  2024-08-26     20    20       0  100
52      YFF  2024-08-27     20    20       0  100
53      YFF  2024-08-28     20    20       0  100
54      YFF  2024-08-29     20    20       0  100
55      YFG  2024-09-23     20     0       3    0
56      YFG  2024-09-24     20    20       0  100
57      YFG  2024-09-25     20    20       0  100
58      YFG  2024-09-26     20    20       0  100
59      YFG  2024-09-27     20    20       0  100
60      YFI  2024-10-15     20    20       0  100
61      YFI  2024-10-16     20    20       0  100
62      YFI  2024-10-17     20    20       0  100
63      YFI  2024-10-18     20    20       0  100
64      YFI  2024-10-19     20    20       0  100
65      YFI  2024-10-20     20    20       0  100
66      YFI  2024-10-21     20    20       0  100
67      YFK  2025-02-10     20    20       0  100
68      YFK  2025-02-11     20    20       0  100
69      YFK  2025-02-12     20    20       0  100
70      YFK  2025-02-13     20    20       0  100
71      YFK  2025-02-14     20    20       0  100
72      YFK  2025-02-15     20    20       0  100
73      YFK  2025-02-16     20    20       0  100
74      YFK  2025-02-17     20    20       0  100
75      YFK  2025-02-18     20    20       0  100
76      YFL  2025-02-28     20    20       0  100
77      YFL  2025-03-01     20    20       0  100
78      YFL  2025-03-02     20    20       0  100
79      YFL  2025-03-03     20    20       0  100
80      YFL  2025-03-04     20    20       0  100
81      YFL  2025-03-05     20    20       0  100
82      YFL  2025-03-06     20    20       0  100
83      YFM  2025-03-10     20    20       0  100
84      YFM  2025-03-11     20    20       0  100
85      YFM  2025-03-12     20    20       0  100
86      YFM  2025-03-13     20    20       0  100
87      YFM  2025-03-14     20    20       0  100
88      YFM  2025-03-15     20    20       0  100
89      YFM  2025-03-17     20    20       0  100
90      YFM  2025-03-18     20    20       0  100
91      YFM  2025-03-19     20    20       0  100
92      YFN  2025-03-31     20    20       0  100
93      YFN  2025-04-01     20    20       0  100
94      YFN  2025-04-02     20    20       0  100
95      YFN  2025-04-03     20    20       0  100
96      YFN  2025-04-04     20    20       0  100
97      YFN  2025-04-05     20    20       0  100
98      YFN  2025-04-06     20    20       0  100
99      YFP  2025-05-06     20    20       0  100
100     YFP  2025-05-07     20    20       0  100
101     YFP  2025-05-08     20    20       0  100
102     YFP  2025-05-09     20    20       0  100
103     YFP  2025-05-10     20    20       0  100
104     YFP  2025-05-11     20    20       0  100
105     YFP  2025-05-12     20    20       0  100
106     YFP  2025-05-13     20    20       0  100
107     YFP  2025-05-14     20    20       0  100
108     YFP  2025-05-15     20    20       0  100
109     YFP  2025-05-16     20    20       0  100
110     YFQ  2025-06-14     20    20       0  100
111     YFQ  2025-06-15     20    20       0  100
112     YFQ  2025-06-16     20    20       0  100
113     YFQ  2025-06-17     20    20       0  100
114     YFQ  2025-06-18     20    20       0  100
115     YFQ  2025-06-19     20    20       0  100
116     YFR  2025-06-30     20     0       3    0
117     YFR  2025-07-01     20    20       0  100
118     YFR  2025-07-02     20    20       0  100
119     YFR  2025-07-03     20    20       0  100
120     YFR  2025-07-04     20    20       0  100
121     YFR  2025-07-05     20    20       0  100
122     YFR  2025-07-06     20    20       0  100
123     YFR  2025-07-07     20    20       0  100
124     YFT  2025-07-28     20    20       0  100
125     YFT  2025-07-29     20    20       0  100
126     YFT  2025-07-30     20    20       0  100
127     YFT  2025-07-31     20    20       0  100
128     YFT  2025-08-01     20    20       0  100
129     YFT  2025-08-02     20    20       0  100
130     YFT  2025-08-03     20    20       0  100
131     YFT  2025-08-04     20    20       0  100
132     YFU  2025-12-08     20    20       0  100
133     YFU  2025-12-09     20    20       0  100
134     YFU  2025-12-10     20    20       0  100
135     YFU  2025-12-11     20    20       0  100
136     YFU  2025-12-12     20    20       0  100
137     YFU  2025-12-13     20    20       0  100
138     YFU  2025-12-14     20    20       0  100
139     YFU  2025-12-15     20    20       0  100
140     YFU  2025-12-16     20    20       0  100
141     YFU  2025-12-17     20    20       0  100
142     YFU  2025-12-18     20    20       0  100
143     YFV  2026-02-17     20    20       0  100
144     YFV  2026-02-18     20    20       0  100
145     YFV  2026-02-19     20    20       0  100
146     YFV  2026-02-20     20    20       0  100

### 9. Inspect Errors

In [11]:
error_rows = status_df[status_df['has_error']].copy()
print(f'resamples with error files: {len(error_rows)}')
for _, row in error_rows.head(10).iterrows():
    print('=' * 100)
    print(row['patient'], row['date'], f'r={row["resample_idx"]}')
    print(row['error_path'].read_text()[:4000])

resamples with error files: 6
====================================================================================================
YFG 2024-09-23 r=0
Traceback (most recent call last):
  File "/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py", line 377, in main
    model, results = run_one_resample(
                     ^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py", line 152, in run_one_resample
    Xtr, Xte, ytr, yte = train_test_split(
                         ^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2945, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 1928, in split
    for train, test in self._iter_indices(X, y, groups):
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2346, in _iter_indices
    raise ValueError(
ValueError: The least populated classes in y have only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2. Classes with too few members are: [8]

====================================================================================================
YFG 2024-09-23 r=1
Traceback (most recent call last):
  File "/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py", line 377, in main
    model, results = run_one_resample(
                     ^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py", line 152, in run_one_resample
    Xtr, Xte, ytr, yte = train_test_split(
                         ^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2945, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 1928, in split
    for train, test in self._iter_indices(X, y, groups):
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2346, in _iter_indices
    raise ValueError(
ValueError: The least populated classes in y have only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2. Classes with too few members are: [8]

====================================================================================================
YFG 2024-09-23 r=2
Traceback (most recent call last):
  File "/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py", line 377, in main
    model, results = run_one_resample(
                     ^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py", line 152, in run_one_resample
    Xtr, Xte, ytr, yte = train_test_split(
                         ^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2945, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 1928, in split
    for train, test in self._iter_indices(X, y, groups):
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2346, in _iter_indices
    raise ValueError(
ValueError: The least populated classes in y have only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2. Classes with too few members are: [8]

====================================================================================================
YFR 2025-06-30 r=0
Traceback (most recent call last):
  File "/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py", line 377, in main
    model, results = run_one_resample(
                     ^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py", line 152, in run_one_resample
    Xtr, Xte, ytr, yte = train_test_split(
                         ^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2945, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 1928, in split
    for train, test in self._iter_indices(X, y, groups):
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2346, in _iter_indices
    raise ValueError(
ValueError: The least populated classes in y have only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2. Classes with too few members are: [8]

====================================================================================================
YFR 2025-06-30 r=1
Traceback (most recent call last):
  File "/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py", line 377, in main
    model, results = run_one_resample(
                     ^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py", line 152, in run_one_resample
    Xtr, Xte, ytr, yte = train_test_split(
                         ^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2945, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 1928, in split
    for train, test in self._iter_indices(X, y, groups):
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2346, in _iter_indices
    raise ValueError(
ValueError: The least populated classes in y have only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2. Classes with too few members are: [8]

====================================================================================================
YFR 2025-06-30 r=2
Traceback (most recent call last):
  File "/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py", line 377, in main
    model, results = run_one_resample(
                     ^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/speech_247/notebooks/REBIRTH_2!/standard_decoding_analysis/scat_classifier_worker.py", line 152, in run_one_resample
    Xtr, Xte, ytr, yte = train_test_split(
                         ^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2945, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 1928, in split
    for train, test in self._iter_indices(X, y, groups):
  File "/scratch/tahaismail424/miniforge3/envs/speech_247_env/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2346, in _iter_indices
    raise ValueError(
ValueError: The least populated classes in y have only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2. Classes with too few members are: [8]

### 10. Aggregate Results Per (Patient, Day)

In [12]:
for (patient, date_str), grp in status_df.groupby(['patient', 'date']):
    if not bool(grp['has_success'].all()):
        print(f'skipping {patient} {date_str}: not all resamples finished')
        continue

    out_root     = grp.iloc[0]['out_root']
    summary_rows = []
    aggregate    = {}
    for r in range(N_RESAMPLES):
        with open(out_root / f'summary_resample_{r}.json') as f:
            summary_rows.append(json.load(f))
        with open(out_root / f'scat_sampled_resample_{r}_.pkl', 'rb') as f:
            aggregate[f'resample_{r}'] = pickle.load(f)

    summary_df = pd.DataFrame(summary_rows).sort_values('resample_idx').reset_index(drop=True)
    agg_csv = out_root / 'scat_sampled_all_resamples.csv'
    agg_pkl = out_root / 'scat_sampled_all_resamples.pkl'
    summary_df.to_csv(agg_csv, index=False)
    with open(agg_pkl, 'wb') as f:
        pickle.dump(aggregate, f)
    print(f'aggregated {patient} {date_str} -> {agg_csv}')
    display(summary_df)

aggregated YEY 2024-04-01 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YEY/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-01/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YEY,0,0,3871,3871,775,0.153548,0.125827,0.124919,0.153548,0.545338,0.118375,0.134194,2.004897e-03,f1_macro,0.124919,0.019608,0.136489,shuffle_training_X_only
1,YEY,1,42,3871,3871,775,0.149677,0.119451,0.116253,0.149677,0.563953,0.118375,0.134194,5.138033e-03,f1_macro,0.116253,0.019608,0.142778,shuffle_training_X_only
2,YEY,2,84,3871,3871,775,0.172903,0.138114,0.135387,0.172903,0.564575,0.118375,0.134194,5.406343e-06,f1_macro,0.135387,0.019608,0.142540,shuffle_training_X_only
3,YEY,3,126,3871,3871,775,0.179355,0.146221,0.144660,0.179355,0.576744,0.118375,0.134194,4.867366e-07,f1_macro,0.144660,0.019608,NaN,shuffle_training_X_only
4,YEY,4,168,3871,3871,775,0.176774,0.140854,0.138499,0.176774,0.557263,0.118375,0.134194,1.308017e-06,f1_macro,0.138499,0.019608,NaN,shuffle_training_X_only
5,YEY,5,210,3871,3871,775,0.197419,0.158467,0.155698,0.197419,0.560260,0.118375,0.134194,1.903913e-10,f1_macro,0.155698,0.019608,NaN,shuffle_training_X_only
6,YEY,6,252,3871,3871,775,0.172903,0.141460,0.138985,0.172903,0.569691,0.118375,0.134194,5.406343e-06,f1_macro,0.138985,0.019608,NaN,shuffle_training_X_only
7,YEY,7,294,3871,3871,775,0.152258,0.120255,0.116493,0.152258,0.559790,0.118375,0.134194,2.768766e-03,f1_macro,0.116493,0.039216,NaN,shuffle_training_X_only
8,YEY,8,336,3871,3871,775,0.161290,0.127814,0.123680,0.161290,0.559582,0.118375,0.134194,2.390449e-04,f1_macro,0.123680,0.019608,NaN,shuffle_training_X_only
9,YEY,9,378,3871,3871,775,0.162581,0.132700,0.130432,0.162581,0.592257,0.118375,0.134194,1.625253e-04,f1_macro,0.130432,0.019608,NaN,shuffle_training_X_only
10,YEY,10,420,3871,3871,775,0.178065,0.144628,0.143009,0.178065,0.561617,0.118375,0.134194,8.012887e-07,f1_macro,0.143009,0.019608,NaN,shuffle_training_X_only
11,YEY,11,462,3871,3871,775,0.158710,0.130404,0.128014,0.158710,0.579221,0.118375,0.134194,5.034689e-04,f1_macro,0.128014,0.019608,NaN,shuffle_training_X_only
12,YEY,12,504,3871,3871,775,0.174194,0.140239,0.137232,0.174194,0.565974,0.118375,0.134194,3.397710e-06,f1_macro,0.137232,0.019608,NaN,shuffle_training_X_only
13,YEY,13,546,3871,3871,775,0.176774,0.146625,0.144544,0.176774,0.588872,0.118375,0.134194,1.308017e-06,f1_macro,0.144544,0.019608,NaN,shuffle_training_X_only
14,YEY,14,588,3871,3871,775,0.154839,0.131885,0.133266,0.154839,0.579063,0.118375,0.134194,1.438640e-03,f1_macro,0.133266,0.019608,NaN,shuffle_training_X_only
15,YEY,15,630,3871,3871,775,0.162581,0.135520,0.134889,0.162581,0.571874,0.118375,0.134194,1.625253e-04,f1_macro,0.134889,0.019608,NaN,shuffle_training_X_only
16,YEY,16,672,3871,3871,775,0.163871,0.134246,0.133740,0.163871,0.573180,0.118375,0.134194,1.095234e-04,f1_macro,0.133740,0.019608,NaN,shuffle_training_X_only
17,YEY,17,714,3871,3871,775,0.171613,0.135647,0.130400,0.171613,0.587979,0.118375,0.134194,8.528783e-06,f1_macro,0.130400,0.019608,NaN,shuffle_training_X_only
18,YEY,18,756,3871,3871,775,0.162581,0.131729,0.128677,0.162581,0.569407,0.118375,0.134194,1.625253e-04,f1_macro,0.128677,0.019608,NaN,shuffle_training_X_only
19,YEY,19,798,3871,3871,775,0.163871,0.130513,0.125179,0.163871,0.562081,0.118375,0.134194,1.095234e-04,f1_macro,0.125179,0.019608,NaN,shuffle_training_X_only

aggregated YEY 2024-04-02 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YEY/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-02/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YEY,0,0,4892,4892,979,0.163432,0.123227,0.113592,0.163432,0.542375,0.119912,0.137896,3.618538e-05,f1_macro,0.113592,0.019608,0.12575,shuffle_training_X_only
1,YEY,1,42,4892,4892,979,0.157303,0.122771,0.120563,0.157303,0.533602,0.119912,0.137896,3.076525e-04,f1_macro,0.120563,0.019608,0.12883,shuffle_training_X_only
2,YEY,2,84,4892,4892,979,0.194076,0.148285,0.140803,0.194076,0.548925,0.119912,0.137896,1.984121e-11,f1_macro,0.140803,0.019608,0.12931,shuffle_training_X_only
3,YEY,3,126,4892,4892,979,0.171604,0.129152,0.121098,0.171604,0.535959,0.119912,0.137896,1.405157e-06,f1_macro,0.121098,0.019608,NaN,shuffle_training_X_only
4,YEY,4,168,4892,4892,979,0.194076,0.147441,0.138261,0.194076,0.566975,0.119912,0.137896,1.984121e-11,f1_macro,0.138261,0.019608,NaN,shuffle_training_X_only
5,YEY,5,210,4892,4892,979,0.162411,0.124818,0.120223,0.162411,0.543717,0.119912,0.137896,5.262352e-05,f1_macro,0.120223,0.039216,NaN,shuffle_training_X_only
6,YEY,6,252,4892,4892,979,0.153218,0.117922,0.113949,0.153218,0.539144,0.119912,0.137896,1.110232e-03,f1_macro,0.113949,0.058824,NaN,shuffle_training_X_only
7,YEY,7,294,4892,4892,979,0.165475,0.127258,0.121923,0.165475,0.556789,0.119912,0.137896,1.675114e-05,f1_macro,0.121923,0.019608,NaN,shuffle_training_X_only
8,YEY,8,336,4892,4892,979,0.167518,0.126743,0.118823,0.167518,0.556236,0.119912,0.137896,7.539806e-06,f1_macro,0.118823,0.019608,NaN,shuffle_training_X_only
9,YEY,9,378,4892,4892,979,0.167518,0.129796,0.124739,0.167518,0.552660,0.119912,0.137896,7.539806e-06,f1_macro,0.124739,0.019608,NaN,shuffle_training_X_only
10,YEY,10,420,4892,4892,979,0.177732,0.138954,0.136129,0.177732,0.562672,0.119912,0.137896,9.200790e-08,f1_macro,0.136129,0.019608,NaN,shuffle_training_X_only
11,YEY,11,462,4892,4892,979,0.191011,0.145244,0.136922,0.191011,0.551034,0.119912,0.137896,1.096895e-10,f1_macro,0.136922,0.019608,NaN,shuffle_training_X_only
12,YEY,12,504,4892,4892,979,0.181818,0.143925,0.143327,0.181818,0.543324,0.119912,0.137896,1.305824e-08,f1_macro,0.143327,0.019608,NaN,shuffle_training_X_only
13,YEY,13,546,4892,4892,979,0.176711,0.136306,0.130584,0.176711,0.544887,0.119912,0.137896,1.474072e-07,f1_macro,0.130584,0.019608,NaN,shuffle_training_X_only
14,YEY,14,588,4892,4892,979,0.166496,0.131376,0.127618,0.166496,0.545585,0.119912,0.137896,1.127773e-05,f1_macro,0.127618,0.019608,NaN,shuffle_training_X_only
15,YEY,15,630,4892,4892,979,0.177732,0.137331,0.131997,0.177732,0.563676,0.119912,0.137896,9.200790e-08,f1_macro,0.131997,0.019608,NaN,shuffle_training_X_only
16,YEY,16,672,4892,4892,979,0.194076,0.144400,0.132988,0.194076,0.559624,0.119912,0.137896,1.984121e-11,f1_macro,0.132988,0.019608,NaN,shuffle_training_X_only
17,YEY,17,714,4892,4892,979,0.148110,0.113151,0.107259,0.148110,0.533226,0.119912,0.137896,4.689370e-03,f1_macro,0.107259,0.176471,NaN,shuffle_training_X_only
18,YEY,18,756,4892,4892,979,0.186925,0.145438,0.140075,0.186925,0.541258,0.119912,0.137896,9.797119e-10,f1_macro,0.140075,0.019608,NaN,shuffle_training_X_only
19,YEY,19,798,4892,4892,979,0.189990,0.146916,0.141054,0.189990,0.560227,0.119912,0.137896,1.914774e-10,f1_macro,0.141054,0.019608,NaN,shuffle_training_X_only

aggregated YEZ 2024-04-09 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YEZ/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-09/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YEZ,0,0,1422,1422,285,0.143860,0.103663,0.104046,0.143860,0.534582,0.132114,0.147368,0.303590,f1_macro,0.104046,0.294118,0.132443,shuffle_training_X_only
1,YEZ,1,42,1422,1422,285,0.189474,0.135165,0.134169,0.189474,0.530213,0.132114,0.147368,0.003999,f1_macro,0.134169,0.039216,0.138725,shuffle_training_X_only
2,YEZ,2,84,1422,1422,285,0.217544,0.155977,0.152222,0.217544,0.542705,0.132114,0.147368,0.000049,f1_macro,0.152222,0.019608,0.143650,shuffle_training_X_only
3,YEZ,3,126,1422,1422,285,0.126316,0.087179,0.080256,0.126316,0.511005,0.132114,0.147368,0.639777,f1_macro,0.080256,0.882353,NaN,shuffle_training_X_only
4,YEZ,4,168,1422,1422,285,0.154386,0.117516,0.119762,0.154386,0.580770,0.132114,0.147368,0.153234,f1_macro,0.119762,0.058824,NaN,shuffle_training_X_only
5,YEZ,5,210,1422,1422,285,0.157895,0.119897,0.124928,0.157895,0.535985,0.132114,0.147368,0.117028,f1_macro,0.124928,0.019608,NaN,shuffle_training_X_only
6,YEZ,6,252,1422,1422,285,0.182456,0.132168,0.131367,0.182456,0.520929,0.132114,0.147368,0.009811,f1_macro,0.131367,0.019608,NaN,shuffle_training_X_only
7,YEZ,7,294,1422,1422,285,0.175439,0.124725,0.121657,0.175439,0.537407,0.132114,0.147368,0.022139,f1_macro,0.121657,0.019608,NaN,shuffle_training_X_only
8,YEZ,8,336,1422,1422,285,0.143860,0.105794,0.106593,0.143860,0.576903,0.132114,0.147368,0.303590,f1_macro,0.106593,0.235294,NaN,shuffle_training_X_only
9,YEZ,9,378,1422,1422,285,0.182456,0.134615,0.136257,0.182456,0.532737,0.132114,0.147368,0.009811,f1_macro,0.136257,0.019608,NaN,shuffle_training_X_only
10,YEZ,10,420,1422,1422,285,0.185965,0.127656,0.118185,0.185965,0.539570,0.132114,0.147368,0.006329,f1_macro,0.118185,0.098039,NaN,shuffle_training_X_only
11,YEZ,11,462,1422,1422,285,0.182456,0.131252,0.127132,0.182456,0.533968,0.132114,0.147368,0.009811,f1_macro,0.127132,0.019608,NaN,shuffle_training_X_only
12,YEZ,12,504,1422,1422,285,0.164912,0.119714,0.115952,0.164912,0.529184,0.132114,0.147368,0.064068,f1_macro,0.115952,0.078431,NaN,shuffle_training_X_only
13,YEZ,13,546,1422,1422,285,0.196491,0.134799,0.127576,0.196491,0.546209,0.132114,0.147368,0.001501,f1_macro,0.127576,0.019608,NaN,shuffle_training_X_only
14,YEZ,14,588,1422,1422,285,0.154386,0.105861,0.100095,0.154386,0.521353,0.132114,0.147368,0.153234,f1_macro,0.100095,0.333333,NaN,shuffle_training_X_only
15,YEZ,15,630,1422,1422,285,0.175439,0.120696,0.112537,0.175439,0.526514,0.132114,0.147368,0.022139,f1_macro,0.112537,0.137255,NaN,shuffle_training_X_only
16,YEZ,16,672,1422,1422,285,0.175439,0.121062,0.112963,0.175439,0.575364,0.132114,0.147368,0.022139,f1_macro,0.112963,0.078431,NaN,shuffle_training_X_only
17,YEZ,17,714,1422,1422,285,0.196491,0.141142,0.140070,0.196491,0.553084,0.132114,0.147368,0.001501,f1_macro,0.140070,0.019608,NaN,shuffle_training_X_only
18,YEZ,18,756,1422,1422,285,0.150877,0.114952,0.116975,0.150877,0.532245,0.132114,0.147368,0.196478,f1_macro,0.116975,0.078431,NaN,shuffle_training_X_only
19,YEZ,19,798,1422,1422,285,0.182456,0.125092,0.117668,0.182456,0.537749,0.132114,0.147368,0.009811,f1_macro,0.117668,0.117647,NaN,shuffle_training_X_only

aggregated YEZ 2024-04-10 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YEZ/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-10/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YEZ,0,0,3770,3770,754,0.188329,0.142008,0.134052,0.188329,0.567797,0.123258,0.14191,2.071074e-07,f1_macro,0.134052,0.019608,0.132537,shuffle_training_X_only
1,YEZ,1,42,3770,3770,754,0.157825,0.121842,0.117720,0.157825,0.578294,0.123258,0.14191,3.022510e-03,f1_macro,0.117720,0.019608,0.131017,shuffle_training_X_only
2,YEZ,2,84,3770,3770,754,0.187003,0.141130,0.136275,0.187003,0.585177,0.123258,0.14191,3.455023e-07,f1_macro,0.136275,0.019608,0.140587,shuffle_training_X_only
3,YEZ,3,126,3770,3770,754,0.164456,0.124756,0.117489,0.164456,0.576955,0.123258,0.14191,5.589544e-04,f1_macro,0.117489,0.058824,NaN,shuffle_training_X_only
4,YEZ,4,168,3770,3770,754,0.168435,0.126876,0.122518,0.168435,0.574391,0.123258,0.14191,1.823126e-04,f1_macro,0.122518,0.019608,NaN,shuffle_training_X_only
5,YEZ,5,210,3770,3770,754,0.194960,0.150092,0.146856,0.194960,0.588712,0.123258,0.14191,1.415271e-08,f1_macro,0.146856,0.019608,NaN,shuffle_training_X_only
6,YEZ,6,252,3770,3770,754,0.198939,0.153948,0.150928,0.198939,0.578604,0.123258,0.14191,2.563912e-09,f1_macro,0.150928,0.019608,NaN,shuffle_training_X_only
7,YEZ,7,294,3770,3770,754,0.205570,0.155719,0.150104,0.205570,0.588439,0.123258,0.14191,1.265943e-10,f1_macro,0.150104,0.019608,NaN,shuffle_training_X_only
8,YEZ,8,336,3770,3770,754,0.185676,0.137807,0.128802,0.185676,0.592304,0.123258,0.14191,5.715648e-07,f1_macro,0.128802,0.019608,NaN,shuffle_training_X_only
9,YEZ,9,378,3770,3770,754,0.202918,0.150801,0.139828,0.202918,0.600852,0.123258,0.14191,4.319288e-10,f1_macro,0.139828,0.019608,NaN,shuffle_training_X_only
10,YEZ,10,420,3770,3770,754,0.187003,0.143781,0.137494,0.187003,0.580813,0.123258,0.14191,3.455023e-07,f1_macro,0.137494,0.019608,NaN,shuffle_training_X_only
11,YEZ,11,462,3770,3770,754,0.201592,0.156522,0.149210,0.201592,0.577565,0.123258,0.14191,7.883594e-10,f1_macro,0.149210,0.019608,NaN,shuffle_training_X_only
12,YEZ,12,504,3770,3770,754,0.190981,0.141442,0.132603,0.190981,0.582295,0.123258,0.14191,7.258115e-08,f1_macro,0.132603,0.019608,NaN,shuffle_training_X_only
13,YEZ,13,546,3770,3770,754,0.179045,0.138404,0.134481,0.179045,0.547933,0.123258,0.14191,6.237229e-06,f1_macro,0.134481,0.019608,NaN,shuffle_training_X_only
14,YEZ,14,588,3770,3770,754,0.177719,0.128619,0.117309,0.177719,0.566615,0.123258,0.14191,9.804846e-06,f1_macro,0.117309,0.019608,NaN,shuffle_training_X_only
15,YEZ,15,630,3770,3770,754,0.180371,0.137624,0.132135,0.180371,0.586658,0.123258,0.14191,3.933782e-06,f1_macro,0.132135,0.019608,NaN,shuffle_training_X_only
16,YEZ,16,672,3770,3770,754,0.190981,0.146624,0.139749,0.190981,0.578634,0.123258,0.14191,7.258115e-08,f1_macro,0.139749,0.019608,NaN,shuffle_training_X_only
17,YEZ,17,714,3770,3770,754,0.187003,0.138762,0.130108,0.187003,0.600707,0.123258,0.14191,3.455023e-07,f1_macro,0.130108,0.019608,NaN,shuffle_training_X_only
18,YEZ,18,756,3770,3770,754,0.193634,0.143961,0.134840,0.193634,0.586367,0.123258,0.14191,2.460771e-08,f1_macro,0.134840,0.019608,NaN,shuffle_training_X_only
19,YEZ,19,798,3770,3770,754,0.198939,0.149235,0.142071,0.198939,0.597649,0.123258,0.14191,2.563912e-09,f1_macro,0.142071,0.019608,NaN,shuffle_training_X_only

aggregated YEZ 2024-04-11 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YEZ/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-11/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YEZ,0,0,294,294,59,0.118644,0.077778,0.065812,0.118644,0.564204,0.13071,0.152542,0.665991,f1_macro,0.065812,0.803922,0.155484,shuffle_training_X_only
1,YEZ,1,42,294,294,59,0.169492,0.120238,0.103659,0.169492,0.544680,0.13071,0.152542,0.237050,f1_macro,0.103659,0.254902,0.132816,shuffle_training_X_only
2,YEZ,2,84,294,294,59,0.135593,0.093452,0.089923,0.135593,0.525524,0.13071,0.152542,0.513350,f1_macro,0.089923,0.431373,0.125151,shuffle_training_X_only
3,YEZ,3,126,294,294,59,0.237288,0.161111,0.134949,0.237288,0.568449,0.13071,0.152542,0.018042,f1_macro,0.134949,0.117647,NaN,shuffle_training_X_only
4,YEZ,4,168,294,294,59,0.203390,0.142063,0.127766,0.203390,0.522112,0.13071,0.152542,0.077471,f1_macro,0.127766,0.137255,NaN,shuffle_training_X_only
5,YEZ,5,210,294,294,59,0.152542,0.110119,0.083409,0.152542,0.476182,0.13071,0.152542,0.364165,f1_macro,0.083409,0.549020,NaN,shuffle_training_X_only
6,YEZ,6,252,294,294,59,0.135593,0.090278,0.084204,0.135593,0.528876,0.13071,0.152542,0.513350,f1_macro,0.084204,0.549020,NaN,shuffle_training_X_only
7,YEZ,7,294,294,294,59,0.101695,0.068056,0.052944,0.101695,0.504713,0.13071,0.152542,0.800067,f1_macro,0.052944,0.921569,NaN,shuffle_training_X_only
8,YEZ,8,336,294,294,59,0.135593,0.095238,0.086381,0.135593,0.507728,0.13071,0.152542,0.513350,f1_macro,0.086381,0.568627,NaN,shuffle_training_X_only
9,YEZ,9,378,294,294,59,0.152542,0.101389,0.086812,0.152542,0.547777,0.13071,0.152542,0.364165,f1_macro,0.086812,0.509804,NaN,shuffle_training_X_only
10,YEZ,10,420,294,294,59,0.271186,0.186508,0.170715,0.271186,0.529767,0.13071,0.152542,0.003038,f1_macro,0.170715,0.019608,NaN,shuffle_training_X_only
11,YEZ,11,462,294,294,59,0.118644,0.082341,0.076691,0.118644,0.543018,0.13071,0.152542,0.665991,f1_macro,0.076691,0.607843,NaN,shuffle_training_X_only
12,YEZ,12,504,294,294,59,0.203390,0.142460,0.133791,0.203390,0.572790,0.13071,0.152542,0.077471,f1_macro,0.133791,0.078431,NaN,shuffle_training_X_only
13,YEZ,13,546,294,294,59,0.169492,0.120238,0.115731,0.169492,0.532497,0.13071,0.152542,0.237050,f1_macro,0.115731,0.274510,NaN,shuffle_training_X_only
14,YEZ,14,588,294,294,59,0.186441,0.131349,0.120405,0.186441,0.530911,0.13071,0.152542,0.141482,f1_macro,0.120405,0.196078,NaN,shuffle_training_X_only
15,YEZ,15,630,294,294,59,0.067797,0.045833,0.040206,0.067797,0.380883,0.13071,0.152542,0.959043,f1_macro,0.040206,0.901961,NaN,shuffle_training_X_only
16,YEZ,16,672,294,294,59,0.169492,0.117063,0.108772,0.169492,0.523945,0.13071,0.152542,0.237050,f1_macro,0.108772,0.352941,NaN,shuffle_training_X_only
17,YEZ,17,714,294,294,59,0.152542,0.105952,0.100495,0.152542,0.516813,0.13071,0.152542,0.364165,f1_macro,0.100495,0.294118,NaN,shuffle_training_X_only
18,YEZ,18,756,294,294,59,0.169492,0.117063,0.103001,0.169492,0.488664,0.13071,0.152542,0.237050,f1_macro,0.103001,0.313725,NaN,shuffle_training_X_only
19,YEZ,19,798,294,294,59,0.135593,0.093452,0.088304,0.135593,0.470971,0.13071,0.152542,0.513350,f1_macro,0.088304,0.529412,NaN,shuffle_training_X_only

aggregated YEZ 2024-04-12 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YEZ/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-12/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YEZ,0,0,1704,1704,341,0.187683,0.136910,0.135767,0.187683,0.624552,0.134287,0.14956,3.477300e-03,f1_macro,0.135767,0.019608,0.146316,shuffle_training_X_only
1,YEZ,1,42,1704,1704,341,0.146628,0.109147,0.107485,0.146628,0.511997,0.134287,0.14956,2.737432e-01,f1_macro,0.107485,0.156863,0.149585,shuffle_training_X_only
2,YEZ,2,84,1704,1704,341,0.205279,0.150546,0.149079,0.205279,0.605441,0.134287,0.14956,1.869477e-04,f1_macro,0.149079,0.019608,0.144719,shuffle_training_X_only
3,YEZ,3,126,1704,1704,341,0.234604,0.166519,0.161828,0.234604,0.630388,0.134287,0.14956,3.781012e-07,f1_macro,0.161828,0.019608,NaN,shuffle_training_X_only
4,YEZ,4,168,1704,1704,341,0.181818,0.132053,0.125301,0.181818,0.563466,0.134287,0.14956,8.022892e-03,f1_macro,0.125301,0.019608,NaN,shuffle_training_X_only
5,YEZ,5,210,1704,1704,341,0.217009,0.160980,0.156759,0.217009,0.600392,0.134287,0.14956,1.900444e-05,f1_macro,0.156759,0.019608,NaN,shuffle_training_X_only
6,YEZ,6,252,1704,1704,341,0.181818,0.130601,0.124257,0.181818,0.599792,0.134287,0.14956,8.022892e-03,f1_macro,0.124257,0.058824,NaN,shuffle_training_X_only
7,YEZ,7,294,1704,1704,341,0.173021,0.116934,0.111671,0.173021,0.573210,0.134287,0.14956,2.463607e-02,f1_macro,0.111671,0.137255,NaN,shuffle_training_X_only
8,YEZ,8,336,1704,1704,341,0.205279,0.148987,0.146216,0.205279,0.606604,0.134287,0.14956,1.869477e-04,f1_macro,0.146216,0.019608,NaN,shuffle_training_X_only
9,YEZ,9,378,1704,1704,341,0.187683,0.134211,0.132239,0.187683,0.623931,0.134287,0.14956,3.477300e-03,f1_macro,0.132239,0.019608,NaN,shuffle_training_X_only
10,YEZ,10,420,1704,1704,341,0.167155,0.119034,0.112538,0.167155,0.595388,0.134287,0.14956,4.762541e-02,f1_macro,0.112538,0.156863,NaN,shuffle_training_X_only
11,YEZ,11,462,1704,1704,341,0.208211,0.150636,0.148663,0.208211,0.555570,0.134287,0.14956,1.082238e-04,f1_macro,0.148663,0.019608,NaN,shuffle_training_X_only
12,YEZ,12,504,1704,1704,341,0.161290,0.117188,0.113695,0.161290,0.621918,0.134287,0.14956,8.573629e-02,f1_macro,0.113695,0.117647,NaN,shuffle_training_X_only
13,YEZ,13,546,1704,1704,341,0.217009,0.159529,0.154901,0.217009,0.565141,0.134287,0.14956,1.900444e-05,f1_macro,0.154901,0.019608,NaN,shuffle_training_X_only
14,YEZ,14,588,1704,1704,341,0.208211,0.152195,0.149730,0.208211,0.581392,0.134287,0.14956,1.082238e-04,f1_macro,0.149730,0.019608,NaN,shuffle_training_X_only
15,YEZ,15,630,1704,1704,341,0.161290,0.119575,0.120050,0.161290,0.558108,0.134287,0.14956,8.573629e-02,f1_macro,0.120050,0.019608,NaN,shuffle_training_X_only
16,YEZ,16,672,1704,1704,341,0.222874,0.155977,0.150476,0.222874,0.564751,0.134287,0.14956,5.490868e-06,f1_macro,0.150476,0.019608,NaN,shuffle_training_X_only
17,YEZ,17,714,1704,1704,341,0.193548,0.141144,0.137650,0.193548,0.600336,0.134287,0.14956,1.405656e-03,f1_macro,0.137650,0.019608,NaN,shuffle_training_X_only
18,YEZ,18,756,1704,1704,341,0.187683,0.137222,0.132980,0.187683,0.589203,0.134287,0.14956,3.477300e-03,f1_macro,0.132980,0.019608,NaN,shuffle_training_X_only
19,YEZ,19,798,1704,1704,341,0.137830,0.103577,0.100186,0.137830,0.544887,0.134287,0.14956,4.476560e-01,f1_macro,0.100186,0.294118,NaN,shuffle_training_X_only

aggregated YEZ 2024-04-14 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YEZ/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-14/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YEZ,0,0,4627,4627,926,0.178186,0.146179,0.145176,0.178186,0.558263,0.118331,0.139309,6.981087e-08,f1_macro,0.145176,0.019608,0.140532,shuffle_training_X_only
1,YEZ,1,42,4627,4627,926,0.187905,0.144688,0.137605,0.187905,0.588170,0.118331,0.139309,6.208880e-10,f1_macro,0.137605,0.019608,0.142671,shuffle_training_X_only
2,YEZ,2,84,4627,4627,926,0.187905,0.140177,0.129393,0.187905,0.577575,0.118331,0.139309,6.208880e-10,f1_macro,0.129393,0.019608,0.142649,shuffle_training_X_only
3,YEZ,3,126,4627,4627,926,0.181425,0.144421,0.142621,0.181425,0.579496,0.118331,0.139309,1.540565e-08,f1_macro,0.142621,0.019608,NaN,shuffle_training_X_only
4,YEZ,4,168,4627,4627,926,0.183585,0.142987,0.138561,0.183585,0.595593,0.118331,0.139309,5.431132e-09,f1_macro,0.138561,0.019608,NaN,shuffle_training_X_only
5,YEZ,5,210,4627,4627,926,0.182505,0.139684,0.132343,0.182505,0.586716,0.118331,0.139309,9.179248e-09,f1_macro,0.132343,0.019608,NaN,shuffle_training_X_only
6,YEZ,6,252,4627,4627,926,0.185745,0.143941,0.138955,0.185745,0.584485,0.118331,0.139309,1.861964e-09,f1_macro,0.138955,0.019608,NaN,shuffle_training_X_only
7,YEZ,7,294,4627,4627,926,0.203024,0.156917,0.150720,0.203024,0.602317,0.118331,0.139309,1.332200e-13,f1_macro,0.150720,0.019608,NaN,shuffle_training_X_only
8,YEZ,8,336,4627,4627,926,0.167387,0.136271,0.135586,0.167387,0.574148,0.118331,0.139309,6.742522e-06,f1_macro,0.135586,0.019608,NaN,shuffle_training_X_only
9,YEZ,9,378,4627,4627,926,0.191145,0.147142,0.139263,0.191145,0.576805,0.118331,0.139309,1.135528e-10,f1_macro,0.139263,0.019608,NaN,shuffle_training_X_only
10,YEZ,10,420,4627,4627,926,0.186825,0.143949,0.137723,0.186825,0.590447,0.118331,0.139309,1.078926e-09,f1_macro,0.137723,0.019608,NaN,shuffle_training_X_only
11,YEZ,11,462,4627,4627,926,0.190065,0.146219,0.139031,0.190065,0.605478,0.118331,0.139309,2.014213e-10,f1_macro,0.139031,0.019608,NaN,shuffle_training_X_only
12,YEZ,12,504,4627,4627,926,0.191145,0.148313,0.142357,0.191145,0.586436,0.118331,0.139309,1.135528e-10,f1_macro,0.142357,0.019608,NaN,shuffle_training_X_only
13,YEZ,13,546,4627,4627,926,0.173866,0.134303,0.129097,0.173866,0.565279,0.118331,0.139309,4.738118e-07,f1_macro,0.129097,0.019608,NaN,shuffle_training_X_only
14,YEZ,14,588,4627,4627,926,0.203024,0.157853,0.151885,0.203024,0.601404,0.118331,0.139309,1.332200e-13,f1_macro,0.151885,0.019608,NaN,shuffle_training_X_only
15,YEZ,15,630,4627,4627,926,0.195464,0.153298,0.148413,0.195464,0.585308,0.118331,0.139309,1.071843e-11,f1_macro,0.148413,0.019608,NaN,shuffle_training_X_only
16,YEZ,16,672,4627,4627,926,0.172786,0.133608,0.128094,0.172786,0.570725,0.118331,0.139309,7.511313e-07,f1_macro,0.128094,0.019608,NaN,shuffle_training_X_only
17,YEZ,17,714,4627,4627,926,0.192225,0.147761,0.140635,0.192225,0.592213,0.118331,0.139309,6.358223e-11,f1_macro,0.140635,0.019608,NaN,shuffle_training_X_only
18,YEZ,18,756,4627,4627,926,0.184665,0.144219,0.139919,0.184665,0.572431,0.118331,0.139309,3.191107e-09,f1_macro,0.139919,0.019608,NaN,shuffle_training_X_only
19,YEZ,19,798,4627,4627,926,0.204104,0.158616,0.152265,0.204104,0.589695,0.118331,0.139309,6.932786e-14,f1_macro,0.152265,0.019608,NaN,shuffle_training_X_only

aggregated YEZ 2024-04-15 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YEZ/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-15/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YEZ,0,0,3662,3662,733,0.214188,0.143551,0.133133,0.214188,0.607318,0.137008,0.150068,7.853805e-09,f1_macro,0.133133,0.019608,0.137814,shuffle_training_X_only
1,YEZ,1,42,3662,3662,733,0.221010,0.148130,0.137425,0.221010,0.611744,0.137008,0.150068,4.479116e-10,f1_macro,0.137425,0.019608,0.141945,shuffle_training_X_only
2,YEZ,2,84,3662,3662,733,0.216917,0.147963,0.142745,0.216917,0.592109,0.137008,0.150068,2.556621e-09,f1_macro,0.142745,0.019608,0.142942,shuffle_training_X_only
3,YEZ,3,126,3662,3662,733,0.201910,0.135472,0.127462,0.201910,0.594955,0.137008,0.150068,8.282465e-07,f1_macro,0.127462,0.019608,NaN,shuffle_training_X_only
4,YEZ,4,168,3662,3662,733,0.210095,0.145738,0.143291,0.210095,0.592716,0.137008,0.150068,3.986518e-08,f1_macro,0.143291,0.019608,NaN,shuffle_training_X_only
5,YEZ,5,210,3662,3662,733,0.195089,0.130789,0.122508,0.195089,0.570457,0.137008,0.150068,8.303624e-06,f1_macro,0.122508,0.019608,NaN,shuffle_training_X_only
6,YEZ,6,252,3662,3662,733,0.189632,0.126947,0.120206,0.189632,0.597960,0.137008,0.150068,4.524647e-05,f1_macro,0.120206,0.019608,NaN,shuffle_training_X_only
7,YEZ,7,294,3662,3662,733,0.185539,0.124220,0.117329,0.185539,0.582061,0.137008,0.150068,1.477837e-04,f1_macro,0.117329,0.019608,NaN,shuffle_training_X_only
8,YEZ,8,336,3662,3662,733,0.184175,0.126316,0.122234,0.184175,0.592040,0.137008,0.150068,2.155925e-04,f1_macro,0.122234,0.019608,NaN,shuffle_training_X_only
9,YEZ,9,378,3662,3662,733,0.188267,0.128702,0.124899,0.188267,0.593742,0.137008,0.150068,6.770023e-05,f1_macro,0.124899,0.019608,NaN,shuffle_training_X_only
10,YEZ,10,420,3662,3662,733,0.197817,0.132916,0.126479,0.197817,0.561653,0.137008,0.150068,3.384611e-06,f1_macro,0.126479,0.019608,NaN,shuffle_training_X_only
11,YEZ,11,462,3662,3662,733,0.207367,0.138868,0.131462,0.207367,0.595437,0.137008,0.150068,1.131658e-07,f1_macro,0.131462,0.019608,NaN,shuffle_training_X_only
12,YEZ,12,504,3662,3662,733,0.208731,0.139983,0.130976,0.208731,0.589563,0.137008,0.150068,6.743497e-08,f1_macro,0.130976,0.019608,NaN,shuffle_training_X_only
13,YEZ,13,546,3662,3662,733,0.214188,0.143551,0.135929,0.214188,0.593669,0.137008,0.150068,7.853805e-09,f1_macro,0.135929,0.019608,NaN,shuffle_training_X_only
14,YEZ,14,588,3662,3662,733,0.190996,0.130484,0.125241,0.190996,0.580375,0.137008,0.150068,2.998730e-05,f1_macro,0.125241,0.019608,NaN,shuffle_training_X_only
15,YEZ,15,630,3662,3662,733,0.210095,0.140686,0.132464,0.210095,0.586730,0.137008,0.150068,3.986518e-08,f1_macro,0.132464,0.019608,NaN,shuffle_training_X_only
16,YEZ,16,672,3662,3662,733,0.226467,0.151938,0.144730,0.226467,0.588791,0.137008,0.150068,3.942363e-11,f1_macro,0.144730,0.019608,NaN,shuffle_training_X_only
17,YEZ,17,714,3662,3662,733,0.233288,0.166502,0.166686,0.233288,0.606980,0.137008,0.150068,1.593435e-12,f1_macro,0.166686,0.019608,NaN,shuffle_training_X_only
18,YEZ,18,756,3662,3662,733,0.215553,0.144460,0.136494,0.215553,0.597466,0.137008,0.150068,4.498543e-09,f1_macro,0.136494,0.019608,NaN,shuffle_training_X_only
19,YEZ,19,798,3662,3662,733,0.218281,0.148805,0.143745,0.218281,0.580011,0.137008,0.150068,1.441704e-09,f1_macro,0.143745,0.019608,NaN,shuffle_training_X_only

aggregated YFA 2024-04-23 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFA/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-23/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFA,0,0,4141,4141,829,0.166466,0.124865,0.119516,0.166466,0.571138,0.121374,0.141134,8.624772e-05,f1_macro,0.119516,0.019608,0.132335,shuffle_training_X_only
1,YFA,1,42,4141,4141,829,0.149578,0.113465,0.109146,0.149578,0.576600,0.121374,0.141134,8.800276e-03,f1_macro,0.109146,0.098039,0.132219,shuffle_training_X_only
2,YFA,2,84,4141,4141,829,0.171291,0.132193,0.129227,0.171291,0.583201,0.121374,0.141134,1.708476e-05,f1_macro,0.129227,0.019608,0.142354,shuffle_training_X_only
3,YFA,3,126,4141,4141,829,0.182147,0.139951,0.136394,0.182147,0.567233,0.121374,0.141134,2.799099e-07,f1_macro,0.136394,0.019608,NaN,shuffle_training_X_only
4,YFA,4,168,4141,4141,829,0.166466,0.129564,0.127073,0.166466,0.577200,0.121374,0.141134,8.624772e-05,f1_macro,0.127073,0.019608,NaN,shuffle_training_X_only
5,YFA,5,210,4141,4141,829,0.167672,0.134101,0.134835,0.167672,0.560908,0.121374,0.141134,5.824516e-05,f1_macro,0.134835,0.019608,NaN,shuffle_training_X_only
6,YFA,6,252,4141,4141,829,0.177322,0.135538,0.131780,0.177322,0.567937,0.121374,0.141134,1.883687e-06,f1_macro,0.131780,0.019608,NaN,shuffle_training_X_only
7,YFA,7,294,4141,4141,829,0.173703,0.140121,0.141335,0.173703,0.578664,0.121374,0.141134,7.244032e-06,f1_macro,0.141335,0.019608,NaN,shuffle_training_X_only
8,YFA,8,336,4141,4141,829,0.159228,0.123003,0.121333,0.159228,0.555945,0.121374,0.141134,7.649935e-04,f1_macro,0.121333,0.058824,NaN,shuffle_training_X_only
9,YFA,9,378,4141,4141,829,0.177322,0.139265,0.136520,0.177322,0.573684,0.121374,0.141134,1.883687e-06,f1_macro,0.136520,0.019608,NaN,shuffle_training_X_only
10,YFA,10,420,4141,4141,829,0.160434,0.124347,0.122238,0.160434,0.563339,0.121374,0.141134,5.428273e-04,f1_macro,0.122238,0.019608,NaN,shuffle_training_X_only
11,YFA,11,462,4141,4141,829,0.156815,0.121383,0.118421,0.156815,0.553122,0.121374,0.141134,1.481755e-03,f1_macro,0.118421,0.019608,NaN,shuffle_training_X_only
12,YFA,12,504,4141,4141,829,0.179735,0.140388,0.136710,0.179735,0.578467,0.121374,0.141134,7.376156e-07,f1_macro,0.136710,0.019608,NaN,shuffle_training_X_only
13,YFA,13,546,4141,4141,829,0.164053,0.125782,0.123523,0.164053,0.583598,0.121374,0.141134,1.845246e-04,f1_macro,0.123523,0.019608,NaN,shuffle_training_X_only
14,YFA,14,588,4141,4141,829,0.174910,0.136984,0.134344,0.174910,0.568386,0.121374,0.141134,4.660657e-06,f1_macro,0.134344,0.019608,NaN,shuffle_training_X_only
15,YFA,15,630,4141,4141,829,0.164053,0.131341,0.132033,0.164053,0.581483,0.121374,0.141134,1.845246e-04,f1_macro,0.132033,0.019608,NaN,shuffle_training_X_only
16,YFA,16,672,4141,4141,829,0.171291,0.132087,0.129087,0.171291,0.573918,0.121374,0.141134,1.708476e-05,f1_macro,0.129087,0.019608,NaN,shuffle_training_X_only
17,YFA,17,714,4141,4141,829,0.186972,0.144800,0.141374,0.186972,0.581469,0.121374,0.141134,3.672167e-08,f1_macro,0.141374,0.019608,NaN,shuffle_training_X_only
18,YFA,18,756,4141,4141,829,0.197829,0.152309,0.148036,0.197829,0.582185,0.121374,0.141134,2.436500e-10,f1_macro,0.148036,0.019608,NaN,shuffle_training_X_only
19,YFA,19,798,4141,4141,829,0.166466,0.125529,0.119994,0.166466,0.561537,0.121374,0.141134,8.624772e-05,f1_macro,0.119994,0.039216,NaN,shuffle_training_X_only

aggregated YFA 2024-04-24 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFA/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-24/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFA,0,0,14359,12653,2531,0.186883,0.145964,0.138186,0.186883,0.585803,0.117359,0.136705,2.738065e-24,f1_macro,0.138186,0.019608,0.138860,shuffle_training_X_only
1,YFA,1,42,14359,12682,2537,0.192747,0.146784,0.134397,0.192747,0.595934,0.117443,0.136382,5.827729e-28,f1_macro,0.134397,0.019608,0.136959,shuffle_training_X_only
2,YFA,2,84,14359,12665,2533,0.189499,0.145726,0.134004,0.189499,0.579739,0.117399,0.136992,6.904907e-26,f1_macro,0.134004,0.019608,0.140678,shuffle_training_X_only
3,YFA,3,126,14359,12677,2536,0.185726,0.143908,0.135929,0.185726,0.583946,0.117430,0.136435,1.390202e-23,f1_macro,0.135929,0.019608,NaN,shuffle_training_X_only
4,YFA,4,168,14359,12696,2540,0.183858,0.145630,0.139728,0.183858,0.577175,0.117488,0.137008,1.807422e-22,f1_macro,0.139728,0.019608,NaN,shuffle_training_X_only
5,YFA,5,210,14359,12631,2527,0.187574,0.147593,0.139911,0.187574,0.586973,0.117312,0.136526,1.042056e-24,f1_macro,0.139911,0.019608,NaN,shuffle_training_X_only
6,YFA,6,252,14359,12680,2536,0.197950,0.155347,0.147184,0.197950,0.591741,0.117430,0.136830,1.990746e-31,f1_macro,0.147184,0.019608,NaN,shuffle_training_X_only
7,YFA,7,294,14359,12654,2531,0.201106,0.158638,0.151303,0.201106,0.583185,0.117379,0.137100,1.321029e-33,f1_macro,0.151303,0.019608,NaN,shuffle_training_X_only
8,YFA,8,336,14359,12656,2532,0.202607,0.159978,0.152352,0.202607,0.589443,0.117370,0.136256,1.081948e-34,f1_macro,0.152352,0.019608,NaN,shuffle_training_X_only
9,YFA,9,378,14359,12630,2526,0.180918,0.141377,0.132968,0.180918,0.586312,0.117288,0.136580,8.221510e-21,f1_macro,0.132968,0.019608,NaN,shuffle_training_X_only
10,YFA,10,420,14359,12709,2542,0.188041,0.149151,0.144134,0.188041,0.575991,0.117512,0.136900,5.575676e-25,f1_macro,0.144134,0.019608,NaN,shuffle_training_X_only
11,YFA,11,462,14359,12650,2530,0.187352,0.149165,0.142569,0.187352,0.584306,0.117280,0.137154,1.265144e-24,f1_macro,0.142569,0.019608,NaN,shuffle_training_X_only
12,YFA,12,504,14359,12659,2532,0.170221,0.131509,0.123662,0.170221,0.568318,0.117392,0.136651,3.449229e-15,f1_macro,0.123662,0.019608,NaN,shuffle_training_X_only
13,YFA,13,546,14359,12622,2525,0.190495,0.150136,0.144363,0.190495,0.588499,0.117199,0.136634,1.362632e-26,f1_macro,0.144363,0.019608,NaN,shuffle_training_X_only
14,YFA,14,588,14359,12652,2531,0.182537,0.142845,0.135738,0.182537,0.580220,0.117375,0.136705,1.037748e-21,f1_macro,0.135738,0.019608,NaN,shuffle_training_X_only
15,YFA,15,630,14359,12663,2533,0.178839,0.142782,0.137948,0.178839,0.586357,0.117398,0.136597,1.236530e-19,f1_macro,0.137948,0.019608,NaN,shuffle_training_X_only
16,YFA,16,672,14359,12653,2531,0.191229,0.153559,0.149880,0.191229,0.589980,0.117372,0.136705,5.566116e-27,f1_macro,0.149880,0.019608,NaN,shuffle_training_X_only
17,YFA,17,714,14359,12683,2537,0.194324,0.153461,0.146657,0.194324,0.580843,0.117456,0.136382,5.561303e-29,f1_macro,0.146657,0.019608,NaN,shuffle_training_X_only
18,YFA,18,756,14359,12661,2533,0.180024,0.141729,0.134581,0.180024,0.580522,0.117305,0.136202,2.375464e-20,f1_macro,0.134581,0.019608,NaN,shuffle_training_X_only
19,YFA,19,798,14359,12668,2534,0.198500,0.155362,0.146827,0.198500,0.590561,0.117419,0.136938,8.603364e-32,f1_macro,0.146827,0.019608,NaN,shuffle_training_X_only

aggregated YFA 2024-04-25 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFA/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-25/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFA,0,0,11038,11038,2208,0.196105,0.145373,0.131959,0.196105,0.574086,0.120096,0.13904,1.303096e-24,f1_macro,0.131959,0.019608,0.134840,shuffle_training_X_only
1,YFA,1,42,11038,11038,2208,0.187047,0.143923,0.137599,0.187047,0.575566,0.120096,0.13904,8.868298e-20,f1_macro,0.137599,0.019608,0.134384,shuffle_training_X_only
2,YFA,2,84,11038,11038,2208,0.185236,0.139764,0.132306,0.185236,0.565001,0.120096,0.13904,7.140246e-19,f1_macro,0.132306,0.019608,0.132935,shuffle_training_X_only
3,YFA,3,126,11038,11038,2208,0.195199,0.148689,0.141518,0.195199,0.578552,0.120096,0.13904,4.175868e-24,f1_macro,0.141518,0.019608,NaN,shuffle_training_X_only
4,YFA,4,168,11038,11038,2208,0.181159,0.139621,0.133622,0.181159,0.570785,0.120096,0.13904,6.554679e-17,f1_macro,0.133622,0.019608,NaN,shuffle_training_X_only
5,YFA,5,210,11038,11038,2208,0.188406,0.143090,0.135548,0.188406,0.579075,0.120096,0.13904,1.798996e-20,f1_macro,0.135548,0.019608,NaN,shuffle_training_X_only
6,YFA,6,252,11038,11038,2208,0.172554,0.131349,0.124620,0.172554,0.577653,0.120096,0.13904,4.084485e-13,f1_macro,0.124620,0.019608,NaN,shuffle_training_X_only
7,YFA,7,294,11038,11038,2208,0.175272,0.137375,0.134470,0.175272,0.582447,0.120096,0.13904,2.915458e-14,f1_macro,0.134470,0.019608,NaN,shuffle_training_X_only
8,YFA,8,336,11038,11038,2208,0.189764,0.146024,0.140216,0.189764,0.570462,0.120096,0.13904,3.554633e-21,f1_macro,0.140216,0.019608,NaN,shuffle_training_X_only
9,YFA,9,378,11038,11038,2208,0.188406,0.141537,0.132534,0.188406,0.577273,0.120096,0.13904,1.798996e-20,f1_macro,0.132534,0.019608,NaN,shuffle_training_X_only
10,YFA,10,420,11038,11038,2208,0.187047,0.145895,0.141644,0.187047,0.592693,0.120096,0.13904,8.868298e-20,f1_macro,0.141644,0.019608,NaN,shuffle_training_X_only
11,YFA,11,462,11038,11038,2208,0.192482,0.145123,0.135489,0.192482,0.574572,0.120096,0.13904,1.283154e-22,f1_macro,0.135489,0.019608,NaN,shuffle_training_X_only
12,YFA,12,504,11038,11038,2208,0.192482,0.148136,0.142415,0.192482,0.577508,0.120096,0.13904,1.283154e-22,f1_macro,0.142415,0.019608,NaN,shuffle_training_X_only
13,YFA,13,546,11038,11038,2208,0.190670,0.148117,0.143597,0.190670,0.583421,0.120096,0.13904,1.188463e-21,f1_macro,0.143597,0.019608,NaN,shuffle_training_X_only
14,YFA,14,588,11038,11038,2208,0.182971,0.136864,0.127118,0.182971,0.581005,0.120096,0.13904,9.060048e-18,f1_macro,0.127118,0.019608,NaN,shuffle_training_X_only
15,YFA,15,630,11038,11038,2208,0.186141,0.140786,0.131697,0.186141,0.582685,0.120096,0.13904,2.531264e-19,f1_macro,0.131697,0.019608,NaN,shuffle_training_X_only
16,YFA,16,672,11038,11038,2208,0.197917,0.151703,0.144585,0.197917,0.590261,0.120096,0.13904,1.226431e-25,f1_macro,0.144585,0.019608,NaN,shuffle_training_X_only
17,YFA,17,714,11038,11038,2208,0.180707,0.137400,0.128954,0.180707,0.585873,0.120096,0.13904,1.066964e-16,f1_macro,0.128954,0.019608,NaN,shuffle_training_X_only
18,YFA,18,756,11038,11038,2208,0.181159,0.137820,0.130705,0.181159,0.578047,0.120096,0.13904,6.554679e-17,f1_macro,0.130705,0.019608,NaN,shuffle_training_X_only
19,YFA,19,798,11038,11038,2208,0.189312,0.143984,0.136288,0.189312,0.571884,0.120096,0.13904,6.120767e-21,f1_macro,0.136288,0.019608,NaN,shuffle_training_X_only

aggregated YFA 2024-04-26 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFA/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-26/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFA,0,0,9271,9271,1855,0.182210,0.134225,0.124544,0.182210,0.577471,0.121995,0.140162,5.195610e-14,f1_macro,0.124544,0.019608,0.130949,shuffle_training_X_only
1,YFA,1,42,9271,9271,1855,0.175741,0.128573,0.118843,0.175741,0.557561,0.121995,0.140162,1.261046e-11,f1_macro,0.118843,0.019608,0.131262,shuffle_training_X_only
2,YFA,2,84,9271,9271,1855,0.180593,0.137206,0.132220,0.180593,0.569294,0.121995,0.140162,2.152411e-13,f1_macro,0.132220,0.019608,0.138856,shuffle_training_X_only
3,YFA,3,126,9271,9271,1855,0.202156,0.152680,0.145175,0.202156,0.580674,0.121995,0.140162,9.708546e-23,f1_macro,0.145175,0.019608,NaN,shuffle_training_X_only
4,YFA,4,168,9271,9271,1855,0.179515,0.135470,0.128076,0.179515,0.566772,0.121995,0.140162,5.453864e-13,f1_macro,0.128076,0.019608,NaN,shuffle_training_X_only
5,YFA,5,210,9271,9271,1855,0.162803,0.120917,0.114126,0.162803,0.570601,0.121995,0.140162,1.524921e-07,f1_macro,0.114126,0.019608,NaN,shuffle_training_X_only
6,YFA,6,252,9271,9271,1855,0.180054,0.135668,0.128284,0.180054,0.570306,0.121995,0.140162,3.432349e-13,f1_macro,0.128284,0.019608,NaN,shuffle_training_X_only
7,YFA,7,294,9271,9271,1855,0.181132,0.136435,0.130547,0.181132,0.570953,0.121995,0.140162,1.344957e-13,f1_macro,0.130547,0.019608,NaN,shuffle_training_X_only
8,YFA,8,336,9271,9271,1855,0.189218,0.146629,0.143899,0.189218,0.579024,0.121995,0.140162,7.612246e-17,f1_macro,0.143899,0.019608,NaN,shuffle_training_X_only
9,YFA,9,378,9271,9271,1855,0.189218,0.141124,0.133308,0.189218,0.582785,0.121995,0.140162,7.612246e-17,f1_macro,0.133308,0.019608,NaN,shuffle_training_X_only
10,YFA,10,420,9271,9271,1855,0.181132,0.138376,0.133982,0.181132,0.564717,0.121995,0.140162,1.344957e-13,f1_macro,0.133982,0.019608,NaN,shuffle_training_X_only
11,YFA,11,462,9271,9271,1855,0.195687,0.145727,0.137989,0.195687,0.576091,0.121995,0.140162,1.096418e-19,f1_macro,0.137989,0.019608,NaN,shuffle_training_X_only
12,YFA,12,504,9271,9271,1855,0.194609,0.144029,0.136063,0.194609,0.573941,0.121995,0.140162,3.375744e-19,f1_macro,0.136063,0.019608,NaN,shuffle_training_X_only
13,YFA,13,546,9271,9271,1855,0.178437,0.131170,0.121677,0.178437,0.574610,0.121995,0.140162,1.362250e-12,f1_macro,0.121677,0.019608,NaN,shuffle_training_X_only
14,YFA,14,588,9271,9271,1855,0.184906,0.139045,0.131708,0.184906,0.575173,0.121995,0.140162,4.529418e-15,f1_macro,0.131708,0.019608,NaN,shuffle_training_X_only
15,YFA,15,630,9271,9271,1855,0.194609,0.146194,0.139099,0.194609,0.581792,0.121995,0.140162,3.375744e-19,f1_macro,0.139099,0.019608,NaN,shuffle_training_X_only
16,YFA,16,672,9271,9271,1855,0.188140,0.144791,0.141093,0.188140,0.557787,0.121995,0.140162,2.158812e-16,f1_macro,0.141093,0.019608,NaN,shuffle_training_X_only
17,YFA,17,714,9271,9271,1855,0.182210,0.137016,0.130807,0.182210,0.572948,0.121995,0.140162,5.195610e-14,f1_macro,0.130807,0.019608,NaN,shuffle_training_X_only
18,YFA,18,756,9271,9271,1855,0.189757,0.141441,0.133866,0.189757,0.578991,0.121995,0.140162,4.496844e-17,f1_macro,0.133866,0.019608,NaN,shuffle_training_X_only
19,YFA,19,798,9271,9271,1855,0.177358,0.135418,0.131580,0.177358,0.573315,0.121995,0.140162,3.353958e-12,f1_macro,0.131580,0.019608,NaN,shuffle_training_X_only

aggregated YFA 2024-04-27 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFA/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-27/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFA,0,0,18659,17526,3506,0.198517,0.147548,0.138273,0.198517,0.576823,0.121934,0.142327,4.231145e-38,f1_macro,0.138273,0.019608,0.136109,shuffle_training_X_only
1,YFA,1,42,18659,17548,3510,0.203419,0.149734,0.137562,0.203419,0.573295,0.122037,0.142450,1.766462e-42,f1_macro,0.137562,0.019608,0.134088,shuffle_training_X_only
2,YFA,2,84,18659,17556,3512,0.186788,0.138475,0.129373,0.186788,0.569677,0.122061,0.142654,2.629456e-28,f1_macro,0.129373,0.019608,0.139709,shuffle_training_X_only
3,YFA,3,126,18659,17537,3508,0.188141,0.139542,0.130447,0.188141,0.569470,0.122072,0.142246,2.565889e-29,f1_macro,0.130447,0.019608,NaN,shuffle_training_X_only
4,YFA,4,168,18659,17558,3512,0.192198,0.141798,0.132101,0.192198,0.568688,0.122120,0.142938,1.456535e-32,f1_macro,0.132101,0.019608,NaN,shuffle_training_X_only
5,YFA,5,210,18659,17542,3509,0.195212,0.144467,0.134398,0.195212,0.566912,0.122087,0.142776,4.284045e-35,f1_macro,0.134398,0.019608,NaN,shuffle_training_X_only
6,YFA,6,252,18659,17495,3499,0.191197,0.145215,0.139721,0.191197,0.571607,0.121980,0.142612,9.019850e-32,f1_macro,0.139721,0.019608,NaN,shuffle_training_X_only
7,YFA,7,294,18659,17565,3513,0.196698,0.144722,0.134400,0.196698,0.579613,0.122120,0.142044,2.244362e-36,f1_macro,0.134400,0.019608,NaN,shuffle_training_X_only
8,YFA,8,336,18659,17541,3509,0.193502,0.145575,0.137952,0.193502,0.578620,0.122085,0.142206,1.181939e-33,f1_macro,0.137952,0.019608,NaN,shuffle_training_X_only
9,YFA,9,378,18659,17542,3509,0.184098,0.137625,0.130539,0.184098,0.567408,0.122080,0.142206,3.129638e-26,f1_macro,0.130539,0.019608,NaN,shuffle_training_X_only
10,YFA,10,420,18659,17530,3506,0.189675,0.142856,0.136083,0.189675,0.570884,0.122050,0.142042,1.553450e-30,f1_macro,0.136083,0.019608,NaN,shuffle_training_X_only
11,YFA,11,462,18659,17536,3508,0.188997,0.141329,0.133124,0.188997,0.570122,0.122017,0.142531,4.824468e-30,f1_macro,0.133124,0.019608,NaN,shuffle_training_X_only
12,YFA,12,504,18659,17542,3509,0.188943,0.142429,0.135691,0.188943,0.566805,0.122084,0.142206,6.054400e-30,f1_macro,0.135691,0.019608,NaN,shuffle_training_X_only
13,YFA,13,546,18659,17550,3510,0.195726,0.145523,0.136872,0.195726,0.579096,0.122093,0.142450,1.543761e-35,f1_macro,0.136872,0.019608,NaN,shuffle_training_X_only
14,YFA,14,588,18659,17551,3511,0.197949,0.148566,0.140921,0.197949,0.580247,0.122105,0.142694,1.830745e-37,f1_macro,0.140921,0.019608,NaN,shuffle_training_X_only
15,YFA,15,630,18659,17538,3508,0.188141,0.141826,0.135333,0.188141,0.568806,0.122075,0.142816,2.583191e-29,f1_macro,0.135333,0.019608,NaN,shuffle_training_X_only
16,YFA,16,672,18659,17527,3506,0.178551,0.132397,0.123924,0.178551,0.556687,0.122058,0.143183,2.891230e-22,f1_macro,0.123924,0.019608,NaN,shuffle_training_X_only
17,YFA,17,714,18659,17517,3504,0.196062,0.145038,0.134955,0.196062,0.566068,0.122036,0.142694,7.924355e-36,f1_macro,0.134955,0.019608,NaN,shuffle_training_X_only
18,YFA,18,756,18659,17526,3506,0.197946,0.150209,0.144147,0.197946,0.567141,0.122000,0.142327,1.590931e-37,f1_macro,0.144147,0.019608,NaN,shuffle_training_X_only
19,YFA,19,798,18659,17554,3511,0.192823,0.143173,0.134343,0.192823,0.572643,0.122101,0.142125,4.340704e-33,f1_macro,0.134343,0.019608,NaN,shuffle_training_X_only

aggregated YFA 2024-04-28 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFA/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-28/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFA,0,0,12671,12671,2535,0.188560,0.158390,0.154102,0.188560,0.585204,0.118139,0.130966,9.179459e-25,f1_macro,0.154102,0.019608,0.145620,shuffle_training_X_only
1,YFA,1,42,12671,12671,2535,0.185010,0.154779,0.149337,0.185010,0.583340,0.118139,0.130966,1.222078e-22,f1_macro,0.149337,0.019608,0.147171,shuffle_training_X_only
2,YFA,2,84,12671,12671,2535,0.175542,0.147287,0.143373,0.175542,0.588592,0.118139,0.130966,2.012540e-17,f1_macro,0.143373,0.019608,0.146876,shuffle_training_X_only
3,YFA,3,126,12671,12671,2535,0.190927,0.160889,0.159356,0.190927,0.585539,0.118139,0.130966,3.138426e-26,f1_macro,0.159356,0.019608,NaN,shuffle_training_X_only
4,YFA,4,168,12671,12671,2535,0.179487,0.152753,0.149917,0.179487,0.584052,0.118139,0.130966,1.622916e-19,f1_macro,0.149917,0.019608,NaN,shuffle_training_X_only
5,YFA,5,210,12671,12671,2535,0.182249,0.154315,0.152598,0.182249,0.587906,0.118139,0.130966,4.747927e-21,f1_macro,0.152598,0.019608,NaN,shuffle_training_X_only
6,YFA,6,252,12671,12671,2535,0.179487,0.156570,0.157576,0.179487,0.592864,0.118139,0.130966,1.622916e-19,f1_macro,0.157576,0.019608,NaN,shuffle_training_X_only
7,YFA,7,294,12671,12671,2535,0.184615,0.150235,0.144974,0.184615,0.581743,0.118139,0.130966,2.077489e-22,f1_macro,0.144974,0.019608,NaN,shuffle_training_X_only
8,YFA,8,336,12671,12671,2535,0.171203,0.142974,0.140757,0.171203,0.573277,0.118139,0.130966,2.963675e-15,f1_macro,0.140757,0.019608,NaN,shuffle_training_X_only
9,YFA,9,378,12671,12671,2535,0.194477,0.161191,0.157394,0.194477,0.579649,0.118139,0.130966,1.673272e-28,f1_macro,0.157394,0.019608,NaN,shuffle_training_X_only
10,YFA,10,420,12671,12671,2535,0.167653,0.136999,0.133263,0.167653,0.583055,0.118139,0.130966,1.377404e-13,f1_macro,0.133263,0.019608,NaN,shuffle_training_X_only
11,YFA,11,462,12671,12671,2535,0.171203,0.143228,0.140454,0.171203,0.576349,0.118139,0.130966,2.963675e-15,f1_macro,0.140454,0.019608,NaN,shuffle_training_X_only
12,YFA,12,504,12671,12671,2535,0.191321,0.157292,0.154511,0.191321,0.598138,0.118139,0.130966,1.772187e-26,f1_macro,0.154511,0.019608,NaN,shuffle_training_X_only
13,YFA,13,546,12671,12671,2535,0.172781,0.142801,0.140218,0.172781,0.580525,0.118139,0.130966,5.010852e-16,f1_macro,0.140218,0.019608,NaN,shuffle_training_X_only
14,YFA,14,588,12671,12671,2535,0.175542,0.149482,0.146346,0.175542,0.574597,0.118139,0.130966,2.012540e-17,f1_macro,0.146346,0.019608,NaN,shuffle_training_X_only
15,YFA,15,630,12671,12671,2535,0.186982,0.156053,0.154059,0.186982,0.586248,0.118139,0.130966,8.281153e-24,f1_macro,0.154059,0.019608,NaN,shuffle_training_X_only
16,YFA,16,672,12671,12671,2535,0.176331,0.148604,0.145630,0.176331,0.577499,0.118139,0.130966,7.840090e-18,f1_macro,0.145630,0.019608,NaN,shuffle_training_X_only
17,YFA,17,714,12671,12671,2535,0.183037,0.153815,0.152419,0.183037,0.579157,0.118139,0.130966,1.690584e-21,f1_macro,0.152419,0.019608,NaN,shuffle_training_X_only
18,YFA,18,756,12671,12671,2535,0.182643,0.153545,0.149875,0.182643,0.581174,0.118139,0.130966,2.836854e-21,f1_macro,0.149875,0.019608,NaN,shuffle_training_X_only
19,YFA,19,798,12671,12671,2535,0.187377,0.156139,0.155826,0.187377,0.582555,0.118139,0.130966,4.796667e-24,f1_macro,0.155826,0.019608,NaN,shuffle_training_X_only

aggregated YFA 2024-04-29 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFA/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-29/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFA,0,0,13671,13671,2735,0.196709,0.158200,0.151206,0.196709,0.594007,0.116524,0.13309,1.133658e-33,f1_macro,0.151206,0.019608,0.152438,shuffle_training_X_only
1,YFA,1,42,13671,13671,2735,0.182084,0.151142,0.149473,0.182084,0.597955,0.116524,0.13309,1.121484e-23,f1_macro,0.149473,0.019608,0.152061,shuffle_training_X_only
2,YFA,2,84,13671,13671,2735,0.191225,0.155198,0.150067,0.191225,0.593256,0.116524,0.13309,9.872179e-30,f1_macro,0.150067,0.019608,0.148789,shuffle_training_X_only
3,YFA,3,126,13671,13671,2735,0.179890,0.143883,0.137630,0.179890,0.592694,0.116524,0.13309,2.546402e-22,f1_macro,0.137630,0.019608,NaN,shuffle_training_X_only
4,YFA,4,168,13671,13671,2735,0.191225,0.155928,0.151478,0.191225,0.596240,0.116524,0.13309,9.872179e-30,f1_macro,0.151478,0.019608,NaN,shuffle_training_X_only
5,YFA,5,210,13671,13671,2735,0.186106,0.150078,0.145109,0.186106,0.594108,0.116524,0.13309,2.918877e-26,f1_macro,0.145109,0.019608,NaN,shuffle_training_X_only
6,YFA,6,252,13671,13671,2735,0.191225,0.156040,0.152375,0.191225,0.602503,0.116524,0.13309,9.872179e-30,f1_macro,0.152375,0.019608,NaN,shuffle_training_X_only
7,YFA,7,294,13671,13671,2735,0.191956,0.156837,0.150885,0.191956,0.605585,0.116524,0.13309,3.035383e-30,f1_macro,0.150885,0.019608,NaN,shuffle_training_X_only
8,YFA,8,336,13671,13671,2735,0.184278,0.153589,0.152736,0.184278,0.603047,0.116524,0.13309,4.525928e-25,f1_macro,0.152736,0.019608,NaN,shuffle_training_X_only
9,YFA,9,378,13671,13671,2735,0.194150,0.160157,0.157545,0.194150,0.590554,0.116524,0.13309,8.342724e-32,f1_macro,0.157545,0.019608,NaN,shuffle_training_X_only
10,YFA,10,420,13671,13671,2735,0.190859,0.156543,0.152496,0.190859,0.597605,0.116524,0.13309,1.774138e-29,f1_macro,0.152496,0.019608,NaN,shuffle_training_X_only
11,YFA,11,462,13671,13671,2735,0.185375,0.152639,0.149865,0.185375,0.597885,0.116524,0.13309,8.801078e-26,f1_macro,0.149865,0.019608,NaN,shuffle_training_X_only
12,YFA,12,504,13671,13671,2735,0.190128,0.153770,0.147783,0.190128,0.590648,0.116524,0.13309,5.689549e-29,f1_macro,0.147783,0.019608,NaN,shuffle_training_X_only
13,YFA,13,546,13671,13671,2735,0.189397,0.156291,0.155094,0.189397,0.592343,0.116524,0.13309,1.807513e-28,f1_macro,0.155094,0.019608,NaN,shuffle_training_X_only
14,YFA,14,588,13671,13671,2735,0.194150,0.156360,0.150002,0.194150,0.594852,0.116524,0.13309,8.342724e-32,f1_macro,0.150002,0.019608,NaN,shuffle_training_X_only
15,YFA,15,630,13671,13671,2735,0.183547,0.149923,0.145610,0.183547,0.592930,0.116524,0.13309,1.332291e-24,f1_macro,0.145610,0.019608,NaN,shuffle_training_X_only
16,YFA,16,672,13671,13671,2735,0.187203,0.151353,0.146579,0.187203,0.598646,0.116524,0.13309,5.475921e-27,f1_macro,0.146579,0.019608,NaN,shuffle_training_X_only
17,YFA,17,714,13671,13671,2735,0.193053,0.156685,0.150715,0.193053,0.592782,0.116524,0.13309,5.085198e-31,f1_macro,0.150715,0.019608,NaN,shuffle_training_X_only
18,YFA,18,756,13671,13671,2735,0.193053,0.155955,0.150826,0.193053,0.593645,0.116524,0.13309,5.085198e-31,f1_macro,0.150826,0.019608,NaN,shuffle_training_X_only
19,YFA,19,798,13671,13671,2735,0.185740,0.150271,0.145957,0.185740,0.600213,0.116524,0.13309,5.074525e-26,f1_macro,0.145957,0.019608,NaN,shuffle_training_X_only

aggregated YFA 2024-04-30 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFA/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-04-30/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFA,0,0,12854,12854,2571,0.183586,0.140638,0.133838,0.183586,0.580389,0.120688,0.134967,2.411661e-20,f1_macro,0.133838,0.019608,0.137328,shuffle_training_X_only
1,YFA,1,42,12854,12854,2571,0.185142,0.142364,0.133261,0.185142,0.593135,0.120688,0.134967,3.217471e-21,f1_macro,0.133261,0.019608,0.134335,shuffle_training_X_only
2,YFA,2,84,12854,12854,2571,0.185142,0.146845,0.142498,0.185142,0.570619,0.120688,0.134967,3.217471e-21,f1_macro,0.142498,0.019608,0.136156,shuffle_training_X_only
3,YFA,3,126,12854,12854,2571,0.184753,0.142029,0.134510,0.184753,0.574049,0.120688,0.134967,5.344137e-21,f1_macro,0.134510,0.019608,NaN,shuffle_training_X_only
4,YFA,4,168,12854,12854,2571,0.178919,0.141325,0.137704,0.178919,0.564541,0.120688,0.134967,7.934338e-18,f1_macro,0.137704,0.019608,NaN,shuffle_training_X_only
5,YFA,5,210,12854,12854,2571,0.190198,0.147462,0.140946,0.190198,0.577014,0.120688,0.134967,3.489625e-24,f1_macro,0.140946,0.019608,NaN,shuffle_training_X_only
6,YFA,6,252,12854,12854,2571,0.194477,0.150010,0.143107,0.194477,0.588348,0.120688,0.134967,7.777490e-27,f1_macro,0.143107,0.019608,NaN,shuffle_training_X_only
7,YFA,7,294,12854,12854,2571,0.180863,0.142293,0.136534,0.180863,0.581744,0.120688,0.134967,7.418767e-19,f1_macro,0.136534,0.019608,NaN,shuffle_training_X_only
8,YFA,8,336,12854,12854,2571,0.166861,0.131077,0.127466,0.166861,0.577162,0.120688,0.134967,4.363351e-12,f1_macro,0.127466,0.019608,NaN,shuffle_training_X_only
9,YFA,9,378,12854,12854,2571,0.188254,0.147305,0.141629,0.188254,0.589821,0.120688,0.134967,5.069279e-23,f1_macro,0.141629,0.019608,NaN,shuffle_training_X_only
10,YFA,10,420,12854,12854,2571,0.176196,0.134585,0.127677,0.176196,0.568953,0.120688,0.134967,1.962180e-16,f1_macro,0.127677,0.019608,NaN,shuffle_training_X_only
11,YFA,11,462,12854,12854,2571,0.180086,0.142014,0.138433,0.180086,0.574448,0.120688,0.134967,1.929246e-18,f1_macro,0.138433,0.019608,NaN,shuffle_training_X_only
12,YFA,12,504,12854,12854,2571,0.180086,0.140927,0.136385,0.180086,0.581615,0.120688,0.134967,1.929246e-18,f1_macro,0.136385,0.019608,NaN,shuffle_training_X_only
13,YFA,13,546,12854,12854,2571,0.180863,0.139707,0.133819,0.180863,0.575331,0.120688,0.134967,7.418767e-19,f1_macro,0.133819,0.019608,NaN,shuffle_training_X_only
14,YFA,14,588,12854,12854,2571,0.174640,0.135041,0.129156,0.174640,0.576336,0.120688,0.134967,1.158027e-15,f1_macro,0.129156,0.019608,NaN,shuffle_training_X_only
15,YFA,15,630,12854,12854,2571,0.179697,0.141037,0.136859,0.179697,0.577647,0.120688,0.134967,3.099025e-18,f1_macro,0.136859,0.019608,NaN,shuffle_training_X_only
16,YFA,16,672,12854,12854,2571,0.196422,0.152276,0.145712,0.196422,0.578588,0.120688,0.134967,4.391242e-28,f1_macro,0.145712,0.019608,NaN,shuffle_training_X_only
17,YFA,17,714,12854,12854,2571,0.169973,0.133372,0.129737,0.169973,0.579103,0.120688,0.134967,1.843328e-13,f1_macro,0.129737,0.019608,NaN,shuffle_training_X_only
18,YFA,18,756,12854,12854,2571,0.176974,0.136548,0.130353,0.176974,0.579705,0.120688,0.134967,7.950088e-17,f1_macro,0.130353,0.019608,NaN,shuffle_training_X_only
19,YFA,19,798,12854,12854,2571,0.169195,0.132203,0.127418,0.169195,0.575353,0.120688,0.134967,4.132721e-13,f1_macro,0.127418,0.019608,NaN,shuffle_training_X_only

aggregated YFA 2024-05-01 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFA/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-05-01/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFA,0,0,719,719,144,0.125000,0.092143,0.085503,0.125000,0.511763,0.118441,0.138889,0.441547,f1_macro,0.085503,0.588235,0.142489,shuffle_training_X_only
1,YFA,1,42,719,719,144,0.187500,0.147143,0.129840,0.187500,0.605540,0.118441,0.138889,0.010523,f1_macro,0.129840,0.019608,0.125392,shuffle_training_X_only
2,YFA,2,84,719,719,144,0.152778,0.116667,0.108981,0.152778,0.527438,0.118441,0.138889,0.127419,f1_macro,0.108981,0.215686,0.144425,shuffle_training_X_only
3,YFA,3,126,719,719,144,0.173611,0.139286,0.134822,0.173611,0.528489,0.118441,0.138889,0.032304,f1_macro,0.134822,0.039216,NaN,shuffle_training_X_only
4,YFA,4,168,719,719,144,0.138889,0.125952,0.126701,0.138889,0.525571,0.118441,0.138889,0.257796,f1_macro,0.126701,0.156863,NaN,shuffle_training_X_only
5,YFA,5,210,719,719,144,0.166667,0.132143,0.128254,0.166667,0.584213,0.118441,0.138889,0.053219,f1_macro,0.128254,0.137255,NaN,shuffle_training_X_only
6,YFA,6,252,719,719,144,0.180556,0.137619,0.129234,0.180556,0.604089,0.118441,0.138889,0.018817,f1_macro,0.129234,0.098039,NaN,shuffle_training_X_only
7,YFA,7,294,719,719,144,0.152778,0.133810,0.138894,0.152778,0.576303,0.118441,0.138889,0.127419,f1_macro,0.138894,0.098039,NaN,shuffle_training_X_only
8,YFA,8,336,719,719,144,0.208333,0.161905,0.157072,0.208333,0.553860,0.118441,0.138889,0.001449,f1_macro,0.157072,0.019608,NaN,shuffle_training_X_only
9,YFA,9,378,719,719,144,0.111111,0.083333,0.075104,0.111111,0.562804,0.118441,0.138889,0.645387,f1_macro,0.075104,0.745098,NaN,shuffle_training_X_only
10,YFA,10,420,719,719,144,0.166667,0.135238,0.131838,0.166667,0.553351,0.118441,0.138889,0.053219,f1_macro,0.131838,0.137255,NaN,shuffle_training_X_only
11,YFA,11,462,719,719,144,0.111111,0.080000,0.078064,0.111111,0.517639,0.118441,0.138889,0.645387,f1_macro,0.078064,0.862745,NaN,shuffle_training_X_only
12,YFA,12,504,719,719,144,0.152778,0.118810,0.110694,0.152778,0.573826,0.118441,0.138889,0.127419,f1_macro,0.110694,0.333333,NaN,shuffle_training_X_only
13,YFA,13,546,719,719,144,0.152778,0.125000,0.119247,0.152778,0.523237,0.118441,0.138889,0.127419,f1_macro,0.119247,0.117647,NaN,shuffle_training_X_only
14,YFA,14,588,719,719,144,0.187500,0.148333,0.138180,0.187500,0.585061,0.118441,0.138889,0.010523,f1_macro,0.138180,0.019608,NaN,shuffle_training_X_only
15,YFA,15,630,719,719,144,0.173611,0.149286,0.156891,0.173611,0.596428,0.118441,0.138889,0.032304,f1_macro,0.156891,0.019608,NaN,shuffle_training_X_only
16,YFA,16,672,719,719,144,0.097222,0.077619,0.072271,0.097222,0.545904,0.118441,0.138889,0.819270,f1_macro,0.072271,0.784314,NaN,shuffle_training_X_only
17,YFA,17,714,719,719,144,0.194444,0.147619,0.137796,0.194444,0.540254,0.118441,0.138889,0.005653,f1_macro,0.137796,0.039216,NaN,shuffle_training_X_only
18,YFA,18,756,719,719,144,0.159722,0.124643,0.111250,0.159722,0.562796,0.118441,0.138889,0.084094,f1_macro,0.111250,0.254902,NaN,shuffle_training_X_only
19,YFA,19,798,719,719,144,0.152778,0.123333,0.110680,0.152778,0.576122,0.118441,0.138889,0.127419,f1_macro,0.110680,0.196078,NaN,shuffle_training_X_only

aggregated YFB 2024-05-02 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFB/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-05-02/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFB,0,0,839,839,168,0.172619,0.138859,0.132871,0.172619,0.539687,0.115859,0.130952,0.018588,f1_macro,0.132871,0.078431,0.141949,shuffle_training_X_only
1,YFB,1,42,839,839,168,0.125000,0.104422,0.106492,0.125000,0.524317,0.115859,0.130952,0.390318,f1_macro,0.106492,0.352941,0.111060,shuffle_training_X_only
2,YFB,2,84,839,839,168,0.113095,0.095004,0.095063,0.113095,0.556607,0.115859,0.130952,0.580324,f1_macro,0.095063,0.352941,0.124432,shuffle_training_X_only
3,YFB,3,126,839,839,168,0.166667,0.140931,0.141259,0.166667,0.543395,0.115859,0.130952,0.030955,f1_macro,0.141259,0.019608,NaN,shuffle_training_X_only
4,YFB,4,168,839,839,168,0.142857,0.121416,0.117578,0.142857,0.536104,0.115859,0.130952,0.164599,f1_macro,0.117578,0.078431,NaN,shuffle_training_X_only
5,YFB,5,210,839,839,168,0.130952,0.110515,0.103298,0.130952,0.541225,0.115859,0.130952,0.303634,f1_macro,0.103298,0.509804,NaN,shuffle_training_X_only
6,YFB,6,252,839,839,168,0.136905,0.108556,0.099969,0.136905,0.562704,0.115859,0.130952,0.227734,f1_macro,0.099969,0.372549,NaN,shuffle_training_X_only
7,YFB,7,294,839,839,168,0.178571,0.153023,0.153535,0.178571,0.544679,0.115859,0.130952,0.010765,f1_macro,0.153535,0.019608,NaN,shuffle_training_X_only
8,YFB,8,336,839,839,168,0.178571,0.146878,0.143338,0.178571,0.573371,0.115859,0.130952,0.010765,f1_macro,0.143338,0.039216,NaN,shuffle_training_X_only
9,YFB,9,378,839,839,168,0.130952,0.124433,0.133233,0.130952,0.555396,0.115859,0.130952,0.303634,f1_macro,0.133233,0.058824,NaN,shuffle_training_X_only
10,YFB,10,420,839,839,168,0.125000,0.100948,0.096885,0.125000,0.510799,0.115859,0.130952,0.390318,f1_macro,0.096885,0.509804,NaN,shuffle_training_X_only
11,YFB,11,462,839,839,168,0.130952,0.105821,0.105606,0.130952,0.559972,0.115859,0.130952,0.303634,f1_macro,0.105606,0.313725,NaN,shuffle_training_X_only
12,YFB,12,504,839,839,168,0.130952,0.105021,0.097706,0.130952,0.560046,0.115859,0.130952,0.303634,f1_macro,0.097706,0.568627,NaN,shuffle_training_X_only
13,YFB,13,546,839,839,168,0.148810,0.117647,0.107080,0.148810,0.568261,0.115859,0.130952,0.114615,f1_macro,0.107080,0.313725,NaN,shuffle_training_X_only
14,YFB,14,588,839,839,168,0.130952,0.107724,0.102474,0.130952,0.543557,0.115859,0.130952,0.303634,f1_macro,0.102474,0.333333,NaN,shuffle_training_X_only
15,YFB,15,630,839,839,168,0.190476,0.155316,0.150540,0.190476,0.550086,0.115859,0.130952,0.003245,f1_macro,0.150540,0.039216,NaN,shuffle_training_X_only
16,YFB,16,672,839,839,168,0.119048,0.095393,0.090713,0.119048,0.532019,0.115859,0.130952,0.484179,f1_macro,0.090713,0.529412,NaN,shuffle_training_X_only
17,YFB,17,714,839,839,168,0.160714,0.133569,0.131279,0.160714,0.553482,0.115859,0.130952,0.049695,f1_macro,0.131279,0.078431,NaN,shuffle_training_X_only
18,YFB,18,756,839,839,168,0.130952,0.110188,0.107794,0.130952,0.607962,0.115859,0.130952,0.303634,f1_macro,0.107794,0.176471,NaN,shuffle_training_X_only
19,YFB,19,798,839,839,168,0.142857,0.119606,0.117624,0.142857,0.528453,0.115859,0.130952,0.164599,f1_macro,0.117624,0.254902,NaN,shuffle_training_X_only

aggregated YFB 2024-05-03 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFB/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-05-03/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFB,0,0,2215,2215,443,0.218962,0.160690,0.152192,0.218962,0.592988,0.125662,0.142212,3.359249e-08,f1_macro,0.152192,0.019608,0.143611,shuffle_training_X_only
1,YFB,1,42,2215,2215,443,0.167043,0.126441,0.123997,0.167043,0.578734,0.125662,0.142212,6.756894e-03,f1_macro,0.123997,0.039216,0.139042,shuffle_training_X_only
2,YFB,2,84,2215,2215,443,0.209932,0.158585,0.155277,0.209932,0.598118,0.125662,0.142212,4.686988e-07,f1_macro,0.155277,0.019608,0.130765,shuffle_training_X_only
3,YFB,3,126,2215,2215,443,0.185102,0.145233,0.150695,0.185102,0.582552,0.125662,0.142212,2.207534e-04,f1_macro,0.150695,0.019608,NaN,shuffle_training_X_only
4,YFB,4,168,2215,2215,443,0.167043,0.122525,0.117499,0.167043,0.596578,0.125662,0.142212,6.756894e-03,f1_macro,0.117499,0.019608,NaN,shuffle_training_X_only
5,YFB,5,210,2215,2215,443,0.173815,0.130375,0.127174,0.173815,0.593353,0.125662,0.142212,2.085168e-03,f1_macro,0.127174,0.019608,NaN,shuffle_training_X_only
6,YFB,6,252,2215,2215,443,0.167043,0.124319,0.122697,0.167043,0.591916,0.125662,0.142212,6.756894e-03,f1_macro,0.122697,0.019608,NaN,shuffle_training_X_only
7,YFB,7,294,2215,2215,443,0.169300,0.123100,0.117446,0.169300,0.561121,0.125662,0.142212,4.632615e-03,f1_macro,0.117446,0.039216,NaN,shuffle_training_X_only
8,YFB,8,336,2215,2215,443,0.155756,0.115562,0.112176,0.155756,0.567656,0.125662,0.142212,3.582872e-02,f1_macro,0.112176,0.156863,NaN,shuffle_training_X_only
9,YFB,9,378,2215,2215,443,0.173815,0.133333,0.132673,0.173815,0.568782,0.125662,0.142212,2.085168e-03,f1_macro,0.132673,0.039216,NaN,shuffle_training_X_only
10,YFB,10,420,2215,2215,443,0.155756,0.115699,0.111198,0.155756,0.548265,0.125662,0.142212,3.582872e-02,f1_macro,0.111198,0.137255,NaN,shuffle_training_X_only
11,YFB,11,462,2215,2215,443,0.171558,0.126521,0.121934,0.171558,0.589956,0.125662,0.142212,3.130510e-03,f1_macro,0.121934,0.019608,NaN,shuffle_training_X_only
12,YFB,12,504,2215,2215,443,0.171558,0.134704,0.136089,0.171558,0.574854,0.125662,0.142212,3.130510e-03,f1_macro,0.136089,0.019608,NaN,shuffle_training_X_only
13,YFB,13,546,2215,2215,443,0.196388,0.146796,0.143191,0.196388,0.563908,0.125662,0.142212,1.648240e-05,f1_macro,0.143191,0.019608,NaN,shuffle_training_X_only
14,YFB,14,588,2215,2215,443,0.180587,0.133721,0.128716,0.180587,0.591930,0.125662,0.142212,5.655140e-04,f1_macro,0.128716,0.039216,NaN,shuffle_training_X_only
15,YFB,15,630,2215,2215,443,0.212190,0.162296,0.161931,0.212190,0.608508,0.125662,0.142212,2.472579e-07,f1_macro,0.161931,0.019608,NaN,shuffle_training_X_only
16,YFB,16,672,2215,2215,443,0.196388,0.156827,0.159555,0.196388,0.589203,0.125662,0.142212,1.648240e-05,f1_macro,0.159555,0.019608,NaN,shuffle_training_X_only
17,YFB,17,714,2215,2215,443,0.205418,0.153699,0.151238,0.205418,0.591716,0.125662,0.142212,1.619322e-06,f1_macro,0.151238,0.019608,NaN,shuffle_training_X_only
18,YFB,18,756,2215,2215,443,0.180587,0.140491,0.142842,0.180587,0.601997,0.125662,0.142212,5.655140e-04,f1_macro,0.142842,0.019608,NaN,shuffle_training_X_only
19,YFB,19,798,2215,2215,443,0.189616,0.144171,0.142355,0.189616,0.587554,0.125662,0.142212,8.148979e-05,f1_macro,0.142355,0.019608,NaN,shuffle_training_X_only

aggregated YFB 2024-05-04 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFB/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-05-04/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFB,0,0,3379,3379,676,0.208580,0.150315,0.143912,0.208580,0.572309,0.127285,0.147929,2.470758e-09,f1_macro,0.143912,0.019608,0.136129,shuffle_training_X_only
1,YFB,1,42,3379,3379,676,0.192308,0.144799,0.145157,0.192308,0.598631,0.127285,0.147929,1.119890e-06,f1_macro,0.145157,0.019608,0.131115,shuffle_training_X_only
2,YFB,2,84,3379,3379,676,0.202663,0.147385,0.143034,0.202663,0.572147,0.127285,0.147929,2.587022e-08,f1_macro,0.143034,0.019608,0.137037,shuffle_training_X_only
3,YFB,3,126,3379,3379,676,0.214497,0.158418,0.153224,0.214497,0.579799,0.127285,0.147929,2.053302e-10,f1_macro,0.153224,0.019608,NaN,shuffle_training_X_only
4,YFB,4,168,3379,3379,676,0.177515,0.133709,0.132290,0.177515,0.600290,0.127285,0.147929,1.118467e-04,f1_macro,0.132290,0.019608,NaN,shuffle_training_X_only
5,YFB,5,210,3379,3379,676,0.204142,0.149017,0.143887,0.204142,0.589732,0.127285,0.147929,1.457232e-08,f1_macro,0.143887,0.019608,NaN,shuffle_training_X_only
6,YFB,6,252,3379,3379,676,0.204142,0.148608,0.145279,0.204142,0.570315,0.127285,0.147929,1.457232e-08,f1_macro,0.145279,0.019608,NaN,shuffle_training_X_only
7,YFB,7,294,3379,3379,676,0.164201,0.116601,0.109963,0.164201,0.550884,0.127285,0.147929,3.129438e-03,f1_macro,0.109963,0.058824,NaN,shuffle_training_X_only
8,YFB,8,336,3379,3379,676,0.187870,0.130268,0.119931,0.187870,0.567349,0.127285,0.147929,4.913550e-06,f1_macro,0.119931,0.039216,NaN,shuffle_training_X_only
9,YFB,9,378,3379,3379,676,0.171598,0.122009,0.117230,0.171598,0.577238,0.127285,0.147929,5.415586e-04,f1_macro,0.117230,0.019608,NaN,shuffle_training_X_only
10,YFB,10,420,3379,3379,676,0.167160,0.118942,0.112647,0.167160,0.580715,0.127285,0.147929,1.597459e-03,f1_macro,0.112647,0.039216,NaN,shuffle_training_X_only
11,YFB,11,462,3379,3379,676,0.201183,0.143526,0.137465,0.201183,0.566880,0.127285,0.147929,4.552289e-08,f1_macro,0.137465,0.019608,NaN,shuffle_training_X_only
12,YFB,12,504,3379,3379,676,0.186391,0.135977,0.130341,0.186391,0.547999,0.127285,0.147929,7.897035e-06,f1_macro,0.130341,0.019608,NaN,shuffle_training_X_only
13,YFB,13,546,3379,3379,676,0.205621,0.144125,0.135719,0.205621,0.588173,0.127285,0.147929,8.136393e-09,f1_macro,0.135719,0.019608,NaN,shuffle_training_X_only
14,YFB,14,588,3379,3379,676,0.211538,0.153015,0.148072,0.211538,0.598317,0.127285,0.147929,7.246480e-10,f1_macro,0.148072,0.019608,NaN,shuffle_training_X_only
15,YFB,15,630,3379,3379,676,0.181953,0.129641,0.123809,0.181953,0.571541,0.127285,0.147929,3.100375e-05,f1_macro,0.123809,0.039216,NaN,shuffle_training_X_only
16,YFB,16,672,3379,3379,676,0.180473,0.128233,0.122191,0.180473,0.589947,0.127285,0.147929,4.800155e-05,f1_macro,0.122191,0.039216,NaN,shuffle_training_X_only
17,YFB,17,714,3379,3379,676,0.178994,0.130859,0.128145,0.178994,0.562393,0.127285,0.147929,7.362022e-05,f1_macro,0.128145,0.019608,NaN,shuffle_training_X_only
18,YFB,18,756,3379,3379,676,0.180473,0.129117,0.123960,0.180473,0.574770,0.127285,0.147929,4.800155e-05,f1_macro,0.123960,0.019608,NaN,shuffle_training_X_only
19,YFB,19,798,3379,3379,676,0.201183,0.149350,0.148381,0.201183,0.548554,0.127285,0.147929,4.552289e-08,f1_macro,0.148381,0.019608,NaN,shuffle_training_X_only

aggregated YFB 2024-05-05 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFB/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-05-05/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFB,0,0,4129,4129,826,0.174334,0.134399,0.130439,0.174334,0.568986,0.120983,0.139225,5.054823e-06,f1_macro,0.130439,0.019608,0.127834,shuffle_training_X_only
1,YFB,1,42,4129,4129,826,0.194915,0.153121,0.149256,0.194915,0.572753,0.120983,0.139225,8.464936e-10,f1_macro,0.149256,0.019608,0.138464,shuffle_training_X_only
2,YFB,2,84,4129,4129,826,0.187651,0.140406,0.132422,0.187651,0.579711,0.120983,0.139225,2.350286e-08,f1_macro,0.132422,0.019608,0.132024,shuffle_training_X_only
3,YFB,3,126,4129,4129,826,0.182809,0.137749,0.129987,0.182809,0.596847,0.120983,0.139225,1.849052e-07,f1_macro,0.129987,0.019608,NaN,shuffle_training_X_only
4,YFB,4,168,4129,4129,826,0.164649,0.127596,0.125352,0.164649,0.558455,0.120983,0.139225,1.369398e-04,f1_macro,0.125352,0.019608,NaN,shuffle_training_X_only
5,YFB,5,210,4129,4129,826,0.159806,0.126723,0.125742,0.159806,0.553616,0.120983,0.139225,5.851760e-04,f1_macro,0.125742,0.019608,NaN,shuffle_training_X_only
6,YFB,6,252,4129,4129,826,0.180387,0.142282,0.140663,0.180387,0.572943,0.120983,0.139225,4.949848e-07,f1_macro,0.140663,0.019608,NaN,shuffle_training_X_only
7,YFB,7,294,4129,4129,826,0.171913,0.134564,0.132499,0.171913,0.579404,0.120983,0.139225,1.210795e-05,f1_macro,0.132499,0.019608,NaN,shuffle_training_X_only
8,YFB,8,336,4129,4129,826,0.192494,0.147615,0.143507,0.192494,0.579696,0.120983,0.139225,2.642098e-09,f1_macro,0.143507,0.019608,NaN,shuffle_training_X_only
9,YFB,9,378,4129,4129,826,0.199758,0.149923,0.141750,0.199758,0.578768,0.120983,0.139225,7.943503e-11,f1_macro,0.141750,0.019608,NaN,shuffle_training_X_only
10,YFB,10,420,4129,4129,826,0.179177,0.140006,0.136577,0.179177,0.578681,0.120983,0.139225,8.003834e-07,f1_macro,0.136577,0.019608,NaN,shuffle_training_X_only
11,YFB,11,462,4129,4129,826,0.169492,0.126465,0.119738,0.169492,0.543810,0.120983,0.139225,2.808014e-05,f1_macro,0.119738,0.019608,NaN,shuffle_training_X_only
12,YFB,12,504,4129,4129,826,0.180387,0.138371,0.133891,0.180387,0.582703,0.120983,0.139225,4.949848e-07,f1_macro,0.133891,0.019608,NaN,shuffle_training_X_only
13,YFB,13,546,4129,4129,826,0.174334,0.132651,0.128777,0.174334,0.564970,0.120983,0.139225,5.054823e-06,f1_macro,0.128777,0.019608,NaN,shuffle_training_X_only
14,YFB,14,588,4129,4129,826,0.187651,0.142297,0.136854,0.187651,0.587172,0.120983,0.139225,2.350286e-08,f1_macro,0.136854,0.019608,NaN,shuffle_training_X_only
15,YFB,15,630,4129,4129,826,0.174334,0.131527,0.124351,0.174334,0.583093,0.120983,0.139225,5.054823e-06,f1_macro,0.124351,0.019608,NaN,shuffle_training_X_only
16,YFB,16,672,4129,4129,826,0.174334,0.134913,0.128203,0.174334,0.556592,0.120983,0.139225,5.054823e-06,f1_macro,0.128203,0.019608,NaN,shuffle_training_X_only
17,YFB,17,714,4129,4129,826,0.173123,0.129588,0.122605,0.173123,0.569192,0.120983,0.139225,7.854818e-06,f1_macro,0.122605,0.019608,NaN,shuffle_training_X_only
18,YFB,18,756,4129,4129,826,0.169492,0.125692,0.117676,0.169492,0.581905,0.120983,0.139225,2.808014e-05,f1_macro,0.117676,0.039216,NaN,shuffle_training_X_only
19,YFB,19,798,4129,4129,826,0.192494,0.143159,0.133927,0.192494,0.583375,0.120983,0.139225,2.642098e-09,f1_macro,0.133927,0.019608,NaN,shuffle_training_X_only

aggregated YFB 2024-05-06 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFB/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-05-06/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFB,0,0,2419,2419,484,0.175620,0.135801,0.134101,0.175620,0.572927,0.124906,0.140496,7.860334e-04,f1_macro,0.134101,0.019608,0.146117,shuffle_training_X_only
1,YFB,1,42,2419,2419,484,0.194215,0.164888,0.176442,0.194215,0.587103,0.124906,0.140496,9.768848e-06,f1_macro,0.176442,0.019608,0.134651,shuffle_training_X_only
2,YFB,2,84,2419,2419,484,0.169421,0.131477,0.130376,0.169421,0.534235,0.124906,0.140496,2.683447e-03,f1_macro,0.130376,0.039216,0.147529,shuffle_training_X_only
3,YFB,3,126,2419,2419,484,0.183884,0.145146,0.146083,0.183884,0.595661,0.124906,0.140496,1.271875e-04,f1_macro,0.146083,0.019608,NaN,shuffle_training_X_only
4,YFB,4,168,2419,2419,484,0.171488,0.128917,0.126974,0.171488,0.557242,0.124906,0.140496,1.805978e-03,f1_macro,0.126974,0.019608,NaN,shuffle_training_X_only
5,YFB,5,210,2419,2419,484,0.169421,0.125496,0.120158,0.169421,0.574947,0.124906,0.140496,2.683447e-03,f1_macro,0.120158,0.058824,NaN,shuffle_training_X_only
6,YFB,6,252,2419,2419,484,0.173554,0.130627,0.126658,0.173554,0.585699,0.124906,0.140496,1.199369e-03,f1_macro,0.126658,0.019608,NaN,shuffle_training_X_only
7,YFB,7,294,2419,2419,484,0.200413,0.161037,0.166742,0.200413,0.563113,0.124906,0.140496,1.800811e-06,f1_macro,0.166742,0.019608,NaN,shuffle_training_X_only
8,YFB,8,336,2419,2419,484,0.163223,0.125005,0.123299,0.163223,0.560205,0.124906,0.140496,8.122977e-03,f1_macro,0.123299,0.058824,NaN,shuffle_training_X_only
9,YFB,9,378,2419,2419,484,0.177686,0.134232,0.131761,0.177686,0.576837,0.124906,0.140496,5.083993e-04,f1_macro,0.131761,0.019608,NaN,shuffle_training_X_only
10,YFB,10,420,2419,2419,484,0.179752,0.148177,0.152025,0.179752,0.562083,0.124906,0.140496,3.245440e-04,f1_macro,0.152025,0.019608,NaN,shuffle_training_X_only
11,YFB,11,462,2419,2419,484,0.190083,0.145091,0.144474,0.190083,0.560603,0.124906,0.140496,2.832996e-05,f1_macro,0.144474,0.019608,NaN,shuffle_training_X_only
12,YFB,12,504,2419,2419,484,0.148760,0.110768,0.106621,0.148760,0.541516,0.124906,0.140496,6.701326e-02,f1_macro,0.106621,0.235294,NaN,shuffle_training_X_only
13,YFB,13,546,2419,2419,484,0.179752,0.132676,0.127523,0.179752,0.588307,0.124906,0.140496,3.245440e-04,f1_macro,0.127523,0.019608,NaN,shuffle_training_X_only
14,YFB,14,588,2419,2419,484,0.169421,0.125650,0.120674,0.169421,0.584285,0.124906,0.140496,2.683447e-03,f1_macro,0.120674,0.058824,NaN,shuffle_training_X_only
15,YFB,15,630,2419,2419,484,0.190083,0.138339,0.131177,0.190083,0.556645,0.124906,0.140496,2.832996e-05,f1_macro,0.131177,0.019608,NaN,shuffle_training_X_only
16,YFB,16,672,2419,2419,484,0.165289,0.122207,0.115584,0.165289,0.557259,0.124906,0.140496,5.691375e-03,f1_macro,0.115584,0.039216,NaN,shuffle_training_X_only
17,YFB,17,714,2419,2419,484,0.159091,0.123183,0.122872,0.159091,0.565869,0.124906,0.140496,1.588861e-02,f1_macro,0.122872,0.039216,NaN,shuffle_training_X_only
18,YFB,18,756,2419,2419,484,0.190083,0.145486,0.143574,0.190083,0.591057,0.124906,0.140496,2.832996e-05,f1_macro,0.143574,0.019608,NaN,shuffle_training_X_only
19,YFB,19,798,2419,2419,484,0.202479,0.157706,0.158049,0.202479,0.586372,0.124906,0.140496,9.998399e-07,f1_macro,0.158049,0.019608,NaN,shuffle_training_X_only

aggregated YFB 2024-05-07 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFB/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-05-07/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFB,0,0,3125,3125,625,0.1600,0.130828,0.126156,0.1600,0.557466,0.113682,0.1296,3.114541e-04,f1_macro,0.126156,0.039216,0.138495,shuffle_training_X_only
1,YFB,1,42,3125,3125,625,0.1552,0.127316,0.123097,0.1552,0.557963,0.113682,0.1296,1.045320e-03,f1_macro,0.123097,0.019608,0.130695,shuffle_training_X_only
2,YFB,2,84,3125,3125,625,0.1840,0.160419,0.162359,0.1840,0.572731,0.113682,0.1296,1.686504e-07,f1_macro,0.162359,0.019608,0.133335,shuffle_training_X_only
3,YFB,3,126,3125,3125,625,0.1840,0.155215,0.153752,0.1840,0.566623,0.113682,0.1296,1.686504e-07,f1_macro,0.153752,0.019608,NaN,shuffle_training_X_only
4,YFB,4,168,3125,3125,625,0.1664,0.136774,0.131834,0.1664,0.553830,0.113682,0.1296,5.308234e-05,f1_macro,0.131834,0.039216,NaN,shuffle_training_X_only
5,YFB,5,210,3125,3125,625,0.1472,0.123545,0.120489,0.1472,0.556560,0.113682,0.1296,6.277651e-03,f1_macro,0.120489,0.039216,NaN,shuffle_training_X_only
6,YFB,6,252,3125,3125,625,0.1760,0.145195,0.139468,0.1760,0.560853,0.113682,0.1296,2.698699e-06,f1_macro,0.139468,0.019608,NaN,shuffle_training_X_only
7,YFB,7,294,3125,3125,625,0.1584,0.127436,0.120413,0.1584,0.561109,0.113682,0.1296,4.715466e-04,f1_macro,0.120413,0.039216,NaN,shuffle_training_X_only
8,YFB,8,336,3125,3125,625,0.1520,0.125090,0.122488,0.1520,0.546260,0.113682,0.1296,2.215386e-03,f1_macro,0.122488,0.078431,NaN,shuffle_training_X_only
9,YFB,9,378,3125,3125,625,0.1568,0.129917,0.126020,0.1568,0.579710,0.113682,0.1296,7.060201e-04,f1_macro,0.126020,0.039216,NaN,shuffle_training_X_only
10,YFB,10,420,3125,3125,625,0.1568,0.132333,0.131513,0.1568,0.571762,0.113682,0.1296,7.060201e-04,f1_macro,0.131513,0.019608,NaN,shuffle_training_X_only
11,YFB,11,462,3125,3125,625,0.1568,0.129013,0.124245,0.1568,0.568026,0.113682,0.1296,7.060201e-04,f1_macro,0.124245,0.019608,NaN,shuffle_training_X_only
12,YFB,12,504,3125,3125,625,0.1536,0.129202,0.126308,0.1536,0.565918,0.113682,0.1296,1.530384e-03,f1_macro,0.126308,0.039216,NaN,shuffle_training_X_only
13,YFB,13,546,3125,3125,625,0.1504,0.130826,0.128567,0.1504,0.556684,0.113682,0.1296,3.170861e-03,f1_macro,0.128567,0.019608,NaN,shuffle_training_X_only
14,YFB,14,588,3125,3125,625,0.1504,0.124739,0.118836,0.1504,0.552796,0.113682,0.1296,3.170861e-03,f1_macro,0.118836,0.039216,NaN,shuffle_training_X_only
15,YFB,15,630,3125,3125,625,0.1568,0.128773,0.124531,0.1568,0.539456,0.113682,0.1296,7.060201e-04,f1_macro,0.124531,0.039216,NaN,shuffle_training_X_only
16,YFB,16,672,3125,3125,625,0.1712,0.141148,0.136054,0.1712,0.568372,0.113682,0.1296,1.255931e-05,f1_macro,0.136054,0.019608,NaN,shuffle_training_X_only
17,YFB,17,714,3125,3125,625,0.1840,0.152077,0.149353,0.1840,0.546785,0.113682,0.1296,1.686504e-07,f1_macro,0.149353,0.019608,NaN,shuffle_training_X_only
18,YFB,18,756,3125,3125,625,0.1520,0.126171,0.123986,0.1520,0.552931,0.113682,0.1296,2.215386e-03,f1_macro,0.123986,0.019608,NaN,shuffle_training_X_only
19,YFB,19,798,3125,3125,625,0.1312,0.108642,0.103562,0.1312,0.540549,0.113682,0.1296,9.577701e-02,f1_macro,0.103562,0.156863,NaN,shuffle_training_X_only

aggregated YFB 2024-05-08 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFB/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-05-08/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFB,0,0,2603,2603,521,0.195777,0.141109,0.133859,0.195777,0.608685,0.128407,0.145873,0.000010,f1_macro,0.133859,0.019608,0.129906,shuffle_training_X_only
1,YFB,1,42,2603,2603,521,0.176583,0.129121,0.127217,0.176583,0.563625,0.128407,0.145873,0.000997,f1_macro,0.127217,0.019608,0.145881,shuffle_training_X_only
2,YFB,2,84,2603,2603,521,0.172745,0.121619,0.115759,0.172745,0.554996,0.128407,0.145873,0.002182,f1_macro,0.115759,0.058824,0.136894,shuffle_training_X_only
3,YFB,3,126,2603,2603,521,0.161228,0.114894,0.110838,0.161228,0.570350,0.128407,0.145873,0.017002,f1_macro,0.110838,0.058824,NaN,shuffle_training_X_only
4,YFB,4,168,2603,2603,521,0.203455,0.150574,0.146828,0.203455,0.593027,0.128407,0.145873,0.000001,f1_macro,0.146828,0.019608,NaN,shuffle_training_X_only
5,YFB,5,210,2603,2603,521,0.203455,0.155356,0.157630,0.203455,0.551513,0.128407,0.145873,0.000001,f1_macro,0.157630,0.019608,NaN,shuffle_training_X_only
6,YFB,6,252,2603,2603,521,0.197697,0.142870,0.139099,0.197697,0.574023,0.128407,0.145873,0.000006,f1_macro,0.139099,0.019608,NaN,shuffle_training_X_only
7,YFB,7,294,2603,2603,521,0.197697,0.145178,0.141678,0.197697,0.581057,0.128407,0.145873,0.000006,f1_macro,0.141678,0.019608,NaN,shuffle_training_X_only
8,YFB,8,336,2603,2603,521,0.186180,0.134474,0.129381,0.186180,0.584813,0.128407,0.145873,0.000114,f1_macro,0.129381,0.019608,NaN,shuffle_training_X_only
9,YFB,9,378,2603,2603,521,0.165067,0.120502,0.117730,0.165067,0.549180,0.128407,0.145873,0.009012,f1_macro,0.117730,0.039216,NaN,shuffle_training_X_only
10,YFB,10,420,2603,2603,521,0.182342,0.133513,0.130219,0.182342,0.551880,0.128407,0.145873,0.000281,f1_macro,0.130219,0.019608,NaN,shuffle_training_X_only
11,YFB,11,462,2603,2603,521,0.176583,0.130011,0.127112,0.176583,0.571800,0.128407,0.145873,0.000997,f1_macro,0.127112,0.039216,NaN,shuffle_training_X_only
12,YFB,12,504,2603,2603,521,0.182342,0.135097,0.132317,0.182342,0.577739,0.128407,0.145873,0.000281,f1_macro,0.132317,0.019608,NaN,shuffle_training_X_only
13,YFB,13,546,2603,2603,521,0.174664,0.130279,0.130537,0.174664,0.540972,0.128407,0.145873,0.001484,f1_macro,0.130537,0.019608,NaN,shuffle_training_X_only
14,YFB,14,588,2603,2603,521,0.193858,0.148889,0.152243,0.193858,0.556362,0.128407,0.145873,0.000016,f1_macro,0.152243,0.019608,NaN,shuffle_training_X_only
15,YFB,15,630,2603,2603,521,0.180422,0.125911,0.118593,0.180422,0.568178,0.128407,0.145873,0.000434,f1_macro,0.118593,0.039216,NaN,shuffle_training_X_only
16,YFB,16,672,2603,2603,521,0.170825,0.130679,0.132203,0.170825,0.583606,0.128407,0.145873,0.003169,f1_macro,0.132203,0.019608,NaN,shuffle_training_X_only
17,YFB,17,714,2603,2603,521,0.195777,0.143417,0.139682,0.195777,0.544150,0.128407,0.145873,0.000010,f1_macro,0.139682,0.019608,NaN,shuffle_training_X_only
18,YFB,18,756,2603,2603,521,0.193858,0.137874,0.132211,0.193858,0.571293,0.128407,0.145873,0.000016,f1_macro,0.132211,0.019608,NaN,shuffle_training_X_only
19,YFB,19,798,2603,2603,521,0.172745,0.122566,0.117750,0.172745,0.557439,0.128407,0.145873,0.002182,f1_macro,0.117750,0.019608,NaN,shuffle_training_X_only

aggregated YFB 2024-05-09 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFB/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-05-09/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFB,0,0,3451,3451,691,0.189580,0.129026,0.121393,0.189580,0.587082,0.133725,0.147612,2.451277e-05,f1_macro,0.121393,0.039216,0.127347,shuffle_training_X_only
1,YFB,1,42,3451,3451,691,0.204052,0.138919,0.130497,0.204052,0.565532,0.133725,0.147612,2.041998e-07,f1_macro,0.130497,0.019608,0.132619,shuffle_training_X_only
2,YFB,2,84,3451,3451,691,0.179450,0.121925,0.115334,0.179450,0.583130,0.133725,0.147612,4.123778e-04,f1_macro,0.115334,0.078431,0.129586,shuffle_training_X_only
3,YFB,3,126,3451,3451,691,0.185239,0.128288,0.123911,0.185239,0.581922,0.133725,0.147612,8.675916e-05,f1_macro,0.123911,0.039216,NaN,shuffle_training_X_only
4,YFB,4,168,3451,3451,691,0.175109,0.127144,0.128126,0.175109,0.563373,0.133725,0.147612,1.206068e-03,f1_macro,0.128126,0.019608,NaN,shuffle_training_X_only
5,YFB,5,210,3451,3451,691,0.185239,0.125847,0.118396,0.185239,0.569415,0.133725,0.147612,8.675916e-05,f1_macro,0.118396,0.019608,NaN,shuffle_training_X_only
6,YFB,6,252,3451,3451,691,0.189580,0.135400,0.132464,0.189580,0.578617,0.133725,0.147612,2.451277e-05,f1_macro,0.132464,0.019608,NaN,shuffle_training_X_only
7,YFB,7,294,3451,3451,691,0.202605,0.140053,0.135710,0.202605,0.559879,0.133725,0.147612,3.427662e-07,f1_macro,0.135710,0.019608,NaN,shuffle_training_X_only
8,YFB,8,336,3451,3451,691,0.185239,0.129482,0.125533,0.185239,0.573761,0.133725,0.147612,8.675916e-05,f1_macro,0.125533,0.019608,NaN,shuffle_training_X_only
9,YFB,9,378,3451,3451,691,0.164978,0.112270,0.105320,0.164978,0.587746,0.133725,0.147612,1.067038e-02,f1_macro,0.105320,0.215686,NaN,shuffle_training_X_only
10,YFB,10,420,3451,3451,691,0.176556,0.122406,0.118766,0.176556,0.552609,0.133725,0.147612,8.511490e-04,f1_macro,0.118766,0.039216,NaN,shuffle_training_X_only
11,YFB,11,462,3451,3451,691,0.172214,0.117053,0.110336,0.172214,0.554443,0.133725,0.147612,2.355431e-03,f1_macro,0.110336,0.098039,NaN,shuffle_training_X_only
12,YFB,12,504,3451,3451,691,0.180897,0.123292,0.117048,0.180897,0.539881,0.133725,0.147612,2.831234e-04,f1_macro,0.117048,0.058824,NaN,shuffle_training_X_only
13,YFB,13,546,3451,3451,691,0.199711,0.137973,0.132194,0.199711,0.573712,0.133725,0.147612,9.411305e-07,f1_macro,0.132194,0.019608,NaN,shuffle_training_X_only
14,YFB,14,588,3451,3451,691,0.198263,0.134908,0.128294,0.198263,0.584109,0.133725,0.147612,1.539320e-06,f1_macro,0.128294,0.019608,NaN,shuffle_training_X_only
15,YFB,15,630,3451,3451,691,0.191027,0.132032,0.127438,0.191027,0.549269,0.133725,0.147612,1.579970e-05,f1_macro,0.127438,0.019608,NaN,shuffle_training_X_only
16,YFB,16,672,3451,3451,691,0.179450,0.122133,0.114290,0.179450,0.567802,0.133725,0.147612,4.123778e-04,f1_macro,0.114290,0.039216,NaN,shuffle_training_X_only
17,YFB,17,714,3451,3451,691,0.170767,0.116191,0.109820,0.170767,0.563338,0.133725,0.147612,3.246250e-03,f1_macro,0.109820,0.078431,NaN,shuffle_training_X_only
18,YFB,18,756,3451,3451,691,0.167873,0.119772,0.118538,0.167873,0.557599,0.133725,0.147612,5.996322e-03,f1_macro,0.118538,0.019608,NaN,shuffle_training_X_only
19,YFB,19,798,3451,3451,691,0.176556,0.122347,0.116973,0.176556,0.570657,0.133725,0.147612,8.511490e-04,f1_macro,0.116973,0.058824,NaN,shuffle_training_X_only

aggregated YFB 2024-05-10 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFB/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-05-10/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFB,0,0,2706,2508,502,0.155378,0.108999,0.104709,0.155378,0.545630,0.131490,0.153386,6.697750e-02,f1_macro,0.104709,0.333333,0.161575,shuffle_training_X_only
1,YFB,1,42,2706,2510,502,0.201195,0.146628,0.146203,0.201195,0.582965,0.131474,0.151394,8.715125e-06,f1_macro,0.146203,0.019608,0.136743,shuffle_training_X_only
2,YFB,2,84,2706,2514,503,0.224652,0.162433,0.157419,0.224652,0.536816,0.131991,0.153082,9.215831e-09,f1_macro,0.157419,0.019608,0.133457,shuffle_training_X_only
3,YFB,3,126,2706,2511,503,0.165010,0.122844,0.126090,0.165010,0.563241,0.131549,0.151093,1.778654e-02,f1_macro,0.126090,0.039216,NaN,shuffle_training_X_only
4,YFB,4,168,2706,2512,503,0.198807,0.136204,0.126340,0.198807,0.552208,0.131557,0.153082,1.641596e-05,f1_macro,0.126340,0.039216,NaN,shuffle_training_X_only
5,YFB,5,210,2706,2509,502,0.199203,0.141869,0.138293,0.199203,0.565836,0.131887,0.151394,1.671013e-05,f1_macro,0.138293,0.019608,NaN,shuffle_training_X_only
6,YFB,6,252,2706,2521,505,0.207921,0.146203,0.141335,0.207921,0.557199,0.131677,0.152475,1.365863e-06,f1_macro,0.141335,0.019608,NaN,shuffle_training_X_only
7,YFB,7,294,2706,2508,502,0.167331,0.117742,0.112659,0.167331,0.555676,0.131474,0.151394,1.225735e-02,f1_macro,0.112659,0.039216,NaN,shuffle_training_X_only
8,YFB,8,336,2706,2508,502,0.187251,0.128842,0.119199,0.187251,0.552440,0.131474,0.151394,2.647832e-04,f1_macro,0.119199,0.019608,NaN,shuffle_training_X_only
9,YFB,9,378,2706,2504,501,0.209581,0.145871,0.139387,0.209581,0.567903,0.131836,0.151697,9.845062e-07,f1_macro,0.139387,0.019608,NaN,shuffle_training_X_only
10,YFB,10,420,2706,2521,505,0.203960,0.147900,0.147301,0.203960,0.554433,0.131709,0.152475,4.191966e-06,f1_macro,0.147301,0.019608,NaN,shuffle_training_X_only
11,YFB,11,462,2706,2516,504,0.196429,0.143450,0.143556,0.196429,0.553373,0.131630,0.152778,3.026184e-05,f1_macro,0.143556,0.019608,NaN,shuffle_training_X_only
12,YFB,12,504,2706,2511,503,0.190855,0.134018,0.128486,0.190855,0.537990,0.131533,0.151093,1.161117e-04,f1_macro,0.128486,0.019608,NaN,shuffle_training_X_only
13,YFB,13,546,2706,2503,501,0.175649,0.123478,0.119697,0.175649,0.560505,0.131398,0.151697,2.855326e-03,f1_macro,0.119697,0.058824,NaN,shuffle_training_X_only
14,YFB,14,588,2706,2513,503,0.196819,0.137100,0.133477,0.196819,0.592484,0.131991,0.153082,3.108501e-05,f1_macro,0.133477,0.039216,NaN,shuffle_training_X_only
15,YFB,15,630,2706,2506,502,0.207171,0.147718,0.145048,0.207171,0.583376,0.131498,0.151394,1.702615e-06,f1_macro,0.145048,0.019608,NaN,shuffle_training_X_only
16,YFB,16,672,2706,2510,502,0.173307,0.125593,0.124376,0.173307,0.541731,0.131474,0.151394,4.423486e-03,f1_macro,0.124376,0.019608,NaN,shuffle_training_X_only
17,YFB,17,714,2706,2517,504,0.180556,0.124070,0.117119,0.180556,0.574120,0.131630,0.152778,1.120938e-03,f1_macro,0.117119,0.039216,NaN,shuffle_training_X_only
18,YFB,18,756,2706,2500,500,0.188000,0.137720,0.139522,0.188000,0.560179,0.131768,0.152000,2.482078e-04,f1_macro,0.139522,0.019608,NaN,shuffle_training_X_only
19,YFB,19,798,2706,2516,504,0.160714,0.112738,0.108561,0.160714,0.541604,0.131630,0.152778,3.367183e-02,f1_macro,0.108561,0.176471,NaN,shuffle_training_X_only

aggregated YFC 2024-07-18 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFC/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-07-18/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFC,0,0,129,129,26,0.076923,0.074074,0.063492,0.076923,0.497182,0.112426,0.115385,0.806753,f1_macro,0.063492,0.705882,0.219466,shuffle_training_X_only
1,YFC,1,42,129,129,26,0.153846,0.148148,0.157672,0.153846,0.542572,0.112426,0.115385,0.334209,f1_macro,0.157672,0.156863,0.160670,shuffle_training_X_only
2,YFC,2,84,129,129,26,0.192308,0.185185,0.174074,0.192308,0.494364,0.112426,0.115385,0.160985,f1_macro,0.174074,0.058824,0.236155,shuffle_training_X_only
3,YFC,3,126,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
4,YFC,4,168,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
5,YFC,5,210,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
6,YFC,6,252,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
7,YFC,7,294,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
8,YFC,8,336,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
9,YFC,9,378,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
10,YFC,10,420,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
11,YFC,11,462,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
12,YFC,12,504,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
13,YFC,13,546,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
14,YFC,14,588,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
15,YFC,15,630,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
16,YFC,16,672,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
17,YFC,17,714,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
18,YFC,18,756,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only
19,YFC,19,798,129,129,26,0.115385,0.111111,0.022989,0.115385,0.500000,0.112426,0.115385,0.572046,f1_macro,0.022989,1.000000,NaN,shuffle_training_X_only

aggregated YFC 2024-07-19 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFC/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-07-19/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFC,0,0,2059,510,102,0.215686,0.131469,0.116482,0.215686,0.581065,0.133987,0.186275,0.015359,f1_macro,0.116482,0.176471,0.132795,shuffle_training_X_only
1,YFC,1,42,2059,529,106,0.235849,0.148056,0.131039,0.235849,0.623072,0.134211,0.188679,0.003176,f1_macro,0.131039,0.019608,0.151420,shuffle_training_X_only
2,YFC,2,84,2059,515,103,0.194175,0.110758,0.093286,0.194175,0.662764,0.138844,0.194175,0.073763,f1_macro,0.093286,0.529412,0.134190,shuffle_training_X_only
3,YFC,3,126,2059,522,105,0.180952,0.119508,0.108360,0.180952,0.589438,0.134331,0.180952,0.107113,f1_macro,0.108360,0.294118,NaN,shuffle_training_X_only
4,YFC,4,168,2059,503,101,0.287129,0.175190,0.149513,0.287129,0.689169,0.133418,0.188119,0.000039,f1_macro,0.149513,0.019608,NaN,shuffle_training_X_only
5,YFC,5,210,2059,542,109,0.220183,0.152868,0.151517,0.220183,0.615365,0.134921,0.192661,0.009897,f1_macro,0.151517,0.019608,NaN,shuffle_training_X_only
6,YFC,6,252,2059,529,106,0.169811,0.110654,0.105931,0.169811,0.555073,0.135991,0.188679,0.188584,f1_macro,0.105931,0.352941,NaN,shuffle_training_X_only
7,YFC,7,294,2059,517,104,0.259615,0.159516,0.143434,0.259615,0.537509,0.134985,0.182692,0.000520,f1_macro,0.143434,0.019608,NaN,shuffle_training_X_only
8,YFC,8,336,2059,515,103,0.223301,0.143645,0.130685,0.223301,0.606959,0.135074,0.194175,0.009741,f1_macro,0.130685,0.039216,NaN,shuffle_training_X_only
9,YFC,9,378,2059,531,107,0.299065,0.199223,0.195036,0.299065,0.665257,0.136344,0.186916,0.000010,f1_macro,0.195036,0.019608,NaN,shuffle_training_X_only
10,YFC,10,420,2059,519,104,0.298077,0.174041,0.156226,0.298077,0.601736,0.138868,0.201923,0.000021,f1_macro,0.156226,0.019608,NaN,shuffle_training_X_only
11,YFC,11,462,2059,517,104,0.221154,0.129608,0.113579,0.221154,0.549116,0.134615,0.192308,0.010526,f1_macro,0.113579,0.137255,NaN,shuffle_training_X_only
12,YFC,12,504,2059,534,107,0.186916,0.120339,0.112559,0.186916,0.457506,0.134597,0.186916,0.078705,f1_macro,0.112559,0.156863,NaN,shuffle_training_X_only
13,YFC,13,546,2059,512,103,0.271845,0.188607,0.179290,0.271845,0.636238,0.136394,0.194175,0.000216,f1_macro,0.179290,0.039216,NaN,shuffle_training_X_only
14,YFC,14,588,2059,517,104,0.192308,0.126076,0.123325,0.192308,0.614990,0.138868,0.201923,0.080006,f1_macro,0.123325,0.117647,NaN,shuffle_training_X_only
15,YFC,15,630,2059,507,102,0.274510,0.178743,0.170402,0.274510,0.633169,0.135717,0.196078,0.000166,f1_macro,0.170402,0.019608,NaN,shuffle_training_X_only
16,YFC,16,672,2059,524,105,0.161905,0.099879,0.081873,0.161905,0.639921,0.133968,0.180952,0.237220,f1_macro,0.081873,0.666667,NaN,shuffle_training_X_only
17,YFC,17,714,2059,530,106,0.273585,0.176280,0.158886,0.273585,0.613188,0.134923,0.188679,0.000123,f1_macro,0.158886,0.019608,NaN,shuffle_training_X_only
18,YFC,18,756,2059,517,104,0.259615,0.162233,0.140098,0.259615,0.606723,0.134800,0.173077,0.000509,f1_macro,0.140098,0.019608,NaN,shuffle_training_X_only
19,YFC,19,798,2059,511,103,0.262136,0.165561,0.151324,0.262136,0.578372,0.135074,0.194175,0.000446,f1_macro,0.151324,0.039216,NaN,shuffle_training_X_only

aggregated YFC 2024-07-20 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFC/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-07-20/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFC,0,0,11261,6620,1324,0.217523,0.167608,0.156616,0.217523,0.616200,0.121475,0.151813,8.771090e-23,f1_macro,0.156616,0.019608,0.178491,shuffle_training_X_only
1,YFC,1,42,11261,6554,1311,0.221968,0.172154,0.157712,0.221968,0.610334,0.121233,0.151793,1.599812e-24,f1_macro,0.157712,0.019608,0.170448,shuffle_training_X_only
2,YFC,2,84,11261,6535,1307,0.237950,0.184598,0.169823,0.237950,0.646849,0.121219,0.153022,1.650817e-31,f1_macro,0.169823,0.019608,0.173781,shuffle_training_X_only
3,YFC,3,126,11261,6610,1322,0.236762,0.184851,0.176922,0.236762,0.615405,0.121617,0.154312,4.817897e-31,f1_macro,0.176922,0.019608,NaN,shuffle_training_X_only
4,YFC,4,168,11261,6570,1314,0.226788,0.182855,0.178979,0.226788,0.621618,0.121302,0.152968,1.382914e-26,f1_macro,0.178979,0.019608,NaN,shuffle_training_X_only
5,YFC,5,210,11261,6620,1324,0.222054,0.174035,0.165850,0.222054,0.623781,0.121513,0.151813,1.247115e-24,f1_macro,0.165850,0.019608,NaN,shuffle_training_X_only
6,YFC,6,252,11261,6554,1311,0.215103,0.173961,0.171678,0.215103,0.596602,0.121314,0.151793,1.067419e-21,f1_macro,0.171678,0.019608,NaN,shuffle_training_X_only
7,YFC,7,294,11261,6621,1325,0.224906,0.174343,0.166127,0.224906,0.604082,0.121472,0.148679,6.995867e-26,f1_macro,0.166127,0.019608,NaN,shuffle_training_X_only
8,YFC,8,336,11261,6630,1326,0.213424,0.168065,0.161766,0.213424,0.615290,0.121634,0.153846,4.209466e-21,f1_macro,0.161766,0.019608,NaN,shuffle_training_X_only
9,YFC,9,378,11261,6591,1319,0.217589,0.178158,0.175204,0.217589,0.605368,0.121414,0.151630,9.202993e-23,f1_macro,0.175204,0.019608,NaN,shuffle_training_X_only
10,YFC,10,420,11261,6554,1311,0.231121,0.183886,0.178003,0.231121,0.627679,0.121322,0.152555,2.030870e-28,f1_macro,0.178003,0.019608,NaN,shuffle_training_X_only
11,YFC,11,462,11261,6599,1320,0.226515,0.186686,0.185335,0.226515,0.617914,0.121500,0.150000,1.815388e-26,f1_macro,0.185335,0.019608,NaN,shuffle_training_X_only
12,YFC,12,504,11261,6578,1316,0.208967,0.164872,0.156927,0.208967,0.611337,0.121347,0.150456,2.134912e-19,f1_macro,0.156927,0.019608,NaN,shuffle_training_X_only
13,YFC,13,546,11261,6585,1317,0.203493,0.158946,0.146536,0.203493,0.611277,0.121340,0.151860,2.047978e-17,f1_macro,0.146536,0.019608,NaN,shuffle_training_X_only
14,YFC,14,588,11261,6616,1324,0.222810,0.173152,0.164162,0.222810,0.618292,0.121560,0.152568,6.364561e-25,f1_macro,0.164162,0.019608,NaN,shuffle_training_X_only
15,YFC,15,630,11261,6569,1314,0.218417,0.171099,0.163327,0.218417,0.609381,0.121323,0.152207,4.589692e-23,f1_macro,0.163327,0.019608,NaN,shuffle_training_X_only
16,YFC,16,672,11261,6544,1309,0.216960,0.168385,0.159082,0.216960,0.615972,0.121305,0.152788,2.081749e-22,f1_macro,0.159082,0.019608,NaN,shuffle_training_X_only
17,YFC,17,714,11261,6567,1314,0.232116,0.182985,0.175331,0.232116,0.621476,0.121264,0.150685,5.840090e-29,f1_macro,0.175331,0.019608,NaN,shuffle_training_X_only
18,YFC,18,756,11261,6554,1311,0.230359,0.178528,0.166490,0.230359,0.616107,0.121396,0.153318,4.893234e-28,f1_macro,0.166490,0.019608,NaN,shuffle_training_X_only
19,YFC,19,798,11261,6604,1321,0.235428,0.183854,0.173413,0.235428,0.626392,0.121492,0.152157,1.764264e-30,f1_macro,0.173413,0.019608,NaN,shuffle_training_X_only

aggregated YFC 2024-07-21 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFC/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-07-21/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFC,0,0,9539,9539,1908,0.211216,0.170753,0.163895,0.211216,0.610709,0.117148,0.132075,1.314980e-31,f1_macro,0.163895,0.019608,0.167813,shuffle_training_X_only
1,YFC,1,42,9539,9539,1908,0.202306,0.165103,0.158989,0.202306,0.611041,0.117148,0.132075,1.361401e-26,f1_macro,0.158989,0.019608,0.168848,shuffle_training_X_only
2,YFC,2,84,9539,9539,1908,0.220650,0.182124,0.173893,0.220650,0.629552,0.117148,0.132075,2.411888e-37,f1_macro,0.173893,0.019608,0.169980,shuffle_training_X_only
3,YFC,3,126,9539,9539,1908,0.189203,0.153795,0.147649,0.189203,0.612049,0.117148,0.132075,5.920142e-20,f1_macro,0.147649,0.019608,NaN,shuffle_training_X_only
4,YFC,4,168,9539,9539,1908,0.229036,0.195294,0.194376,0.229036,0.624456,0.117148,0.132075,8.420530e-43,f1_macro,0.194376,0.019608,NaN,shuffle_training_X_only
5,YFC,5,210,9539,9539,1908,0.223270,0.184957,0.178615,0.223270,0.623104,0.117148,0.132075,5.161388e-39,f1_macro,0.178615,0.019608,NaN,shuffle_training_X_only
6,YFC,6,252,9539,9539,1908,0.208071,0.172270,0.166303,0.208071,0.620275,0.117148,0.132075,8.595022e-30,f1_macro,0.166303,0.019608,NaN,shuffle_training_X_only
7,YFC,7,294,9539,9539,1908,0.201782,0.167161,0.163202,0.201782,0.614903,0.117148,0.132075,2.609430e-26,f1_macro,0.163202,0.019608,NaN,shuffle_training_X_only
8,YFC,8,336,9539,9539,1908,0.209119,0.173812,0.171512,0.209119,0.620700,0.117148,0.132075,2.160663e-30,f1_macro,0.171512,0.019608,NaN,shuffle_training_X_only
9,YFC,9,378,9539,9539,1908,0.209119,0.179119,0.178343,0.209119,0.609900,0.117148,0.132075,2.160663e-30,f1_macro,0.178343,0.019608,NaN,shuffle_training_X_only
10,YFC,10,420,9539,9539,1908,0.199686,0.162553,0.157719,0.199686,0.616102,0.117148,0.132075,3.410135e-25,f1_macro,0.157719,0.019608,NaN,shuffle_training_X_only
11,YFC,11,462,9539,9539,1908,0.194969,0.157758,0.150850,0.194969,0.603278,0.117148,0.132075,9.153752e-23,f1_macro,0.150850,0.019608,NaN,shuffle_training_X_only
12,YFC,12,504,9539,9539,1908,0.208071,0.171807,0.165416,0.208071,0.624477,0.117148,0.132075,8.595022e-30,f1_macro,0.165416,0.019608,NaN,shuffle_training_X_only
13,YFC,13,546,9539,9539,1908,0.218553,0.182444,0.177382,0.218553,0.619999,0.117148,0.132075,4.947564e-36,f1_macro,0.177382,0.019608,NaN,shuffle_training_X_only
14,YFC,14,588,9539,9539,1908,0.210168,0.169048,0.159710,0.210168,0.621218,0.117148,0.132075,5.363787e-31,f1_macro,0.159710,0.019608,NaN,shuffle_training_X_only
15,YFC,15,630,9539,9539,1908,0.199686,0.167244,0.162120,0.199686,0.622445,0.117148,0.132075,3.410135e-25,f1_macro,0.162120,0.019608,NaN,shuffle_training_X_only
16,YFC,16,672,9539,9539,1908,0.212788,0.177639,0.173617,0.212788,0.621770,0.117148,0.132075,1.559332e-32,f1_macro,0.173617,0.019608,NaN,shuffle_training_X_only
17,YFC,17,714,9539,9539,1908,0.219602,0.178999,0.171799,0.219602,0.615906,0.117148,0.132075,1.099033e-36,f1_macro,0.171799,0.019608,NaN,shuffle_training_X_only
18,YFC,18,756,9539,9539,1908,0.193920,0.162162,0.158390,0.193920,0.613306,0.117148,0.132075,3.059465e-22,f1_macro,0.158390,0.019608,NaN,shuffle_training_X_only
19,YFC,19,798,9539,9539,1908,0.217505,0.180518,0.175741,0.217505,0.608236,0.117148,0.132075,2.200298e-35,f1_macro,0.175741,0.019608,NaN,shuffle_training_X_only

aggregated YFC 2024-07-22 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFC/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-07-22/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFC,0,0,5409,5409,1082,0.200555,0.163318,0.162493,0.200555,0.587095,0.12011,0.134935,3.304564e-14,f1_macro,0.162493,0.019608,0.179437,shuffle_training_X_only
1,YFC,1,42,5409,5409,1082,0.235675,0.192752,0.191143,0.235675,0.634281,0.12011,0.134935,4.278336e-26,f1_macro,0.191143,0.019608,0.170764,shuffle_training_X_only
2,YFC,2,84,5409,5409,1082,0.234750,0.193932,0.189979,0.234750,0.618520,0.12011,0.134935,9.690975e-26,f1_macro,0.189979,0.019608,0.176809,shuffle_training_X_only
3,YFC,3,126,5409,5409,1082,0.200555,0.165945,0.164767,0.200555,0.610067,0.12011,0.134935,3.304564e-14,f1_macro,0.164767,0.019608,NaN,shuffle_training_X_only
4,YFC,4,168,5409,5409,1082,0.207024,0.168226,0.166811,0.207024,0.615917,0.12011,0.134935,3.838164e-16,f1_macro,0.166811,0.019608,NaN,shuffle_training_X_only
5,YFC,5,210,5409,5409,1082,0.221811,0.178792,0.175717,0.221811,0.620461,0.12011,0.134935,5.283404e-21,f1_macro,0.175717,0.019608,NaN,shuffle_training_X_only
6,YFC,6,252,5409,5409,1082,0.213494,0.172575,0.166914,0.213494,0.601234,0.12011,0.134935,3.399109e-18,f1_macro,0.166914,0.019608,NaN,shuffle_training_X_only
7,YFC,7,294,5409,5409,1082,0.242144,0.196503,0.194414,0.242144,0.614572,0.12011,0.134935,1.213978e-28,f1_macro,0.194414,0.019608,NaN,shuffle_training_X_only
8,YFC,8,336,5409,5409,1082,0.222736,0.183152,0.182451,0.222736,0.623486,0.12011,0.134935,2.507861e-21,f1_macro,0.182451,0.019608,NaN,shuffle_training_X_only
9,YFC,9,378,5409,5409,1082,0.223660,0.179645,0.176294,0.223660,0.625970,0.12011,0.134935,1.184144e-21,f1_macro,0.176294,0.019608,NaN,shuffle_training_X_only
10,YFC,10,420,5409,5409,1082,0.201479,0.162831,0.157546,0.201479,0.605265,0.12011,0.134935,1.778246e-14,f1_macro,0.157546,0.019608,NaN,shuffle_training_X_only
11,YFC,11,462,5409,5409,1082,0.211645,0.174989,0.175127,0.211645,0.617047,0.12011,0.134935,1.348162e-17,f1_macro,0.175127,0.019608,NaN,shuffle_training_X_only
12,YFC,12,504,5409,5409,1082,0.225508,0.184952,0.184570,0.225508,0.623260,0.12011,0.134935,2.598765e-22,f1_macro,0.184570,0.019608,NaN,shuffle_training_X_only
13,YFC,13,546,5409,5409,1082,0.227357,0.192270,0.193131,0.227357,0.603640,0.12011,0.134935,5.585355e-23,f1_macro,0.193131,0.019608,NaN,shuffle_training_X_only
14,YFC,14,588,5409,5409,1082,0.231978,0.187737,0.181633,0.231978,0.602027,0.12011,0.134935,1.092347e-24,f1_macro,0.181633,0.019608,NaN,shuffle_training_X_only
15,YFC,15,630,5409,5409,1082,0.215342,0.176102,0.172550,0.215342,0.625031,0.12011,0.134935,8.386323e-19,f1_macro,0.172550,0.019608,NaN,shuffle_training_X_only
16,YFC,16,672,5409,5409,1082,0.223660,0.182712,0.179862,0.223660,0.600130,0.12011,0.134935,1.184144e-21,f1_macro,0.179862,0.019608,NaN,shuffle_training_X_only
17,YFC,17,714,5409,5409,1082,0.215342,0.175765,0.174006,0.215342,0.605813,0.12011,0.134935,8.386323e-19,f1_macro,0.174006,0.019608,NaN,shuffle_training_X_only
18,YFC,18,756,5409,5409,1082,0.214418,0.178584,0.179804,0.214418,0.604787,0.12011,0.134935,1.692942e-18,f1_macro,0.179804,0.019608,NaN,shuffle_training_X_only
19,YFC,19,798,5409,5409,1082,0.223660,0.183875,0.184024,0.223660,0.614877,0.12011,0.134935,1.184144e-21,f1_macro,0.184024,0.019608,NaN,shuffle_training_X_only

aggregated YFC 2024-07-23 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFC/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-07-23/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFC,0,0,5414,5414,1083,0.197599,0.161947,0.166643,0.197599,0.598900,0.122372,0.140351,1.337039e-12,f1_macro,0.166643,0.019608,0.159543,shuffle_training_X_only
1,YFC,1,42,5414,5414,1083,0.214220,0.181052,0.185079,0.214220,0.609095,0.122372,0.140351,1.644065e-17,f1_macro,0.185079,0.019608,0.164466,shuffle_training_X_only
2,YFC,2,84,5414,5414,1083,0.204063,0.165850,0.167506,0.204063,0.604400,0.122372,0.140351,2.039364e-14,f1_macro,0.167506,0.019608,0.166498,shuffle_training_X_only
3,YFC,3,126,5414,5414,1083,0.211450,0.172135,0.174880,0.211450,0.606702,0.122372,0.140351,1.225024e-16,f1_macro,0.174880,0.019608,NaN,shuffle_training_X_only
4,YFC,4,168,5414,5414,1083,0.205910,0.167202,0.170013,0.205910,0.605904,0.122372,0.140351,5.868741e-15,f1_macro,0.170013,0.019608,NaN,shuffle_training_X_only
5,YFC,5,210,5414,5414,1083,0.212373,0.161392,0.156717,0.212373,0.618201,0.122372,0.140351,6.306070e-17,f1_macro,0.156717,0.019608,NaN,shuffle_training_X_only
6,YFC,6,252,5414,5414,1083,0.207756,0.173197,0.177946,0.207756,0.616462,0.122372,0.140351,1.651830e-15,f1_macro,0.177946,0.019608,NaN,shuffle_training_X_only
7,YFC,7,294,5414,5414,1083,0.191136,0.155074,0.156057,0.191136,0.600572,0.122372,0.140351,6.630687e-11,f1_macro,0.156057,0.019608,NaN,shuffle_training_X_only
8,YFC,8,336,5414,5414,1083,0.216990,0.173855,0.177485,0.216990,0.607259,0.122372,0.140351,2.101793e-18,f1_macro,0.177485,0.019608,NaN,shuffle_training_X_only
9,YFC,9,378,5414,5414,1083,0.207756,0.173667,0.176828,0.207756,0.605315,0.122372,0.140351,1.651830e-15,f1_macro,0.176828,0.019608,NaN,shuffle_training_X_only
10,YFC,10,420,5414,5414,1083,0.178209,0.140634,0.141120,0.178209,0.597131,0.122372,0.140351,6.885419e-08,f1_macro,0.141120,0.019608,NaN,shuffle_training_X_only
11,YFC,11,462,5414,5414,1083,0.182825,0.142072,0.140580,0.182825,0.619494,0.122372,0.140351,6.590781e-09,f1_macro,0.140580,0.019608,NaN,shuffle_training_X_only
12,YFC,12,504,5414,5414,1083,0.219760,0.180765,0.184500,0.219760,0.622081,0.122372,0.140351,2.560569e-19,f1_macro,0.184500,0.019608,NaN,shuffle_training_X_only
13,YFC,13,546,5414,5414,1083,0.201293,0.165825,0.167295,0.201293,0.628222,0.122372,0.140351,1.266885e-13,f1_macro,0.167295,0.019608,NaN,shuffle_training_X_only
14,YFC,14,588,5414,5414,1083,0.210526,0.159663,0.157113,0.210526,0.582062,0.122372,0.140351,2.366818e-16,f1_macro,0.157113,0.019608,NaN,shuffle_training_X_only
15,YFC,15,630,5414,5414,1083,0.204986,0.164174,0.164685,0.204986,0.616156,0.122372,0.140351,1.097052e-14,f1_macro,0.164685,0.019608,NaN,shuffle_training_X_only
16,YFC,16,672,5414,5414,1083,0.219760,0.179550,0.184418,0.219760,0.615967,0.122372,0.140351,2.560569e-19,f1_macro,0.184418,0.019608,NaN,shuffle_training_X_only
17,YFC,17,714,5414,5414,1083,0.198523,0.163065,0.166138,0.198523,0.595176,0.122372,0.140351,7.481426e-13,f1_macro,0.166138,0.019608,NaN,shuffle_training_X_only
18,YFC,18,756,5414,5414,1083,0.204063,0.159934,0.158318,0.204063,0.603505,0.122372,0.140351,2.039364e-14,f1_macro,0.158318,0.019608,NaN,shuffle_training_X_only
19,YFC,19,798,5414,5414,1083,0.197599,0.160281,0.163246,0.197599,0.608506,0.122372,0.140351,1.337039e-12,f1_macro,0.163246,0.019608,NaN,shuffle_training_X_only

aggregated YFC 2024-07-24 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFC/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-07-24/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFC,0,0,9805,9805,1961,0.194799,0.171787,0.173253,0.194799,0.604697,0.111841,0.124426,7.255216e-27,f1_macro,0.173253,0.019608,0.162917,shuffle_training_X_only
1,YFC,1,42,9805,9805,1961,0.190209,0.167867,0.167321,0.190209,0.617044,0.111841,0.124426,2.361622e-24,f1_macro,0.167321,0.019608,0.169366,shuffle_training_X_only
2,YFC,2,84,9805,9805,1961,0.172871,0.153084,0.151563,0.172871,0.608475,0.111841,0.124426,6.432669e-16,f1_macro,0.151563,0.019608,0.173495,shuffle_training_X_only
3,YFC,3,126,9805,9805,1961,0.190719,0.164968,0.160491,0.190719,0.613454,0.111841,0.124426,1.258021e-24,f1_macro,0.160491,0.019608,NaN,shuffle_training_X_only
4,YFC,4,168,9805,9805,1961,0.190719,0.164834,0.162880,0.190719,0.615803,0.111841,0.124426,1.258021e-24,f1_macro,0.162880,0.019608,NaN,shuffle_training_X_only
5,YFC,5,210,9805,9805,1961,0.209077,0.182847,0.179524,0.209077,0.626777,0.111841,0.124426,2.128761e-35,f1_macro,0.179524,0.019608,NaN,shuffle_training_X_only
6,YFC,6,252,9805,9805,1961,0.176951,0.153273,0.148162,0.176951,0.607305,0.111841,0.124426,9.495339e-18,f1_macro,0.148162,0.019608,NaN,shuffle_training_X_only
7,YFC,7,294,9805,9805,1961,0.180520,0.158227,0.156093,0.180520,0.608394,0.111841,0.124426,1.980699e-19,f1_macro,0.156093,0.019608,NaN,shuffle_training_X_only
8,YFC,8,336,9805,9805,1961,0.181030,0.156518,0.152083,0.181030,0.607396,0.111841,0.124426,1.124064e-19,f1_macro,0.152083,0.019608,NaN,shuffle_training_X_only
9,YFC,9,378,9805,9805,1961,0.180010,0.160916,0.161596,0.180010,0.610439,0.111841,0.124426,3.478323e-19,f1_macro,0.161596,0.019608,NaN,shuffle_training_X_only
10,YFC,10,420,9805,9805,1961,0.190209,0.164642,0.160632,0.190209,0.616583,0.111841,0.124426,2.361622e-24,f1_macro,0.160632,0.019608,NaN,shuffle_training_X_only
11,YFC,11,462,9805,9805,1961,0.190209,0.164968,0.161987,0.190209,0.619128,0.111841,0.124426,2.361622e-24,f1_macro,0.161987,0.019608,NaN,shuffle_training_X_only
12,YFC,12,504,9805,9805,1961,0.187149,0.165637,0.164201,0.187149,0.613618,0.111841,0.124426,9.647021e-23,f1_macro,0.164201,0.019608,NaN,shuffle_training_X_only
13,YFC,13,546,9805,9805,1961,0.181030,0.156736,0.154570,0.181030,0.601055,0.111841,0.124426,1.124064e-19,f1_macro,0.154570,0.019608,NaN,shuffle_training_X_only
14,YFC,14,588,9805,9805,1961,0.171851,0.151959,0.150433,0.171851,0.595128,0.111841,0.124426,1.782172e-15,f1_macro,0.150433,0.019608,NaN,shuffle_training_X_only
15,YFC,15,630,9805,9805,1961,0.183070,0.158074,0.152935,0.183070,0.605353,0.111841,0.124426,1.127142e-20,f1_macro,0.152935,0.019608,NaN,shuffle_training_X_only
16,YFC,16,672,9805,9805,1961,0.178990,0.159251,0.158466,0.178990,0.604278,0.111841,0.124426,1.061774e-18,f1_macro,0.158466,0.019608,NaN,shuffle_training_X_only
17,YFC,17,714,9805,9805,1961,0.175931,0.154671,0.152415,0.175931,0.615002,0.111841,0.124426,2.781489e-17,f1_macro,0.152415,0.019608,NaN,shuffle_training_X_only
18,YFC,18,756,9805,9805,1961,0.197858,0.171362,0.167903,0.197858,0.615439,0.111841,0.124426,1.326165e-28,f1_macro,0.167903,0.019608,NaN,shuffle_training_X_only
19,YFC,19,798,9805,9805,1961,0.182560,0.157927,0.153767,0.182560,0.606474,0.111841,0.124426,2.013173e-20,f1_macro,0.153767,0.019608,NaN,shuffle_training_X_only

aggregated YFC 2024-07-25 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFC/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-07-25/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFC,0,0,9465,9465,1893,0.232435,0.184340,0.173903,0.232435,0.626921,0.117078,0.129952,7.842655e-45,f1_macro,0.173903,0.019608,0.179375,shuffle_training_X_only
1,YFC,1,42,9465,9465,1893,0.229266,0.183326,0.171812,0.229266,0.621791,0.117061,0.129952,1.036763e-42,f1_macro,0.171812,0.019608,0.179361,shuffle_training_X_only
2,YFC,2,84,9465,9465,1893,0.233492,0.182949,0.168566,0.233492,0.623267,0.117061,0.129952,1.431869e-45,f1_macro,0.168566,0.019608,0.180933,shuffle_training_X_only
3,YFC,3,126,9465,9465,1893,0.252509,0.205083,0.197491,0.252509,0.631650,0.117061,0.129952,1.956709e-59,f1_macro,0.197491,0.019608,NaN,shuffle_training_X_only
4,YFC,4,168,9465,9465,1893,0.220814,0.175303,0.162920,0.220814,0.622596,0.117078,0.129952,3.168297e-37,f1_macro,0.162920,0.019608,NaN,shuffle_training_X_only
5,YFC,5,210,9465,9465,1893,0.243529,0.192926,0.178742,0.243529,0.622417,0.117061,0.129952,1.093687e-52,f1_macro,0.178742,0.019608,NaN,shuffle_training_X_only
6,YFC,6,252,9465,9465,1893,0.232435,0.185051,0.175345,0.232435,0.631306,0.117061,0.129952,7.560168e-45,f1_macro,0.175345,0.019608,NaN,shuffle_training_X_only
7,YFC,7,294,9465,9465,1893,0.232964,0.185725,0.177399,0.232964,0.615564,0.117061,0.129952,3.295000e-45,f1_macro,0.177399,0.019608,NaN,shuffle_training_X_only
8,YFC,8,336,9465,9465,1893,0.236133,0.186556,0.173998,0.236133,0.628992,0.117078,0.129952,2.205504e-47,f1_macro,0.173998,0.019608,NaN,shuffle_training_X_only
9,YFC,9,378,9465,9465,1893,0.245642,0.196497,0.186996,0.245642,0.629970,0.117061,0.129952,3.042079e-54,f1_macro,0.186996,0.019608,NaN,shuffle_training_X_only
10,YFC,10,420,9465,9465,1893,0.255679,0.202592,0.190903,0.255679,0.635882,0.117061,0.129952,6.701928e-62,f1_macro,0.190903,0.019608,NaN,shuffle_training_X_only
11,YFC,11,462,9465,9465,1893,0.237718,0.188803,0.176662,0.237718,0.629053,0.117078,0.129952,1.703079e-48,f1_macro,0.176662,0.019608,NaN,shuffle_training_X_only
12,YFC,12,504,9465,9465,1893,0.236661,0.186989,0.172552,0.236661,0.625295,0.117061,0.129952,9.067784e-48,f1_macro,0.172552,0.019608,NaN,shuffle_training_X_only
13,YFC,13,546,9465,9465,1893,0.249340,0.200518,0.188545,0.249340,0.633864,0.117061,0.129952,5.167708e-57,f1_macro,0.188545,0.019608,NaN,shuffle_training_X_only
14,YFC,14,588,9465,9465,1893,0.221870,0.173856,0.160278,0.221870,0.621975,0.117061,0.129952,6.621957e-38,f1_macro,0.160278,0.019608,NaN,shuffle_training_X_only
15,YFC,15,630,9465,9465,1893,0.240359,0.189659,0.177817,0.240359,0.632623,0.117078,0.129952,2.250576e-50,f1_macro,0.177817,0.019608,NaN,shuffle_training_X_only
16,YFC,16,672,9465,9465,1893,0.239831,0.188319,0.173970,0.239831,0.615900,0.117078,0.129952,5.377600e-50,f1_macro,0.173970,0.019608,NaN,shuffle_training_X_only
17,YFC,17,714,9465,9465,1893,0.239303,0.194470,0.187650,0.239303,0.643263,0.117061,0.129952,1.232420e-49,f1_macro,0.187650,0.019608,NaN,shuffle_training_X_only
18,YFC,18,756,9465,9465,1893,0.237718,0.189065,0.177902,0.237718,0.633333,0.117078,0.129952,1.703079e-48,f1_macro,0.177902,0.019608,NaN,shuffle_training_X_only
19,YFC,19,798,9465,9465,1893,0.237718,0.187890,0.174361,0.237718,0.631076,0.117078,0.129952,1.703079e-48,f1_macro,0.174361,0.019608,NaN,shuffle_training_X_only

aggregated YFC 2024-07-26 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFC/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-07-26/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFC,0,0,6025,6025,1205,0.214938,0.171867,0.167601,0.214938,0.607765,0.118556,0.129461,2.449363e-21,f1_macro,0.167601,0.019608,0.158339,shuffle_training_X_only
1,YFC,1,42,6025,6025,1205,0.226556,0.179397,0.169461,0.226556,0.629569,0.118556,0.129461,6.712651e-26,f1_macro,0.169461,0.019608,0.152130,shuffle_training_X_only
2,YFC,2,84,6025,6025,1205,0.188382,0.146492,0.136356,0.188382,0.599749,0.118556,0.129461,1.733388e-12,f1_macro,0.136356,0.019608,0.151705,shuffle_training_X_only
3,YFC,3,126,6025,6025,1205,0.213278,0.166874,0.157959,0.213278,0.612503,0.118556,0.129461,1.017189e-20,f1_macro,0.157959,0.019608,NaN,shuffle_training_X_only
4,YFC,4,168,6025,6025,1205,0.196680,0.152779,0.140907,0.196680,0.606666,0.118594,0.129461,5.391278e-15,f1_macro,0.140907,0.019608,NaN,shuffle_training_X_only
5,YFC,5,210,6025,6025,1205,0.188382,0.148396,0.140219,0.188382,0.603951,0.118556,0.129461,1.733388e-12,f1_macro,0.140219,0.019608,NaN,shuffle_training_X_only
6,YFC,6,252,6025,6025,1205,0.199170,0.161907,0.157632,0.199170,0.604372,0.118594,0.129461,8.542925e-16,f1_macro,0.157632,0.019608,NaN,shuffle_training_X_only
7,YFC,7,294,6025,6025,1205,0.203320,0.160194,0.152356,0.203320,0.591766,0.118556,0.129461,3.450331e-17,f1_macro,0.152356,0.019608,NaN,shuffle_training_X_only
8,YFC,8,336,6025,6025,1205,0.200000,0.157711,0.151009,0.200000,0.601863,0.118594,0.129461,4.575753e-16,f1_macro,0.151009,0.019608,NaN,shuffle_training_X_only
9,YFC,9,378,6025,6025,1205,0.198340,0.157578,0.151165,0.198340,0.599275,0.118556,0.129461,1.532848e-15,f1_macro,0.151165,0.019608,NaN,shuffle_training_X_only
10,YFC,10,420,6025,6025,1205,0.191701,0.152640,0.146086,0.191701,0.609481,0.118594,0.129461,1.867349e-13,f1_macro,0.146086,0.019608,NaN,shuffle_training_X_only
11,YFC,11,462,6025,6025,1205,0.224066,0.179508,0.171130,0.224066,0.599659,0.118556,0.129461,6.895303e-25,f1_macro,0.171130,0.019608,NaN,shuffle_training_X_only
12,YFC,12,504,6025,6025,1205,0.212448,0.168302,0.160050,0.212448,0.617760,0.118594,0.129461,2.143036e-20,f1_macro,0.160050,0.019608,NaN,shuffle_training_X_only
13,YFC,13,546,6025,6025,1205,0.197510,0.153349,0.143132,0.197510,0.621219,0.118556,0.129461,2.833667e-15,f1_macro,0.143132,0.019608,NaN,shuffle_training_X_only
14,YFC,14,588,6025,6025,1205,0.200000,0.157509,0.151867,0.200000,0.611471,0.118594,0.129461,4.575753e-16,f1_macro,0.151867,0.019608,NaN,shuffle_training_X_only
15,YFC,15,630,6025,6025,1205,0.180083,0.141240,0.135001,0.180083,0.604509,0.118556,0.129461,3.390428e-10,f1_macro,0.135001,0.019608,NaN,shuffle_training_X_only
16,YFC,16,672,6025,6025,1205,0.192531,0.155936,0.153665,0.192531,0.605811,0.118594,0.129461,1.047838e-13,f1_macro,0.153665,0.019608,NaN,shuffle_training_X_only
17,YFC,17,714,6025,6025,1205,0.209129,0.164519,0.155978,0.209129,0.601831,0.118594,0.129461,3.412727e-19,f1_macro,0.155978,0.019608,NaN,shuffle_training_X_only
18,YFC,18,756,6025,6025,1205,0.195021,0.156944,0.148627,0.195021,0.616714,0.118594,0.129461,1.794303e-14,f1_macro,0.148627,0.019608,NaN,shuffle_training_X_only
19,YFC,19,798,6025,6025,1205,0.201660,0.160524,0.153518,0.201660,0.613010,0.118556,0.129461,1.247087e-16,f1_macro,0.153518,0.019608,NaN,shuffle_training_X_only

aggregated YFD 2024-07-29 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFD/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-07-29/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFD,0,0,882,882,177,0.135593,0.105710,0.104807,0.135593,0.547853,0.124964,0.146893,0.367139,f1_macro,0.104807,0.294118,0.105520,shuffle_training_X_only
1,YFD,1,42,882,882,177,0.169492,0.120970,0.109605,0.169492,0.537651,0.124964,0.146893,0.051086,f1_macro,0.109605,0.156863,0.126159,shuffle_training_X_only
2,YFD,2,84,882,882,177,0.158192,0.113625,0.106718,0.158192,0.570040,0.124964,0.146893,0.112789,f1_macro,0.106718,0.215686,0.104000,shuffle_training_X_only
3,YFD,3,126,882,882,177,0.152542,0.109973,0.102620,0.152542,0.508776,0.124964,0.146893,0.159308,f1_macro,0.102620,0.352941,NaN,shuffle_training_X_only
4,YFD,4,168,882,882,177,0.180791,0.130977,0.118698,0.180791,0.548984,0.124964,0.146893,0.020228,f1_macro,0.118698,0.137255,NaN,shuffle_training_X_only
5,YFD,5,210,882,882,177,0.146893,0.105318,0.098199,0.146893,0.524950,0.124964,0.146893,0.217554,f1_macro,0.098199,0.431373,NaN,shuffle_training_X_only
6,YFD,6,252,882,882,177,0.186441,0.132161,0.124689,0.186441,0.546501,0.124964,0.146893,0.012110,f1_macro,0.124689,0.117647,NaN,shuffle_training_X_only
7,YFD,7,294,882,882,177,0.124294,0.088274,0.085695,0.124294,0.530316,0.124964,0.146893,0.544753,f1_macro,0.085695,0.529412,NaN,shuffle_training_X_only
8,YFD,8,336,882,882,177,0.124294,0.089933,0.082136,0.124294,0.519144,0.124964,0.146893,0.544753,f1_macro,0.082136,0.764706,NaN,shuffle_training_X_only
9,YFD,9,378,882,882,177,0.225989,0.160776,0.151378,0.225989,0.568833,0.124964,0.146893,0.000136,f1_macro,0.151378,0.019608,NaN,shuffle_training_X_only
10,YFD,10,420,882,882,177,0.192090,0.137318,0.130104,0.192090,0.553204,0.124964,0.146893,0.007016,f1_macro,0.130104,0.058824,NaN,shuffle_training_X_only
11,YFD,11,462,882,882,177,0.141243,0.100930,0.094557,0.141243,0.514857,0.124964,0.146893,0.287317,f1_macro,0.094557,0.529412,NaN,shuffle_training_X_only
12,YFD,12,504,882,882,177,0.169492,0.120662,0.113660,0.169492,0.549475,0.124964,0.146893,0.051086,f1_macro,0.113660,0.313725,NaN,shuffle_training_X_only
13,YFD,13,546,882,882,177,0.112994,0.080388,0.077060,0.112994,0.533610,0.124964,0.146893,0.717842,f1_macro,0.077060,0.843137,NaN,shuffle_training_X_only
14,YFD,14,588,882,882,177,0.169492,0.120508,0.113923,0.169492,0.539647,0.124964,0.146893,0.051086,f1_macro,0.113923,0.274510,NaN,shuffle_training_X_only
15,YFD,15,630,882,882,177,0.197740,0.141398,0.134992,0.197740,0.534316,0.124964,0.146893,0.003935,f1_macro,0.134992,0.078431,NaN,shuffle_training_X_only
16,YFD,16,672,882,882,177,0.124294,0.088542,0.082384,0.124294,0.532121,0.124964,0.146893,0.544753,f1_macro,0.082384,0.686275,NaN,shuffle_training_X_only
17,YFD,17,714,882,882,177,0.169492,0.120776,0.114699,0.169492,0.517934,0.124964,0.146893,0.051086,f1_macro,0.114699,0.117647,NaN,shuffle_training_X_only
18,YFD,18,756,882,882,177,0.158192,0.112234,0.102792,0.158192,0.525870,0.124964,0.146893,0.112789,f1_macro,0.102792,0.333333,NaN,shuffle_training_X_only
19,YFD,19,798,882,882,177,0.152542,0.117082,0.113716,0.152542,0.529295,0.124964,0.146893,0.159308,f1_macro,0.113716,0.196078,NaN,shuffle_training_X_only

aggregated YFD 2024-07-30 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFD/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-07-30/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFD,0,0,14519,14519,2904,0.171488,0.143025,0.140708,0.171488,0.566379,0.11435,0.132576,5.654336e-20,f1_macro,0.140708,0.019608,0.129878,shuffle_training_X_only
1,YFD,1,42,14519,14519,2904,0.180441,0.142695,0.131725,0.180441,0.579113,0.11435,0.132576,1.056097e-25,f1_macro,0.131725,0.019608,0.130986,shuffle_training_X_only
2,YFD,2,84,14519,14519,2904,0.168044,0.137125,0.131683,0.168044,0.575359,0.11435,0.132576,5.891105e-18,f1_macro,0.131683,0.019608,0.131055,shuffle_training_X_only
3,YFD,3,126,14519,14519,2904,0.163223,0.133863,0.130503,0.163223,0.576595,0.11435,0.132576,2.616569e-15,f1_macro,0.130503,0.019608,NaN,shuffle_training_X_only
4,YFD,4,168,14519,14519,2904,0.176997,0.146023,0.142630,0.176997,0.575551,0.11435,0.132576,2.034571e-23,f1_macro,0.142630,0.019608,NaN,shuffle_training_X_only
5,YFD,5,210,14519,14519,2904,0.171488,0.139750,0.134285,0.171488,0.575726,0.11435,0.132576,5.654336e-20,f1_macro,0.134285,0.019608,NaN,shuffle_training_X_only
6,YFD,6,252,14519,14519,2904,0.168044,0.136472,0.130820,0.168044,0.571354,0.11435,0.132576,5.891105e-18,f1_macro,0.130820,0.019608,NaN,shuffle_training_X_only
7,YFD,7,294,14519,14519,2904,0.158402,0.129860,0.126019,0.158402,0.579650,0.11435,0.132576,7.151007e-13,f1_macro,0.126019,0.019608,NaN,shuffle_training_X_only
8,YFD,8,336,14519,14519,2904,0.174242,0.143664,0.139795,0.174242,0.586236,0.11435,0.132576,1.156856e-21,f1_macro,0.139795,0.019608,NaN,shuffle_training_X_only
9,YFD,9,378,14519,14519,2904,0.161501,0.131123,0.125732,0.161501,0.576106,0.11435,0.132576,2.053045e-14,f1_macro,0.125732,0.019608,NaN,shuffle_training_X_only
10,YFD,10,420,14519,14519,2904,0.165978,0.136028,0.131356,0.165978,0.575287,0.11435,0.132576,8.519192e-17,f1_macro,0.131356,0.019608,NaN,shuffle_training_X_only
11,YFD,11,462,14519,14519,2904,0.173898,0.140629,0.135200,0.173898,0.575227,0.11435,0.132576,1.896818e-21,f1_macro,0.135200,0.019608,NaN,shuffle_training_X_only
12,YFD,12,504,14519,14519,2904,0.157025,0.127467,0.122654,0.157025,0.567472,0.11435,0.132576,3.244824e-12,f1_macro,0.122654,0.019608,NaN,shuffle_training_X_only
13,YFD,13,546,14519,14519,2904,0.169766,0.135844,0.127304,0.169766,0.565304,0.11435,0.132576,5.947936e-19,f1_macro,0.127304,0.019608,NaN,shuffle_training_X_only
14,YFD,14,588,14519,14519,2904,0.167011,0.134225,0.126703,0.167011,0.566074,0.11435,0.132576,2.264963e-17,f1_macro,0.126703,0.019608,NaN,shuffle_training_X_only
15,YFD,15,630,14519,14519,2904,0.178375,0.143467,0.136553,0.178375,0.582541,0.11435,0.132576,2.550730e-24,f1_macro,0.136553,0.019608,NaN,shuffle_training_X_only
16,YFD,16,672,14519,14519,2904,0.164945,0.131064,0.123218,0.164945,0.572117,0.11435,0.132576,3.134487e-16,f1_macro,0.123218,0.019608,NaN,shuffle_training_X_only
17,YFD,17,714,14519,14519,2904,0.178375,0.144768,0.138487,0.178375,0.576140,0.11435,0.132576,2.550730e-24,f1_macro,0.138487,0.019608,NaN,shuffle_training_X_only
18,YFD,18,756,14519,14519,2904,0.175275,0.141329,0.134139,0.175275,0.564024,0.11435,0.132576,2.587534e-22,f1_macro,0.134139,0.019608,NaN,shuffle_training_X_only
19,YFD,19,798,14519,14519,2904,0.173209,0.139382,0.132755,0.173209,0.572223,0.11435,0.132576,5.063293e-21,f1_macro,0.132755,0.019608,NaN,shuffle_training_X_only

aggregated YFD 2024-07-31 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFD/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-07-31/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFD,0,0,8699,8699,1740,0.195977,0.151021,0.142196,0.195977,0.601294,0.119104,0.136207,2.863547e-20,f1_macro,0.142196,0.019608,0.142960,shuffle_training_X_only
1,YFD,1,42,8699,8699,1740,0.186782,0.148511,0.144785,0.186782,0.588127,0.119104,0.136207,2.443073e-16,f1_macro,0.144785,0.019608,0.144750,shuffle_training_X_only
2,YFD,2,84,8699,8699,1740,0.183333,0.144733,0.140465,0.183333,0.584366,0.119104,0.136207,5.703733e-15,f1_macro,0.140465,0.019608,0.142545,shuffle_training_X_only
3,YFD,3,126,8699,8699,1740,0.178736,0.141883,0.138115,0.178736,0.579779,0.119104,0.136207,3.080718e-13,f1_macro,0.138115,0.019608,NaN,shuffle_training_X_only
4,YFD,4,168,8699,8699,1740,0.178736,0.140405,0.136733,0.178736,0.584130,0.119104,0.136207,3.080718e-13,f1_macro,0.136733,0.019608,NaN,shuffle_training_X_only
5,YFD,5,210,8699,8699,1740,0.177586,0.138747,0.134840,0.177586,0.581966,0.119104,0.136207,8.038795e-13,f1_macro,0.134840,0.019608,NaN,shuffle_training_X_only
6,YFD,6,252,8699,8699,1740,0.198851,0.154581,0.147623,0.198851,0.597773,0.119104,0.136207,1.398875e-21,f1_macro,0.147623,0.019608,NaN,shuffle_training_X_only
7,YFD,7,294,8699,8699,1740,0.181034,0.148065,0.147873,0.181034,0.576503,0.119104,0.136207,4.321308e-14,f1_macro,0.147873,0.019608,NaN,shuffle_training_X_only
8,YFD,8,336,8699,8699,1740,0.195977,0.160585,0.160369,0.195977,0.605760,0.119104,0.136207,2.863547e-20,f1_macro,0.160369,0.019608,NaN,shuffle_training_X_only
9,YFD,9,378,8699,8699,1740,0.179885,0.139906,0.134671,0.179885,0.602173,0.119104,0.136207,1.162654e-13,f1_macro,0.134671,0.019608,NaN,shuffle_training_X_only
10,YFD,10,420,8699,8699,1740,0.186207,0.150324,0.150025,0.186207,0.602416,0.119104,0.136207,4.169018e-16,f1_macro,0.150025,0.019608,NaN,shuffle_training_X_only
11,YFD,11,462,8699,8699,1740,0.185632,0.150702,0.149696,0.185632,0.579745,0.119104,0.136207,7.087804e-16,f1_macro,0.149696,0.019608,NaN,shuffle_training_X_only
12,YFD,12,504,8699,8699,1740,0.197701,0.157648,0.153950,0.197701,0.597417,0.119104,0.136207,4.730337e-21,f1_macro,0.153950,0.019608,NaN,shuffle_training_X_only
13,YFD,13,546,8699,8699,1740,0.186782,0.149631,0.147249,0.186782,0.592943,0.119104,0.136207,2.443073e-16,f1_macro,0.147249,0.019608,NaN,shuffle_training_X_only
14,YFD,14,588,8699,8699,1740,0.173563,0.134631,0.129175,0.173563,0.598071,0.119104,0.136207,2.042610e-11,f1_macro,0.129175,0.019608,NaN,shuffle_training_X_only
15,YFD,15,630,8699,8699,1740,0.182184,0.144582,0.140719,0.182184,0.597235,0.119104,0.136207,1.581886e-14,f1_macro,0.140719,0.019608,NaN,shuffle_training_X_only
16,YFD,16,672,8699,8699,1740,0.201724,0.161434,0.159237,0.201724,0.585491,0.119104,0.136207,6.251393e-23,f1_macro,0.159237,0.019608,NaN,shuffle_training_X_only
17,YFD,17,714,8699,8699,1740,0.185632,0.145959,0.142211,0.185632,0.594731,0.119104,0.136207,7.087804e-16,f1_macro,0.142211,0.019608,NaN,shuffle_training_X_only
18,YFD,18,756,8699,8699,1740,0.192529,0.149364,0.143959,0.192529,0.601382,0.119104,0.136207,9.520180e-19,f1_macro,0.143959,0.019608,NaN,shuffle_training_X_only
19,YFD,19,798,8699,8699,1740,0.201724,0.158315,0.153262,0.201724,0.607868,0.119104,0.136207,6.251393e-23,f1_macro,0.153262,0.019608,NaN,shuffle_training_X_only

aggregated YFD 2024-08-01 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFD/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-01/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFD,0,0,5226,5226,1046,0.188337,0.147019,0.146344,0.188337,0.594197,0.123939,0.141491,1.775741e-09,f1_macro,0.146344,0.019608,0.152932,shuffle_training_X_only
1,YFD,1,42,5226,5226,1046,0.184512,0.151201,0.155337,0.184512,0.576516,0.123939,0.141491,1.279330e-08,f1_macro,0.155337,0.019608,0.140801,shuffle_training_X_only
2,YFD,2,84,5226,5226,1046,0.164436,0.133759,0.136823,0.164436,0.572022,0.123939,0.141491,7.861423e-05,f1_macro,0.136823,0.019608,0.154629,shuffle_training_X_only
3,YFD,3,126,5226,5226,1046,0.183556,0.138860,0.134796,0.183556,0.590726,0.123939,0.141491,2.064082e-08,f1_macro,0.134796,0.019608,NaN,shuffle_training_X_only
4,YFD,4,168,5226,5226,1046,0.184512,0.150423,0.154554,0.184512,0.594695,0.123939,0.141491,1.279330e-08,f1_macro,0.154554,0.019608,NaN,shuffle_training_X_only
5,YFD,5,210,5226,5226,1046,0.187380,0.140832,0.137146,0.187380,0.577260,0.123939,0.141491,2.936009e-09,f1_macro,0.137146,0.019608,NaN,shuffle_training_X_only
6,YFD,6,252,5226,5226,1046,0.165392,0.137407,0.142905,0.165392,0.589378,0.123939,0.141491,5.533094e-05,f1_macro,0.142905,0.019608,NaN,shuffle_training_X_only
7,YFD,7,294,5226,5226,1046,0.176864,0.140645,0.141037,0.176864,0.580824,0.123939,0.141491,4.936554e-07,f1_macro,0.141037,0.019608,NaN,shuffle_training_X_only
8,YFD,8,336,5226,5226,1046,0.167304,0.134716,0.135032,0.167304,0.602664,0.123939,0.141491,2.687771e-05,f1_macro,0.135032,0.019608,NaN,shuffle_training_X_only
9,YFD,9,378,5226,5226,1046,0.174952,0.139323,0.141306,0.174952,0.576191,0.123939,0.141491,1.155601e-06,f1_macro,0.141306,0.019608,NaN,shuffle_training_X_only
10,YFD,10,420,5226,5226,1046,0.173996,0.136667,0.136787,0.173996,0.585235,0.123939,0.141491,1.751333e-06,f1_macro,0.136787,0.019608,NaN,shuffle_training_X_only
11,YFD,11,462,5226,5226,1046,0.184512,0.147983,0.149824,0.184512,0.605157,0.123939,0.141491,1.279330e-08,f1_macro,0.149824,0.019608,NaN,shuffle_training_X_only
12,YFD,12,504,5226,5226,1046,0.200765,0.159342,0.160821,0.200765,0.602754,0.123939,0.141491,1.491120e-12,f1_macro,0.160821,0.019608,NaN,shuffle_training_X_only
13,YFD,13,546,5226,5226,1046,0.186424,0.145379,0.145830,0.186424,0.584714,0.123939,0.141491,4.824912e-09,f1_macro,0.145830,0.019608,NaN,shuffle_training_X_only
14,YFD,14,588,5226,5226,1046,0.182600,0.155846,0.163834,0.182600,0.588666,0.123939,0.141491,3.309721e-08,f1_macro,0.163834,0.019608,NaN,shuffle_training_X_only
15,YFD,15,630,5226,5226,1046,0.172084,0.139644,0.144818,0.172084,0.590417,0.123939,0.141491,3.946261e-06,f1_macro,0.144818,0.019608,NaN,shuffle_training_X_only
16,YFD,16,672,5226,5226,1046,0.173996,0.140600,0.143558,0.173996,0.578854,0.123939,0.141491,1.751333e-06,f1_macro,0.143558,0.019608,NaN,shuffle_training_X_only
17,YFD,17,714,5226,5226,1046,0.204589,0.153924,0.149651,0.204589,0.585202,0.123939,0.141491,1.381085e-13,f1_macro,0.149651,0.019608,NaN,shuffle_training_X_only
18,YFD,18,756,5226,5226,1046,0.166348,0.129044,0.127342,0.166348,0.571936,0.123939,0.141491,3.868974e-05,f1_macro,0.127342,0.019608,NaN,shuffle_training_X_only
19,YFD,19,798,5226,5226,1046,0.182600,0.144951,0.146509,0.182600,0.588820,0.123939,0.141491,3.309721e-08,f1_macro,0.146509,0.019608,NaN,shuffle_training_X_only

aggregated YFD 2024-08-02 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFD/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-02/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFD,0,0,8467,8467,1694,0.176505,0.140309,0.141300,0.176505,0.583556,0.122227,0.138725,6.397516e-11,f1_macro,0.141300,0.019608,0.145075,shuffle_training_X_only
1,YFD,1,42,8467,8467,1694,0.190673,0.151210,0.151795,0.190673,0.586932,0.122227,0.138725,5.440463e-16,f1_macro,0.151795,0.019608,0.144087,shuffle_training_X_only
2,YFD,2,84,8467,8467,1694,0.188902,0.150233,0.150672,0.188902,0.578089,0.122227,0.138725,2.641722e-15,f1_macro,0.150672,0.019608,0.136261,shuffle_training_X_only
3,YFD,3,126,8467,8467,1694,0.180638,0.144208,0.143724,0.180638,0.572960,0.122227,0.138725,2.674458e-12,f1_macro,0.143724,0.019608,NaN,shuffle_training_X_only
4,YFD,4,168,8467,8467,1694,0.181228,0.138501,0.134205,0.181228,0.586996,0.122227,0.138725,1.672868e-12,f1_macro,0.134205,0.019608,NaN,shuffle_training_X_only
5,YFD,5,210,8467,8467,1694,0.187131,0.143650,0.140643,0.187131,0.576297,0.122227,0.138725,1.239780e-14,f1_macro,0.140643,0.019608,NaN,shuffle_training_X_only
6,YFD,6,252,8467,8467,1694,0.178276,0.136989,0.134197,0.178276,0.581899,0.122227,0.138725,1.680174e-11,f1_macro,0.134197,0.019608,NaN,shuffle_training_X_only
7,YFD,7,294,8467,8467,1694,0.181818,0.136764,0.131520,0.181818,0.581147,0.122227,0.138725,1.042310e-12,f1_macro,0.131520,0.019608,NaN,shuffle_training_X_only
8,YFD,8,336,8467,8467,1694,0.183589,0.144916,0.144553,0.183589,0.588013,0.122227,0.138725,2.463182e-13,f1_macro,0.144553,0.019608,NaN,shuffle_training_X_only
9,YFD,9,378,8467,8467,1694,0.180047,0.136264,0.131754,0.180047,0.586458,0.122227,0.138725,4.259081e-12,f1_macro,0.131754,0.019608,NaN,shuffle_training_X_only
10,YFD,10,420,8467,8467,1694,0.185360,0.147489,0.147798,0.185360,0.588877,0.122227,0.138725,5.622290e-14,f1_macro,0.147798,0.019608,NaN,shuffle_training_X_only
11,YFD,11,462,8467,8467,1694,0.199528,0.155467,0.153170,0.199528,0.595839,0.122227,0.138725,1.218217e-19,f1_macro,0.153170,0.019608,NaN,shuffle_training_X_only
12,YFD,12,504,8467,8467,1694,0.174144,0.144299,0.147997,0.174144,0.586127,0.122227,0.138725,3.598488e-10,f1_macro,0.147997,0.019608,NaN,shuffle_training_X_only
13,YFD,13,546,8467,8467,1694,0.189492,0.151227,0.150663,0.189492,0.586850,0.122227,0.138725,1.565942e-15,f1_macro,0.150663,0.019608,NaN,shuffle_training_X_only
14,YFD,14,588,8467,8467,1694,0.160567,0.123537,0.120506,0.160567,0.568146,0.122227,0.138725,2.103731e-06,f1_macro,0.120506,0.019608,NaN,shuffle_training_X_only
15,YFD,15,630,8467,8467,1694,0.175325,0.135199,0.132758,0.175325,0.587170,0.122227,0.138725,1.529401e-10,f1_macro,0.132758,0.019608,NaN,shuffle_training_X_only
16,YFD,16,672,8467,8467,1694,0.167651,0.129819,0.127270,0.167651,0.579701,0.122227,0.138725,2.985560e-08,f1_macro,0.127270,0.019608,NaN,shuffle_training_X_only
17,YFD,17,714,8467,8467,1694,0.187721,0.146097,0.143771,0.187721,0.590958,0.122227,0.138725,7.433187e-15,f1_macro,0.143771,0.019608,NaN,shuffle_training_X_only
18,YFD,18,756,8467,8467,1694,0.180047,0.140053,0.138390,0.180047,0.579384,0.122227,0.138725,4.259081e-12,f1_macro,0.138390,0.019608,NaN,shuffle_training_X_only
19,YFD,19,798,8467,8467,1694,0.187721,0.146390,0.144488,0.187721,0.592203,0.122227,0.138725,7.433187e-15,f1_macro,0.144488,0.019608,NaN,shuffle_training_X_only

aggregated YFD 2024-08-03 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFD/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-03/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFD,0,0,7669,7669,1534,0.181226,0.135874,0.130095,0.181226,0.578911,0.123546,0.139505,5.381995e-11,f1_macro,0.130095,0.019608,0.133825,shuffle_training_X_only
1,YFD,1,42,7669,7669,1534,0.179270,0.134506,0.127410,0.179270,0.568974,0.123546,0.139505,2.097633e-10,f1_macro,0.127410,0.019608,0.127141,shuffle_training_X_only
2,YFD,2,84,7669,7669,1534,0.176010,0.131934,0.125670,0.176010,0.569106,0.123546,0.139505,1.857084e-09,f1_macro,0.125670,0.019608,0.130404,shuffle_training_X_only
3,YFD,3,126,7669,7669,1534,0.159061,0.117770,0.111420,0.159061,0.556719,0.123546,0.139505,2.613424e-05,f1_macro,0.111420,0.019608,NaN,shuffle_training_X_only
4,YFD,4,168,7669,7669,1534,0.183181,0.140990,0.138759,0.183181,0.576196,0.123546,0.139505,1.328642e-11,f1_macro,0.138759,0.019608,NaN,shuffle_training_X_only
5,YFD,5,210,7669,7669,1534,0.172099,0.130515,0.126503,0.172099,0.569696,0.123546,0.139505,2.201565e-08,f1_macro,0.126503,0.019608,NaN,shuffle_training_X_only
6,YFD,6,252,7669,7669,1534,0.176662,0.135224,0.131543,0.176662,0.561130,0.123546,0.139505,1.211116e-09,f1_macro,0.131543,0.019608,NaN,shuffle_training_X_only
7,YFD,7,294,7669,7669,1534,0.188396,0.144112,0.141577,0.188396,0.567036,0.123546,0.139505,2.644329e-13,f1_macro,0.141577,0.019608,NaN,shuffle_training_X_only
8,YFD,8,336,7669,7669,1534,0.186441,0.147417,0.149285,0.186441,0.558738,0.123546,0.139505,1.185621e-12,f1_macro,0.149285,0.019608,NaN,shuffle_training_X_only
9,YFD,9,378,7669,7669,1534,0.164276,0.123285,0.118119,0.164276,0.557908,0.123546,0.139505,1.913947e-06,f1_macro,0.118119,0.019608,NaN,shuffle_training_X_only
10,YFD,10,420,7669,7669,1534,0.175359,0.135486,0.132801,0.175359,0.563741,0.123546,0.139505,2.835183e-09,f1_macro,0.132801,0.019608,NaN,shuffle_training_X_only
11,YFD,11,462,7669,7669,1534,0.161669,0.121652,0.118131,0.161669,0.557816,0.123546,0.139505,7.336697e-06,f1_macro,0.118131,0.019608,NaN,shuffle_training_X_only
12,YFD,12,504,7669,7669,1534,0.177314,0.133272,0.128182,0.177314,0.560923,0.123546,0.139505,7.864087e-10,f1_macro,0.128182,0.019608,NaN,shuffle_training_X_only
13,YFD,13,546,7669,7669,1534,0.193611,0.143111,0.136232,0.193611,0.592971,0.123546,0.139505,4.028350e-15,f1_macro,0.136232,0.019608,NaN,shuffle_training_X_only
14,YFD,14,588,7669,7669,1534,0.178618,0.136078,0.132767,0.178618,0.560111,0.123546,0.139505,3.272772e-10,f1_macro,0.132767,0.019608,NaN,shuffle_training_X_only
15,YFD,15,630,7669,7669,1534,0.185789,0.143191,0.140880,0.185789,0.576507,0.123546,0.139505,1.938691e-12,f1_macro,0.140880,0.019608,NaN,shuffle_training_X_only
16,YFD,16,672,7669,7669,1534,0.177314,0.131496,0.124795,0.177314,0.569704,0.123546,0.139505,7.864087e-10,f1_macro,0.124795,0.019608,NaN,shuffle_training_X_only
17,YFD,17,714,7669,7669,1534,0.163625,0.125769,0.123716,0.163625,0.556630,0.123546,0.139505,2.696468e-06,f1_macro,0.123716,0.019608,NaN,shuffle_training_X_only
18,YFD,18,756,7669,7669,1534,0.180574,0.137717,0.134361,0.180574,0.573839,0.123546,0.139505,8.506264e-11,f1_macro,0.134361,0.019608,NaN,shuffle_training_X_only
19,YFD,19,798,7669,7669,1534,0.180574,0.137234,0.132972,0.180574,0.573664,0.123546,0.139505,8.506264e-11,f1_macro,0.132972,0.019608,NaN,shuffle_training_X_only

aggregated YFE 2024-08-13 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFE/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-13/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFE,0,0,2067,2067,414,0.207729,0.145578,0.130837,0.207729,0.544514,0.126246,0.144928,0.000002,f1_macro,0.130837,0.019608,0.126470,shuffle_training_X_only
1,YFE,1,42,2067,2067,414,0.154589,0.107789,0.094530,0.154589,0.532965,0.126246,0.144928,0.051188,f1_macro,0.094530,0.450980,0.137638,shuffle_training_X_only
2,YFE,2,84,2067,2067,414,0.161836,0.116412,0.110979,0.161836,0.552309,0.126246,0.144928,0.020155,f1_macro,0.110979,0.078431,0.122592,shuffle_training_X_only
3,YFE,3,126,2067,2066,414,0.188406,0.140867,0.139127,0.188406,0.535506,0.126246,0.144928,0.000202,f1_macro,0.139127,0.019608,NaN,shuffle_training_X_only
4,YFE,4,168,2067,2067,414,0.166667,0.117993,0.108065,0.166667,0.525723,0.126246,0.144928,0.010017,f1_macro,0.108065,0.137255,NaN,shuffle_training_X_only
5,YFE,5,210,2067,2067,414,0.190821,0.139371,0.136176,0.190821,0.526819,0.126246,0.144928,0.000122,f1_macro,0.136176,0.039216,NaN,shuffle_training_X_only
6,YFE,6,252,2067,2067,414,0.164251,0.121327,0.115721,0.164251,0.562102,0.126246,0.144928,0.014319,f1_macro,0.115721,0.058824,NaN,shuffle_training_X_only
7,YFE,7,294,2067,2066,414,0.149758,0.110952,0.107298,0.149758,0.512172,0.126246,0.144928,0.088143,f1_macro,0.107298,0.333333,NaN,shuffle_training_X_only
8,YFE,8,336,2067,2067,414,0.149758,0.111701,0.110791,0.149758,0.559224,0.126246,0.144928,0.088143,f1_macro,0.110791,0.254902,NaN,shuffle_training_X_only
9,YFE,9,378,2067,2067,414,0.185990,0.136905,0.130187,0.185990,0.525974,0.126246,0.144928,0.000331,f1_macro,0.130187,0.019608,NaN,shuffle_training_X_only
10,YFE,10,420,2067,2067,414,0.176329,0.127160,0.121128,0.176329,0.544208,0.126246,0.144928,0.002057,f1_macro,0.121128,0.058824,NaN,shuffle_training_X_only
11,YFE,11,462,2067,2067,414,0.171498,0.125578,0.120256,0.171498,0.561219,0.126246,0.144928,0.004680,f1_macro,0.120256,0.039216,NaN,shuffle_training_X_only
12,YFE,12,504,2067,2066,414,0.140097,0.107993,0.106851,0.140097,0.535029,0.126246,0.144928,0.217096,f1_macro,0.106851,0.176471,NaN,shuffle_training_X_only
13,YFE,13,546,2067,2066,414,0.164251,0.120034,0.111097,0.164251,0.534602,0.126246,0.144928,0.014319,f1_macro,0.111097,0.137255,NaN,shuffle_training_X_only
14,YFE,14,588,2067,2067,414,0.149758,0.109201,0.105817,0.149758,0.536402,0.126246,0.144928,0.088143,f1_macro,0.105817,0.274510,NaN,shuffle_training_X_only
15,YFE,15,630,2067,2067,414,0.171498,0.124575,0.120339,0.171498,0.557103,0.126246,0.144928,0.004680,f1_macro,0.120339,0.117647,NaN,shuffle_training_X_only
16,YFE,16,672,2067,2067,414,0.149758,0.110578,0.106923,0.149758,0.526253,0.126246,0.144928,0.088143,f1_macro,0.106923,0.254902,NaN,shuffle_training_X_only
17,YFE,17,714,2067,2067,414,0.171498,0.123078,0.117937,0.171498,0.547556,0.126246,0.144928,0.004680,f1_macro,0.117937,0.039216,NaN,shuffle_training_X_only
18,YFE,18,756,2067,2067,414,0.164251,0.118827,0.111948,0.164251,0.524218,0.126246,0.144928,0.014319,f1_macro,0.111948,0.098039,NaN,shuffle_training_X_only
19,YFE,19,798,2067,2067,414,0.173913,0.128367,0.124773,0.173913,0.530011,0.126246,0.144928,0.003126,f1_macro,0.124773,0.039216,NaN,shuffle_training_X_only

aggregated YFE 2024-08-14 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFE/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-14/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFE,0,0,4937,4937,988,0.171053,0.127608,0.124100,0.171053,0.559411,0.125563,0.144737,2.166917e-05,f1_macro,0.124100,0.019608,0.130336,shuffle_training_X_only
1,YFE,1,42,4937,4937,988,0.194332,0.146685,0.142918,0.194332,0.564045,0.125563,0.144737,6.119923e-10,f1_macro,0.142918,0.019608,0.125445,shuffle_training_X_only
2,YFE,2,84,4937,4937,988,0.187247,0.137176,0.132859,0.187247,0.579451,0.125563,0.144737,2.134225e-08,f1_macro,0.132859,0.019608,0.138072,shuffle_training_X_only
3,YFE,3,126,4937,4937,988,0.180162,0.131671,0.126093,0.180162,0.557357,0.125563,0.144737,5.430639e-07,f1_macro,0.126093,0.039216,NaN,shuffle_training_X_only
4,YFE,4,168,4937,4937,988,0.173077,0.130120,0.127309,0.173077,0.537065,0.125563,0.144737,1.000955e-05,f1_macro,0.127309,0.019608,NaN,shuffle_training_X_only
5,YFE,5,210,4937,4937,988,0.184211,0.140814,0.139975,0.184211,0.552505,0.125563,0.144737,8.883626e-08,f1_macro,0.139975,0.019608,NaN,shuffle_training_X_only
6,YFE,6,252,4937,4937,988,0.167004,0.124312,0.122088,0.167004,0.565503,0.125563,0.144737,9.361681e-05,f1_macro,0.122088,0.019608,NaN,shuffle_training_X_only
7,YFE,7,294,4937,4937,988,0.181174,0.133383,0.128126,0.181174,0.565294,0.125563,0.144737,3.487786e-07,f1_macro,0.128126,0.019608,NaN,shuffle_training_X_only
8,YFE,8,336,4937,4937,988,0.182186,0.142010,0.141824,0.182186,0.545173,0.125563,0.144737,2.225358e-07,f1_macro,0.141824,0.019608,NaN,shuffle_training_X_only
9,YFE,9,378,4937,4937,988,0.162955,0.121912,0.117171,0.162955,0.543576,0.125563,0.144737,3.624891e-04,f1_macro,0.117171,0.039216,NaN,shuffle_training_X_only
10,YFE,10,420,4937,4937,988,0.184211,0.135419,0.130534,0.184211,0.550976,0.125563,0.144737,8.883626e-08,f1_macro,0.130534,0.019608,NaN,shuffle_training_X_only
11,YFE,11,462,4937,4937,988,0.158907,0.121048,0.119803,0.158907,0.542145,0.125563,0.144737,1.256536e-03,f1_macro,0.119803,0.019608,NaN,shuffle_training_X_only
12,YFE,12,504,4937,4937,988,0.176113,0.132025,0.127384,0.176113,0.567433,0.125563,0.144737,2.988004e-06,f1_macro,0.127384,0.019608,NaN,shuffle_training_X_only
13,YFE,13,546,4937,4937,988,0.182186,0.135147,0.132510,0.182186,0.549007,0.125563,0.144737,2.225358e-07,f1_macro,0.132510,0.019608,NaN,shuffle_training_X_only
14,YFE,14,588,4937,4937,988,0.185223,0.139273,0.133995,0.185223,0.556657,0.125563,0.144737,5.558391e-08,f1_macro,0.133995,0.019608,NaN,shuffle_training_X_only
15,YFE,15,630,4937,4937,988,0.185223,0.136894,0.132498,0.185223,0.564435,0.125563,0.144737,5.558391e-08,f1_macro,0.132498,0.019608,NaN,shuffle_training_X_only
16,YFE,16,672,4937,4937,988,0.188259,0.139496,0.135119,0.188259,0.575637,0.125563,0.144737,1.309758e-08,f1_macro,0.135119,0.019608,NaN,shuffle_training_X_only
17,YFE,17,714,4937,4937,988,0.163968,0.123020,0.120837,0.163968,0.540094,0.125563,0.144737,2.610942e-04,f1_macro,0.120837,0.019608,NaN,shuffle_training_X_only
18,YFE,18,756,4937,4937,988,0.176113,0.130141,0.127059,0.176113,0.558768,0.125563,0.144737,2.988004e-06,f1_macro,0.127059,0.019608,NaN,shuffle_training_X_only
19,YFE,19,798,4937,4937,988,0.177126,0.134456,0.130908,0.177126,0.551910,0.125563,0.144737,1.970462e-06,f1_macro,0.130908,0.019608,NaN,shuffle_training_X_only

aggregated YFE 2024-08-15 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFE/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-15/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFE,0,0,16904,16904,3381,0.194617,0.165119,0.171389,0.194617,0.589360,0.120348,0.138125,3.635064e-35,f1_macro,0.171389,0.019608,0.160142,shuffle_training_X_only
1,YFE,1,42,16904,16904,3381,0.195209,0.165223,0.170266,0.195209,0.599662,0.120348,0.138125,1.153931e-35,f1_macro,0.170266,0.019608,0.165846,shuffle_training_X_only
2,YFE,2,84,16904,16904,3381,0.216208,0.181012,0.184901,0.216208,0.595916,0.120348,0.138125,2.083403e-55,f1_macro,0.184901,0.019608,0.164756,shuffle_training_X_only
3,YFE,3,126,16904,16904,3381,0.209406,0.175562,0.182174,0.209406,0.600410,0.120348,0.138125,1.393802e-48,f1_macro,0.182174,0.019608,NaN,shuffle_training_X_only
4,YFE,4,168,16904,16904,3381,0.215321,0.179611,0.184479,0.215321,0.594577,0.120348,0.138125,1.705565e-54,f1_macro,0.184479,0.019608,NaN,shuffle_training_X_only
5,YFE,5,210,16904,16904,3381,0.209997,0.178336,0.185446,0.209997,0.596080,0.120348,0.138125,3.687700e-49,f1_macro,0.185446,0.019608,NaN,shuffle_training_X_only
6,YFE,6,252,16904,16904,3381,0.205856,0.171117,0.175840,0.205856,0.597784,0.120348,0.138125,3.498161e-45,f1_macro,0.175840,0.019608,NaN,shuffle_training_X_only
7,YFE,7,294,16904,16904,3381,0.193434,0.160912,0.163888,0.193434,0.594495,0.120348,0.138125,3.527031e-34,f1_macro,0.163888,0.019608,NaN,shuffle_training_X_only
8,YFE,8,336,16904,16904,3381,0.212659,0.178509,0.183983,0.212659,0.596813,0.120348,0.138125,8.515730e-52,f1_macro,0.183983,0.019608,NaN,shuffle_training_X_only
9,YFE,9,378,16904,16904,3381,0.215321,0.181747,0.187277,0.215321,0.595028,0.120348,0.138125,1.705565e-54,f1_macro,0.187277,0.019608,NaN,shuffle_training_X_only
10,YFE,10,420,16904,16904,3381,0.208222,0.177203,0.183918,0.208222,0.597247,0.120348,0.138125,1.949066e-47,f1_macro,0.183918,0.019608,NaN,shuffle_training_X_only
11,YFE,11,462,16904,16904,3381,0.212067,0.182034,0.189926,0.212067,0.592306,0.120348,0.138125,3.322616e-51,f1_macro,0.189926,0.019608,NaN,shuffle_training_X_only
12,YFE,12,504,16904,16904,3381,0.219462,0.184986,0.192203,0.219462,0.600168,0.120348,0.138125,8.181340e-59,f1_macro,0.192203,0.019608,NaN,shuffle_training_X_only
13,YFE,13,546,16904,16904,3381,0.207631,0.170517,0.174133,0.207631,0.596230,0.120348,0.138125,7.210975e-47,f1_macro,0.174133,0.019608,NaN,shuffle_training_X_only
14,YFE,14,588,16904,16904,3381,0.203194,0.170748,0.177024,0.203194,0.591087,0.120348,0.138125,1.046720e-42,f1_macro,0.177024,0.019608,NaN,shuffle_training_X_only
15,YFE,15,630,16904,16904,3381,0.197575,0.165003,0.169865,0.197575,0.599174,0.120348,0.138125,1.087580e-37,f1_macro,0.169865,0.019608,NaN,shuffle_training_X_only
16,YFE,16,672,16904,16904,3381,0.209406,0.171910,0.175379,0.209406,0.598042,0.120348,0.138125,1.393802e-48,f1_macro,0.175379,0.019608,NaN,shuffle_training_X_only
17,YFE,17,714,16904,16904,3381,0.213842,0.181417,0.189050,0.213842,0.606501,0.120348,0.138125,5.477132e-53,f1_macro,0.189050,0.019608,NaN,shuffle_training_X_only
18,YFE,18,756,16904,16904,3381,0.207631,0.176570,0.183830,0.207631,0.595631,0.120348,0.138125,7.210975e-47,f1_macro,0.183830,0.019608,NaN,shuffle_training_X_only
19,YFE,19,798,16904,16904,3381,0.213546,0.179855,0.186176,0.213546,0.592681,0.120348,0.138125,1.090467e-52,f1_macro,0.186176,0.019608,NaN,shuffle_training_X_only

aggregated YFE 2024-08-16 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFE/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-16/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFE,0,0,9760,9760,1952,0.175717,0.129992,0.123778,0.175717,0.560975,0.122608,0.142418,7.125245e-12,f1_macro,0.123778,0.019608,0.125748,shuffle_training_X_only
1,YFE,1,42,9760,9760,1952,0.172131,0.128180,0.123058,0.172131,0.554663,0.122608,0.142418,1.326452e-10,f1_macro,0.123058,0.019608,0.122520,shuffle_training_X_only
2,YFE,2,84,9760,9760,1952,0.175717,0.131815,0.127113,0.175717,0.570720,0.122608,0.142418,7.125245e-12,f1_macro,0.127113,0.019608,0.124758,shuffle_training_X_only
3,YFE,3,126,9760,9760,1952,0.178279,0.134325,0.130586,0.178279,0.558786,0.122608,0.142418,7.954881e-13,f1_macro,0.130586,0.019608,NaN,shuffle_training_X_only
4,YFE,4,168,9760,9760,1952,0.177766,0.137957,0.137053,0.177766,0.570705,0.122608,0.142418,1.241802e-12,f1_macro,0.137053,0.019608,NaN,shuffle_training_X_only
5,YFE,5,210,9760,9760,1952,0.179303,0.134675,0.129999,0.179303,0.557547,0.122608,0.142418,3.231009e-13,f1_macro,0.129999,0.019608,NaN,shuffle_training_X_only
6,YFE,6,252,9760,9760,1952,0.185451,0.139553,0.135129,0.185451,0.564209,0.122608,0.142418,1.091263e-15,f1_macro,0.135129,0.019608,NaN,shuffle_training_X_only
7,YFE,7,294,9760,9760,1952,0.173156,0.134531,0.134156,0.173156,0.554267,0.122608,0.142418,5.853701e-11,f1_macro,0.134156,0.019608,NaN,shuffle_training_X_only
8,YFE,8,336,9760,9760,1952,0.178791,0.136466,0.134152,0.178791,0.553514,0.122608,0.142418,5.078413e-13,f1_macro,0.134152,0.019608,NaN,shuffle_training_X_only
9,YFE,9,378,9760,9760,1952,0.181352,0.138818,0.136595,0.181352,0.553254,0.122608,0.142418,5.116754e-14,f1_macro,0.136595,0.019608,NaN,shuffle_training_X_only
10,YFE,10,420,9760,9760,1952,0.178791,0.138234,0.136620,0.178791,0.551877,0.122608,0.142418,5.078413e-13,f1_macro,0.136620,0.019608,NaN,shuffle_training_X_only
11,YFE,11,462,9760,9760,1952,0.169570,0.131677,0.131191,0.169570,0.557860,0.122608,0.142418,9.641861e-10,f1_macro,0.131191,0.019608,NaN,shuffle_training_X_only
12,YFE,12,504,9760,9760,1952,0.173668,0.130986,0.126999,0.173668,0.559949,0.122608,0.142418,3.868340e-11,f1_macro,0.126999,0.019608,NaN,shuffle_training_X_only
13,YFE,13,546,9760,9760,1952,0.167008,0.128394,0.127228,0.167008,0.548649,0.122608,0.142418,6.415319e-09,f1_macro,0.127228,0.019608,NaN,shuffle_training_X_only
14,YFE,14,588,9760,9760,1952,0.166496,0.132018,0.131273,0.166496,0.556558,0.122608,0.142418,9.272312e-09,f1_macro,0.131273,0.019608,NaN,shuffle_training_X_only
15,YFE,15,630,9760,9760,1952,0.170594,0.130834,0.128387,0.170594,0.562609,0.122608,0.142418,4.407192e-10,f1_macro,0.128387,0.019608,NaN,shuffle_training_X_only
16,YFE,16,672,9760,9760,1952,0.182889,0.143588,0.143153,0.182889,0.554812,0.122608,0.142418,1.239632e-14,f1_macro,0.143153,0.019608,NaN,shuffle_training_X_only
17,YFE,17,714,9760,9760,1952,0.169570,0.131243,0.129925,0.169570,0.556339,0.122608,0.142418,9.641861e-10,f1_macro,0.129925,0.019608,NaN,shuffle_training_X_only
18,YFE,18,756,9760,9760,1952,0.174180,0.137371,0.137978,0.174180,0.558510,0.122608,0.142418,2.547450e-11,f1_macro,0.137978,0.019608,NaN,shuffle_training_X_only
19,YFE,19,798,9760,9760,1952,0.160861,0.123890,0.122222,0.160861,0.549810,0.122608,0.142418,4.203862e-07,f1_macro,0.122222,0.039216,NaN,shuffle_training_X_only

aggregated YFF 2024-08-20 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFF/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-20/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFF,0,0,426,426,86,0.151163,0.111667,0.105427,0.151163,0.470719,0.120606,0.139535,0.233927,f1_macro,0.105427,0.313725,0.127004,shuffle_training_X_only
1,YFF,1,42,426,426,86,0.104651,0.085000,0.085157,0.104651,0.459274,0.120606,0.139535,0.723409,f1_macro,0.085157,0.568627,0.139600,shuffle_training_X_only
2,YFF,2,84,426,426,86,0.186047,0.146667,0.136797,0.186047,0.554763,0.120606,0.139535,0.050898,f1_macro,0.136797,0.039216,0.125512,shuffle_training_X_only
3,YFF,3,126,426,426,86,0.127907,0.093333,0.080187,0.127907,0.503944,0.120606,0.139535,0.466309,f1_macro,0.080187,0.784314,NaN,shuffle_training_X_only
4,YFF,4,168,426,426,86,0.209302,0.160000,0.146742,0.209302,0.543279,0.120606,0.139535,0.013362,f1_macro,0.146742,0.039216,NaN,shuffle_training_X_only
5,YFF,5,210,426,426,86,0.127907,0.091667,0.086580,0.127907,0.495129,0.120606,0.139535,0.466309,f1_macro,0.086580,0.588235,NaN,shuffle_training_X_only
6,YFF,6,252,426,426,86,0.127907,0.101667,0.092801,0.127907,0.483484,0.120606,0.139535,0.466309,f1_macro,0.092801,0.490196,NaN,shuffle_training_X_only
7,YFF,7,294,426,426,86,0.162791,0.121667,0.113249,0.162791,0.555640,0.120606,0.139535,0.150195,f1_macro,0.113249,0.196078,NaN,shuffle_training_X_only
8,YFF,8,336,426,426,86,0.116279,0.083333,0.074440,0.116279,0.559908,0.120606,0.139535,0.598362,f1_macro,0.074440,0.745098,NaN,shuffle_training_X_only
9,YFF,9,378,426,426,86,0.116279,0.100000,0.090527,0.116279,0.506617,0.120606,0.139535,0.598362,f1_macro,0.090527,0.568627,NaN,shuffle_training_X_only
10,YFF,10,420,426,426,86,0.151163,0.110000,0.097375,0.151163,0.537300,0.120606,0.139535,0.233927,f1_macro,0.097375,0.294118,NaN,shuffle_training_X_only
11,YFF,11,462,426,426,86,0.186047,0.136667,0.118115,0.186047,0.519284,0.120606,0.139535,0.050898,f1_macro,0.118115,0.156863,NaN,shuffle_training_X_only
12,YFF,12,504,426,426,86,0.116279,0.085000,0.083919,0.116279,0.439398,0.120606,0.139535,0.598362,f1_macro,0.083919,0.529412,NaN,shuffle_training_X_only
13,YFF,13,546,426,426,86,0.174419,0.128333,0.116407,0.174419,0.576898,0.120606,0.139535,0.090316,f1_macro,0.116407,0.196078,NaN,shuffle_training_X_only
14,YFF,14,588,426,426,86,0.255814,0.186667,0.166254,0.255814,0.524217,0.120606,0.139535,0.000445,f1_macro,0.166254,0.019608,NaN,shuffle_training_X_only
15,YFF,15,630,426,426,86,0.197674,0.150000,0.131087,0.197674,0.582275,0.120606,0.139535,0.026909,f1_macro,0.131087,0.078431,NaN,shuffle_training_X_only
16,YFF,16,672,426,426,86,0.127907,0.093333,0.083026,0.127907,0.493550,0.120606,0.139535,0.466309,f1_macro,0.083026,0.607843,NaN,shuffle_training_X_only
17,YFF,17,714,426,426,86,0.104651,0.076667,0.066950,0.104651,0.463914,0.120606,0.139535,0.723409,f1_macro,0.066950,0.941176,NaN,shuffle_training_X_only
18,YFF,18,756,426,426,86,0.081395,0.061667,0.055391,0.081395,0.485855,0.120606,0.139535,0.906296,f1_macro,0.055391,0.882353,NaN,shuffle_training_X_only
19,YFF,19,798,426,426,86,0.151163,0.108333,0.098053,0.151163,0.530248,0.120606,0.139535,0.233927,f1_macro,0.098053,0.490196,NaN,shuffle_training_X_only

aggregated YFF 2024-08-21 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFF/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-21/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFF,0,0,6177,6177,1236,0.197411,0.155909,0.146997,0.197411,0.605486,0.115633,0.134304,7.998740e-17,f1_macro,0.146997,0.019608,0.155095,shuffle_training_X_only
1,YFF,1,42,6177,6177,1236,0.200647,0.162387,0.154086,0.200647,0.604157,0.115633,0.134304,5.964164e-18,f1_macro,0.154086,0.019608,0.150198,shuffle_training_X_only
2,YFF,2,84,6177,6177,1236,0.169094,0.139742,0.135265,0.169094,0.576305,0.115633,0.134304,1.713025e-08,f1_macro,0.135265,0.019608,0.142330,shuffle_training_X_only
3,YFF,3,126,6177,6177,1236,0.186084,0.152478,0.146720,0.186084,0.606257,0.115633,0.134304,3.729695e-13,f1_macro,0.146720,0.019608,NaN,shuffle_training_X_only
4,YFF,4,168,6177,6177,1236,0.192557,0.156442,0.151643,0.192557,0.596611,0.115633,0.134304,3.378026e-15,f1_macro,0.151643,0.019608,NaN,shuffle_training_X_only
5,YFF,5,210,6177,6177,1236,0.194175,0.161235,0.159499,0.194175,0.594368,0.115633,0.134304,9.898992e-16,f1_macro,0.159499,0.019608,NaN,shuffle_training_X_only
6,YFF,6,252,6177,6177,1236,0.210356,0.166871,0.158067,0.210356,0.602208,0.115633,0.134304,1.540094e-21,f1_macro,0.158067,0.019608,NaN,shuffle_training_X_only
7,YFF,7,294,6177,6177,1236,0.198220,0.161520,0.154860,0.198220,0.591605,0.115633,0.134304,4.211244e-17,f1_macro,0.154860,0.019608,NaN,shuffle_training_X_only
8,YFF,8,336,6177,6177,1236,0.190939,0.153000,0.146172,0.190939,0.587416,0.115633,0.134304,1.129429e-14,f1_macro,0.146172,0.019608,NaN,shuffle_training_X_only
9,YFF,9,378,6177,6177,1236,0.184466,0.146742,0.136962,0.184466,0.596280,0.115633,0.134304,1.147742e-12,f1_macro,0.136962,0.019608,NaN,shuffle_training_X_only
10,YFF,10,420,6177,6177,1236,0.199029,0.164959,0.160813,0.199029,0.598585,0.115633,0.134304,2.206093e-17,f1_macro,0.160813,0.019608,NaN,shuffle_training_X_only
11,YFF,11,462,6177,6177,1236,0.208738,0.176659,0.173882,0.208738,0.596241,0.115633,0.134304,6.407551e-21,f1_macro,0.173882,0.019608,NaN,shuffle_training_X_only
12,YFF,12,504,6177,6177,1236,0.189320,0.153295,0.144948,0.189320,0.588208,0.115633,0.134304,3.699369e-14,f1_macro,0.144948,0.019608,NaN,shuffle_training_X_only
13,YFF,13,546,6177,6177,1236,0.178803,0.147755,0.144443,0.178803,0.581317,0.115633,0.134304,4.967156e-11,f1_macro,0.144443,0.019608,NaN,shuffle_training_X_only
14,YFF,14,588,6177,6177,1236,0.199029,0.161160,0.153272,0.199029,0.593599,0.115633,0.134304,2.206093e-17,f1_macro,0.153272,0.019608,NaN,shuffle_training_X_only
15,YFF,15,630,6177,6177,1236,0.187702,0.150844,0.142714,0.187702,0.580746,0.115633,0.134304,1.186907e-13,f1_macro,0.142714,0.019608,NaN,shuffle_training_X_only
16,YFF,16,672,6177,6177,1236,0.194984,0.163989,0.162468,0.194984,0.598291,0.115633,0.134304,5.317927e-16,f1_macro,0.162468,0.019608,NaN,shuffle_training_X_only
17,YFF,17,714,6177,6177,1236,0.199029,0.161620,0.155867,0.199029,0.595613,0.115633,0.134304,2.206093e-17,f1_macro,0.155867,0.019608,NaN,shuffle_training_X_only
18,YFF,18,756,6177,6177,1236,0.186893,0.152351,0.145209,0.186893,0.584080,0.115633,0.134304,2.109489e-13,f1_macro,0.145209,0.019608,NaN,shuffle_training_X_only
19,YFF,19,798,6177,6177,1236,0.194175,0.157979,0.153210,0.194175,0.597864,0.115633,0.134304,9.898992e-16,f1_macro,0.153210,0.019608,NaN,shuffle_training_X_only

aggregated YFF 2024-08-22 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFF/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-22/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFF,0,0,3791,3791,759,0.176548,0.144355,0.144314,0.176548,0.563916,0.118405,0.135705,1.833634e-06,f1_macro,0.144314,0.019608,0.139052,shuffle_training_X_only
1,YFF,1,42,3791,3791,759,0.192358,0.149180,0.141695,0.192358,0.567771,0.118405,0.135705,2.969847e-09,f1_macro,0.141695,0.019608,0.146786,shuffle_training_X_only
2,YFF,2,84,3791,3791,759,0.185771,0.148445,0.145166,0.185771,0.571575,0.118405,0.135705,5.006660e-08,f1_macro,0.145166,0.019608,0.136655,shuffle_training_X_only
3,YFF,3,126,3791,3791,759,0.197628,0.155408,0.147381,0.197628,0.560844,0.118405,0.135705,2.672396e-10,f1_macro,0.147381,0.019608,NaN,shuffle_training_X_only
4,YFF,4,168,3791,3791,759,0.187088,0.146932,0.141879,0.187088,0.562917,0.118405,0.135705,2.893493e-08,f1_macro,0.141879,0.019608,NaN,shuffle_training_X_only
5,YFF,5,210,3791,3791,759,0.151515,0.120003,0.115247,0.151515,0.573709,0.118405,0.135705,3.651674e-03,f1_macro,0.115247,0.058824,NaN,shuffle_training_X_only
6,YFF,6,252,3791,3791,759,0.191041,0.147166,0.139061,0.191041,0.566005,0.118405,0.135705,5.312543e-09,f1_macro,0.139061,0.019608,NaN,shuffle_training_X_only
7,YFF,7,294,3791,3791,759,0.166008,0.137072,0.138488,0.166008,0.572176,0.118405,0.135705,6.672816e-05,f1_macro,0.138488,0.019608,NaN,shuffle_training_X_only
8,YFF,8,336,3791,3791,759,0.166008,0.134208,0.132925,0.166008,0.545201,0.118405,0.135705,6.672816e-05,f1_macro,0.132925,0.019608,NaN,shuffle_training_X_only
9,YFF,9,378,3791,3791,759,0.169960,0.131904,0.126760,0.169960,0.557428,0.118405,0.135705,1.852223e-05,f1_macro,0.126760,0.019608,NaN,shuffle_training_X_only
10,YFF,10,420,3791,3791,759,0.176548,0.141060,0.138032,0.176548,0.565201,0.118405,0.135705,1.833634e-06,f1_macro,0.138032,0.019608,NaN,shuffle_training_X_only
11,YFF,11,462,3791,3791,759,0.175231,0.134344,0.124674,0.175231,0.567421,0.118405,0.135705,2.963343e-06,f1_macro,0.124674,0.019608,NaN,shuffle_training_X_only
12,YFF,12,504,3791,3791,759,0.189723,0.149008,0.144327,0.189723,0.570352,0.118405,0.135705,9.425052e-09,f1_macro,0.144327,0.019608,NaN,shuffle_training_X_only
13,YFF,13,546,3791,3791,759,0.176548,0.141578,0.139652,0.176548,0.548032,0.118405,0.135705,1.833634e-06,f1_macro,0.139652,0.019608,NaN,shuffle_training_X_only
14,YFF,14,588,3791,3791,759,0.172596,0.137683,0.134674,0.172596,0.546656,0.118405,0.135705,7.539861e-06,f1_macro,0.134674,0.019608,NaN,shuffle_training_X_only
15,YFF,15,630,3791,3791,759,0.159420,0.128386,0.126974,0.159420,0.549922,0.118405,0.135705,4.720057e-04,f1_macro,0.126974,0.019608,NaN,shuffle_training_X_only
16,YFF,16,672,3791,3791,759,0.158103,0.124981,0.122002,0.158103,0.546940,0.118405,0.135705,6.792532e-04,f1_macro,0.122002,0.039216,NaN,shuffle_training_X_only
17,YFF,17,714,3791,3791,759,0.191041,0.151590,0.147942,0.191041,0.542997,0.118405,0.135705,5.312543e-09,f1_macro,0.147942,0.019608,NaN,shuffle_training_X_only
18,YFF,18,756,3791,3791,759,0.159420,0.124267,0.119352,0.159420,0.546299,0.118405,0.135705,4.720057e-04,f1_macro,0.119352,0.019608,NaN,shuffle_training_X_only
19,YFF,19,798,3791,3791,759,0.162055,0.129482,0.128600,0.162055,0.549013,0.118405,0.135705,2.217643e-04,f1_macro,0.128600,0.019608,NaN,shuffle_training_X_only

aggregated YFF 2024-08-23 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFF/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-23/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFF,0,0,8251,8251,1651,0.192005,0.146700,0.139300,0.192005,0.576275,0.120704,0.135675,7.157677e-17,f1_macro,0.139300,0.019608,0.137215,shuffle_training_X_only
1,YFF,1,42,8251,8251,1651,0.188976,0.143939,0.135968,0.188976,0.563180,0.120704,0.135675,1.094496e-15,f1_macro,0.135968,0.019608,0.129404,shuffle_training_X_only
2,YFF,2,84,8251,8251,1651,0.202302,0.158367,0.154696,0.202302,0.583436,0.120704,0.135675,3.298674e-21,f1_macro,0.154696,0.019608,0.133808,shuffle_training_X_only
3,YFF,3,126,8251,8251,1651,0.198062,0.153089,0.147905,0.198062,0.569459,0.120704,0.135675,2.297244e-19,f1_macro,0.147905,0.019608,NaN,shuffle_training_X_only
4,YFF,4,168,8251,8251,1651,0.176257,0.134996,0.128739,0.176257,0.570264,0.120704,0.135675,3.530788e-11,f1_macro,0.128739,0.019608,NaN,shuffle_training_X_only
5,YFF,5,210,8251,8251,1651,0.176257,0.133994,0.127333,0.176257,0.578688,0.120704,0.135675,3.530788e-11,f1_macro,0.127333,0.019608,NaN,shuffle_training_X_only
6,YFF,6,252,8251,8251,1651,0.185342,0.144334,0.139280,0.185342,0.569917,0.120704,0.135675,2.540046e-14,f1_macro,0.139280,0.019608,NaN,shuffle_training_X_only
7,YFF,7,294,8251,8251,1651,0.184737,0.145747,0.142963,0.184737,0.573603,0.120704,0.135675,4.231417e-14,f1_macro,0.142963,0.019608,NaN,shuffle_training_X_only
8,YFF,8,336,8251,8251,1651,0.173834,0.133145,0.127115,0.173834,0.568348,0.120704,0.135675,2.086331e-10,f1_macro,0.127115,0.019608,NaN,shuffle_training_X_only
9,YFF,9,378,8251,8251,1651,0.178680,0.139210,0.135684,0.178680,0.553035,0.120704,0.135675,5.598519e-12,f1_macro,0.135684,0.019608,NaN,shuffle_training_X_only
10,YFF,10,420,8251,8251,1651,0.178074,0.135536,0.128998,0.178074,0.562516,0.120704,0.135675,8.926078e-12,f1_macro,0.128998,0.019608,NaN,shuffle_training_X_only
11,YFF,11,462,8251,8251,1651,0.184131,0.143554,0.139266,0.184131,0.575778,0.120704,0.135675,7.021291e-14,f1_macro,0.139266,0.019608,NaN,shuffle_training_X_only
12,YFF,12,504,8251,8251,1651,0.190188,0.147423,0.140452,0.190188,0.573042,0.120704,0.135675,3.719389e-16,f1_macro,0.140452,0.019608,NaN,shuffle_training_X_only
13,YFF,13,546,8251,8251,1651,0.180497,0.140183,0.136375,0.180497,0.568685,0.120704,0.135675,1.348386e-12,f1_macro,0.136375,0.019608,NaN,shuffle_training_X_only
14,YFF,14,588,8251,8251,1651,0.188371,0.145529,0.137600,0.188371,0.577985,0.120704,0.135675,1.866626e-15,f1_macro,0.137600,0.019608,NaN,shuffle_training_X_only
15,YFF,15,630,8251,8251,1651,0.174440,0.137144,0.134323,0.174440,0.573370,0.120704,0.135675,1.346391e-10,f1_macro,0.134323,0.019608,NaN,shuffle_training_X_only
16,YFF,16,672,8251,8251,1651,0.175651,0.139295,0.136461,0.175651,0.564251,0.120704,0.135675,5.538746e-11,f1_macro,0.136461,0.019608,NaN,shuffle_training_X_only
17,YFF,17,714,8251,8251,1651,0.176257,0.140931,0.138455,0.176257,0.575810,0.120704,0.135675,3.530788e-11,f1_macro,0.138455,0.019608,NaN,shuffle_training_X_only
18,YFF,18,756,8251,8251,1651,0.199879,0.154199,0.148057,0.199879,0.572837,0.120704,0.135675,3.811850e-20,f1_macro,0.148057,0.019608,NaN,shuffle_training_X_only
19,YFF,19,798,8251,8251,1651,0.180497,0.139842,0.135789,0.180497,0.571867,0.120704,0.135675,1.348386e-12,f1_macro,0.135789,0.019608,NaN,shuffle_training_X_only

aggregated YFF 2024-08-24 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFF/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-24/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFF,0,0,6301,6301,1261,0.175258,0.142264,0.146310,0.175258,0.565711,0.121964,0.137986,2.546237e-08,f1_macro,0.146310,0.019608,0.138145,shuffle_training_X_only
1,YFF,1,42,6301,6301,1261,0.181602,0.139489,0.134611,0.181602,0.588458,0.121964,0.137986,6.546553e-10,f1_macro,0.134611,0.019608,0.138757,shuffle_training_X_only
2,YFF,2,84,6301,6301,1261,0.190325,0.145173,0.138257,0.190325,0.586908,0.121964,0.137986,2.483615e-12,f1_macro,0.138257,0.019608,0.138641,shuffle_training_X_only
3,YFF,3,126,6301,6301,1261,0.182395,0.139252,0.135616,0.182395,0.574124,0.121964,0.137986,4.046413e-10,f1_macro,0.135616,0.019608,NaN,shuffle_training_X_only
4,YFF,4,168,6301,6301,1261,0.168121,0.133123,0.131362,0.168121,0.568230,0.121964,0.137986,1.042508e-06,f1_macro,0.131362,0.019608,NaN,shuffle_training_X_only
5,YFF,5,210,6301,6301,1261,0.177637,0.136316,0.133290,0.177637,0.579617,0.121964,0.137986,6.711167e-09,f1_macro,0.133290,0.019608,NaN,shuffle_training_X_only
6,YFF,6,252,6301,6301,1261,0.175258,0.133705,0.130092,0.175258,0.568197,0.121964,0.137986,2.546237e-08,f1_macro,0.130092,0.019608,NaN,shuffle_training_X_only
7,YFF,7,294,6301,6301,1261,0.182395,0.138108,0.131417,0.182395,0.567791,0.121964,0.137986,4.046413e-10,f1_macro,0.131417,0.019608,NaN,shuffle_training_X_only
8,YFF,8,336,6301,6301,1261,0.189532,0.149468,0.148723,0.189532,0.574620,0.121964,0.137986,4.228807e-12,f1_macro,0.148723,0.019608,NaN,shuffle_training_X_only
9,YFF,9,378,6301,6301,1261,0.181602,0.140036,0.136680,0.181602,0.586707,0.121964,0.137986,6.546553e-10,f1_macro,0.136680,0.019608,NaN,shuffle_training_X_only
10,YFF,10,420,6301,6301,1261,0.180016,0.139738,0.137074,0.180016,0.571770,0.121964,0.137986,1.687063e-09,f1_macro,0.137074,0.019608,NaN,shuffle_training_X_only
11,YFF,11,462,6301,6301,1261,0.187946,0.148057,0.146228,0.187946,0.576204,0.121964,0.137986,1.207549e-11,f1_macro,0.146228,0.019608,NaN,shuffle_training_X_only
12,YFF,12,504,6301,6301,1261,0.180809,0.139475,0.136067,0.180809,0.565697,0.121964,0.137986,1.053663e-09,f1_macro,0.136067,0.019608,NaN,shuffle_training_X_only
13,YFF,13,546,6301,6301,1261,0.186360,0.146545,0.145728,0.186360,0.574398,0.121964,0.137986,3.378911e-11,f1_macro,0.145728,0.019608,NaN,shuffle_training_X_only
14,YFF,14,588,6301,6301,1261,0.173672,0.134880,0.133411,0.173672,0.582344,0.121964,0.137986,6.031915e-08,f1_macro,0.133411,0.019608,NaN,shuffle_training_X_only
15,YFF,15,630,6301,6301,1261,0.190325,0.147122,0.143250,0.190325,0.582865,0.121964,0.137986,2.483615e-12,f1_macro,0.143250,0.019608,NaN,shuffle_training_X_only
16,YFF,16,672,6301,6301,1261,0.167328,0.129045,0.125830,0.167328,0.551057,0.121964,0.137986,1.532806e-06,f1_macro,0.125830,0.019608,NaN,shuffle_training_X_only
17,YFF,17,714,6301,6301,1261,0.179223,0.142139,0.141615,0.179223,0.584030,0.121964,0.137986,2.687167e-09,f1_macro,0.141615,0.019608,NaN,shuffle_training_X_only
18,YFF,18,756,6301,6301,1261,0.173672,0.138614,0.137868,0.173672,0.567118,0.121964,0.137986,6.031915e-08,f1_macro,0.137868,0.019608,NaN,shuffle_training_X_only
19,YFF,19,798,6301,6301,1261,0.171293,0.132849,0.130273,0.171293,0.573516,0.121964,0.137986,2.112982e-07,f1_macro,0.130273,0.019608,NaN,shuffle_training_X_only

aggregated YFF 2024-08-25 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFF/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-25/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFF,0,0,3470,3470,694,0.187320,0.135303,0.130734,0.187320,0.556807,0.128678,0.145533,7.622451e-06,f1_macro,0.130734,0.019608,0.127261,shuffle_training_X_only
1,YFF,1,42,3470,3470,694,0.191643,0.133256,0.123669,0.191643,0.572383,0.128678,0.145533,1.824119e-06,f1_macro,0.123669,0.019608,0.126722,shuffle_training_X_only
2,YFF,2,84,3470,3470,694,0.188761,0.131760,0.124757,0.188761,0.564753,0.128678,0.145533,4.774983e-06,f1_macro,0.124757,0.019608,0.135433,shuffle_training_X_only
3,YFF,3,126,3470,3470,694,0.148415,0.104903,0.100054,0.148415,0.556023,0.128678,0.145533,6.940820e-02,f1_macro,0.100054,0.274510,NaN,shuffle_training_X_only
4,YFF,4,168,3470,3470,694,0.220461,0.160037,0.154998,0.220461,0.568640,0.128641,0.145533,1.751997e-11,f1_macro,0.154998,0.019608,NaN,shuffle_training_X_only
5,YFF,5,210,3470,3470,694,0.172911,0.123849,0.118118,0.172911,0.526603,0.128678,0.145533,4.960503e-04,f1_macro,0.118118,0.039216,NaN,shuffle_training_X_only
6,YFF,6,252,3470,3470,694,0.187320,0.134074,0.128719,0.187320,0.561791,0.128641,0.145533,7.515651e-06,f1_macro,0.128719,0.019608,NaN,shuffle_training_X_only
7,YFF,7,294,3470,3470,694,0.177233,0.123597,0.115152,0.177233,0.540654,0.128678,0.145533,1.561386e-04,f1_macro,0.115152,0.039216,NaN,shuffle_training_X_only
8,YFF,8,336,3470,3470,694,0.178674,0.129846,0.124706,0.178674,0.544823,0.128641,0.145533,1.029943e-04,f1_macro,0.124706,0.019608,NaN,shuffle_training_X_only
9,YFF,9,378,3470,3470,694,0.184438,0.130663,0.125220,0.184438,0.566865,0.128678,0.145533,1.890542e-05,f1_macro,0.125220,0.019608,NaN,shuffle_training_X_only
10,YFF,10,420,3470,3470,694,0.194524,0.142329,0.138047,0.194524,0.572275,0.128641,0.145533,6.619884e-07,f1_macro,0.138047,0.019608,NaN,shuffle_training_X_only
11,YFF,11,462,3470,3470,694,0.174352,0.123088,0.116627,0.174352,0.570446,0.128678,0.145533,3.405911e-04,f1_macro,0.116627,0.039216,NaN,shuffle_training_X_only
12,YFF,12,504,3470,3470,694,0.158501,0.115752,0.113019,0.158501,0.550700,0.128641,0.145533,1.257556e-02,f1_macro,0.113019,0.019608,NaN,shuffle_training_X_only
13,YFF,13,546,3470,3470,694,0.204611,0.146440,0.140107,0.204611,0.570747,0.128678,0.145533,1.552454e-08,f1_macro,0.140107,0.019608,NaN,shuffle_training_X_only
14,YFF,14,588,3470,3470,694,0.155620,0.110968,0.105698,0.155620,0.544564,0.128641,0.145533,2.145744e-02,f1_macro,0.105698,0.176471,NaN,shuffle_training_X_only
15,YFF,15,630,3470,3470,694,0.197406,0.143323,0.140402,0.197406,0.571499,0.128678,0.145533,2.393190e-07,f1_macro,0.140402,0.019608,NaN,shuffle_training_X_only
16,YFF,16,672,3470,3470,694,0.175793,0.126759,0.121617,0.175793,0.545948,0.128641,0.145533,2.290183e-04,f1_macro,0.121617,0.058824,NaN,shuffle_training_X_only
17,YFF,17,714,3470,3470,694,0.187320,0.130528,0.122449,0.187320,0.576377,0.128641,0.145533,7.515651e-06,f1_macro,0.122449,0.019608,NaN,shuffle_training_X_only
18,YFF,18,756,3470,3470,694,0.185879,0.130022,0.123151,0.185879,0.570080,0.128641,0.145533,1.189368e-05,f1_macro,0.123151,0.019608,NaN,shuffle_training_X_only
19,YFF,19,798,3470,3470,694,0.188761,0.134580,0.129228,0.188761,0.561481,0.128678,0.145533,4.774983e-06,f1_macro,0.129228,0.019608,NaN,shuffle_training_X_only

aggregated YFF 2024-08-26 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFF/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-26/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFF,0,0,1847,1847,370,0.164865,0.132659,0.129131,0.164865,0.560664,0.120175,0.137838,6.809863e-03,f1_macro,0.129131,0.019608,0.147778,shuffle_training_X_only
1,YFF,1,42,1847,1847,370,0.175676,0.140547,0.136782,0.175676,0.603961,0.120175,0.137838,1.155089e-03,f1_macro,0.136782,0.019608,0.151107,shuffle_training_X_only
2,YFF,2,84,1847,1847,370,0.208108,0.167403,0.162209,0.208108,0.602184,0.120175,0.137838,1.121561e-06,f1_macro,0.162209,0.019608,0.143655,shuffle_training_X_only
3,YFF,3,126,1847,1847,370,0.208108,0.168532,0.165473,0.208108,0.611109,0.120175,0.137838,1.121561e-06,f1_macro,0.165473,0.019608,NaN,shuffle_training_X_only
4,YFF,4,168,1847,1847,370,0.208108,0.160428,0.155327,0.208108,0.585966,0.120175,0.137838,1.121561e-06,f1_macro,0.155327,0.019608,NaN,shuffle_training_X_only
5,YFF,5,210,1847,1847,370,0.216216,0.165666,0.159511,0.216216,0.613639,0.120175,0.137838,1.379684e-07,f1_macro,0.159511,0.019608,NaN,shuffle_training_X_only
6,YFF,6,252,1847,1847,370,0.200000,0.160202,0.158164,0.200000,0.602967,0.120175,0.137838,7.916774e-06,f1_macro,0.158164,0.019608,NaN,shuffle_training_X_only
7,YFF,7,294,1847,1847,370,0.194595,0.159417,0.154216,0.194595,0.594006,0.120175,0.137838,2.689097e-05,f1_macro,0.154216,0.019608,NaN,shuffle_training_X_only
8,YFF,8,336,1847,1847,370,0.208108,0.170924,0.173536,0.208108,0.587384,0.120175,0.137838,1.121561e-06,f1_macro,0.173536,0.019608,NaN,shuffle_training_X_only
9,YFF,9,378,1847,1847,370,0.164865,0.129022,0.125823,0.164865,0.585747,0.120175,0.137838,6.809863e-03,f1_macro,0.125823,0.039216,NaN,shuffle_training_X_only
10,YFF,10,420,1847,1847,370,0.208108,0.165991,0.164750,0.208108,0.593835,0.120175,0.137838,1.121561e-06,f1_macro,0.164750,0.019608,NaN,shuffle_training_X_only
11,YFF,11,462,1847,1847,370,0.170270,0.127208,0.120753,0.170270,0.603652,0.120175,0.137838,2.903761e-03,f1_macro,0.120753,0.058824,NaN,shuffle_training_X_only
12,YFF,12,504,1847,1847,370,0.148649,0.122035,0.123994,0.148649,0.586634,0.120175,0.137838,5.748319e-02,f1_macro,0.123994,0.058824,NaN,shuffle_training_X_only
13,YFF,13,546,1847,1847,370,0.189189,0.149407,0.143319,0.189189,0.602898,0.120175,0.137838,8.557796e-05,f1_macro,0.143319,0.019608,NaN,shuffle_training_X_only
14,YFF,14,588,1847,1847,370,0.167568,0.135289,0.133525,0.167568,0.593539,0.120175,0.137838,4.485836e-03,f1_macro,0.133525,0.019608,NaN,shuffle_training_X_only
15,YFF,15,630,1847,1847,370,0.151351,0.114712,0.107874,0.151351,0.591860,0.120175,0.137838,4.211972e-02,f1_macro,0.107874,0.137255,NaN,shuffle_training_X_only
16,YFF,16,672,1847,1847,370,0.197297,0.156600,0.157281,0.197297,0.592851,0.120175,0.137838,1.470918e-05,f1_macro,0.157281,0.019608,NaN,shuffle_training_X_only
17,YFF,17,714,1847,1847,370,0.162162,0.127075,0.125846,0.162162,0.588430,0.120175,0.137838,1.015790e-02,f1_macro,0.125846,0.019608,NaN,shuffle_training_X_only
18,YFF,18,756,1847,1847,370,0.170270,0.142890,0.145022,0.170270,0.574219,0.120175,0.137838,2.903761e-03,f1_macro,0.145022,0.019608,NaN,shuffle_training_X_only
19,YFF,19,798,1847,1847,370,0.216216,0.171178,0.162005,0.216216,0.587931,0.120175,0.137838,1.379684e-07,f1_macro,0.162005,0.019608,NaN,shuffle_training_X_only

aggregated YFF 2024-08-27 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFF/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-27/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFF,0,0,4399,4399,880,0.170455,0.134828,0.128243,0.170455,0.556698,0.114755,0.132955,6.304507e-07,f1_macro,0.128243,0.019608,0.144652,shuffle_training_X_only
1,YFF,1,42,4399,4399,880,0.201136,0.160364,0.153256,0.201136,0.554564,0.114755,0.132955,1.103565e-13,f1_macro,0.153256,0.019608,0.141693,shuffle_training_X_only
2,YFF,2,84,4399,4399,880,0.187500,0.155668,0.153224,0.187500,0.569006,0.114755,0.132955,2.141941e-10,f1_macro,0.153224,0.019608,0.133129,shuffle_training_X_only
3,YFF,3,126,4399,4399,880,0.160227,0.134460,0.133480,0.160227,0.550963,0.114755,0.132955,3.327823e-05,f1_macro,0.133480,0.019608,NaN,shuffle_training_X_only
4,YFF,4,168,4399,4399,880,0.163636,0.133546,0.131083,0.163636,0.557106,0.114755,0.132955,9.522062e-06,f1_macro,0.131083,0.019608,NaN,shuffle_training_X_only
5,YFF,5,210,4399,4399,880,0.175000,0.137656,0.130239,0.175000,0.571289,0.114755,0.132955,8.839846e-08,f1_macro,0.130239,0.019608,NaN,shuffle_training_X_only
6,YFF,6,252,4399,4399,880,0.156818,0.126369,0.124222,0.156818,0.552461,0.114755,0.132955,1.082371e-04,f1_macro,0.124222,0.019608,NaN,shuffle_training_X_only
7,YFF,7,294,4399,4399,880,0.172727,0.139293,0.135213,0.172727,0.558842,0.114755,0.132955,2.397131e-07,f1_macro,0.135213,0.019608,NaN,shuffle_training_X_only
8,YFF,8,336,4399,4399,880,0.167045,0.132166,0.124849,0.167045,0.566983,0.114755,0.132955,2.537707e-06,f1_macro,0.124849,0.019608,NaN,shuffle_training_X_only
9,YFF,9,378,4399,4399,880,0.182955,0.144832,0.138581,0.182955,0.572308,0.114755,0.132955,2.123135e-09,f1_macro,0.138581,0.019608,NaN,shuffle_training_X_only
10,YFF,10,420,4399,4399,880,0.162500,0.129925,0.124493,0.162500,0.579029,0.114755,0.132955,1.456534e-05,f1_macro,0.124493,0.019608,NaN,shuffle_training_X_only
11,YFF,11,462,4399,4399,880,0.167045,0.132337,0.125036,0.167045,0.565791,0.114755,0.132955,2.537707e-06,f1_macro,0.125036,0.019608,NaN,shuffle_training_X_only
12,YFF,12,504,4399,4399,880,0.178409,0.152248,0.152056,0.178409,0.576420,0.114755,0.132955,1.870225e-08,f1_macro,0.152056,0.019608,NaN,shuffle_training_X_only
13,YFF,13,546,4399,4399,880,0.165909,0.144007,0.146757,0.165909,0.568842,0.114755,0.132955,3.974460e-06,f1_macro,0.146757,0.019608,NaN,shuffle_training_X_only
14,YFF,14,588,4399,4399,880,0.163636,0.126814,0.117770,0.163636,0.554715,0.114755,0.132955,9.522062e-06,f1_macro,0.117770,0.058824,NaN,shuffle_training_X_only
15,YFF,15,630,4399,4399,880,0.169318,0.131415,0.122456,0.169318,0.564275,0.114755,0.132955,1.010682e-06,f1_macro,0.122456,0.039216,NaN,shuffle_training_X_only
16,YFF,16,672,4399,4399,880,0.161364,0.129944,0.124663,0.161364,0.558862,0.114755,0.132955,2.210386e-05,f1_macro,0.124663,0.019608,NaN,shuffle_training_X_only
17,YFF,17,714,4399,4399,880,0.161364,0.132886,0.129895,0.161364,0.564016,0.114755,0.132955,2.210386e-05,f1_macro,0.129895,0.019608,NaN,shuffle_training_X_only
18,YFF,18,756,4399,4399,880,0.148864,0.124663,0.124682,0.148864,0.557692,0.114755,0.132955,1.277271e-03,f1_macro,0.124682,0.019608,NaN,shuffle_training_X_only
19,YFF,19,798,4399,4399,880,0.142045,0.113636,0.108899,0.142045,0.542132,0.114755,0.132955,7.681778e-03,f1_macro,0.108899,0.098039,NaN,shuffle_training_X_only

aggregated YFF 2024-08-28 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFF/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-28/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFF,0,0,7740,7740,1548,0.182817,0.146943,0.140431,0.182817,0.589107,0.115825,0.131783,9.724849e-15,f1_macro,0.140431,0.019608,0.139819,shuffle_training_X_only
1,YFF,1,42,7740,7740,1548,0.175065,0.137198,0.128477,0.175065,0.572850,0.115825,0.131783,4.794028e-12,f1_macro,0.128477,0.019608,0.136853,shuffle_training_X_only
2,YFF,2,84,7740,7740,1548,0.195090,0.153053,0.143712,0.195090,0.578823,0.115825,0.131783,1.528905e-19,f1_macro,0.143712,0.019608,0.140656,shuffle_training_X_only
3,YFF,3,126,7740,7740,1548,0.188630,0.155890,0.152730,0.188630,0.576516,0.115824,0.131783,6.212107e-17,f1_macro,0.152730,0.019608,NaN,shuffle_training_X_only
4,YFF,4,168,7740,7740,1548,0.184109,0.148194,0.141911,0.184109,0.574543,0.115825,0.131783,3.258832e-15,f1_macro,0.141911,0.019608,NaN,shuffle_training_X_only
5,YFF,5,210,7740,7740,1548,0.162145,0.130412,0.125383,0.162145,0.576906,0.115825,0.131783,3.605457e-08,f1_macro,0.125383,0.019608,NaN,shuffle_training_X_only
6,YFF,6,252,7740,7740,1548,0.182171,0.149217,0.146045,0.182171,0.569707,0.115825,0.131783,1.669286e-14,f1_macro,0.146045,0.019608,NaN,shuffle_training_X_only
7,YFF,7,294,7740,7740,1548,0.166667,0.137329,0.132396,0.166667,0.570350,0.115825,0.131783,1.945727e-09,f1_macro,0.132396,0.019608,NaN,shuffle_training_X_only
8,YFF,8,336,7740,7740,1548,0.188630,0.152921,0.145985,0.188630,0.583073,0.115825,0.131783,6.217879e-17,f1_macro,0.145985,0.019608,NaN,shuffle_training_X_only
9,YFF,9,378,7740,7740,1548,0.163437,0.131832,0.126995,0.163437,0.579275,0.115825,0.131783,1.601829e-08,f1_macro,0.126995,0.019608,NaN,shuffle_training_X_only
10,YFF,10,420,7740,7740,1548,0.167959,0.139672,0.135887,0.167959,0.563507,0.115825,0.131783,8.111518e-10,f1_macro,0.135887,0.019608,NaN,shuffle_training_X_only
11,YFF,11,462,7740,7740,1548,0.186693,0.151566,0.144191,0.186693,0.584085,0.115825,0.131783,3.478922e-16,f1_macro,0.144191,0.019608,NaN,shuffle_training_X_only
12,YFF,12,504,7740,7740,1548,0.180233,0.146381,0.142018,0.180233,0.583843,0.115825,0.131783,8.229438e-14,f1_macro,0.142018,0.019608,NaN,shuffle_training_X_only
13,YFF,13,546,7740,7740,1548,0.181525,0.149966,0.145199,0.181525,0.578520,0.115825,0.131783,2.853192e-14,f1_macro,0.145199,0.019608,NaN,shuffle_training_X_only
14,YFF,14,588,7740,7740,1548,0.185401,0.151659,0.147708,0.185401,0.571073,0.115824,0.131783,1.072799e-15,f1_macro,0.147708,0.019608,NaN,shuffle_training_X_only
15,YFF,15,630,7740,7740,1548,0.163437,0.133440,0.130510,0.163437,0.579896,0.115825,0.131783,1.601829e-08,f1_macro,0.130510,0.019608,NaN,shuffle_training_X_only
16,YFF,16,672,7740,7740,1548,0.172481,0.138354,0.131517,0.172481,0.581019,0.115825,0.131783,3.295689e-11,f1_macro,0.131517,0.019608,NaN,shuffle_training_X_only
17,YFF,17,714,7740,7740,1548,0.175065,0.141821,0.137403,0.175065,0.573271,0.115825,0.131783,4.794028e-12,f1_macro,0.137403,0.019608,NaN,shuffle_training_X_only
18,YFF,18,756,7740,7740,1548,0.184755,0.149291,0.144076,0.184755,0.560142,0.115825,0.131783,1.874554e-15,f1_macro,0.144076,0.019608,NaN,shuffle_training_X_only
19,YFF,19,798,7740,7740,1548,0.175711,0.142739,0.137494,0.175711,0.567283,0.115825,0.131783,2.928400e-12,f1_macro,0.137494,0.019608,NaN,shuffle_training_X_only

aggregated YFF 2024-08-29 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFF/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-08-29/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFF,0,0,1801,1801,361,0.160665,0.144616,0.154037,0.160665,0.577485,0.119727,0.135734,1.262623e-02,f1_macro,0.154037,0.019608,0.143162,shuffle_training_X_only
1,YFF,1,42,1801,1801,361,0.168975,0.138744,0.136977,0.168975,0.569981,0.119727,0.135734,3.656547e-03,f1_macro,0.136977,0.019608,0.138536,shuffle_training_X_only
2,YFF,2,84,1801,1801,361,0.174515,0.147088,0.150935,0.174515,0.592668,0.119727,0.135734,1.463696e-03,f1_macro,0.150935,0.019608,0.158828,shuffle_training_X_only
3,YFF,3,126,1801,1801,361,0.155125,0.127525,0.119747,0.155125,0.586995,0.119727,0.135734,2.634912e-02,f1_macro,0.119747,0.117647,NaN,shuffle_training_X_only
4,YFF,4,168,1801,1801,361,0.199446,0.163133,0.162682,0.199446,0.584721,0.119727,0.135734,1.008887e-05,f1_macro,0.162682,0.019608,NaN,shuffle_training_X_only
5,YFF,5,210,1801,1801,361,0.174515,0.144539,0.142891,0.174515,0.597694,0.119727,0.135734,1.463696e-03,f1_macro,0.142891,0.019608,NaN,shuffle_training_X_only
6,YFF,6,252,1801,1801,361,0.177285,0.157221,0.159589,0.177285,0.583298,0.119727,0.135734,9.018642e-04,f1_macro,0.159589,0.019608,NaN,shuffle_training_X_only
7,YFF,7,294,1801,1801,361,0.155125,0.135217,0.139419,0.155125,0.584097,0.119727,0.135734,2.634912e-02,f1_macro,0.139419,0.019608,NaN,shuffle_training_X_only
8,YFF,8,336,1801,1801,361,0.138504,0.113214,0.110419,0.138504,0.556635,0.119727,0.135734,1.543858e-01,f1_macro,0.110419,0.215686,NaN,shuffle_training_X_only
9,YFF,9,378,1801,1801,361,0.157895,0.127892,0.125173,0.157895,0.556349,0.119727,0.135734,1.840663e-02,f1_macro,0.125173,0.039216,NaN,shuffle_training_X_only
10,YFF,10,420,1801,1801,361,0.132964,0.103894,0.100892,0.132964,0.583862,0.119727,0.135734,2.406199e-01,f1_macro,0.100892,0.313725,NaN,shuffle_training_X_only
11,YFF,11,462,1801,1801,361,0.171745,0.139676,0.140909,0.171745,0.559483,0.119727,0.135734,2.334056e-03,f1_macro,0.140909,0.019608,NaN,shuffle_training_X_only
12,YFF,12,504,1801,1801,361,0.149584,0.114084,0.109561,0.149584,0.568241,0.119727,0.135734,5.111239e-02,f1_macro,0.109561,0.176471,NaN,shuffle_training_X_only
13,YFF,13,546,1801,1801,361,0.180055,0.148487,0.149105,0.180055,0.601866,0.119727,0.135734,5.460535e-04,f1_macro,0.149105,0.019608,NaN,shuffle_training_X_only
14,YFF,14,588,1801,1801,361,0.196676,0.152773,0.147132,0.196676,0.591196,0.119727,0.135734,1.876586e-05,f1_macro,0.147132,0.019608,NaN,shuffle_training_X_only
15,YFF,15,630,1801,1801,361,0.155125,0.135092,0.134263,0.155125,0.542848,0.119727,0.135734,2.634912e-02,f1_macro,0.134263,0.019608,NaN,shuffle_training_X_only
16,YFF,16,672,1801,1801,361,0.166205,0.132348,0.128856,0.166205,0.556570,0.119727,0.135734,5.627062e-03,f1_macro,0.128856,0.019608,NaN,shuffle_training_X_only
17,YFF,17,714,1801,1801,361,0.163435,0.133388,0.130217,0.163435,0.562505,0.119727,0.135734,8.505438e-03,f1_macro,0.130217,0.019608,NaN,shuffle_training_X_only
18,YFF,18,756,1801,1801,361,0.210526,0.168513,0.165317,0.210526,0.568191,0.119727,0.135734,7.157956e-07,f1_macro,0.165317,0.019608,NaN,shuffle_training_X_only
19,YFF,19,798,1801,1801,361,0.177285,0.144125,0.147176,0.177285,0.581546,0.119727,0.135734,9.018642e-04,f1_macro,0.147176,0.019608,NaN,shuffle_training_X_only

skipping YFG 2024-09-23: not all resamples finished
aggregated YFG 2024-09-24 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFG/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-09-24/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFG,0,0,1462,1462,293,0.191126,0.145748,0.141137,0.191126,0.611752,0.124206,0.139932,6.959774e-04,f1_macro,0.141137,0.019608,0.125342,shuffle_training_X_only
1,YFG,1,42,1462,1462,293,0.174061,0.127267,0.118475,0.174061,0.606323,0.124206,0.139932,8.187673e-03,f1_macro,0.118475,0.019608,0.142965,shuffle_training_X_only
2,YFG,2,84,1462,1462,293,0.177474,0.133132,0.127635,0.177474,0.598806,0.124206,0.139932,5.213925e-03,f1_macro,0.127635,0.039216,0.133905,shuffle_training_X_only
3,YFG,3,126,1462,1462,293,0.204778,0.159733,0.157390,0.204778,0.585909,0.124206,0.139932,6.705877e-05,f1_macro,0.157390,0.019608,NaN,shuffle_training_X_only
4,YFG,4,168,1462,1462,293,0.170648,0.140134,0.137527,0.170648,0.560218,0.124206,0.139932,1.258841e-02,f1_macro,0.137527,0.058824,NaN,shuffle_training_X_only
5,YFG,5,210,1462,1462,293,0.201365,0.160528,0.160097,0.201365,0.565653,0.124206,0.139932,1.240243e-04,f1_macro,0.160097,0.019608,NaN,shuffle_training_X_only
6,YFG,6,252,1462,1462,293,0.153584,0.118550,0.117664,0.153584,0.575383,0.124206,0.139932,7.845309e-02,f1_macro,0.117664,0.117647,NaN,shuffle_training_X_only
7,YFG,7,294,1462,1462,293,0.184300,0.147013,0.146414,0.184300,0.582145,0.124206,0.139932,1.985469e-03,f1_macro,0.146414,0.019608,NaN,shuffle_training_X_only
8,YFG,8,336,1462,1462,293,0.156997,0.120989,0.118706,0.156997,0.559864,0.124206,0.139932,5.680414e-02,f1_macro,0.118706,0.078431,NaN,shuffle_training_X_only
9,YFG,9,378,1462,1462,293,0.208191,0.180129,0.187198,0.208191,0.619344,0.124206,0.139932,3.555091e-05,f1_macro,0.187198,0.019608,NaN,shuffle_training_X_only
10,YFG,10,420,1462,1462,293,0.150171,0.122991,0.126093,0.150171,0.581989,0.124206,0.139932,1.060403e-01,f1_macro,0.126093,0.019608,NaN,shuffle_training_X_only
11,YFG,11,462,1462,1462,293,0.194539,0.156822,0.156176,0.194539,0.586659,0.124206,0.139932,3.996231e-04,f1_macro,0.156176,0.019608,NaN,shuffle_training_X_only
12,YFG,12,504,1462,1462,293,0.153584,0.127168,0.124550,0.153584,0.549675,0.124206,0.139932,7.845309e-02,f1_macro,0.124550,0.117647,NaN,shuffle_training_X_only
13,YFG,13,546,1462,1462,293,0.136519,0.100823,0.096690,0.136519,0.550375,0.124206,0.139932,2.857649e-01,f1_macro,0.096690,0.470588,NaN,shuffle_training_X_only
14,YFG,14,588,1462,1462,293,0.232082,0.175050,0.167053,0.232082,0.551472,0.124206,0.139932,2.444685e-07,f1_macro,0.167053,0.019608,NaN,shuffle_training_X_only
15,YFG,15,630,1462,1462,293,0.184300,0.136498,0.130393,0.184300,0.622712,0.124206,0.139932,1.985469e-03,f1_macro,0.130393,0.019608,NaN,shuffle_training_X_only
16,YFG,16,672,1462,1462,293,0.177474,0.136410,0.137811,0.177474,0.588288,0.124206,0.139932,5.213925e-03,f1_macro,0.137811,0.019608,NaN,shuffle_training_X_only
17,YFG,17,714,1462,1462,293,0.177474,0.138307,0.132417,0.177474,0.556770,0.124206,0.139932,5.213925e-03,f1_macro,0.132417,0.058824,NaN,shuffle_training_X_only
18,YFG,18,756,1462,1462,293,0.177474,0.149774,0.148646,0.177474,0.543402,0.124206,0.139932,5.213925e-03,f1_macro,0.148646,0.019608,NaN,shuffle_training_X_only
19,YFG,19,798,1462,1462,293,0.180887,0.139042,0.138088,0.180887,0.612203,0.124206,0.139932,3.251203e-03,f1_macro,0.138088,0.039216,NaN,shuffle_training_X_only

aggregated YFG 2024-09-25 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFG/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-09-25/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFG,0,0,4221,4221,845,0.204734,0.177413,0.171900,0.204734,0.618105,0.114401,0.128994,3.161739e-14,f1_macro,0.171900,0.019608,0.169653,shuffle_training_X_only
1,YFG,1,42,4221,4221,845,0.201183,0.168774,0.165670,0.201183,0.618432,0.114401,0.128994,2.490541e-13,f1_macro,0.165670,0.019608,0.174464,shuffle_training_X_only
2,YFG,2,84,4221,4221,845,0.181065,0.151159,0.149949,0.181065,0.608365,0.114401,0.128994,8.576628e-09,f1_macro,0.149949,0.019608,0.177891,shuffle_training_X_only
3,YFG,3,126,4221,4221,845,0.197633,0.173758,0.171893,0.197633,0.626849,0.114401,0.128994,1.838580e-12,f1_macro,0.171893,0.019608,NaN,shuffle_training_X_only
4,YFG,4,168,4221,4221,845,0.191716,0.165383,0.162881,0.191716,0.616892,0.114401,0.128994,4.445562e-11,f1_macro,0.162881,0.019608,NaN,shuffle_training_X_only
5,YFG,5,210,4221,4221,845,0.184615,0.162293,0.157785,0.184615,0.604101,0.114401,0.128994,1.589359e-09,f1_macro,0.157785,0.019608,NaN,shuffle_training_X_only
6,YFG,6,252,4221,4221,845,0.185799,0.155844,0.151621,0.185799,0.610014,0.114401,0.128994,8.923687e-10,f1_macro,0.151621,0.019608,NaN,shuffle_training_X_only
7,YFG,7,294,4221,4221,845,0.197633,0.168710,0.167329,0.197633,0.612888,0.114401,0.128994,1.838580e-12,f1_macro,0.167329,0.019608,NaN,shuffle_training_X_only
8,YFG,8,336,4221,4221,845,0.194083,0.168208,0.166368,0.194083,0.629554,0.114401,0.128994,1.271032e-11,f1_macro,0.166368,0.019608,NaN,shuffle_training_X_only
9,YFG,9,378,4221,4221,845,0.201183,0.172500,0.170128,0.201183,0.616450,0.114401,0.128994,2.490541e-13,f1_macro,0.170128,0.019608,NaN,shuffle_training_X_only
10,YFG,10,420,4221,4221,845,0.164497,0.142219,0.141140,0.164497,0.604914,0.114401,0.128994,8.794592e-06,f1_macro,0.141140,0.019608,NaN,shuffle_training_X_only
11,YFG,11,462,4221,4221,845,0.190533,0.167013,0.166195,0.190533,0.622244,0.114401,0.128994,8.221843e-11,f1_macro,0.166195,0.019608,NaN,shuffle_training_X_only
12,YFG,12,504,4221,4221,845,0.220118,0.188645,0.185326,0.220118,0.609913,0.114401,0.128994,1.985419e-18,f1_macro,0.185326,0.019608,NaN,shuffle_training_X_only
13,YFG,13,546,4221,4221,845,0.229586,0.199808,0.197902,0.229586,0.629025,0.114401,0.128994,2.902200e-21,f1_macro,0.197902,0.019608,NaN,shuffle_training_X_only
14,YFG,14,588,4221,4221,845,0.216568,0.187832,0.186808,0.216568,0.645095,0.114401,0.128994,2.054276e-17,f1_macro,0.186808,0.019608,NaN,shuffle_training_X_only
15,YFG,15,630,4221,4221,845,0.186982,0.160151,0.156420,0.186982,0.613616,0.114401,0.128994,4.972407e-10,f1_macro,0.156420,0.019608,NaN,shuffle_training_X_only
16,YFG,16,672,4221,4221,845,0.195266,0.167367,0.164215,0.195266,0.621736,0.114401,0.128994,6.721321e-12,f1_macro,0.164215,0.019608,NaN,shuffle_training_X_only
17,YFG,17,714,4221,4221,845,0.204734,0.174969,0.171929,0.204734,0.605292,0.114401,0.128994,3.161739e-14,f1_macro,0.171929,0.019608,NaN,shuffle_training_X_only
18,YFG,18,756,4221,4221,845,0.202367,0.175288,0.171856,0.202367,0.620404,0.114401,0.128994,1.260721e-13,f1_macro,0.171856,0.019608,NaN,shuffle_training_X_only
19,YFG,19,798,4221,4221,845,0.192899,0.170305,0.167316,0.192899,0.618888,0.114401,0.128994,2.385895e-11,f1_macro,0.167316,0.019608,NaN,shuffle_training_X_only

aggregated YFG 2024-09-26 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFG/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-09-26/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFG,0,0,3223,3223,645,0.201550,0.151039,0.147787,0.201550,0.580177,0.124706,0.144186,2.456678e-08,f1_macro,0.147787,0.019608,0.144230,shuffle_training_X_only
1,YFG,1,42,3223,3223,645,0.206202,0.154453,0.148410,0.206202,0.589125,0.124706,0.144186,4.057703e-09,f1_macro,0.148410,0.019608,0.139076,shuffle_training_X_only
2,YFG,2,84,3223,3223,645,0.195349,0.150202,0.146490,0.195349,0.577294,0.124706,0.144186,2.379113e-07,f1_macro,0.146490,0.019608,0.150501,shuffle_training_X_only
3,YFG,3,126,3223,3223,645,0.184496,0.140905,0.137015,0.184496,0.582201,0.124706,0.144186,8.763680e-06,f1_macro,0.137015,0.019608,NaN,shuffle_training_X_only
4,YFG,4,168,3223,3223,645,0.192248,0.142757,0.136774,0.192248,0.582450,0.124706,0.144186,6.995350e-07,f1_macro,0.136774,0.019608,NaN,shuffle_training_X_only
5,YFG,5,210,3223,3223,645,0.189147,0.140644,0.134572,0.189147,0.585897,0.124706,0.144186,1.979572e-06,f1_macro,0.134572,0.019608,NaN,shuffle_training_X_only
6,YFG,6,252,3223,3223,645,0.190698,0.139390,0.129857,0.190698,0.580931,0.124706,0.144186,1.182440e-06,f1_macro,0.129857,0.019608,NaN,shuffle_training_X_only
7,YFG,7,294,3223,3223,645,0.231008,0.169247,0.158969,0.231008,0.611563,0.124706,0.144186,6.965151e-14,f1_macro,0.158969,0.019608,NaN,shuffle_training_X_only
8,YFG,8,336,3223,3223,645,0.206202,0.160621,0.159806,0.206202,0.599881,0.124706,0.144186,4.057703e-09,f1_macro,0.159806,0.019608,NaN,shuffle_training_X_only
9,YFG,9,378,3223,3223,645,0.201550,0.147857,0.139341,0.201550,0.599249,0.124706,0.144186,2.456678e-08,f1_macro,0.139341,0.019608,NaN,shuffle_training_X_only
10,YFG,10,420,3223,3223,645,0.212403,0.158204,0.150609,0.212403,0.592536,0.124706,0.144186,3.234374e-10,f1_macro,0.150609,0.019608,NaN,shuffle_training_X_only
11,YFG,11,462,3223,3223,645,0.186047,0.140032,0.133839,0.186047,0.576943,0.124706,0.144186,5.389450e-06,f1_macro,0.133839,0.019608,NaN,shuffle_training_X_only
12,YFG,12,504,3223,3223,645,0.200000,0.148203,0.142145,0.200000,0.575097,0.124706,0.144186,4.395181e-08,f1_macro,0.142145,0.019608,NaN,shuffle_training_X_only
13,YFG,13,546,3223,3223,645,0.206202,0.151482,0.141799,0.206202,0.584247,0.124706,0.144186,4.057703e-09,f1_macro,0.141799,0.019608,NaN,shuffle_training_X_only
14,YFG,14,588,3223,3223,645,0.218605,0.160330,0.152586,0.218605,0.569403,0.124706,0.144186,2.231855e-11,f1_macro,0.152586,0.019608,NaN,shuffle_training_X_only
15,YFG,15,630,3223,3223,645,0.220155,0.161748,0.153056,0.220155,0.575055,0.124706,0.144186,1.118742e-11,f1_macro,0.153056,0.019608,NaN,shuffle_training_X_only
16,YFG,16,672,3223,3223,645,0.176744,0.129973,0.123644,0.176744,0.551838,0.124706,0.144186,8.593565e-05,f1_macro,0.123644,0.019608,NaN,shuffle_training_X_only
17,YFG,17,714,3223,3223,645,0.204651,0.149620,0.141434,0.204651,0.602954,0.124706,0.144186,7.464165e-09,f1_macro,0.141434,0.019608,NaN,shuffle_training_X_only
18,YFG,18,756,3223,3223,645,0.195349,0.149475,0.147928,0.195349,0.593627,0.124706,0.144186,2.379113e-07,f1_macro,0.147928,0.019608,NaN,shuffle_training_X_only
19,YFG,19,798,3223,3223,645,0.209302,0.152588,0.144005,0.209302,0.594919,0.124706,0.144186,1.166638e-09,f1_macro,0.144005,0.019608,NaN,shuffle_training_X_only

aggregated YFG 2024-09-27 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFG/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-09-27/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFG,0,0,453,453,91,0.164835,0.184747,0.173498,0.164835,0.575095,0.112426,0.131868,0.083279,f1_macro,0.173498,0.019608,0.233089,shuffle_training_X_only
1,YFG,1,42,453,453,91,0.109890,0.091061,0.076132,0.109890,0.477055,0.112426,0.131868,0.579633,f1_macro,0.076132,0.764706,0.192356,shuffle_training_X_only
2,YFG,2,84,453,453,91,0.131868,0.158838,0.158452,0.131868,0.543243,0.112426,0.131868,0.324122,f1_macro,0.158452,0.058824,0.173883,shuffle_training_X_only
3,YFG,3,126,453,453,91,0.142857,0.146212,0.147797,0.142857,0.600990,0.112426,0.131868,0.219995,f1_macro,0.147797,0.117647,NaN,shuffle_training_X_only
4,YFG,4,168,453,453,91,0.098901,0.084899,0.079386,0.098901,0.560872,0.112426,0.131868,0.706914,f1_macro,0.079386,0.764706,NaN,shuffle_training_X_only
5,YFG,5,210,453,453,91,0.197802,0.175303,0.170114,0.197802,0.601373,0.112426,0.131868,0.012005,f1_macro,0.170114,0.019608,NaN,shuffle_training_X_only
6,YFG,6,252,453,453,91,0.164835,0.137172,0.129297,0.164835,0.577018,0.112426,0.131868,0.083279,f1_macro,0.129297,0.137255,NaN,shuffle_training_X_only
7,YFG,7,294,453,453,91,0.120879,0.130253,0.116783,0.120879,0.592394,0.112426,0.131868,0.447431,f1_macro,0.116783,0.235294,NaN,shuffle_training_X_only
8,YFG,8,336,453,453,91,0.175824,0.194747,0.201548,0.175824,0.582962,0.112426,0.131868,0.046500,f1_macro,0.201548,0.019608,NaN,shuffle_training_X_only
9,YFG,9,378,453,453,91,0.109890,0.116869,0.104208,0.109890,0.564997,0.112426,0.131868,0.579633,f1_macro,0.104208,0.352941,NaN,shuffle_training_X_only
10,YFG,10,420,453,453,91,0.142857,0.149697,0.147345,0.142857,0.551398,0.112426,0.131868,0.219995,f1_macro,0.147345,0.039216,NaN,shuffle_training_X_only
11,YFG,11,462,453,453,91,0.197802,0.196616,0.193516,0.197802,0.585535,0.112426,0.131868,0.012005,f1_macro,0.193516,0.019608,NaN,shuffle_training_X_only
12,YFG,12,504,453,453,91,0.197802,0.192727,0.183007,0.197802,0.621222,0.112426,0.131868,0.012005,f1_macro,0.183007,0.039216,NaN,shuffle_training_X_only
13,YFG,13,546,453,453,91,0.164835,0.186616,0.183298,0.164835,0.540593,0.112426,0.131868,0.083279,f1_macro,0.183298,0.039216,NaN,shuffle_training_X_only
14,YFG,14,588,453,453,91,0.197802,0.188838,0.186395,0.197802,0.597908,0.112426,0.131868,0.012005,f1_macro,0.186395,0.039216,NaN,shuffle_training_X_only
15,YFG,15,630,453,453,91,0.153846,0.152323,0.165361,0.153846,0.601961,0.112426,0.131868,0.139843,f1_macro,0.165361,0.058824,NaN,shuffle_training_X_only
16,YFG,16,672,453,453,91,0.175824,0.218990,0.201458,0.175824,0.687370,0.112426,0.131868,0.046500,f1_macro,0.201458,0.019608,NaN,shuffle_training_X_only
17,YFG,17,714,453,453,91,0.197802,0.188687,0.163926,0.197802,0.602395,0.112426,0.131868,0.012005,f1_macro,0.163926,0.039216,NaN,shuffle_training_X_only
18,YFG,18,756,453,453,91,0.153846,0.177677,0.160768,0.153846,0.643065,0.112426,0.131868,0.139843,f1_macro,0.160768,0.019608,NaN,shuffle_training_X_only
19,YFG,19,798,453,453,91,0.175824,0.198434,0.196269,0.175824,0.622423,0.112426,0.131868,0.046500,f1_macro,0.196269,0.019608,NaN,shuffle_training_X_only

aggregated YFI 2024-10-15 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFI/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-10-15/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFI,0,0,1056,1056,212,0.179245,0.146053,0.143447,0.179245,0.533857,0.118681,0.132075,0.006364,f1_macro,0.143447,0.019608,0.154231,shuffle_training_X_only
1,YFI,1,42,1056,1056,212,0.165094,0.131955,0.129456,0.165094,0.545014,0.118681,0.132075,0.027636,f1_macro,0.129456,0.058824,0.150303,shuffle_training_X_only
2,YFI,2,84,1056,1056,212,0.132075,0.101692,0.096899,0.132075,0.530715,0.118681,0.132075,0.302571,f1_macro,0.096899,0.529412,0.124856,shuffle_training_X_only
3,YFI,3,126,1056,1056,212,0.132075,0.105075,0.096730,0.132075,0.544920,0.118681,0.132075,0.302571,f1_macro,0.096730,0.392157,NaN,shuffle_training_X_only
4,YFI,4,168,1056,1056,212,0.165094,0.130075,0.124794,0.165094,0.583480,0.118681,0.132075,0.027636,f1_macro,0.124794,0.078431,NaN,shuffle_training_X_only
5,YFI,5,210,1056,1056,212,0.179245,0.146053,0.142306,0.179245,0.549428,0.118681,0.132075,0.006364,f1_macro,0.142306,0.019608,NaN,shuffle_training_X_only
6,YFI,6,252,1056,1056,212,0.146226,0.114098,0.107646,0.146226,0.558793,0.118681,0.132075,0.129651,f1_macro,0.107646,0.098039,NaN,shuffle_training_X_only
7,YFI,7,294,1056,1056,212,0.146226,0.112406,0.104628,0.146226,0.531174,0.118681,0.132075,0.129651,f1_macro,0.104628,0.235294,NaN,shuffle_training_X_only
8,YFI,8,336,1056,1056,212,0.165094,0.133647,0.132697,0.165094,0.564982,0.118681,0.132075,0.027636,f1_macro,0.132697,0.019608,NaN,shuffle_training_X_only
9,YFI,9,378,1056,1056,212,0.202830,0.158647,0.140590,0.202830,0.604335,0.118681,0.132075,0.000312,f1_macro,0.140590,0.019608,NaN,shuffle_training_X_only
10,YFI,10,420,1056,1056,212,0.132075,0.101692,0.095259,0.132075,0.519864,0.118681,0.132075,0.302571,f1_macro,0.095259,0.352941,NaN,shuffle_training_X_only
11,YFI,11,462,1056,1056,212,0.174528,0.135526,0.126276,0.174528,0.588891,0.118681,0.132075,0.010689,f1_macro,0.126276,0.039216,NaN,shuffle_training_X_only
12,YFI,12,504,1056,1056,212,0.108491,0.082143,0.076433,0.108491,0.542944,0.118681,0.132075,0.707530,f1_macro,0.076433,0.823529,NaN,shuffle_training_X_only
13,YFI,13,546,1056,1056,212,0.174528,0.145865,0.139254,0.174528,0.547282,0.118681,0.132075,0.010689,f1_macro,0.139254,0.019608,NaN,shuffle_training_X_only
14,YFI,14,588,1056,1056,212,0.113208,0.085714,0.078593,0.113208,0.500881,0.118681,0.132075,0.628734,f1_macro,0.078593,0.705882,NaN,shuffle_training_X_only
15,YFI,15,630,1056,1056,212,0.188679,0.146241,0.136746,0.188679,0.546646,0.118681,0.132075,0.002071,f1_macro,0.136746,0.058824,NaN,shuffle_training_X_only
16,YFI,16,672,1056,1056,212,0.136792,0.105263,0.097703,0.136792,0.576081,0.118681,0.132075,0.234926,f1_macro,0.097703,0.411765,NaN,shuffle_training_X_only
17,YFI,17,714,1056,1056,212,0.165094,0.128383,0.121558,0.165094,0.557801,0.118681,0.132075,0.027636,f1_macro,0.121558,0.058824,NaN,shuffle_training_X_only
18,YFI,18,756,1056,1056,212,0.141509,0.110526,0.104137,0.141509,0.567264,0.118681,0.132075,0.177128,f1_macro,0.104137,0.215686,NaN,shuffle_training_X_only
19,YFI,19,798,1056,1056,212,0.216981,0.179981,0.175517,0.216981,0.594841,0.118681,0.132075,0.000037,f1_macro,0.175517,0.019608,NaN,shuffle_training_X_only

aggregated YFI 2024-10-16 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFI/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-10-16/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFI,0,0,3660,3660,732,0.202186,0.155141,0.151770,0.202186,0.595653,0.12263,0.142077,7.473758e-10,f1_macro,0.151770,0.019608,0.141299,shuffle_training_X_only
1,YFI,1,42,3660,3660,732,0.217213,0.170986,0.171106,0.217213,0.603268,0.12263,0.142077,5.744828e-13,f1_macro,0.171106,0.019608,0.146566,shuffle_training_X_only
2,YFI,2,84,3660,3660,732,0.180328,0.137797,0.133109,0.180328,0.573536,0.12263,0.142077,4.222723e-06,f1_macro,0.133109,0.019608,0.153033,shuffle_training_X_only
3,YFI,3,126,3660,3660,732,0.173497,0.131194,0.125816,0.173497,0.581915,0.12263,0.142077,3.983225e-05,f1_macro,0.125816,0.019608,NaN,shuffle_training_X_only
4,YFI,4,168,3660,3660,732,0.176230,0.134488,0.131115,0.176230,0.578947,0.12263,0.142077,1.667216e-05,f1_macro,0.131115,0.019608,NaN,shuffle_training_X_only
5,YFI,5,210,3660,3660,732,0.217213,0.161257,0.151112,0.217213,0.605645,0.12263,0.142077,5.744828e-13,f1_macro,0.151112,0.019608,NaN,shuffle_training_X_only
6,YFI,6,252,3660,3660,732,0.178962,0.137216,0.131523,0.178962,0.601270,0.12263,0.142077,6.733522e-06,f1_macro,0.131523,0.019608,NaN,shuffle_training_X_only
7,YFI,7,294,3660,3660,732,0.207650,0.160562,0.157397,0.207650,0.596386,0.12263,0.142077,6.166993e-11,f1_macro,0.157397,0.019608,NaN,shuffle_training_X_only
8,YFI,8,336,3660,3660,732,0.189891,0.145467,0.141307,0.189891,0.587156,0.12263,0.142077,1.261134e-07,f1_macro,0.141307,0.019608,NaN,shuffle_training_X_only
9,YFI,9,378,3660,3660,732,0.178962,0.138368,0.134338,0.178962,0.586629,0.12263,0.142077,6.733522e-06,f1_macro,0.134338,0.019608,NaN,shuffle_training_X_only
10,YFI,10,420,3660,3660,732,0.169399,0.127796,0.122106,0.169399,0.567274,0.12263,0.142077,1.374825e-04,f1_macro,0.122106,0.019608,NaN,shuffle_training_X_only
11,YFI,11,462,3660,3660,732,0.199454,0.153650,0.148433,0.199454,0.581793,0.12263,0.142077,2.476795e-09,f1_macro,0.148433,0.019608,NaN,shuffle_training_X_only
12,YFI,12,504,3660,3660,732,0.189891,0.144596,0.137332,0.189891,0.574582,0.12263,0.142077,1.261134e-07,f1_macro,0.137332,0.019608,NaN,shuffle_training_X_only
13,YFI,13,546,3660,3660,732,0.189891,0.146788,0.140016,0.189891,0.587984,0.12263,0.142077,1.261134e-07,f1_macro,0.140016,0.019608,NaN,shuffle_training_X_only
14,YFI,14,588,3660,3660,732,0.191257,0.144060,0.139510,0.191257,0.560887,0.12263,0.142077,7.378013e-08,f1_macro,0.139510,0.019608,NaN,shuffle_training_X_only
15,YFI,15,630,3660,3660,732,0.209016,0.158543,0.147993,0.209016,0.591154,0.12263,0.142077,3.238809e-11,f1_macro,0.147993,0.019608,NaN,shuffle_training_X_only
16,YFI,16,672,3660,3660,732,0.203552,0.152550,0.144553,0.203552,0.595295,0.12263,0.142077,4.055043e-10,f1_macro,0.144553,0.019608,NaN,shuffle_training_X_only
17,YFI,17,714,3660,3660,732,0.188525,0.143710,0.137749,0.188525,0.582033,0.12263,0.142077,2.137313e-07,f1_macro,0.137749,0.019608,NaN,shuffle_training_X_only
18,YFI,18,756,3660,3660,732,0.198087,0.146277,0.136781,0.198087,0.593924,0.12263,0.142077,4.453144e-09,f1_macro,0.136781,0.019608,NaN,shuffle_training_X_only
19,YFI,19,798,3660,3660,732,0.184426,0.138222,0.128873,0.184426,0.589519,0.12263,0.142077,9.879582e-07,f1_macro,0.128873,0.019608,NaN,shuffle_training_X_only

aggregated YFI 2024-10-17 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFI/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-10-17/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFI,0,0,4741,4741,949,0.221286,0.148474,0.140507,0.221286,0.626456,0.137749,0.1549,2.085550e-12,f1_macro,0.140507,0.019608,0.142292,shuffle_training_X_only
1,YFI,1,42,4741,4741,949,0.212856,0.144303,0.138685,0.212856,0.602799,0.137749,0.1549,1.854535e-10,f1_macro,0.138685,0.019608,0.150771,shuffle_training_X_only
2,YFI,2,84,4741,4741,949,0.227608,0.161280,0.158172,0.227608,0.612860,0.137749,0.1549,5.599468e-14,f1_macro,0.158172,0.019608,0.147636,shuffle_training_X_only
3,YFI,3,126,4741,4741,949,0.216017,0.143845,0.132943,0.216017,0.620805,0.137749,0.1549,3.606513e-11,f1_macro,0.132943,0.019608,NaN,shuffle_training_X_only
4,YFI,4,168,4741,4741,949,0.245522,0.160706,0.142783,0.245522,0.607217,0.137749,0.1549,6.351383e-19,f1_macro,0.142783,0.019608,NaN,shuffle_training_X_only
5,YFI,5,210,4741,4741,949,0.229715,0.155121,0.146433,0.229715,0.627748,0.137749,0.1549,1.599401e-14,f1_macro,0.146433,0.019608,NaN,shuffle_training_X_only
6,YFI,6,252,4741,4741,949,0.227608,0.154318,0.143061,0.227608,0.609984,0.137749,0.1549,5.599468e-14,f1_macro,0.143061,0.019608,NaN,shuffle_training_X_only
7,YFI,7,294,4741,4741,949,0.212856,0.141484,0.131938,0.212856,0.619180,0.137749,0.1549,1.854535e-10,f1_macro,0.131938,0.019608,NaN,shuffle_training_X_only
8,YFI,8,336,4741,4741,949,0.243414,0.166274,0.157666,0.243414,0.630858,0.137749,0.1549,2.641342e-18,f1_macro,0.157666,0.019608,NaN,shuffle_training_X_only
9,YFI,9,378,4741,4741,949,0.222339,0.145248,0.130392,0.222339,0.607974,0.137749,0.1549,1.158309e-12,f1_macro,0.130392,0.019608,NaN,shuffle_training_X_only
10,YFI,10,420,4741,4741,949,0.197050,0.131513,0.122816,0.197050,0.591702,0.137749,0.1549,2.887174e-07,f1_macro,0.122816,0.019608,NaN,shuffle_training_X_only
11,YFI,11,462,4741,4741,949,0.232877,0.154882,0.144431,0.232877,0.619096,0.137749,0.1549,2.336995e-15,f1_macro,0.144431,0.019608,NaN,shuffle_training_X_only
12,YFI,12,504,4741,4741,949,0.232877,0.151813,0.135945,0.232877,0.604904,0.137749,0.1549,2.336995e-15,f1_macro,0.135945,0.019608,NaN,shuffle_training_X_only
13,YFI,13,546,4741,4741,949,0.222339,0.147742,0.132016,0.222339,0.616908,0.137749,0.1549,1.158309e-12,f1_macro,0.132016,0.019608,NaN,shuffle_training_X_only
14,YFI,14,588,4741,4741,949,0.228662,0.153917,0.144008,0.228662,0.607823,0.137749,0.1549,3.001404e-14,f1_macro,0.144008,0.019608,NaN,shuffle_training_X_only
15,YFI,15,630,4741,4741,949,0.240253,0.164130,0.155108,0.240253,0.608487,0.137749,0.1549,2.147252e-17,f1_macro,0.155108,0.019608,NaN,shuffle_training_X_only
16,YFI,16,672,4741,4741,949,0.243414,0.159433,0.142274,0.243414,0.633112,0.137749,0.1549,2.641342e-18,f1_macro,0.142274,0.019608,NaN,shuffle_training_X_only
17,YFI,17,714,4741,4741,949,0.201264,0.141199,0.136301,0.201264,0.615752,0.137749,0.1549,4.669668e-08,f1_macro,0.136301,0.019608,NaN,shuffle_training_X_only
18,YFI,18,756,4741,4741,949,0.225501,0.152127,0.142907,0.225501,0.629919,0.137749,0.1549,1.914815e-13,f1_macro,0.142907,0.019608,NaN,shuffle_training_X_only
19,YFI,19,798,4741,4741,949,0.230769,0.157535,0.149494,0.230769,0.612399,0.137749,0.1549,8.473293e-15,f1_macro,0.149494,0.019608,NaN,shuffle_training_X_only

aggregated YFI 2024-10-18 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFI/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-10-18/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFI,0,0,5350,5350,1070,0.191589,0.149523,0.146932,0.191589,0.576339,0.123719,0.139252,1.676005e-10,f1_macro,0.146932,0.019608,0.138533,shuffle_training_X_only
1,YFI,1,42,5350,5350,1070,0.194393,0.145328,0.139796,0.194393,0.590136,0.123719,0.139252,3.347072e-11,f1_macro,0.139796,0.019608,0.146937,shuffle_training_X_only
2,YFI,2,84,5350,5350,1070,0.192523,0.149360,0.150602,0.192523,0.576953,0.123719,0.139252,9.854016e-11,f1_macro,0.150602,0.019608,0.146552,shuffle_training_X_only
3,YFI,3,126,5350,5350,1070,0.199065,0.147735,0.137779,0.199065,0.600663,0.123719,0.139252,2.033234e-12,f1_macro,0.137779,0.019608,NaN,shuffle_training_X_only
4,YFI,4,168,5350,5350,1070,0.178505,0.128560,0.115632,0.178505,0.579778,0.123719,0.139252,1.520184e-07,f1_macro,0.115632,0.019608,NaN,shuffle_training_X_only
5,YFI,5,210,5350,5350,1070,0.194393,0.140764,0.127896,0.194393,0.573784,0.123719,0.139252,3.347072e-11,f1_macro,0.127896,0.019608,NaN,shuffle_training_X_only
6,YFI,6,252,5350,5350,1070,0.202804,0.149820,0.141364,0.202804,0.595672,0.123719,0.139252,1.950515e-13,f1_macro,0.141364,0.019608,NaN,shuffle_training_X_only
7,YFI,7,294,5350,5350,1070,0.208411,0.152892,0.141248,0.208411,0.586979,0.123719,0.139252,4.891737e-15,f1_macro,0.141248,0.019608,NaN,shuffle_training_X_only
8,YFI,8,336,5350,5350,1070,0.194393,0.148244,0.141741,0.194393,0.594180,0.123719,0.139252,3.347072e-11,f1_macro,0.141741,0.019608,NaN,shuffle_training_X_only
9,YFI,9,378,5350,5350,1070,0.195327,0.144899,0.136127,0.195327,0.597340,0.123719,0.139252,1.933725e-11,f1_macro,0.136127,0.019608,NaN,shuffle_training_X_only
10,YFI,10,420,5350,5350,1070,0.207477,0.153825,0.144796,0.207477,0.585698,0.123719,0.139252,9.169055e-15,f1_macro,0.144796,0.019608,NaN,shuffle_training_X_only
11,YFI,11,462,5350,5350,1070,0.176636,0.128062,0.116956,0.176636,0.579535,0.123719,0.139252,3.649858e-07,f1_macro,0.116956,0.019608,NaN,shuffle_training_X_only
12,YFI,12,504,5350,5350,1070,0.202804,0.148810,0.139073,0.202804,0.595593,0.123719,0.139252,1.950515e-13,f1_macro,0.139073,0.019608,NaN,shuffle_training_X_only
13,YFI,13,546,5350,5350,1070,0.203738,0.149440,0.139627,0.203738,0.573162,0.123719,0.139252,1.070220e-13,f1_macro,0.139627,0.019608,NaN,shuffle_training_X_only
14,YFI,14,588,5350,5350,1070,0.213084,0.159670,0.150080,0.213084,0.595940,0.123719,0.139252,1.945667e-16,f1_macro,0.150080,0.019608,NaN,shuffle_training_X_only
15,YFI,15,630,5350,5350,1070,0.199065,0.143381,0.127213,0.199065,0.597791,0.123719,0.139252,2.033234e-12,f1_macro,0.127213,0.019608,NaN,shuffle_training_X_only
16,YFI,16,672,5350,5350,1070,0.180374,0.135765,0.129036,0.180374,0.578913,0.123719,0.139252,6.178029e-08,f1_macro,0.129036,0.019608,NaN,shuffle_training_X_only
17,YFI,17,714,5350,5350,1070,0.209346,0.155063,0.142798,0.209346,0.589991,0.123719,0.139252,2.595293e-15,f1_macro,0.142798,0.019608,NaN,shuffle_training_X_only
18,YFI,18,756,5350,5350,1070,0.217757,0.162120,0.153205,0.217757,0.607995,0.123719,0.139252,6.747903e-18,f1_macro,0.153205,0.019608,NaN,shuffle_training_X_only
19,YFI,19,798,5350,5350,1070,0.205607,0.150733,0.139812,0.205607,0.597558,0.123719,0.139252,3.167910e-14,f1_macro,0.139812,0.019608,NaN,shuffle_training_X_only

aggregated YFI 2024-10-19 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFI/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-10-19/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFI,0,0,7365,7365,1473,0.203666,0.155775,0.145110,0.203666,0.580929,0.120038,0.139172,5.377167e-20,f1_macro,0.145110,0.019608,0.147319,shuffle_training_X_only
1,YFI,1,42,7365,7365,1473,0.191446,0.148054,0.142633,0.191446,0.581420,0.120038,0.139172,2.484801e-15,f1_macro,0.142633,0.019608,0.147375,shuffle_training_X_only
2,YFI,2,84,7365,7365,1473,0.216565,0.175101,0.173683,0.216565,0.606043,0.120038,0.139172,1.501898e-25,f1_macro,0.173683,0.019608,0.151058,shuffle_training_X_only
3,YFI,3,126,7365,7365,1473,0.205703,0.157826,0.146068,0.205703,0.592412,0.120038,0.139172,7.869558e-21,f1_macro,0.146068,0.019608,NaN,shuffle_training_X_only
4,YFI,4,168,7365,7365,1473,0.193483,0.146965,0.135360,0.193483,0.598678,0.120038,0.139172,4.562819e-16,f1_macro,0.135360,0.019608,NaN,shuffle_training_X_only
5,YFI,5,210,7365,7365,1473,0.202987,0.153054,0.141860,0.202987,0.603279,0.120038,0.139172,1.011985e-19,f1_macro,0.141860,0.019608,NaN,shuffle_training_X_only
6,YFI,6,252,7365,7365,1473,0.190088,0.142739,0.132158,0.190088,0.606775,0.120038,0.139172,7.527493e-15,f1_macro,0.132158,0.019608,NaN,shuffle_training_X_only
7,YFI,7,294,7365,7365,1473,0.194162,0.148780,0.136688,0.194162,0.587996,0.120038,0.139172,2.571341e-16,f1_macro,0.136688,0.019608,NaN,shuffle_training_X_only
8,YFI,8,336,7365,7365,1473,0.208418,0.158896,0.147659,0.208418,0.597632,0.120038,0.139172,5.731028e-22,f1_macro,0.147659,0.019608,NaN,shuffle_training_X_only
9,YFI,9,378,7365,7365,1473,0.205703,0.158005,0.147297,0.205703,0.592200,0.120038,0.139172,7.869558e-21,f1_macro,0.147297,0.019608,NaN,shuffle_training_X_only
10,YFI,10,420,7365,7365,1473,0.212492,0.161530,0.149487,0.212492,0.610132,0.120038,0.139172,9.972099e-24,f1_macro,0.149487,0.019608,NaN,shuffle_training_X_only
11,YFI,11,462,7365,7365,1473,0.205703,0.156792,0.143716,0.205703,0.589058,0.120038,0.139172,7.869558e-21,f1_macro,0.143716,0.019608,NaN,shuffle_training_X_only
12,YFI,12,504,7365,7365,1473,0.221317,0.168905,0.157130,0.221317,0.600652,0.120038,0.139172,9.389320e-28,f1_macro,0.157130,0.019608,NaN,shuffle_training_X_only
13,YFI,13,546,7365,7365,1473,0.218601,0.168754,0.159367,0.218601,0.608681,0.120038,0.139172,1.747062e-26,f1_macro,0.159367,0.019608,NaN,shuffle_training_X_only
14,YFI,14,588,7365,7365,1473,0.205703,0.155592,0.142521,0.205703,0.591217,0.120038,0.139172,7.869558e-21,f1_macro,0.142521,0.019608,NaN,shuffle_training_X_only
15,YFI,15,630,7365,7365,1473,0.211813,0.162701,0.153735,0.211813,0.608300,0.120038,0.139172,1.978810e-23,f1_macro,0.153735,0.019608,NaN,shuffle_training_X_only
16,YFI,16,672,7365,7365,1473,0.214528,0.164614,0.152189,0.214528,0.601367,0.120038,0.139172,1.245948e-24,f1_macro,0.152189,0.019608,NaN,shuffle_training_X_only
17,YFI,17,714,7365,7365,1473,0.196198,0.151290,0.140183,0.196198,0.598386,0.120038,0.139172,4.485791e-17,f1_macro,0.140183,0.019608,NaN,shuffle_training_X_only
18,YFI,18,756,7365,7365,1473,0.207060,0.155840,0.143899,0.207060,0.592482,0.120038,0.139172,2.141101e-21,f1_macro,0.143899,0.019608,NaN,shuffle_training_X_only
19,YFI,19,798,7365,7365,1473,0.202308,0.154672,0.147199,0.202308,0.600603,0.120038,0.139172,1.896693e-19,f1_macro,0.147199,0.019608,NaN,shuffle_training_X_only

aggregated YFI 2024-10-20 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFI/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-10-20/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFI,0,0,5383,5383,1077,0.218199,0.176085,0.170632,0.218199,0.610288,0.117949,0.131848,1.216118e-20,f1_macro,0.170632,0.019608,0.173365,shuffle_training_X_only
1,YFI,1,42,5383,5383,1077,0.206128,0.164009,0.159019,0.206128,0.610227,0.117949,0.131848,1.190205e-16,f1_macro,0.159019,0.019608,0.186906,shuffle_training_X_only
2,YFI,2,84,5383,5383,1077,0.221913,0.181495,0.177211,0.221913,0.618087,0.117949,0.131848,5.985396e-22,f1_macro,0.177211,0.019608,0.173053,shuffle_training_X_only
3,YFI,3,126,5383,5383,1077,0.232126,0.183002,0.172952,0.232126,0.621286,0.117949,0.131848,9.803688e-26,f1_macro,0.172952,0.019608,NaN,shuffle_training_X_only
4,YFI,4,168,5383,5383,1077,0.224698,0.177980,0.163993,0.224698,0.623352,0.117949,0.131848,5.914876e-23,f1_macro,0.163993,0.019608,NaN,shuffle_training_X_only
5,YFI,5,210,5383,5383,1077,0.233055,0.183498,0.170026,0.233055,0.626834,0.117949,0.131848,4.302158e-26,f1_macro,0.170026,0.019608,NaN,shuffle_training_X_only
6,YFI,6,252,5383,5383,1077,0.203343,0.160244,0.151699,0.203343,0.598625,0.117949,0.131848,8.688701e-16,f1_macro,0.151699,0.019608,NaN,shuffle_training_X_only
7,YFI,7,294,5383,5383,1077,0.217270,0.170907,0.158817,0.217270,0.621218,0.117949,0.131848,2.547609e-20,f1_macro,0.158817,0.019608,NaN,shuffle_training_X_only
8,YFI,8,336,5383,5383,1077,0.221913,0.177007,0.169018,0.221913,0.616485,0.117949,0.131848,5.985396e-22,f1_macro,0.169018,0.019608,NaN,shuffle_training_X_only
9,YFI,9,378,5383,5383,1077,0.246054,0.195575,0.186068,0.246054,0.638636,0.117949,0.131848,2.477847e-31,f1_macro,0.186068,0.019608,NaN,shuffle_training_X_only
10,YFI,10,420,5383,5383,1077,0.228412,0.182339,0.178278,0.228412,0.615817,0.117949,0.131848,2.510519e-24,f1_macro,0.178278,0.019608,NaN,shuffle_training_X_only
11,YFI,11,462,5383,5383,1077,0.239554,0.192526,0.183949,0.239554,0.636101,0.117949,0.131848,1.168399e-28,f1_macro,0.183949,0.019608,NaN,shuffle_training_X_only
12,YFI,12,504,5383,5383,1077,0.213556,0.167889,0.160306,0.213556,0.616285,0.117949,0.131848,4.648414e-19,f1_macro,0.160306,0.019608,NaN,shuffle_training_X_only
13,YFI,13,546,5383,5383,1077,0.202414,0.161627,0.154822,0.202414,0.622316,0.117949,0.131848,1.666676e-15,f1_macro,0.154822,0.019608,NaN,shuffle_training_X_only
14,YFI,14,588,5383,5383,1077,0.225627,0.179424,0.171161,0.225627,0.615921,0.117949,0.131848,2.705918e-23,f1_macro,0.171161,0.019608,NaN,shuffle_training_X_only
15,YFI,15,630,5383,5383,1077,0.239554,0.191831,0.184122,0.239554,0.638605,0.117949,0.131848,1.168399e-28,f1_macro,0.184122,0.019608,NaN,shuffle_training_X_only
16,YFI,16,672,5383,5383,1077,0.219127,0.173916,0.163619,0.219127,0.611824,0.117949,0.131848,5.774133e-21,f1_macro,0.163619,0.019608,NaN,shuffle_training_X_only
17,YFI,17,714,5383,5383,1077,0.229341,0.183003,0.172139,0.229341,0.613011,0.117949,0.131848,1.124729e-24,f1_macro,0.172139,0.019608,NaN,shuffle_training_X_only
18,YFI,18,756,5383,5383,1077,0.212628,0.168856,0.160597,0.212628,0.605114,0.117949,0.131848,9.477629e-19,f1_macro,0.160597,0.019608,NaN,shuffle_training_X_only
19,YFI,19,798,5383,5383,1077,0.215413,0.170684,0.159249,0.215413,0.619593,0.117949,0.131848,1.100078e-19,f1_macro,0.159249,0.019608,NaN,shuffle_training_X_only

aggregated YFI 2024-10-21 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFI/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2024-10-21/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFI,0,0,1367,1367,274,0.149635,0.105628,0.103325,0.149635,0.588109,0.135516,0.153285,0.271477,f1_macro,0.103325,0.274510,0.140009,shuffle_training_X_only
1,YFI,1,42,1367,1367,274,0.211679,0.139394,0.130890,0.211679,0.589459,0.135516,0.153285,0.000350,f1_macro,0.130890,0.039216,0.157125,shuffle_training_X_only
2,YFI,2,84,1367,1367,274,0.186131,0.122727,0.112504,0.186131,0.582638,0.135516,0.153285,0.011420,f1_macro,0.112504,0.117647,0.151575,shuffle_training_X_only
3,YFI,3,126,1367,1367,274,0.186131,0.122727,0.112245,0.186131,0.583924,0.135516,0.153285,0.011420,f1_macro,0.112245,0.117647,NaN,shuffle_training_X_only
4,YFI,4,168,1367,1367,274,0.193431,0.128139,0.116925,0.193431,0.597738,0.135516,0.153285,0.004685,f1_macro,0.116925,0.058824,NaN,shuffle_training_X_only
5,YFI,5,210,1367,1367,274,0.186131,0.124675,0.114500,0.186131,0.548614,0.135516,0.153285,0.011420,f1_macro,0.114500,0.078431,NaN,shuffle_training_X_only
6,YFI,6,252,1367,1367,274,0.215328,0.142424,0.131122,0.215328,0.569345,0.135516,0.153285,0.000196,f1_macro,0.131122,0.019608,NaN,shuffle_training_X_only
7,YFI,7,294,1367,1367,274,0.200730,0.131602,0.117172,0.200730,0.582843,0.135516,0.153285,0.001767,f1_macro,0.117172,0.098039,NaN,shuffle_training_X_only
8,YFI,8,336,1367,1367,274,0.211679,0.140043,0.128481,0.211679,0.579512,0.135516,0.153285,0.000350,f1_macro,0.128481,0.019608,NaN,shuffle_training_X_only
9,YFI,9,378,1367,1367,274,0.237226,0.156061,0.145436,0.237226,0.627476,0.135516,0.153285,0.000004,f1_macro,0.145436,0.019608,NaN,shuffle_training_X_only
10,YFI,10,420,1367,1367,274,0.197080,0.129221,0.115663,0.197080,0.576261,0.135516,0.153285,0.002907,f1_macro,0.115663,0.078431,NaN,shuffle_training_X_only
11,YFI,11,462,1367,1367,274,0.240876,0.159740,0.144845,0.240876,0.595323,0.135516,0.153285,0.000002,f1_macro,0.144845,0.019608,NaN,shuffle_training_X_only
12,YFI,12,504,1367,1367,274,0.189781,0.124459,0.113515,0.189781,0.624879,0.135516,0.153285,0.007392,f1_macro,0.113515,0.058824,NaN,shuffle_training_X_only
13,YFI,13,546,1367,1367,274,0.175182,0.116234,0.105366,0.175182,0.591715,0.135516,0.153285,0.037030,f1_macro,0.105366,0.137255,NaN,shuffle_training_X_only
14,YFI,14,588,1367,1367,274,0.226277,0.150216,0.133070,0.226277,0.572682,0.135516,0.153285,0.000030,f1_macro,0.133070,0.019608,NaN,shuffle_training_X_only
15,YFI,15,630,1367,1367,274,0.237226,0.158009,0.146145,0.237226,0.599428,0.135516,0.153285,0.000004,f1_macro,0.146145,0.019608,NaN,shuffle_training_X_only
16,YFI,16,672,1367,1367,274,0.189781,0.124459,0.111556,0.189781,0.578267,0.135516,0.153285,0.007392,f1_macro,0.111556,0.039216,NaN,shuffle_training_X_only
17,YFI,17,714,1367,1367,274,0.200730,0.131602,0.116323,0.200730,0.611190,0.135516,0.153285,0.001767,f1_macro,0.116323,0.058824,NaN,shuffle_training_X_only
18,YFI,18,756,1367,1367,274,0.208029,0.138961,0.129312,0.208029,0.566186,0.135516,0.153285,0.000613,f1_macro,0.129312,0.019608,NaN,shuffle_training_X_only
19,YFI,19,798,1367,1367,274,0.233577,0.157576,0.148376,0.233577,0.636911,0.135516,0.153285,0.000008,f1_macro,0.148376,0.019608,NaN,shuffle_training_X_only

aggregated YFK 2025-02-10 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFK/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-02-10/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFK,0,0,286,286,58,0.155172,0.135802,0.137731,0.155172,0.586173,0.12604,0.155172,0.305457,f1_macro,0.137731,0.235294,0.155072,shuffle_training_X_only
1,YFK,1,42,286,286,58,0.155172,0.148148,0.141543,0.155172,0.583097,0.12604,0.155172,0.305457,f1_macro,0.141543,0.156863,0.171076,shuffle_training_X_only
2,YFK,2,84,286,286,58,0.120690,0.095679,0.087348,0.120690,0.467520,0.12604,0.155172,0.608070,f1_macro,0.087348,0.568627,0.179555,shuffle_training_X_only
3,YFK,3,126,286,286,58,0.172414,0.135802,0.128263,0.172414,0.576696,0.12604,0.155172,0.189321,f1_macro,0.128263,0.215686,NaN,shuffle_training_X_only
4,YFK,4,168,286,286,58,0.120690,0.100309,0.106625,0.120690,0.528099,0.12604,0.155172,0.608070,f1_macro,0.106625,0.333333,NaN,shuffle_training_X_only
5,YFK,5,210,286,286,58,0.206897,0.168210,0.167502,0.206897,0.513207,0.12604,0.155172,0.055604,f1_macro,0.167502,0.039216,NaN,shuffle_training_X_only
6,YFK,6,252,286,286,58,0.086207,0.066358,0.061514,0.086207,0.503026,0.12604,0.155172,0.870753,f1_macro,0.061514,0.882353,NaN,shuffle_training_X_only
7,YFK,7,294,286,286,58,0.086207,0.066358,0.055852,0.086207,0.520942,0.12604,0.155172,0.870753,f1_macro,0.055852,0.823529,NaN,shuffle_training_X_only
8,YFK,8,336,286,286,58,0.137931,0.103395,0.081790,0.137931,0.501105,0.12604,0.155172,0.450409,f1_macro,0.081790,0.745098,NaN,shuffle_training_X_only
9,YFK,9,378,286,286,58,0.137931,0.108025,0.084739,0.137931,0.573751,0.12604,0.155172,0.450409,f1_macro,0.084739,0.588235,NaN,shuffle_training_X_only
10,YFK,10,420,286,286,58,0.137931,0.115741,0.097165,0.137931,0.467706,0.12604,0.155172,0.450409,f1_macro,0.097165,0.450980,NaN,shuffle_training_X_only
11,YFK,11,462,286,286,58,0.172414,0.138889,0.128347,0.172414,0.542818,0.12604,0.155172,0.189321,f1_macro,0.128347,0.137255,NaN,shuffle_training_X_only
12,YFK,12,504,286,286,58,0.103448,0.084877,0.080035,0.103448,0.502681,0.12604,0.155172,0.755233,f1_macro,0.080035,0.686275,NaN,shuffle_training_X_only
13,YFK,13,546,286,286,58,0.103448,0.080247,0.076461,0.103448,0.494149,0.12604,0.155172,0.755233,f1_macro,0.076461,0.745098,NaN,shuffle_training_X_only
14,YFK,14,588,286,286,58,0.137931,0.103395,0.087181,0.137931,0.505942,0.12604,0.155172,0.450409,f1_macro,0.087181,0.549020,NaN,shuffle_training_X_only
15,YFK,15,630,286,286,58,0.206897,0.157407,0.124909,0.206897,0.550401,0.12604,0.155172,0.055604,f1_macro,0.124909,0.196078,NaN,shuffle_training_X_only
16,YFK,16,672,286,286,58,0.155172,0.135802,0.131361,0.155172,0.525730,0.12604,0.155172,0.305457,f1_macro,0.131361,0.156863,NaN,shuffle_training_X_only
17,YFK,17,714,286,286,58,0.155172,0.121914,0.114924,0.155172,0.446916,0.12604,0.155172,0.305457,f1_macro,0.114924,0.352941,NaN,shuffle_training_X_only
18,YFK,18,756,286,286,58,0.155172,0.118827,0.106443,0.155172,0.567035,0.12604,0.155172,0.305457,f1_macro,0.106443,0.274510,NaN,shuffle_training_X_only
19,YFK,19,798,286,286,58,0.155172,0.123457,0.096910,0.155172,0.499598,0.12604,0.155172,0.305457,f1_macro,0.096910,0.490196,NaN,shuffle_training_X_only

aggregated YFK 2025-02-11 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFK/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-02-11/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFK,0,0,2737,2737,548,0.222628,0.160751,0.154186,0.222628,0.582035,0.129049,0.144161,1.139751e-09,f1_macro,0.154186,0.019608,0.149474,shuffle_training_X_only
1,YFK,1,42,2737,2737,548,0.191606,0.149390,0.157679,0.191606,0.561390,0.129049,0.144161,2.292096e-05,f1_macro,0.157679,0.019608,0.135323,shuffle_training_X_only
2,YFK,2,84,2737,2737,548,0.184307,0.136111,0.134370,0.184307,0.572669,0.129049,0.144161,1.491754e-04,f1_macro,0.134370,0.039216,0.139087,shuffle_training_X_only
3,YFK,3,126,2737,2737,548,0.182482,0.130841,0.122972,0.182482,0.554823,0.129049,0.144161,2.316192e-04,f1_macro,0.122972,0.019608,NaN,shuffle_training_X_only
4,YFK,4,168,2737,2737,548,0.160584,0.115448,0.112711,0.160584,0.547880,0.129049,0.144161,1.840436e-02,f1_macro,0.112711,0.078431,NaN,shuffle_training_X_only
5,YFK,5,210,2737,2737,548,0.177007,0.129206,0.126415,0.177007,0.561561,0.129049,0.144161,8.093742e-04,f1_macro,0.126415,0.019608,NaN,shuffle_training_X_only
6,YFK,6,252,2737,2737,548,0.200730,0.149549,0.145608,0.200730,0.545665,0.129049,0.144161,1.716273e-06,f1_macro,0.145608,0.019608,NaN,shuffle_training_X_only
7,YFK,7,294,2737,2737,548,0.164234,0.120177,0.117743,0.164234,0.551972,0.129049,0.144161,9.982496e-03,f1_macro,0.117743,0.058824,NaN,shuffle_training_X_only
8,YFK,8,336,2737,2737,548,0.187956,0.145960,0.149534,0.187956,0.598126,0.129049,0.144161,5.980659e-05,f1_macro,0.149534,0.019608,NaN,shuffle_training_X_only
9,YFK,9,378,2737,2737,548,0.171533,0.130395,0.135316,0.171533,0.516773,0.129049,0.144161,2.548532e-03,f1_macro,0.135316,0.019608,NaN,shuffle_training_X_only
10,YFK,10,420,2737,2737,548,0.195255,0.147492,0.148516,0.195255,0.530294,0.129049,0.144161,8.401156e-06,f1_macro,0.148516,0.019608,NaN,shuffle_training_X_only
11,YFK,11,462,2737,2737,548,0.184307,0.128658,0.120950,0.184307,0.545812,0.129049,0.144161,1.491754e-04,f1_macro,0.120950,0.019608,NaN,shuffle_training_X_only
12,YFK,12,504,2737,2737,548,0.187956,0.136918,0.134247,0.187956,0.510884,0.129049,0.144161,5.980659e-05,f1_macro,0.134247,0.019608,NaN,shuffle_training_X_only
13,YFK,13,546,2737,2737,548,0.209854,0.155826,0.155744,0.209854,0.600540,0.129049,0.144161,9.791245e-08,f1_macro,0.155744,0.019608,NaN,shuffle_training_X_only
14,YFK,14,588,2737,2737,548,0.209854,0.149963,0.143226,0.209854,0.578073,0.129049,0.144161,9.791245e-08,f1_macro,0.143226,0.019608,NaN,shuffle_training_X_only
15,YFK,15,630,2737,2737,548,0.171533,0.123448,0.119501,0.171533,0.572493,0.129049,0.144161,2.548532e-03,f1_macro,0.119501,0.039216,NaN,shuffle_training_X_only
16,YFK,16,672,2737,2737,548,0.158759,0.118238,0.116001,0.158759,0.570050,0.129049,0.144161,2.454878e-02,f1_macro,0.116001,0.058824,NaN,shuffle_training_X_only
17,YFK,17,714,2737,2737,548,0.229927,0.171661,0.165294,0.229927,0.572714,0.129049,0.144161,7.134121e-11,f1_macro,0.165294,0.019608,NaN,shuffle_training_X_only
18,YFK,18,756,2737,2737,548,0.202555,0.146590,0.141988,0.202555,0.559834,0.129049,0.144161,9.889829e-07,f1_macro,0.141988,0.019608,NaN,shuffle_training_X_only
19,YFK,19,798,2737,2737,548,0.186131,0.133777,0.129671,0.186131,0.534935,0.129049,0.144161,9.499065e-05,f1_macro,0.129671,0.019608,NaN,shuffle_training_X_only

aggregated YFK 2025-02-12 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFK/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-02-12/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFK,0,0,12374,12374,2475,0.215354,0.160248,0.153552,0.215354,0.603993,0.125991,0.143434,3.087413e-35,f1_macro,0.153552,0.019608,0.154356,shuffle_training_X_only
1,YFK,1,42,12374,12374,2475,0.213737,0.160840,0.155557,0.213737,0.615254,0.125991,0.143434,4.033170e-34,f1_macro,0.155557,0.019608,0.147409,shuffle_training_X_only
2,YFK,2,84,12374,12374,2475,0.205253,0.152600,0.148210,0.205253,0.597071,0.125991,0.143434,1.552089e-28,f1_macro,0.148210,0.019608,0.155856,shuffle_training_X_only
3,YFK,3,126,12374,12374,2475,0.207273,0.150746,0.141293,0.207273,0.599621,0.125991,0.143434,8.002340e-30,f1_macro,0.141293,0.019608,NaN,shuffle_training_X_only
4,YFK,4,168,12374,12374,2475,0.219394,0.164586,0.159468,0.219394,0.615489,0.125991,0.143434,4.241433e-38,f1_macro,0.159468,0.019608,NaN,shuffle_training_X_only
5,YFK,5,210,12374,12374,2475,0.204848,0.153186,0.148360,0.204848,0.606688,0.125991,0.143434,2.787825e-28,f1_macro,0.148360,0.019608,NaN,shuffle_training_X_only
6,YFK,6,252,12374,12374,2475,0.210909,0.155114,0.147682,0.210909,0.605117,0.125991,0.143434,3.302175e-32,f1_macro,0.147682,0.019608,NaN,shuffle_training_X_only
7,YFK,7,294,12374,12374,2475,0.219798,0.164692,0.159494,0.219798,0.621904,0.125991,0.143434,2.166144e-38,f1_macro,0.159494,0.019608,NaN,shuffle_training_X_only
8,YFK,8,336,12374,12374,2475,0.214545,0.161615,0.158643,0.214545,0.606517,0.125991,0.143434,1.121210e-34,f1_macro,0.158643,0.019608,NaN,shuffle_training_X_only
9,YFK,9,378,12374,12374,2475,0.221010,0.166480,0.161586,0.221010,0.607857,0.125991,0.143434,2.845247e-39,f1_macro,0.161586,0.019608,NaN,shuffle_training_X_only
10,YFK,10,420,12374,12374,2475,0.214949,0.163519,0.160026,0.214949,0.597859,0.125991,0.143434,5.890563e-35,f1_macro,0.160026,0.019608,NaN,shuffle_training_X_only
11,YFK,11,462,12374,12374,2475,0.227475,0.162337,0.149869,0.227475,0.601601,0.125991,0.143434,3.975515e-44,f1_macro,0.149869,0.019608,NaN,shuffle_training_X_only
12,YFK,12,504,12374,12374,2475,0.216970,0.158478,0.149924,0.216970,0.601076,0.125991,0.143434,2.275381e-36,f1_macro,0.149924,0.019608,NaN,shuffle_training_X_only
13,YFK,13,546,12374,12374,2475,0.213333,0.157596,0.151481,0.213333,0.607300,0.125991,0.143434,7.622070e-34,f1_macro,0.151481,0.019608,NaN,shuffle_training_X_only
14,YFK,14,588,12374,12374,2475,0.208485,0.156325,0.151758,0.208485,0.606641,0.125991,0.143434,1.311853e-30,f1_macro,0.151758,0.019608,NaN,shuffle_training_X_only
15,YFK,15,630,12374,12374,2475,0.219798,0.163734,0.158744,0.219798,0.609438,0.125991,0.143434,2.166144e-38,f1_macro,0.158744,0.019608,NaN,shuffle_training_X_only
16,YFK,16,672,12374,12374,2475,0.220202,0.163837,0.156113,0.220202,0.601193,0.125991,0.143434,1.103687e-38,f1_macro,0.156113,0.019608,NaN,shuffle_training_X_only
17,YFK,17,714,12374,12374,2475,0.212929,0.155362,0.147322,0.212929,0.607505,0.125991,0.143434,1.437018e-33,f1_macro,0.147322,0.019608,NaN,shuffle_training_X_only
18,YFK,18,756,12374,12374,2475,0.224242,0.165498,0.157223,0.224242,0.601328,0.125991,0.143434,1.145059e-41,f1_macro,0.157223,0.019608,NaN,shuffle_training_X_only
19,YFK,19,798,12374,12374,2475,0.211313,0.159940,0.156410,0.211313,0.598652,0.125991,0.143434,1.772630e-32,f1_macro,0.156410,0.019608,NaN,shuffle_training_X_only

aggregated YFK 2025-02-13 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFK/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-02-13/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFK,0,0,12408,11806,2362,0.204064,0.153022,0.150976,0.204064,0.594389,0.126693,0.144369,4.273363e-26,f1_macro,0.150976,0.019608,0.148166,shuffle_training_X_only
1,YFK,1,42,12408,11803,2361,0.207539,0.150624,0.143060,0.207539,0.609146,0.126784,0.144854,4.251814e-28,f1_macro,0.143060,0.019608,0.145665,shuffle_training_X_only
2,YFK,2,84,12408,11793,2359,0.213226,0.162635,0.162422,0.213226,0.592452,0.126757,0.144977,1.175447e-31,f1_macro,0.162422,0.019608,0.151290,shuffle_training_X_only
3,YFK,3,126,12408,11796,2360,0.207627,0.153027,0.146611,0.207627,0.607979,0.126666,0.144492,3.138554e-28,f1_macro,0.146611,0.019608,NaN,shuffle_training_X_only
4,YFK,4,168,12408,11807,2362,0.214225,0.160354,0.156770,0.214225,0.607190,0.126798,0.144793,2.623555e-32,f1_macro,0.156770,0.019608,NaN,shuffle_training_X_only
5,YFK,5,210,12408,11796,2360,0.205932,0.150907,0.143614,0.205932,0.605622,0.126667,0.144492,3.331324e-27,f1_macro,0.143614,0.019608,NaN,shuffle_training_X_only
6,YFK,6,252,12408,11799,2360,0.217797,0.161756,0.158745,0.217797,0.609402,0.126665,0.144492,9.437229e-35,f1_macro,0.158745,0.019608,NaN,shuffle_training_X_only
7,YFK,7,294,12408,11809,2362,0.221846,0.162695,0.156350,0.221846,0.607231,0.126691,0.144369,1.577435e-37,f1_macro,0.156350,0.019608,NaN,shuffle_training_X_only
8,YFK,8,336,12408,11788,2358,0.206531,0.149903,0.142448,0.206531,0.597644,0.126643,0.145038,1.467947e-27,f1_macro,0.142448,0.019608,NaN,shuffle_training_X_only
9,YFK,9,378,12408,11836,2368,0.214949,0.159167,0.154878,0.214949,0.603855,0.126773,0.144426,7.051215e-33,f1_macro,0.154878,0.019608,NaN,shuffle_training_X_only
10,YFK,10,420,12408,11808,2362,0.202371,0.147702,0.141325,0.202371,0.621210,0.126798,0.144793,4.917622e-25,f1_macro,0.141325,0.019608,NaN,shuffle_training_X_only
11,YFK,11,462,12408,11796,2360,0.200424,0.145274,0.136815,0.200424,0.589589,0.126667,0.144492,5.386673e-24,f1_macro,0.136815,0.019608,NaN,shuffle_training_X_only
12,YFK,12,504,12408,11800,2360,0.202542,0.148250,0.142075,0.202542,0.606152,0.126666,0.144915,3.307216e-25,f1_macro,0.142075,0.019608,NaN,shuffle_training_X_only
13,YFK,13,546,12408,11799,2360,0.209746,0.155855,0.151621,0.209746,0.596689,0.126774,0.144492,1.879372e-29,f1_macro,0.151621,0.019608,NaN,shuffle_training_X_only
14,YFK,14,588,12408,11814,2363,0.215404,0.158781,0.153673,0.215404,0.614513,0.126811,0.144731,4.429404e-33,f1_macro,0.153673,0.019608,NaN,shuffle_training_X_only
15,YFK,15,630,12408,11797,2360,0.214831,0.157826,0.152131,0.214831,0.609642,0.126774,0.144915,1.074156e-32,f1_macro,0.152131,0.019608,NaN,shuffle_training_X_only
16,YFK,16,672,12408,11800,2360,0.216525,0.159909,0.154903,0.216525,0.610505,0.126775,0.144915,8.247552e-34,f1_macro,0.154903,0.019608,NaN,shuffle_training_X_only
17,YFK,17,714,12408,11817,2364,0.200085,0.146692,0.141258,0.200085,0.596860,0.126720,0.144247,8.356805e-24,f1_macro,0.141258,0.019608,NaN,shuffle_training_X_only
18,YFK,18,756,12408,11789,2358,0.208651,0.155396,0.152975,0.208651,0.596313,0.126744,0.144614,8.934932e-29,f1_macro,0.152975,0.019608,NaN,shuffle_training_X_only
19,YFK,19,798,12408,11785,2357,0.199830,0.151870,0.150147,0.199830,0.611154,0.126733,0.145100,1.375532e-23,f1_macro,0.150147,0.019608,NaN,shuffle_training_X_only

aggregated YFK 2025-02-14 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFK/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-02-14/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFK,0,0,9888,9888,1978,0.189585,0.146384,0.136577,0.189585,0.586193,0.119245,0.138018,1.459713e-19,f1_macro,0.136577,0.019608,0.141153,shuffle_training_X_only
1,YFK,1,42,9888,9888,1978,0.192619,0.150817,0.146967,0.192619,0.580431,0.119245,0.138018,5.010179e-21,f1_macro,0.146967,0.019608,0.143316,shuffle_training_X_only
2,YFK,2,84,9888,9888,1978,0.189080,0.144462,0.135878,0.189080,0.594340,0.119245,0.138018,2.531739e-19,f1_macro,0.135878,0.019608,0.144898,shuffle_training_X_only
3,YFK,3,126,9888,9888,1978,0.179474,0.135445,0.126294,0.179474,0.580104,0.119245,0.138018,4.741738e-15,f1_macro,0.126294,0.019608,NaN,shuffle_training_X_only
4,YFK,4,168,9888,9888,1978,0.191102,0.146651,0.138939,0.191102,0.576353,0.119245,0.138018,2.743892e-20,f1_macro,0.138939,0.019608,NaN,shuffle_training_X_only
5,YFK,5,210,9888,9888,1978,0.187058,0.141845,0.132350,0.187058,0.593553,0.119245,0.138018,2.217577e-18,f1_macro,0.132350,0.019608,NaN,shuffle_training_X_only
6,YFK,6,252,9888,9888,1978,0.190597,0.145826,0.137216,0.190597,0.589665,0.119245,0.138018,4.805502e-20,f1_macro,0.137216,0.019608,NaN,shuffle_training_X_only
7,YFK,7,294,9888,9888,1978,0.212336,0.164555,0.155542,0.212336,0.597748,0.119245,0.138018,9.593384e-32,f1_macro,0.155542,0.019608,NaN,shuffle_training_X_only
8,YFK,8,336,9888,9888,1978,0.197169,0.150809,0.142036,0.197169,0.593798,0.119245,0.138018,2.566413e-23,f1_macro,0.142036,0.019608,NaN,shuffle_training_X_only
9,YFK,9,378,9888,9888,1978,0.200202,0.154722,0.145928,0.200202,0.604341,0.119245,0.138018,6.614554e-25,f1_macro,0.145928,0.019608,NaN,shuffle_training_X_only
10,YFK,10,420,9888,9888,1978,0.216886,0.167287,0.158149,0.216886,0.601742,0.119245,0.138018,1.669495e-34,f1_macro,0.158149,0.019608,NaN,shuffle_training_X_only
11,YFK,11,462,9888,9888,1978,0.201213,0.152837,0.142630,0.201213,0.601524,0.119245,0.138018,1.905528e-25,f1_macro,0.142630,0.019608,NaN,shuffle_training_X_only
12,YFK,12,504,9888,9888,1978,0.175935,0.134816,0.126443,0.175935,0.585291,0.119245,0.138018,1.311557e-13,f1_macro,0.126443,0.019608,NaN,shuffle_training_X_only
13,YFK,13,546,9888,9888,1978,0.196663,0.148240,0.137250,0.196663,0.602998,0.119245,0.138018,4.670322e-23,f1_macro,0.137250,0.019608,NaN,shuffle_training_X_only
14,YFK,14,588,9888,9888,1978,0.187563,0.141353,0.131152,0.187563,0.599884,0.119245,0.138018,1.295362e-18,f1_macro,0.131152,0.019608,NaN,shuffle_training_X_only
15,YFK,15,630,9888,9888,1978,0.195147,0.149650,0.141161,0.195147,0.588490,0.119245,0.138018,2.761574e-22,f1_macro,0.141161,0.019608,NaN,shuffle_training_X_only
16,YFK,16,672,9888,9888,1978,0.199697,0.153561,0.144972,0.199697,0.597476,0.119245,0.138018,1.226620e-24,f1_macro,0.144972,0.019608,NaN,shuffle_training_X_only
17,YFK,17,714,9888,9888,1978,0.201719,0.155394,0.146308,0.201719,0.595268,0.119245,0.138018,1.017992e-25,f1_macro,0.146308,0.019608,NaN,shuffle_training_X_only
18,YFK,18,756,9888,9888,1978,0.183013,0.141160,0.133622,0.183013,0.592179,0.119245,0.138018,1.453230e-16,f1_macro,0.133622,0.019608,NaN,shuffle_training_X_only
19,YFK,19,798,9888,9888,1978,0.219919,0.168926,0.159277,0.219919,0.601216,0.119245,0.138018,2.114391e-36,f1_macro,0.159277,0.019608,NaN,shuffle_training_X_only

aggregated YFK 2025-02-15 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFK/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-02-15/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFK,0,0,12498,12498,2500,0.1996,0.170078,0.166403,0.1996,0.601593,0.113755,0.1296,1.989573e-35,f1_macro,0.166403,0.019608,0.158087,shuffle_training_X_only
1,YFK,1,42,12498,12498,2500,0.1904,0.156150,0.149525,0.1904,0.604577,0.113755,0.1296,4.761550e-29,f1_macro,0.149525,0.019608,0.159441,shuffle_training_X_only
2,YFK,2,84,12498,12498,2500,0.2012,0.170798,0.167113,0.2012,0.602175,0.113755,0.1296,1.350696e-36,f1_macro,0.167113,0.019608,0.159984,shuffle_training_X_only
3,YFK,3,126,12498,12498,2500,0.1840,0.156269,0.154224,0.1840,0.608175,0.113755,0.1296,5.863172e-25,f1_macro,0.154224,0.019608,NaN,shuffle_training_X_only
4,YFK,4,168,12498,12498,2500,0.1920,0.163421,0.160706,0.1920,0.608639,0.113755,0.1296,4.075835e-30,f1_macro,0.160706,0.019608,NaN,shuffle_training_X_only
5,YFK,5,210,12498,12498,2500,0.1964,0.164226,0.159246,0.1964,0.600828,0.113755,0.1296,3.830627e-33,f1_macro,0.159246,0.019608,NaN,shuffle_training_X_only
6,YFK,6,252,12498,12498,2500,0.1832,0.153779,0.149360,0.1832,0.596784,0.113755,0.1296,1.815426e-24,f1_macro,0.149360,0.019608,NaN,shuffle_training_X_only
7,YFK,7,294,12498,12498,2500,0.1852,0.155903,0.152724,0.1852,0.607341,0.113755,0.1296,1.055077e-25,f1_macro,0.152724,0.019608,NaN,shuffle_training_X_only
8,YFK,8,336,12498,12498,2500,0.1920,0.166319,0.165108,0.1920,0.605810,0.113755,0.1296,4.075835e-30,f1_macro,0.165108,0.019608,NaN,shuffle_training_X_only
9,YFK,9,378,12498,12498,2500,0.1968,0.168167,0.165935,0.1968,0.605304,0.113755,0.1296,2.002213e-33,f1_macro,0.165935,0.019608,NaN,shuffle_training_X_only
10,YFK,10,420,12498,12498,2500,0.1800,0.151397,0.148611,0.1800,0.594418,0.113755,0.1296,1.500686e-22,f1_macro,0.148611,0.019608,NaN,shuffle_training_X_only
11,YFK,11,462,12498,12498,2500,0.1988,0.166601,0.162168,0.1988,0.618880,0.113755,0.1296,7.523034e-35,f1_macro,0.162168,0.019608,NaN,shuffle_training_X_only
12,YFK,12,504,12498,12498,2500,0.1988,0.166695,0.162481,0.1988,0.615971,0.113755,0.1296,7.523034e-35,f1_macro,0.162481,0.019608,NaN,shuffle_training_X_only
13,YFK,13,546,12498,12498,2500,0.1892,0.159925,0.157262,0.1892,0.600867,0.113755,0.1296,2.928735e-28,f1_macro,0.157262,0.019608,NaN,shuffle_training_X_only
14,YFK,14,588,12498,12498,2500,0.1892,0.157481,0.152241,0.1892,0.613278,0.113755,0.1296,2.928735e-28,f1_macro,0.152241,0.019608,NaN,shuffle_training_X_only
15,YFK,15,630,12498,12498,2500,0.1980,0.165208,0.158688,0.1980,0.613160,0.113755,0.1296,2.816421e-34,f1_macro,0.158688,0.019608,NaN,shuffle_training_X_only
16,YFK,16,672,12498,12498,2500,0.1852,0.158639,0.156806,0.1852,0.602546,0.113755,0.1296,1.055077e-25,f1_macro,0.156806,0.019608,NaN,shuffle_training_X_only
17,YFK,17,714,12498,12498,2500,0.1824,0.149339,0.142038,0.1824,0.603201,0.113755,0.1296,5.562013e-24,f1_macro,0.142038,0.019608,NaN,shuffle_training_X_only
18,YFK,18,756,12498,12498,2500,0.1868,0.162443,0.162647,0.1868,0.601932,0.113755,0.1296,1.033269e-26,f1_macro,0.162647,0.019608,NaN,shuffle_training_X_only
19,YFK,19,798,12498,12498,2500,0.1892,0.158126,0.152394,0.1892,0.612086,0.113755,0.1296,2.928735e-28,f1_macro,0.152394,0.019608,NaN,shuffle_training_X_only

aggregated YFK 2025-02-16 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFK/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-02-16/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFK,0,0,6597,6597,1320,0.193939,0.146109,0.139480,0.193939,0.576199,0.12178,0.140152,4.946209e-14,f1_macro,0.139480,0.019608,0.138047,shuffle_training_X_only
1,YFK,1,42,6597,6597,1320,0.167424,0.126617,0.120872,0.167424,0.558985,0.12178,0.140152,7.668152e-07,f1_macro,0.120872,0.019608,0.130746,shuffle_training_X_only
2,YFK,2,84,6597,6597,1320,0.170455,0.134294,0.132710,0.170455,0.559445,0.12178,0.140152,1.580018e-07,f1_macro,0.132710,0.019608,0.131299,shuffle_training_X_only
3,YFK,3,126,6597,6597,1320,0.168939,0.126643,0.119710,0.168939,0.562167,0.12178,0.140152,3.517097e-07,f1_macro,0.119710,0.019608,NaN,shuffle_training_X_only
4,YFK,4,168,6597,6597,1320,0.183333,0.139353,0.134909,0.183333,0.540592,0.12178,0.140152,7.715943e-11,f1_macro,0.134909,0.019608,NaN,shuffle_training_X_only
5,YFK,5,210,6597,6597,1320,0.186364,0.143376,0.140864,0.186364,0.568369,0.12178,0.140152,1.040473e-11,f1_macro,0.140864,0.019608,NaN,shuffle_training_X_only
6,YFK,6,252,6597,6597,1320,0.173485,0.134090,0.130753,0.173485,0.572998,0.12178,0.140152,2.997499e-08,f1_macro,0.130753,0.019608,NaN,shuffle_training_X_only
7,YFK,7,294,6597,6597,1320,0.176515,0.131865,0.123913,0.176515,0.566293,0.12178,0.140152,5.240348e-09,f1_macro,0.123913,0.019608,NaN,shuffle_training_X_only
8,YFK,8,336,6597,6597,1320,0.187879,0.142139,0.136513,0.187879,0.565923,0.12178,0.140152,3.710336e-12,f1_macro,0.136513,0.019608,NaN,shuffle_training_X_only
9,YFK,9,378,6597,6597,1320,0.173485,0.129714,0.121611,0.173485,0.571076,0.12178,0.140152,2.997499e-08,f1_macro,0.121611,0.019608,NaN,shuffle_training_X_only
10,YFK,10,420,6597,6597,1320,0.183333,0.136987,0.130208,0.183333,0.591140,0.12178,0.140152,7.715943e-11,f1_macro,0.130208,0.019608,NaN,shuffle_training_X_only
11,YFK,11,462,6597,6597,1320,0.190152,0.143785,0.138613,0.190152,0.580479,0.12178,0.140152,7.618888e-13,f1_macro,0.138613,0.019608,NaN,shuffle_training_X_only
12,YFK,12,504,6597,6597,1320,0.169697,0.127448,0.121981,0.169697,0.557187,0.12178,0.140152,2.363454e-07,f1_macro,0.121981,0.019608,NaN,shuffle_training_X_only
13,YFK,13,546,6597,6597,1320,0.162121,0.122855,0.117365,0.162121,0.563043,0.12178,0.140152,9.949313e-06,f1_macro,0.117365,0.019608,NaN,shuffle_training_X_only
14,YFK,14,588,6597,6597,1320,0.182576,0.137349,0.130314,0.182576,0.556590,0.12178,0.140152,1.257730e-10,f1_macro,0.130314,0.019608,NaN,shuffle_training_X_only
15,YFK,15,630,6597,6597,1320,0.178788,0.131773,0.124047,0.178788,0.565239,0.12178,0.140152,1.343522e-09,f1_macro,0.124047,0.019608,NaN,shuffle_training_X_only
16,YFK,16,672,6597,6597,1320,0.173485,0.132086,0.127376,0.173485,0.550968,0.12178,0.140152,2.997499e-08,f1_macro,0.127376,0.019608,NaN,shuffle_training_X_only
17,YFK,17,714,6597,6597,1320,0.188636,0.141601,0.134707,0.188636,0.570257,0.12178,0.140152,2.199580e-12,f1_macro,0.134707,0.019608,NaN,shuffle_training_X_only
18,YFK,18,756,6597,6597,1320,0.180303,0.136605,0.131237,0.180303,0.573206,0.12178,0.140152,5.287766e-10,f1_macro,0.131237,0.019608,NaN,shuffle_training_X_only
19,YFK,19,798,6597,6597,1320,0.187879,0.140346,0.131713,0.187879,0.573290,0.12178,0.140152,3.710336e-12,f1_macro,0.131713,0.019608,NaN,shuffle_training_X_only

aggregated YFK 2025-02-17 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFK/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-02-17/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFK,0,0,7324,7324,1465,0.219795,0.165474,0.164253,0.219795,0.591828,0.126981,0.142662,6.057806e-23,f1_macro,0.164253,0.019608,0.142491,shuffle_training_X_only
1,YFK,1,42,7324,7324,1465,0.188396,0.134878,0.127936,0.188396,0.593260,0.126981,0.142662,1.677735e-11,f1_macro,0.127936,0.019608,0.152029,shuffle_training_X_only
2,YFK,2,84,7324,7324,1465,0.203413,0.152128,0.149462,0.203413,0.572163,0.126981,0.142662,1.686008e-16,f1_macro,0.149462,0.019608,0.142562,shuffle_training_X_only
3,YFK,3,126,7324,7324,1465,0.182253,0.138670,0.138128,0.182253,0.592517,0.126981,0.142662,1.018173e-09,f1_macro,0.138128,0.019608,NaN,shuffle_training_X_only
4,YFK,4,168,7324,7324,1465,0.194539,0.142482,0.137257,0.194539,0.585076,0.126981,0.142662,1.942081e-13,f1_macro,0.137257,0.019608,NaN,shuffle_training_X_only
5,YFK,5,210,7324,7324,1465,0.182253,0.134291,0.130619,0.182253,0.574670,0.126981,0.142662,1.018173e-09,f1_macro,0.130619,0.019608,NaN,shuffle_training_X_only
6,YFK,6,252,7324,7324,1465,0.191809,0.139223,0.133599,0.191809,0.599796,0.126981,0.142662,1.471096e-12,f1_macro,0.133599,0.019608,NaN,shuffle_training_X_only
7,YFK,7,294,7324,7324,1465,0.199317,0.142499,0.134718,0.199317,0.587125,0.126981,0.142662,4.766012e-15,f1_macro,0.134718,0.019608,NaN,shuffle_training_X_only
8,YFK,8,336,7324,7324,1465,0.175427,0.131775,0.130893,0.175427,0.568909,0.126981,0.142662,6.385474e-08,f1_macro,0.130893,0.019608,NaN,shuffle_training_X_only
9,YFK,9,378,7324,7324,1465,0.204778,0.149064,0.142089,0.204778,0.579299,0.126981,0.142662,5.353709e-17,f1_macro,0.142089,0.019608,NaN,shuffle_training_X_only
10,YFK,10,420,7324,7324,1465,0.208191,0.157521,0.157014,0.208191,0.589614,0.126981,0.142662,2.830494e-18,f1_macro,0.157014,0.019608,NaN,shuffle_training_X_only
11,YFK,11,462,7324,7324,1465,0.199317,0.141208,0.131394,0.199317,0.606818,0.126981,0.142662,4.766012e-15,f1_macro,0.131394,0.019608,NaN,shuffle_training_X_only
12,YFK,12,504,7324,7324,1465,0.208874,0.156014,0.154157,0.208874,0.600557,0.126981,0.142662,1.553006e-18,f1_macro,0.154157,0.019608,NaN,shuffle_training_X_only
13,YFK,13,546,7324,7324,1465,0.202730,0.148736,0.144557,0.202730,0.594482,0.126981,0.142662,2.973478e-16,f1_macro,0.144557,0.019608,NaN,shuffle_training_X_only
14,YFK,14,588,7324,7324,1465,0.187031,0.139043,0.135534,0.187031,0.586847,0.126981,0.142662,4.308585e-11,f1_macro,0.135534,0.019608,NaN,shuffle_training_X_only
15,YFK,15,630,7324,7324,1465,0.203413,0.150561,0.147350,0.203413,0.587597,0.126981,0.142662,1.686008e-16,f1_macro,0.147350,0.019608,NaN,shuffle_training_X_only
16,YFK,16,672,7324,7324,1465,0.200683,0.147598,0.142584,0.200683,0.598997,0.126981,0.142662,1.590898e-15,f1_macro,0.142584,0.019608,NaN,shuffle_training_X_only
17,YFK,17,714,7324,7324,1465,0.195904,0.141467,0.135073,0.195904,0.590678,0.126981,0.142662,6.877655e-14,f1_macro,0.135073,0.019608,NaN,shuffle_training_X_only
18,YFK,18,756,7324,7324,1465,0.216382,0.160189,0.157570,0.216382,0.588923,0.126981,0.142662,1.613472e-21,f1_macro,0.157570,0.019608,NaN,shuffle_training_X_only
19,YFK,19,798,7324,7324,1465,0.208191,0.148803,0.141011,0.208191,0.592637,0.126981,0.142662,2.830494e-18,f1_macro,0.141011,0.019608,NaN,shuffle_training_X_only

aggregated YFK 2025-02-18 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFK/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-02-18/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFK,0,0,8418,6463,1293,0.182521,0.143777,0.140945,0.182521,0.595707,0.123116,0.143078,5.319874e-10,f1_macro,0.140945,0.019608,0.159532,shuffle_training_X_only
1,YFK,1,42,8418,6424,1285,0.192996,0.156494,0.155940,0.192996,0.585735,0.122762,0.143969,4.788120e-13,f1_macro,0.155940,0.019608,0.161393,shuffle_training_X_only
2,YFK,2,84,8418,6420,1284,0.183801,0.148457,0.146878,0.183801,0.583281,0.122801,0.143302,2.197603e-10,f1_macro,0.146878,0.019608,0.155023,shuffle_training_X_only
3,YFK,3,126,8418,6459,1292,0.203560,0.158221,0.157077,0.203560,0.601340,0.122964,0.143189,1.926661e-16,f1_macro,0.157077,0.019608,NaN,shuffle_training_X_only
4,YFK,4,168,8418,6451,1291,0.193648,0.153037,0.150512,0.193648,0.605054,0.122986,0.144074,3.246354e-13,f1_macro,0.150512,0.019608,NaN,shuffle_training_X_only
5,YFK,5,210,8418,6439,1288,0.199534,0.162361,0.161284,0.199534,0.608966,0.123011,0.143634,4.892282e-15,f1_macro,0.161284,0.019608,NaN,shuffle_training_X_only
6,YFK,6,252,8418,6458,1292,0.184985,0.149300,0.147404,0.184985,0.618758,0.122974,0.143963,1.046854e-10,f1_macro,0.147404,0.019608,NaN,shuffle_training_X_only
7,YFK,7,294,8418,6466,1294,0.190881,0.150400,0.147759,0.190881,0.597113,0.122994,0.142968,2.104886e-12,f1_macro,0.147759,0.019608,NaN,shuffle_training_X_only
8,YFK,8,336,8418,6471,1295,0.206178,0.171228,0.169425,0.206178,0.619544,0.123074,0.143629,2.472352e-17,f1_macro,0.169425,0.019608,NaN,shuffle_training_X_only
9,YFK,9,378,8418,6444,1289,0.190070,0.151768,0.148502,0.190070,0.607882,0.122936,0.143522,3.828033e-12,f1_macro,0.148502,0.019608,NaN,shuffle_training_X_only
10,YFK,10,420,8418,6485,1297,0.191981,0.159277,0.163030,0.191981,0.605187,0.123122,0.145721,1.035696e-12,f1_macro,0.163030,0.019608,NaN,shuffle_training_X_only
11,YFK,11,462,8418,6463,1293,0.201083,0.154157,0.149729,0.201083,0.608754,0.123012,0.145398,1.341403e-15,f1_macro,0.149729,0.019608,NaN,shuffle_training_X_only
12,YFK,12,504,8418,6466,1294,0.209428,0.170741,0.170637,0.209428,0.600134,0.123026,0.143740,1.693894e-18,f1_macro,0.170637,0.019608,NaN,shuffle_training_X_only
13,YFK,13,546,8418,6477,1296,0.192901,0.147894,0.143061,0.192901,0.607528,0.123135,0.143519,5.629814e-13,f1_macro,0.143061,0.019608,NaN,shuffle_training_X_only
14,YFK,14,588,8418,6436,1288,0.199534,0.156505,0.155421,0.199534,0.603403,0.122850,0.142857,4.216833e-15,f1_macro,0.155421,0.019608,NaN,shuffle_training_X_only
15,YFK,15,630,8418,6444,1289,0.182312,0.141686,0.138915,0.182312,0.586666,0.122895,0.145074,5.469241e-10,f1_macro,0.138915,0.019608,NaN,shuffle_training_X_only
16,YFK,16,672,8418,6484,1297,0.171164,0.137676,0.137854,0.171164,0.600247,0.123115,0.144179,3.094073e-07,f1_macro,0.137854,0.019608,NaN,shuffle_training_X_only
17,YFK,17,714,8418,6464,1293,0.202630,0.153934,0.146996,0.202630,0.606474,0.123150,0.143852,4.649564e-16,f1_macro,0.146996,0.019608,NaN,shuffle_training_X_only
18,YFK,18,756,8418,6432,1287,0.188034,0.149505,0.146861,0.188034,0.611075,0.122821,0.142191,1.407723e-11,f1_macro,0.146861,0.019608,NaN,shuffle_training_X_only
19,YFK,19,798,8418,6466,1294,0.189335,0.147789,0.144008,0.189335,0.602694,0.123017,0.144513,6.110542e-12,f1_macro,0.144008,0.019608,NaN,shuffle_training_X_only

aggregated YFL 2025-02-28 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFL/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-02-28/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFL,0,0,2055,2054,411,0.184915,0.140259,0.132349,0.184915,0.580907,0.11992,0.138686,8.908612e-05,f1_macro,0.132349,0.019608,0.137791,shuffle_training_X_only
1,YFL,1,42,2055,2054,411,0.172749,0.137120,0.135345,0.172749,0.557610,0.11992,0.138686,1.071669e-03,f1_macro,0.135345,0.039216,0.135561,shuffle_training_X_only
2,YFL,2,84,2055,2054,411,0.148418,0.123874,0.127174,0.148418,0.554052,0.11992,0.138686,4.745100e-02,f1_macro,0.127174,0.019608,0.137374,shuffle_training_X_only
3,YFL,3,126,2055,2054,411,0.182482,0.134565,0.122637,0.182482,0.549431,0.11992,0.138686,1.510781e-04,f1_macro,0.122637,0.019608,NaN,shuffle_training_X_only
4,YFL,4,168,2055,2054,411,0.214112,0.161880,0.151197,0.214112,0.554371,0.11992,0.138686,4.972708e-08,f1_macro,0.151197,0.019608,NaN,shuffle_training_X_only
5,YFL,5,210,2055,2054,411,0.209246,0.154983,0.139337,0.209246,0.574393,0.11992,0.138686,2.001427e-07,f1_macro,0.139337,0.019608,NaN,shuffle_training_X_only
6,YFL,6,252,2055,2054,411,0.165450,0.129220,0.126543,0.165450,0.532898,0.11992,0.138686,3.953273e-03,f1_macro,0.126543,0.019608,NaN,shuffle_training_X_only
7,YFL,7,294,2055,2054,411,0.177616,0.136311,0.125171,0.177616,0.535342,0.11992,0.138686,4.150123e-04,f1_macro,0.125171,0.039216,NaN,shuffle_training_X_only
8,YFL,8,336,2055,2054,411,0.153285,0.115206,0.104521,0.153285,0.544219,0.11992,0.138686,2.529473e-02,f1_macro,0.104521,0.196078,NaN,shuffle_training_X_only
9,YFL,9,378,2055,2054,411,0.187348,0.140514,0.128358,0.187348,0.544408,0.11992,0.138686,5.174126e-05,f1_macro,0.128358,0.019608,NaN,shuffle_training_X_only
10,YFL,10,420,2055,2054,411,0.182482,0.134565,0.121906,0.182482,0.550057,0.11992,0.138686,1.510781e-04,f1_macro,0.121906,0.019608,NaN,shuffle_training_X_only
11,YFL,11,462,2055,2054,411,0.187348,0.144263,0.135690,0.187348,0.534053,0.11992,0.138686,5.174126e-05,f1_macro,0.135690,0.019608,NaN,shuffle_training_X_only
12,YFL,12,504,2055,2054,411,0.180049,0.133557,0.122198,0.180049,0.548827,0.11992,0.138686,2.523288e-04,f1_macro,0.122198,0.019608,NaN,shuffle_training_X_only
13,YFL,13,546,2055,2054,411,0.226277,0.168412,0.153942,0.226277,0.582749,0.11992,0.138686,1.200818e-09,f1_macro,0.153942,0.019608,NaN,shuffle_training_X_only
14,YFL,14,588,2055,2054,411,0.187348,0.141462,0.132006,0.187348,0.564153,0.11992,0.138686,5.174126e-05,f1_macro,0.132006,0.019608,NaN,shuffle_training_X_only
15,YFL,15,630,2055,2054,411,0.197080,0.147159,0.136299,0.197080,0.549263,0.11992,0.138686,5.070304e-06,f1_macro,0.136299,0.019608,NaN,shuffle_training_X_only
16,YFL,16,672,2055,2055,411,0.170316,0.125047,0.112849,0.170316,0.552782,0.11992,0.138686,1.682212e-03,f1_macro,0.112849,0.039216,NaN,shuffle_training_X_only
17,YFL,17,714,2055,2054,411,0.192214,0.143277,0.131631,0.192214,0.560287,0.11992,0.138686,1.668504e-05,f1_macro,0.131631,0.058824,NaN,shuffle_training_X_only
18,YFL,18,756,2055,2054,411,0.182482,0.140927,0.132205,0.182482,0.521275,0.11992,0.138686,1.510781e-04,f1_macro,0.132205,0.019608,NaN,shuffle_training_X_only
19,YFL,19,798,2055,2054,411,0.167883,0.127053,0.117334,0.167883,0.522000,0.11992,0.138686,2.599317e-03,f1_macro,0.117334,0.058824,NaN,shuffle_training_X_only

aggregated YFL 2025-03-01 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFL/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-01/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFL,0,0,2225,2225,445,0.204494,0.158396,0.147461,0.204494,0.611014,0.119556,0.137079,2.337902e-07,f1_macro,0.147461,0.019608,0.152392,shuffle_training_X_only
1,YFL,1,42,2225,2225,445,0.200000,0.156534,0.148283,0.200000,0.613573,0.119556,0.137079,8.459451e-07,f1_macro,0.148283,0.019608,0.157265,shuffle_training_X_only
2,YFL,2,84,2225,2225,445,0.188764,0.165896,0.165418,0.188764,0.596169,0.119556,0.137079,1.662373e-05,f1_macro,0.165418,0.019608,0.149124,shuffle_training_X_only
3,YFL,3,126,2225,2225,445,0.164045,0.129312,0.120626,0.164045,0.612824,0.119556,0.137079,3.372585e-03,f1_macro,0.120626,0.019608,NaN,shuffle_training_X_only
4,YFL,4,168,2225,2225,445,0.215730,0.170986,0.161046,0.215730,0.614455,0.119556,0.137079,7.452521e-09,f1_macro,0.161046,0.019608,NaN,shuffle_training_X_only
5,YFL,5,210,2225,2225,445,0.204494,0.162081,0.152000,0.204494,0.628364,0.119556,0.137079,2.337902e-07,f1_macro,0.152000,0.019608,NaN,shuffle_training_X_only
6,YFL,6,252,2225,2225,445,0.231461,0.190967,0.180878,0.231461,0.618802,0.119556,0.137079,3.496803e-11,f1_macro,0.180878,0.019608,NaN,shuffle_training_X_only
7,YFL,7,294,2225,2225,445,0.177528,0.140565,0.133001,0.177528,0.603234,0.119556,0.137079,2.307665e-04,f1_macro,0.133001,0.019608,NaN,shuffle_training_X_only
8,YFL,8,336,2225,2225,445,0.182022,0.145404,0.136252,0.182022,0.621260,0.119556,0.137079,8.406699e-05,f1_macro,0.136252,0.019608,NaN,shuffle_training_X_only
9,YFL,9,378,2225,2225,445,0.200000,0.156393,0.145165,0.200000,0.631158,0.119556,0.137079,8.459451e-07,f1_macro,0.145165,0.019608,NaN,shuffle_training_X_only
10,YFL,10,420,2225,2225,445,0.182022,0.144271,0.138338,0.182022,0.619504,0.119556,0.137079,8.406699e-05,f1_macro,0.138338,0.019608,NaN,shuffle_training_X_only
11,YFL,11,462,2225,2225,445,0.200000,0.159795,0.149029,0.200000,0.605495,0.119556,0.137079,8.459451e-07,f1_macro,0.149029,0.019608,NaN,shuffle_training_X_only
12,YFL,12,504,2225,2225,445,0.204494,0.166334,0.154979,0.204494,0.613913,0.119556,0.137079,2.337902e-07,f1_macro,0.154979,0.019608,NaN,shuffle_training_X_only
13,YFL,13,546,2225,2225,445,0.197753,0.153478,0.143416,0.197753,0.597671,0.119556,0.137079,1.577094e-06,f1_macro,0.143416,0.019608,NaN,shuffle_training_X_only
14,YFL,14,588,2225,2225,445,0.202247,0.161291,0.150734,0.202247,0.642069,0.119556,0.137079,4.476985e-07,f1_macro,0.150734,0.019608,NaN,shuffle_training_X_only
15,YFL,15,630,2225,2225,445,0.197753,0.157730,0.149202,0.197753,0.617576,0.119556,0.137079,1.577094e-06,f1_macro,0.149202,0.019608,NaN,shuffle_training_X_only
16,YFL,16,672,2225,2225,445,0.193258,0.157670,0.151330,0.193258,0.608134,0.119556,0.137079,5.262713e-06,f1_macro,0.151330,0.019608,NaN,shuffle_training_X_only
17,YFL,17,714,2225,2225,445,0.211236,0.170546,0.164971,0.211236,0.623095,0.119556,0.137079,3.075458e-08,f1_macro,0.164971,0.019608,NaN,shuffle_training_X_only
18,YFL,18,756,2225,2225,445,0.179775,0.150148,0.142378,0.179775,0.597789,0.119556,0.137079,1.402805e-04,f1_macro,0.142378,0.019608,NaN,shuffle_training_X_only
19,YFL,19,798,2225,2225,445,0.186517,0.153506,0.143588,0.186517,0.584472,0.119556,0.137079,2.893686e-05,f1_macro,0.143588,0.019608,NaN,shuffle_training_X_only

aggregated YFL 2025-03-02 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFL/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-02/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFL,0,0,1412,1412,283,0.176678,0.130474,0.127051,0.176678,0.584767,0.125523,0.144876,0.008025,f1_macro,0.127051,0.039216,0.137158,shuffle_training_X_only
1,YFL,1,42,1412,1412,283,0.151943,0.111959,0.108568,0.151943,0.604292,0.125523,0.144876,0.107302,f1_macro,0.108568,0.078431,0.126362,shuffle_training_X_only
2,YFL,2,84,1412,1412,283,0.169611,0.121033,0.113238,0.169611,0.548451,0.125523,0.144876,0.018788,f1_macro,0.113238,0.156863,0.140054,shuffle_training_X_only
3,YFL,3,126,1412,1412,283,0.169611,0.126104,0.121831,0.169611,0.596426,0.125523,0.144876,0.018788,f1_macro,0.121831,0.098039,NaN,shuffle_training_X_only
4,YFL,4,168,1412,1412,283,0.183746,0.130748,0.118583,0.183746,0.609851,0.125523,0.144876,0.003143,f1_macro,0.118583,0.039216,NaN,shuffle_training_X_only
5,YFL,5,210,1412,1412,283,0.183746,0.130587,0.121502,0.183746,0.551947,0.125523,0.144876,0.003143,f1_macro,0.121502,0.058824,NaN,shuffle_training_X_only
6,YFL,6,252,1412,1412,283,0.155477,0.115454,0.110322,0.155477,0.541155,0.125523,0.144876,0.079149,f1_macro,0.110322,0.117647,NaN,shuffle_training_X_only
7,YFL,7,294,1412,1412,283,0.190813,0.135323,0.124575,0.190813,0.594488,0.125523,0.144876,0.001130,f1_macro,0.124575,0.019608,NaN,shuffle_training_X_only
8,YFL,8,336,1412,1412,283,0.190813,0.135181,0.124531,0.190813,0.568294,0.125523,0.144876,0.001130,f1_macro,0.124531,0.039216,NaN,shuffle_training_X_only
9,YFL,9,378,1412,1412,283,0.204947,0.145241,0.128708,0.204947,0.607212,0.125523,0.144876,0.000114,f1_macro,0.128708,0.039216,NaN,shuffle_training_X_only
10,YFL,10,420,1412,1412,283,0.180212,0.127782,0.117437,0.180212,0.606035,0.125523,0.144876,0.005076,f1_macro,0.117437,0.078431,NaN,shuffle_training_X_only
11,YFL,11,462,1412,1412,283,0.162544,0.115140,0.104217,0.162544,0.578830,0.125523,0.144876,0.040302,f1_macro,0.104217,0.254902,NaN,shuffle_training_X_only
12,YFL,12,504,1412,1412,283,0.183746,0.130809,0.121290,0.183746,0.586797,0.125523,0.144876,0.003143,f1_macro,0.121290,0.098039,NaN,shuffle_training_X_only
13,YFL,13,546,1412,1412,283,0.176678,0.125241,0.111560,0.176678,0.608970,0.125523,0.144876,0.008025,f1_macro,0.111560,0.156863,NaN,shuffle_training_X_only
14,YFL,14,588,1412,1412,283,0.183746,0.135596,0.128035,0.183746,0.583044,0.125523,0.144876,0.003143,f1_macro,0.128035,0.039216,NaN,shuffle_training_X_only
15,YFL,15,630,1412,1412,283,0.219081,0.155404,0.140221,0.219081,0.591700,0.125523,0.144876,0.000008,f1_macro,0.140221,0.019608,NaN,shuffle_training_X_only
16,YFL,16,672,1412,1412,283,0.173145,0.122924,0.112498,0.173145,0.595618,0.125523,0.144876,0.012413,f1_macro,0.112498,0.078431,NaN,shuffle_training_X_only
17,YFL,17,714,1412,1412,283,0.187279,0.133897,0.122530,0.187279,0.562286,0.125523,0.144876,0.001905,f1_macro,0.122530,0.019608,NaN,shuffle_training_X_only
18,YFL,18,756,1412,1412,283,0.183746,0.129632,0.114385,0.183746,0.577620,0.125523,0.144876,0.003143,f1_macro,0.114385,0.117647,NaN,shuffle_training_X_only
19,YFL,19,798,1412,1412,283,0.190813,0.135160,0.120644,0.190813,0.575844,0.125523,0.144876,0.001130,f1_macro,0.120644,0.058824,NaN,shuffle_training_X_only

aggregated YFL 2025-03-03 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFL/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-03/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFL,0,0,7419,7419,1484,0.201482,0.158601,0.149141,0.201482,0.599453,0.116248,0.134097,3.205801e-21,f1_macro,0.149141,0.019608,0.140028,shuffle_training_X_only
1,YFL,1,42,7419,7419,1484,0.173181,0.135459,0.125958,0.173181,0.587290,0.116248,0.134097,7.123612e-11,f1_macro,0.125958,0.019608,0.145779,shuffle_training_X_only
2,YFL,2,84,7419,7419,1484,0.186658,0.151604,0.147531,0.186658,0.586413,0.116248,0.134097,2.196514e-15,f1_macro,0.147531,0.019608,0.152399,shuffle_training_X_only
3,YFL,3,126,7419,7419,1484,0.200135,0.156996,0.148648,0.200135,0.598550,0.116248,0.134097,1.183216e-20,f1_macro,0.148648,0.019608,NaN,shuffle_training_X_only
4,YFL,4,168,7419,7419,1484,0.187332,0.148336,0.138976,0.187332,0.590570,0.116248,0.134097,1.247332e-15,f1_macro,0.138976,0.019608,NaN,shuffle_training_X_only
5,YFL,5,210,7419,7419,1484,0.180593,0.145633,0.139722,0.180593,0.581353,0.116248,0.134097,2.935761e-13,f1_macro,0.139722,0.019608,NaN,shuffle_training_X_only
6,YFL,6,252,7419,7419,1484,0.181941,0.142340,0.132984,0.181941,0.595642,0.116248,0.134097,1.020264e-13,f1_macro,0.132984,0.019608,NaN,shuffle_training_X_only
7,YFL,7,294,7419,7419,1484,0.184636,0.146658,0.139628,0.184636,0.591458,0.116248,0.134097,1.168448e-14,f1_macro,0.139628,0.019608,NaN,shuffle_training_X_only
8,YFL,8,336,7419,7419,1484,0.189353,0.150581,0.143353,0.189353,0.605644,0.116248,0.134097,2.225426e-16,f1_macro,0.143353,0.019608,NaN,shuffle_training_X_only
9,YFL,9,378,7419,7419,1484,0.174528,0.133581,0.120750,0.174528,0.599788,0.116248,0.134097,2.734018e-11,f1_macro,0.120750,0.019608,NaN,shuffle_training_X_only
10,YFL,10,420,7419,7419,1484,0.183962,0.148341,0.143796,0.183962,0.598916,0.116248,0.134097,2.021897e-14,f1_macro,0.143796,0.019608,NaN,shuffle_training_X_only
11,YFL,11,462,7419,7419,1484,0.179919,0.142516,0.134685,0.179919,0.592155,0.116248,0.134097,4.946771e-13,f1_macro,0.134685,0.019608,NaN,shuffle_training_X_only
12,YFL,12,504,7419,7419,1484,0.183288,0.144305,0.135532,0.183288,0.583219,0.116248,0.134097,3.483340e-14,f1_macro,0.135532,0.019608,NaN,shuffle_training_X_only
13,YFL,13,546,7419,7419,1484,0.189353,0.149910,0.142763,0.189353,0.600179,0.116248,0.134097,2.225426e-16,f1_macro,0.142763,0.019608,NaN,shuffle_training_X_only
14,YFL,14,588,7419,7419,1484,0.206199,0.164076,0.155595,0.206199,0.609166,0.116248,0.134097,2.915070e-23,f1_macro,0.155595,0.019608,NaN,shuffle_training_X_only
15,YFL,15,630,7419,7419,1484,0.195418,0.153936,0.145657,0.195418,0.589931,0.116248,0.134097,1.002220e-18,f1_macro,0.145657,0.019608,NaN,shuffle_training_X_only
16,YFL,16,672,7419,7419,1484,0.199461,0.155758,0.144082,0.199461,0.588733,0.116248,0.134097,2.259041e-20,f1_macro,0.144082,0.019608,NaN,shuffle_training_X_only
17,YFL,17,714,7419,7419,1484,0.187332,0.146579,0.138048,0.187332,0.601269,0.116248,0.134097,1.247332e-15,f1_macro,0.138048,0.019608,NaN,shuffle_training_X_only
18,YFL,18,756,7419,7419,1484,0.171833,0.132992,0.121722,0.171833,0.600894,0.116248,0.134097,1.822338e-10,f1_macro,0.121722,0.019608,NaN,shuffle_training_X_only
19,YFL,19,798,7419,7419,1484,0.192722,0.151432,0.142028,0.192722,0.583024,0.116248,0.134097,1.154421e-17,f1_macro,0.142028,0.019608,NaN,shuffle_training_X_only

aggregated YFL 2025-03-04 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFL/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-04/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFL,0,0,5215,5215,1043,0.154362,0.113197,0.104029,0.154362,0.545218,0.121071,0.139981,8.264176e-04,f1_macro,0.104029,0.098039,0.128830,shuffle_training_X_only
1,YFL,1,42,5215,5215,1043,0.179291,0.136398,0.129333,0.179291,0.555204,0.121071,0.139981,3.314636e-08,f1_macro,0.129333,0.019608,0.125144,shuffle_training_X_only
2,YFL,2,84,5215,5215,1043,0.161074,0.119179,0.110339,0.161074,0.558766,0.121071,0.139981,8.396376e-05,f1_macro,0.110339,0.039216,0.123541,shuffle_training_X_only
3,YFL,3,126,5215,5215,1043,0.156280,0.115137,0.104010,0.156280,0.565998,0.121071,0.139981,4.447458e-04,f1_macro,0.104010,0.058824,NaN,shuffle_training_X_only
4,YFL,4,168,5215,5215,1043,0.170662,0.130553,0.125679,0.170662,0.555857,0.121071,0.139981,1.817670e-06,f1_macro,0.125679,0.019608,NaN,shuffle_training_X_only
5,YFL,5,210,5215,5215,1043,0.181208,0.133520,0.123079,0.181208,0.548089,0.121071,0.139981,1.269589e-08,f1_macro,0.123079,0.019608,NaN,shuffle_training_X_only
6,YFL,6,252,5215,5215,1043,0.178332,0.132437,0.121636,0.178332,0.576319,0.121071,0.139981,5.305484e-08,f1_macro,0.121636,0.019608,NaN,shuffle_training_X_only
7,YFL,7,294,5215,5215,1043,0.187919,0.144748,0.138805,0.187919,0.560200,0.121071,0.139981,3.629589e-10,f1_macro,0.138805,0.019608,NaN,shuffle_training_X_only
8,YFL,8,336,5215,5215,1043,0.186002,0.138569,0.129674,0.186002,0.550374,0.121071,0.139981,1.033592e-09,f1_macro,0.129674,0.019608,NaN,shuffle_training_X_only
9,YFL,9,378,5215,5215,1043,0.181208,0.135860,0.127018,0.181208,0.571466,0.121071,0.139981,1.269589e-08,f1_macro,0.127018,0.019608,NaN,shuffle_training_X_only
10,YFL,10,420,5215,5215,1043,0.183126,0.136622,0.128091,0.183126,0.564067,0.121071,0.139981,4.742688e-09,f1_macro,0.128091,0.019608,NaN,shuffle_training_X_only
11,YFL,11,462,5215,5215,1043,0.158198,0.120121,0.112597,0.158198,0.554099,0.121071,0.139981,2.329537e-04,f1_macro,0.112597,0.019608,NaN,shuffle_training_X_only
12,YFL,12,504,5215,5215,1043,0.173538,0.130229,0.121341,0.173538,0.546388,0.121071,0.139981,5.068019e-07,f1_macro,0.121341,0.019608,NaN,shuffle_training_X_only
13,YFL,13,546,5215,5215,1043,0.166826,0.129785,0.126149,0.166826,0.558702,0.121071,0.139981,9.112228e-06,f1_macro,0.126149,0.019608,NaN,shuffle_training_X_only
14,YFL,14,588,5215,5215,1043,0.150527,0.111901,0.102534,0.150527,0.549389,0.121071,0.139981,2.629709e-03,f1_macro,0.102534,0.137255,NaN,shuffle_training_X_only
15,YFL,15,630,5215,5215,1043,0.162033,0.121822,0.112903,0.162033,0.559275,0.121071,0.139981,5.895936e-05,f1_macro,0.112903,0.058824,NaN,shuffle_training_X_only
16,YFL,16,672,5215,5215,1043,0.190796,0.141390,0.131398,0.190796,0.580492,0.121071,0.139981,7.214939e-11,f1_macro,0.131398,0.019608,NaN,shuffle_training_X_only
17,YFL,17,714,5215,5215,1043,0.178332,0.133350,0.123558,0.178332,0.559661,0.121071,0.139981,5.305484e-08,f1_macro,0.123558,0.019608,NaN,shuffle_training_X_only
18,YFL,18,756,5215,5215,1043,0.162991,0.125167,0.121124,0.162991,0.561548,0.121071,0.139981,4.112637e-05,f1_macro,0.121124,0.019608,NaN,shuffle_training_X_only
19,YFL,19,798,5215,5215,1043,0.184084,0.139055,0.129804,0.184084,0.558160,0.121071,0.139981,2.871791e-09,f1_macro,0.129804,0.019608,NaN,shuffle_training_X_only

aggregated YFL 2025-03-05 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFL/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-05/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFL,0,0,1657,1657,332,0.177711,0.129948,0.123562,0.177711,0.579546,0.125962,0.144578,4.098328e-03,f1_macro,0.123562,0.058824,0.143316,shuffle_training_X_only
1,YFL,1,42,1657,1657,332,0.201807,0.151442,0.149362,0.201807,0.612294,0.125962,0.144578,6.535240e-05,f1_macro,0.149362,0.019608,0.137576,shuffle_training_X_only
2,YFL,2,84,1657,1657,332,0.177711,0.127783,0.120518,0.177711,0.582556,0.125962,0.144578,4.098328e-03,f1_macro,0.120518,0.058824,0.141251,shuffle_training_X_only
3,YFL,3,126,1657,1657,332,0.216867,0.153201,0.138842,0.216867,0.578669,0.125962,0.144578,2.766112e-06,f1_macro,0.138842,0.019608,NaN,shuffle_training_X_only
4,YFL,4,168,1657,1657,332,0.189759,0.133384,0.123229,0.189759,0.549080,0.125962,0.144578,5.982399e-04,f1_macro,0.123229,0.039216,NaN,shuffle_training_X_only
5,YFL,5,210,1657,1657,332,0.231928,0.177473,0.176062,0.231928,0.590541,0.125962,0.144578,7.669840e-08,f1_macro,0.176062,0.019608,NaN,shuffle_training_X_only
6,YFL,6,252,1657,1657,332,0.207831,0.145528,0.131772,0.207831,0.576245,0.125962,0.144578,1.942692e-05,f1_macro,0.131772,0.019608,NaN,shuffle_training_X_only
7,YFL,7,294,1657,1657,332,0.192771,0.135467,0.124666,0.192771,0.536009,0.125962,0.144578,3.532897e-04,f1_macro,0.124666,0.058824,NaN,shuffle_training_X_only
8,YFL,8,336,1657,1657,332,0.159639,0.112195,0.100975,0.159639,0.569845,0.125962,0.144578,4.197412e-02,f1_macro,0.100975,0.372549,NaN,shuffle_training_X_only
9,YFL,9,378,1657,1657,332,0.180723,0.126778,0.115140,0.180723,0.569985,0.125962,0.144578,2.604176e-03,f1_macro,0.115140,0.078431,NaN,shuffle_training_X_only
10,YFL,10,420,1657,1657,332,0.180723,0.133740,0.125346,0.180723,0.562429,0.125962,0.144578,2.604176e-03,f1_macro,0.125346,0.039216,NaN,shuffle_training_X_only
11,YFL,11,462,1657,1657,332,0.204819,0.145224,0.132127,0.204819,0.580499,0.125962,0.144578,3.594359e-05,f1_macro,0.132127,0.019608,NaN,shuffle_training_X_only
12,YFL,12,504,1657,1657,332,0.198795,0.139990,0.130275,0.198795,0.601540,0.125962,0.144578,1.167524e-04,f1_macro,0.130275,0.019608,NaN,shuffle_training_X_only
13,YFL,13,546,1657,1657,332,0.171687,0.124683,0.120258,0.171687,0.570601,0.125962,0.144578,9.598009e-03,f1_macro,0.120258,0.058824,NaN,shuffle_training_X_only
14,YFL,14,588,1657,1657,332,0.192771,0.134756,0.122757,0.192771,0.597261,0.125962,0.144578,3.532897e-04,f1_macro,0.122757,0.019608,NaN,shuffle_training_X_only
15,YFL,15,630,1657,1657,332,0.141566,0.098628,0.088980,0.141566,0.559012,0.125962,0.144578,2.169304e-01,f1_macro,0.088980,0.607843,NaN,shuffle_training_X_only
16,YFL,16,672,1657,1657,332,0.183735,0.138957,0.133118,0.183735,0.575760,0.125962,0.144578,1.624429e-03,f1_macro,0.133118,0.019608,NaN,shuffle_training_X_only
17,YFL,17,714,1657,1657,332,0.204819,0.149765,0.145549,0.204819,0.591999,0.125962,0.144578,3.594359e-05,f1_macro,0.145549,0.019608,NaN,shuffle_training_X_only
18,YFL,18,756,1657,1657,332,0.177711,0.125051,0.112933,0.177711,0.576670,0.125962,0.144578,4.098328e-03,f1_macro,0.112933,0.058824,NaN,shuffle_training_X_only
19,YFL,19,798,1657,1657,332,0.171687,0.130979,0.128048,0.171687,0.549754,0.125962,0.144578,9.598009e-03,f1_macro,0.128048,0.019608,NaN,shuffle_training_X_only

aggregated YFL 2025-03-06 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFL/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-06/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFL,0,0,741,741,149,0.167785,0.128647,0.127357,0.167785,0.547244,0.123193,0.14094,0.067242,f1_macro,0.127357,0.156863,0.144110,shuffle_training_X_only
1,YFL,1,42,741,741,149,0.154362,0.134599,0.135874,0.154362,0.538277,0.123193,0.14094,0.150898,f1_macro,0.135874,0.058824,0.163705,shuffle_training_X_only
2,YFL,2,84,741,741,149,0.187919,0.146767,0.146220,0.187919,0.577668,0.123193,0.14094,0.014877,f1_macro,0.146220,0.058824,0.135085,shuffle_training_X_only
3,YFL,3,126,741,741,149,0.154362,0.111216,0.102238,0.154362,0.566623,0.123193,0.14094,0.150898,f1_macro,0.102238,0.156863,NaN,shuffle_training_X_only
4,YFL,4,168,741,741,149,0.140940,0.102694,0.092134,0.140940,0.580126,0.123193,0.14094,0.288866,f1_macro,0.092134,0.431373,NaN,shuffle_training_X_only
5,YFL,5,210,741,741,149,0.194631,0.166241,0.173714,0.194631,0.543981,0.123193,0.14094,0.008327,f1_macro,0.173714,0.019608,NaN,shuffle_training_X_only
6,YFL,6,252,741,741,149,0.161074,0.118195,0.106599,0.161074,0.580825,0.123193,0.14094,0.102754,f1_macro,0.106599,0.352941,NaN,shuffle_training_X_only
7,YFL,7,294,741,741,149,0.147651,0.109837,0.102176,0.147651,0.565110,0.123193,0.14094,0.212953,f1_macro,0.102176,0.254902,NaN,shuffle_training_X_only
8,YFL,8,336,741,741,149,0.161074,0.135050,0.139140,0.161074,0.552689,0.123193,0.14094,0.102754,f1_macro,0.139140,0.039216,NaN,shuffle_training_X_only
9,YFL,9,378,741,741,149,0.140940,0.112406,0.109757,0.140940,0.583189,0.123193,0.14094,0.288866,f1_macro,0.109757,0.137255,NaN,shuffle_training_X_only
10,YFL,10,420,741,741,149,0.087248,0.063145,0.058006,0.087248,0.573045,0.123193,0.14094,0.933643,f1_macro,0.058006,0.921569,NaN,shuffle_training_X_only
11,YFL,11,462,741,741,149,0.161074,0.134286,0.134823,0.161074,0.578355,0.123193,0.14094,0.102754,f1_macro,0.134823,0.019608,NaN,shuffle_training_X_only
12,YFL,12,504,741,741,149,0.120805,0.093095,0.089151,0.120805,0.585914,0.123193,0.14094,0.572550,f1_macro,0.089151,0.666667,NaN,shuffle_training_X_only
13,YFL,13,546,741,741,149,0.208054,0.151291,0.139944,0.208054,0.605909,0.123193,0.14094,0.002329,f1_macro,0.139944,0.019608,NaN,shuffle_training_X_only
14,YFL,14,588,741,741,149,0.147651,0.110338,0.105101,0.147651,0.565853,0.123193,0.14094,0.212953,f1_macro,0.105101,0.313725,NaN,shuffle_training_X_only
15,YFL,15,630,741,741,149,0.147651,0.110576,0.106395,0.147651,0.555641,0.123193,0.14094,0.212953,f1_macro,0.106395,0.176471,NaN,shuffle_training_X_only
16,YFL,16,672,741,741,149,0.187919,0.157932,0.167513,0.187919,0.565076,0.123193,0.14094,0.014877,f1_macro,0.167513,0.019608,NaN,shuffle_training_X_only
17,YFL,17,714,741,741,149,0.147651,0.107957,0.099390,0.147651,0.577453,0.123193,0.14094,0.212953,f1_macro,0.099390,0.254902,NaN,shuffle_training_X_only
18,YFL,18,756,741,741,149,0.181208,0.130764,0.120323,0.181208,0.595276,0.123193,0.14094,0.025577,f1_macro,0.120323,0.137255,NaN,shuffle_training_X_only
19,YFL,19,798,741,741,149,0.228188,0.170764,0.160488,0.228188,0.628391,0.123193,0.14094,0.000261,f1_macro,0.160488,0.019608,NaN,shuffle_training_X_only

aggregated YFM 2025-03-10 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFM/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-10/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFM,0,0,158,158,32,0.18750,0.159259,0.144541,0.18750,NaN,0.126953,0.15625,0.214016,f1_macro,0.144541,0.098039,0.141101,shuffle_training_X_only
1,YFM,1,42,158,158,32,0.15625,0.122222,0.107520,0.15625,NaN,0.126953,0.15625,0.383933,f1_macro,0.107520,0.392157,0.133663,shuffle_training_X_only
2,YFM,2,84,158,158,32,0.09375,0.101852,0.074956,0.09375,NaN,0.126953,0.15625,0.790522,f1_macro,0.074956,0.705882,0.119184,shuffle_training_X_only
3,YFM,3,126,158,158,32,0.09375,0.072222,0.057498,0.09375,NaN,0.126953,0.15625,0.790522,f1_macro,0.057498,0.764706,NaN,shuffle_training_X_only
4,YFM,4,168,158,158,32,0.09375,0.083333,0.059524,0.09375,NaN,0.126953,0.15625,0.790522,f1_macro,0.059524,0.862745,NaN,shuffle_training_X_only
5,YFM,5,210,158,158,32,0.09375,0.077778,0.055815,0.09375,NaN,0.126953,0.15625,0.790522,f1_macro,0.055815,0.764706,NaN,shuffle_training_X_only
6,YFM,6,252,158,158,32,0.12500,0.094444,0.080688,0.12500,NaN,0.126953,0.15625,0.592596,f1_macro,0.080688,0.470588,NaN,shuffle_training_X_only
7,YFM,7,294,158,158,32,0.15625,0.127778,0.093712,0.15625,NaN,0.126953,0.15625,0.383933,f1_macro,0.093712,0.411765,NaN,shuffle_training_X_only
8,YFM,8,336,158,158,32,0.18750,0.150000,0.121869,0.18750,NaN,0.126953,0.15625,0.214016,f1_macro,0.121869,0.254902,NaN,shuffle_training_X_only
9,YFM,9,378,158,158,32,0.12500,0.105556,0.066138,0.12500,NaN,0.126953,0.15625,0.592596,f1_macro,0.066138,0.627451,NaN,shuffle_training_X_only
10,YFM,10,420,158,158,32,0.06250,0.050000,0.038721,0.06250,NaN,0.126953,0.15625,0.926633,f1_macro,0.038721,0.921569,NaN,shuffle_training_X_only
11,YFM,11,462,158,158,32,0.15625,0.116667,0.091807,0.15625,NaN,0.126953,0.15625,0.383933,f1_macro,0.091807,0.450980,NaN,shuffle_training_X_only
12,YFM,12,504,158,158,32,0.12500,0.100000,0.074956,0.12500,NaN,0.126953,0.15625,0.592596,f1_macro,0.074956,0.568627,NaN,shuffle_training_X_only
13,YFM,13,546,158,158,32,0.21875,0.172222,0.124492,0.21875,NaN,0.126953,0.15625,0.102828,f1_macro,0.124492,0.215686,NaN,shuffle_training_X_only
14,YFM,14,588,158,158,32,0.18750,0.161111,0.096714,0.18750,NaN,0.126953,0.15625,0.214016,f1_macro,0.096714,0.294118,NaN,shuffle_training_X_only
15,YFM,15,630,158,158,32,0.12500,0.100000,0.079461,0.12500,NaN,0.126953,0.15625,0.592596,f1_macro,0.079461,0.450980,NaN,shuffle_training_X_only
16,YFM,16,672,158,158,32,0.15625,0.122222,0.101190,0.15625,NaN,0.126953,0.15625,0.383933,f1_macro,0.101190,0.333333,NaN,shuffle_training_X_only
17,YFM,17,714,158,158,32,0.25000,0.200000,0.159524,0.25000,NaN,0.126953,0.15625,0.042774,f1_macro,0.159524,0.058824,NaN,shuffle_training_X_only
18,YFM,18,756,158,158,32,0.21875,0.172222,0.130079,0.21875,NaN,0.126953,0.15625,0.102828,f1_macro,0.130079,0.137255,NaN,shuffle_training_X_only
19,YFM,19,798,158,158,32,0.12500,0.094444,0.081481,0.12500,NaN,0.126953,0.15625,0.592596,f1_macro,0.081481,0.509804,NaN,shuffle_training_X_only

aggregated YFM 2025-03-11 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFM/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-11/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFM,0,0,2885,2885,577,0.223570,0.159454,0.150487,0.223570,0.603351,0.127273,0.145581,1.212874e-10,f1_macro,0.150487,0.019608,0.138146,shuffle_training_X_only
1,YFM,1,42,2885,2885,577,0.171577,0.125490,0.119501,0.171577,0.570710,0.127273,0.145581,1.295872e-03,f1_macro,0.119501,0.039216,0.141896,shuffle_training_X_only
2,YFM,2,84,2885,2885,577,0.192374,0.138978,0.133013,0.192374,0.585141,0.127273,0.145581,6.228239e-06,f1_macro,0.133013,0.019608,0.152557,shuffle_training_X_only
3,YFM,3,126,2885,2885,577,0.206239,0.145560,0.136072,0.206239,0.612581,0.127273,0.145581,7.543034e-08,f1_macro,0.136072,0.019608,NaN,shuffle_training_X_only
4,YFM,4,168,2885,2885,577,0.204506,0.146359,0.136751,0.204506,0.589901,0.127273,0.145581,1.357990e-07,f1_macro,0.136751,0.019608,NaN,shuffle_training_X_only
5,YFM,5,210,2885,2885,577,0.183709,0.133775,0.129025,0.183709,0.552854,0.127273,0.145581,6.969600e-05,f1_macro,0.129025,0.019608,NaN,shuffle_training_X_only
6,YFM,6,252,2885,2885,577,0.211438,0.148333,0.135901,0.211438,0.590704,0.127273,0.145581,1.216150e-08,f1_macro,0.135901,0.019608,NaN,shuffle_training_X_only
7,YFM,7,294,2885,2885,577,0.223570,0.158894,0.148307,0.223570,0.614751,0.127273,0.145581,1.212874e-10,f1_macro,0.148307,0.019608,NaN,shuffle_training_X_only
8,YFM,8,336,2885,2885,577,0.164645,0.121776,0.119509,0.164645,0.589474,0.127273,0.145581,5.385789e-03,f1_macro,0.119509,0.019608,NaN,shuffle_training_X_only
9,YFM,9,378,2885,2885,577,0.187175,0.133655,0.125055,0.187175,0.593536,0.127273,0.145581,2.739614e-05,f1_macro,0.125055,0.019608,NaN,shuffle_training_X_only
10,YFM,10,420,2885,2885,577,0.176776,0.125322,0.116339,0.176776,0.569260,0.127273,0.145581,3.957052e-04,f1_macro,0.116339,0.058824,NaN,shuffle_training_X_only
11,YFM,11,462,2885,2885,577,0.194107,0.135952,0.124985,0.194107,0.593086,0.127273,0.145581,3.721077e-06,f1_macro,0.124985,0.019608,NaN,shuffle_training_X_only
12,YFM,12,504,2885,2885,577,0.173310,0.125168,0.116701,0.173310,0.560908,0.127273,0.145581,8.824203e-04,f1_macro,0.116701,0.019608,NaN,shuffle_training_X_only
13,YFM,13,546,2885,2885,577,0.216638,0.153179,0.143066,0.216638,0.604256,0.127273,0.145581,1.791112e-09,f1_macro,0.143066,0.019608,NaN,shuffle_training_X_only
14,YFM,14,588,2885,2885,577,0.206239,0.148263,0.140697,0.206239,0.598768,0.127273,0.145581,7.543034e-08,f1_macro,0.140697,0.019608,NaN,shuffle_training_X_only
15,YFM,15,630,2885,2885,577,0.214905,0.153978,0.141712,0.214905,0.603162,0.127273,0.145581,3.425646e-09,f1_macro,0.141712,0.019608,NaN,shuffle_training_X_only
16,YFM,16,672,2885,2885,577,0.190641,0.142658,0.141396,0.190641,0.568462,0.127273,0.145581,1.031453e-05,f1_macro,0.141396,0.019608,NaN,shuffle_training_X_only
17,YFM,17,714,2885,2885,577,0.162912,0.114286,0.103687,0.162912,0.557087,0.127273,0.145581,7.475275e-03,f1_macro,0.103687,0.137255,NaN,shuffle_training_X_only
18,YFM,18,756,2885,2885,577,0.216638,0.157906,0.152169,0.216638,0.618715,0.127273,0.145581,1.791112e-09,f1_macro,0.152169,0.019608,NaN,shuffle_training_X_only
19,YFM,19,798,2885,2885,577,0.187175,0.133978,0.123889,0.187175,0.587396,0.127273,0.145581,2.739614e-05,f1_macro,0.123889,0.019608,NaN,shuffle_training_X_only

aggregated YFM 2025-03-12 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFM/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-12/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFM,0,0,2908,2908,582,0.214777,0.156190,0.159441,0.214777,0.536576,0.135833,0.154639,1.272902e-07,f1_macro,0.159441,0.019608,0.148406,shuffle_training_X_only
1,YFM,1,42,2908,2908,582,0.209622,0.145794,0.143094,0.209622,0.612362,0.135833,0.154639,6.722052e-07,f1_macro,0.143094,0.019608,0.150742,shuffle_training_X_only
2,YFM,2,84,2908,2908,582,0.202749,0.135238,0.128281,0.202749,0.604028,0.135833,0.154639,5.376874e-06,f1_macro,0.128281,0.019608,0.143134,shuffle_training_X_only
3,YFM,3,126,2908,2908,582,0.225086,0.153254,0.146760,0.225086,0.624317,0.135833,0.154639,3.506074e-09,f1_macro,0.146760,0.019608,NaN,shuffle_training_X_only
4,YFM,4,168,2908,2908,582,0.201031,0.131429,0.119585,0.201031,0.560480,0.135833,0.154639,8.817341e-06,f1_macro,0.119585,0.019608,NaN,shuffle_training_X_only
5,YFM,5,210,2908,2908,582,0.226804,0.151984,0.141422,0.226804,0.614424,0.135833,0.154639,1.862933e-09,f1_macro,0.141422,0.019608,NaN,shuffle_training_X_only
6,YFM,6,252,2908,2908,582,0.226804,0.161746,0.162512,0.226804,0.583877,0.135833,0.154639,1.862933e-09,f1_macro,0.162512,0.019608,NaN,shuffle_training_X_only
7,YFM,7,294,2908,2908,582,0.226804,0.159524,0.159576,0.226804,0.599877,0.135833,0.154639,1.862933e-09,f1_macro,0.159576,0.019608,NaN,shuffle_training_X_only
8,YFM,8,336,2908,2908,582,0.269759,0.186349,0.179975,0.269759,0.612954,0.135833,0.154639,1.280183e-17,f1_macro,0.179975,0.019608,NaN,shuffle_training_X_only
9,YFM,9,378,2908,2908,582,0.235395,0.158254,0.150445,0.235395,0.617401,0.135833,0.154639,6.846943e-11,f1_macro,0.150445,0.019608,NaN,shuffle_training_X_only
10,YFM,10,420,2908,2908,582,0.226804,0.156111,0.152041,0.226804,0.603220,0.135833,0.154639,1.862933e-09,f1_macro,0.152041,0.019608,NaN,shuffle_training_X_only
11,YFM,11,462,2908,2908,582,0.218213,0.142540,0.130464,0.218213,0.602821,0.135833,0.154639,3.996202e-08,f1_macro,0.130464,0.019608,NaN,shuffle_training_X_only
12,YFM,12,504,2908,2908,582,0.223368,0.149524,0.140898,0.223368,0.613662,0.135833,0.154639,6.535768e-09,f1_macro,0.140898,0.019608,NaN,shuffle_training_X_only
13,YFM,13,546,2908,2908,582,0.207904,0.143968,0.140595,0.207904,0.589142,0.135833,0.154639,1.147596e-06,f1_macro,0.140595,0.019608,NaN,shuffle_training_X_only
14,YFM,14,588,2908,2908,582,0.238832,0.161746,0.153074,0.238832,0.581799,0.135833,0.154639,1.710851e-11,f1_macro,0.153074,0.019608,NaN,shuffle_training_X_only
15,YFM,15,630,2908,2908,582,0.219931,0.147460,0.137995,0.219931,0.621472,0.135833,0.154639,2.206626e-08,f1_macro,0.137995,0.019608,NaN,shuffle_training_X_only
16,YFM,16,672,2908,2908,582,0.219931,0.154048,0.153261,0.219931,0.591930,0.135833,0.154639,2.206626e-08,f1_macro,0.153261,0.019608,NaN,shuffle_training_X_only
17,YFM,17,714,2908,2908,582,0.228522,0.151111,0.138949,0.228522,0.605152,0.135833,0.154639,9.804917e-10,f1_macro,0.138949,0.019608,NaN,shuffle_training_X_only
18,YFM,18,756,2908,2908,582,0.204467,0.140714,0.135841,0.204467,0.545421,0.135833,0.154639,3.245807e-06,f1_macro,0.135841,0.019608,NaN,shuffle_training_X_only
19,YFM,19,798,2908,2908,582,0.243986,0.169921,0.165398,0.243986,0.601277,0.135833,0.154639,1.994285e-12,f1_macro,0.165398,0.019608,NaN,shuffle_training_X_only

aggregated YFM 2025-03-13 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFM/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-13/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFM,0,0,4791,4791,959,0.251303,0.191753,0.186972,0.251303,0.637013,0.12531,0.140772,2.387778e-26,f1_macro,0.186972,0.019608,0.160799,shuffle_training_X_only
1,YFM,1,42,4791,4791,959,0.234619,0.179702,0.176134,0.234619,0.630745,0.12531,0.140772,1.053059e-20,f1_macro,0.176134,0.019608,0.164134,shuffle_training_X_only
2,YFM,2,84,4791,4791,959,0.222106,0.180916,0.184955,0.222106,0.632854,0.12531,0.140772,6.905482e-17,f1_macro,0.184955,0.019608,0.178646,shuffle_training_X_only
3,YFM,3,126,4791,4791,959,0.236705,0.180647,0.177768,0.236705,0.650213,0.12531,0.140772,2.244667e-21,f1_macro,0.177768,0.019608,NaN,shuffle_training_X_only
4,YFM,4,168,4791,4791,959,0.236705,0.178067,0.171572,0.236705,0.629682,0.12531,0.140772,2.244667e-21,f1_macro,0.171572,0.019608,NaN,shuffle_training_X_only
5,YFM,5,210,4791,4791,959,0.225235,0.169931,0.164646,0.225235,0.635098,0.12531,0.140772,8.304186e-18,f1_macro,0.164646,0.019608,NaN,shuffle_training_X_only
6,YFM,6,252,4791,4791,959,0.253389,0.187316,0.178263,0.253389,0.650602,0.12531,0.140772,4.256242e-27,f1_macro,0.178263,0.019608,NaN,shuffle_training_X_only
7,YFM,7,294,4791,4791,959,0.221064,0.161715,0.148988,0.221064,0.644780,0.12531,0.140772,1.382548e-16,f1_macro,0.148988,0.019608,NaN,shuffle_training_X_only
8,YFM,8,336,4791,4791,959,0.234619,0.174619,0.168163,0.234619,0.657853,0.12531,0.140772,1.053059e-20,f1_macro,0.168163,0.019608,NaN,shuffle_training_X_only
9,YFM,9,378,4791,4791,959,0.226277,0.171159,0.162513,0.226277,0.639151,0.12531,0.140772,4.050835e-18,f1_macro,0.162513,0.019608,NaN,shuffle_training_X_only
10,YFM,10,420,4791,4791,959,0.249218,0.187824,0.181613,0.249218,0.658363,0.12531,0.140772,1.310493e-25,f1_macro,0.181613,0.019608,NaN,shuffle_training_X_only
11,YFM,11,462,4791,4791,959,0.242961,0.180723,0.171877,0.242961,0.646478,0.12531,0.140772,1.897109e-23,f1_macro,0.171877,0.019608,NaN,shuffle_training_X_only
12,YFM,12,504,4791,4791,959,0.222106,0.165708,0.160490,0.222106,0.640921,0.12531,0.140772,6.905482e-17,f1_macro,0.160490,0.019608,NaN,shuffle_training_X_only
13,YFM,13,546,4791,4791,959,0.241919,0.177149,0.167528,0.241919,0.639557,0.12531,0.140772,4.263089e-23,f1_macro,0.167528,0.019608,NaN,shuffle_training_X_only
14,YFM,14,588,4791,4791,959,0.241919,0.183363,0.173139,0.241919,0.631746,0.12531,0.140772,4.263089e-23,f1_macro,0.173139,0.019608,NaN,shuffle_training_X_only
15,YFM,15,630,4791,4791,959,0.242961,0.190439,0.191445,0.242961,0.669308,0.12531,0.140772,1.897109e-23,f1_macro,0.191445,0.019608,NaN,shuffle_training_X_only
16,YFM,16,672,4791,4791,959,0.230448,0.175798,0.172795,0.230448,0.642739,0.12531,0.140772,2.163403e-19,f1_macro,0.172795,0.019608,NaN,shuffle_training_X_only
17,YFM,17,714,4791,4791,959,0.227320,0.167533,0.158319,0.227320,0.658907,0.12531,0.140772,1.964467e-18,f1_macro,0.158319,0.019608,NaN,shuffle_training_X_only
18,YFM,18,756,4791,4791,959,0.228363,0.170997,0.161859,0.228363,0.645650,0.12531,0.140772,9.471207e-19,f1_macro,0.161859,0.019608,NaN,shuffle_training_X_only
19,YFM,19,798,4791,4791,959,0.215850,0.161878,0.155517,0.215850,0.639669,0.12531,0.140772,4.065902e-15,f1_macro,0.155517,0.019608,NaN,shuffle_training_X_only

aggregated YFM 2025-03-14 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFM/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-14/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFM,0,0,8015,8015,1603,0.227698,0.165661,0.159851,0.227698,0.619607,0.129431,0.145352,3.400058e-27,f1_macro,0.159851,0.019608,0.164955,shuffle_training_X_only
1,YFM,1,42,8015,8015,1603,0.221460,0.157270,0.147918,0.221460,0.630169,0.129431,0.145352,2.803003e-24,f1_macro,0.147918,0.019608,0.162472,shuffle_training_X_only
2,YFM,2,84,8015,8015,1603,0.227698,0.162446,0.152434,0.227698,0.613073,0.129431,0.145352,3.400058e-27,f1_macro,0.152434,0.019608,0.160148,shuffle_training_X_only
3,YFM,3,126,8015,8015,1603,0.218964,0.156362,0.149013,0.218964,0.625011,0.129431,0.145352,3.721614e-23,f1_macro,0.149013,0.019608,NaN,shuffle_training_X_only
4,YFM,4,168,8015,8015,1603,0.234560,0.172528,0.169704,0.234560,0.626870,0.129431,0.145352,1.404919e-30,f1_macro,0.169704,0.019608,NaN,shuffle_training_X_only
5,YFM,5,210,8015,8015,1603,0.207735,0.152682,0.147498,0.207735,0.630354,0.129431,0.145352,2.050553e-18,f1_macro,0.147498,0.019608,NaN,shuffle_training_X_only
6,YFM,6,252,8015,8015,1603,0.237679,0.171018,0.161828,0.237679,0.646468,0.129431,0.145352,3.544099e-32,f1_macro,0.161828,0.019608,NaN,shuffle_training_X_only
7,YFM,7,294,8015,8015,1603,0.245789,0.180380,0.174844,0.245789,0.631884,0.129431,0.145352,1.665843e-36,f1_macro,0.174844,0.019608,NaN,shuffle_training_X_only
8,YFM,8,336,8015,8015,1603,0.233313,0.172573,0.169875,0.233313,0.626147,0.129431,0.145352,5.976660e-30,f1_macro,0.169875,0.019608,NaN,shuffle_training_X_only
9,YFM,9,378,8015,8015,1603,0.228946,0.172423,0.173227,0.228946,0.620657,0.129431,0.145352,8.508730e-28,f1_macro,0.173227,0.019608,NaN,shuffle_training_X_only
10,YFM,10,420,8015,8015,1603,0.221460,0.162682,0.158841,0.221460,0.629588,0.129431,0.145352,2.803003e-24,f1_macro,0.158841,0.019608,NaN,shuffle_training_X_only
11,YFM,11,462,8015,8015,1603,0.224579,0.162806,0.155091,0.224579,0.623748,0.129431,0.145352,1.020465e-25,f1_macro,0.155091,0.019608,NaN,shuffle_training_X_only
12,YFM,12,504,8015,8015,1603,0.240175,0.174610,0.168566,0.240175,0.630572,0.129431,0.145352,1.755034e-33,f1_macro,0.168566,0.019608,NaN,shuffle_training_X_only
13,YFM,13,546,8015,8015,1603,0.219588,0.156962,0.145954,0.219588,0.616774,0.129431,0.145352,1.960178e-23,f1_macro,0.145954,0.019608,NaN,shuffle_training_X_only
14,YFM,14,588,8015,8015,1603,0.222707,0.165047,0.159784,0.222707,0.612527,0.129431,0.145352,7.528954e-25,f1_macro,0.159784,0.019608,NaN,shuffle_training_X_only
15,YFM,15,630,8015,8015,1603,0.240799,0.181145,0.181151,0.240799,0.629638,0.129431,0.145352,8.209047e-34,f1_macro,0.181151,0.019608,NaN,shuffle_training_X_only
16,YFM,16,672,8015,8015,1603,0.227698,0.165036,0.157885,0.227698,0.640412,0.129431,0.145352,3.400058e-27,f1_macro,0.157885,0.019608,NaN,shuffle_training_X_only
17,YFM,17,714,8015,8015,1603,0.220836,0.161539,0.155463,0.220836,0.622613,0.129431,0.145352,5.379460e-24,f1_macro,0.155463,0.019608,NaN,shuffle_training_X_only
18,YFM,18,756,8015,8015,1603,0.242670,0.180652,0.179153,0.242670,0.633958,0.129431,0.145352,8.231970e-35,f1_macro,0.179153,0.019608,NaN,shuffle_training_X_only
19,YFM,19,798,8015,8015,1603,0.220836,0.161147,0.156331,0.220836,0.627304,0.129431,0.145352,5.379460e-24,f1_macro,0.156331,0.019608,NaN,shuffle_training_X_only

aggregated YFM 2025-03-15 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFM/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-15/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFM,0,0,3267,3267,654,0.203364,0.146848,0.140411,0.203364,0.576825,0.12534,0.142202,1.328049e-08,f1_macro,0.140411,0.019608,0.147751,shuffle_training_X_only
1,YFM,1,42,3267,3267,654,0.186544,0.139269,0.135361,0.186544,0.587577,0.12534,0.142202,5.062710e-06,f1_macro,0.135361,0.019608,0.142868,shuffle_training_X_only
2,YFM,2,84,3267,3267,654,0.221713,0.162386,0.155923,0.221713,0.583452,0.12534,0.142202,5.765434e-12,f1_macro,0.155923,0.019608,0.144487,shuffle_training_X_only
3,YFM,3,126,3267,3267,654,0.197248,0.140486,0.128417,0.197248,0.575593,0.12534,0.142202,1.314098e-07,f1_macro,0.128417,0.019608,NaN,shuffle_training_X_only
4,YFM,4,168,3267,3267,654,0.207951,0.150193,0.140471,0.207951,0.583732,0.12534,0.142202,2.162491e-09,f1_macro,0.140471,0.019608,NaN,shuffle_training_X_only
5,YFM,5,210,3267,3267,654,0.229358,0.167752,0.159470,0.229358,0.603209,0.12534,0.142202,1.579187e-13,f1_macro,0.159470,0.019608,NaN,shuffle_training_X_only
6,YFM,6,252,3267,3267,654,0.212538,0.157771,0.152270,0.212538,0.578247,0.12534,0.142202,3.247069e-10,f1_macro,0.152270,0.019608,NaN,shuffle_training_X_only
7,YFM,7,294,3267,3267,654,0.209480,0.151225,0.141673,0.209480,0.595035,0.12534,0.142202,1.159724e-09,f1_macro,0.141673,0.019608,NaN,shuffle_training_X_only
8,YFM,8,336,3267,3267,654,0.197248,0.140740,0.127531,0.197248,0.579834,0.12534,0.142202,1.314098e-07,f1_macro,0.127531,0.019608,NaN,shuffle_training_X_only
9,YFM,9,378,3267,3267,654,0.215596,0.153788,0.142574,0.215596,0.594711,0.12534,0.142202,8.773899e-11,f1_macro,0.142574,0.019608,NaN,shuffle_training_X_only
10,YFM,10,420,3267,3267,654,0.201835,0.144027,0.130897,0.201835,0.571242,0.12534,0.142202,2.388146e-08,f1_macro,0.130897,0.019608,NaN,shuffle_training_X_only
11,YFM,11,462,3267,3267,654,0.181957,0.131515,0.124122,0.181957,0.592610,0.12534,0.142202,2.098034e-05,f1_macro,0.124122,0.019608,NaN,shuffle_training_X_only
12,YFM,12,504,3267,3267,654,0.207951,0.150433,0.142329,0.207951,0.568978,0.12534,0.142202,2.162491e-09,f1_macro,0.142329,0.019608,NaN,shuffle_training_X_only
13,YFM,13,546,3267,3267,654,0.214067,0.154482,0.145613,0.214067,0.608771,0.12534,0.142202,1.695364e-10,f1_macro,0.145613,0.019608,NaN,shuffle_training_X_only
14,YFM,14,588,3267,3267,654,0.212538,0.155607,0.149127,0.212538,0.582401,0.12534,0.142202,3.247069e-10,f1_macro,0.149127,0.019608,NaN,shuffle_training_X_only
15,YFM,15,630,3267,3267,654,0.206422,0.148517,0.138426,0.206422,0.607037,0.12534,0.142202,3.996159e-09,f1_macro,0.138426,0.019608,NaN,shuffle_training_X_only
16,YFM,16,672,3267,3267,654,0.195719,0.139082,0.128392,0.195719,0.603493,0.12534,0.142202,2.277353e-07,f1_macro,0.128392,0.019608,NaN,shuffle_training_X_only
17,YFM,17,714,3267,3267,654,0.183486,0.130626,0.119963,0.183486,0.617110,0.12534,0.142202,1.318878e-05,f1_macro,0.119963,0.019608,NaN,shuffle_training_X_only
18,YFM,18,756,3267,3267,654,0.226300,0.162977,0.151252,0.226300,0.606514,0.12534,0.142202,6.831878e-13,f1_macro,0.151252,0.019608,NaN,shuffle_training_X_only
19,YFM,19,798,3267,3267,654,0.207951,0.152612,0.145093,0.207951,0.606343,0.12534,0.142202,2.162491e-09,f1_macro,0.145093,0.019608,NaN,shuffle_training_X_only

aggregated YFM 2025-03-17 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFM/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-17/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFM,0,0,10123,10123,2025,0.199012,0.150960,0.146611,0.199012,0.599344,0.122403,0.137778,9.461438e-23,f1_macro,0.146611,0.019608,0.156063,shuffle_training_X_only
1,YFM,1,42,10123,10123,2025,0.212840,0.162032,0.154854,0.212840,0.620928,0.122403,0.137778,2.418412e-30,f1_macro,0.154854,0.019608,0.156333,shuffle_training_X_only
2,YFM,2,84,10123,10123,2025,0.201975,0.155006,0.150766,0.201975,0.605789,0.122403,0.137778,2.723223e-24,f1_macro,0.150766,0.019608,0.157545,shuffle_training_X_only
3,YFM,3,126,10123,10123,2025,0.208395,0.159611,0.150872,0.208395,0.622858,0.122403,0.137778,8.603043e-28,f1_macro,0.150872,0.019608,NaN,shuffle_training_X_only
4,YFM,4,168,10123,10123,2025,0.210864,0.162354,0.155463,0.210864,0.623065,0.122403,0.137778,3.389523e-29,f1_macro,0.155463,0.019608,NaN,shuffle_training_X_only
5,YFM,5,210,10123,10123,2025,0.213827,0.163081,0.153814,0.213827,0.616720,0.122403,0.137778,6.347544e-31,f1_macro,0.153814,0.019608,NaN,shuffle_training_X_only
6,YFM,6,252,10123,10123,2025,0.215309,0.167287,0.160481,0.215309,0.617812,0.122403,0.137778,8.351014e-32,f1_macro,0.160481,0.019608,NaN,shuffle_training_X_only
7,YFM,7,294,10123,10123,2025,0.213333,0.164240,0.157033,0.213333,0.627820,0.122403,0.137778,1.240799e-30,f1_macro,0.157033,0.019608,NaN,shuffle_training_X_only
8,YFM,8,336,10123,10123,2025,0.203457,0.155700,0.148691,0.203457,0.623671,0.122403,0.137778,4.434573e-25,f1_macro,0.148691,0.019608,NaN,shuffle_training_X_only
9,YFM,9,378,10123,10123,2025,0.206914,0.158241,0.150337,0.206914,0.614663,0.122403,0.137778,5.780000e-27,f1_macro,0.150337,0.019608,NaN,shuffle_training_X_only
10,YFM,10,420,10123,10123,2025,0.191111,0.148665,0.144785,0.191111,0.607400,0.122403,0.137778,7.072664e-19,f1_macro,0.144785,0.019608,NaN,shuffle_training_X_only
11,YFM,11,462,10123,10123,2025,0.219259,0.167557,0.159951,0.219259,0.619729,0.122403,0.137778,3.292519e-34,f1_macro,0.159951,0.019608,NaN,shuffle_training_X_only
12,YFM,12,504,10123,10123,2025,0.217284,0.168939,0.162524,0.217284,0.618630,0.122403,0.137778,5.365860e-33,f1_macro,0.162524,0.019608,NaN,shuffle_training_X_only
13,YFM,13,546,10123,10123,2025,0.201975,0.154343,0.146768,0.201975,0.620586,0.122403,0.137778,2.723223e-24,f1_macro,0.146768,0.019608,NaN,shuffle_training_X_only
14,YFM,14,588,10123,10123,2025,0.220741,0.169238,0.160946,0.220741,0.617060,0.122403,0.137778,3.939014e-35,f1_macro,0.160946,0.019608,NaN,shuffle_training_X_only
15,YFM,15,630,10123,10123,2025,0.210370,0.159264,0.149432,0.210370,0.621176,0.122403,0.137778,6.510338e-29,f1_macro,0.149432,0.019608,NaN,shuffle_training_X_only
16,YFM,16,672,10123,10123,2025,0.215802,0.162884,0.154129,0.215802,0.623043,0.122403,0.137778,4.222768e-32,f1_macro,0.154129,0.019608,NaN,shuffle_training_X_only
17,YFM,17,714,10123,10123,2025,0.207901,0.156148,0.145736,0.207901,0.610069,0.122403,0.137778,1.628175e-27,f1_macro,0.145736,0.019608,NaN,shuffle_training_X_only
18,YFM,18,756,10123,10123,2025,0.212346,0.162116,0.153706,0.212346,0.618922,0.122403,0.137778,4.699921e-30,f1_macro,0.153706,0.019608,NaN,shuffle_training_X_only
19,YFM,19,798,10123,10123,2025,0.212840,0.161718,0.153036,0.212840,0.626231,0.122403,0.137778,2.418412e-30,f1_macro,0.153036,0.019608,NaN,shuffle_training_X_only

aggregated YFM 2025-03-18 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFM/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-18/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFM,0,0,4780,4716,944,0.194915,0.157490,0.159082,0.194915,0.584385,0.122827,0.140890,1.931800e-10,f1_macro,0.159082,0.019608,0.155857,shuffle_training_X_only
1,YFM,1,42,4780,4718,944,0.188559,0.148476,0.146414,0.188559,0.596309,0.122827,0.140890,4.886961e-09,f1_macro,0.146414,0.019608,0.157024,shuffle_training_X_only
2,YFM,2,84,4780,4718,944,0.190678,0.160008,0.164007,0.190678,0.598066,0.123086,0.140890,1.998888e-09,f1_macro,0.164007,0.019608,0.152328,shuffle_training_X_only
3,YFM,3,126,4780,4714,943,0.183457,0.140836,0.136011,0.183457,0.599979,0.123049,0.141039,6.288901e-08,f1_macro,0.136011,0.019608,NaN,shuffle_training_X_only
4,YFM,4,168,4780,4721,945,0.174603,0.136898,0.133116,0.174603,0.589295,0.123120,0.140741,2.838115e-06,f1_macro,0.133116,0.019608,NaN,shuffle_training_X_only
5,YFM,5,210,4780,4714,943,0.166490,0.130794,0.129779,0.166490,0.617922,0.123049,0.141039,5.942949e-05,f1_macro,0.129779,0.019608,NaN,shuffle_training_X_only
6,YFM,6,252,4780,4721,945,0.203175,0.164218,0.165127,0.203175,0.613222,0.122864,0.140741,2.039807e-12,f1_macro,0.165127,0.019608,NaN,shuffle_training_X_only
7,YFM,7,294,4780,4724,945,0.198942,0.157830,0.156326,0.198942,0.617071,0.123120,0.140741,2.626797e-11,f1_macro,0.156326,0.019608,NaN,shuffle_training_X_only
8,YFM,8,336,4780,4714,943,0.188759,0.152199,0.150857,0.188759,0.617211,0.123049,0.141039,5.140356e-09,f1_macro,0.150857,0.019608,NaN,shuffle_training_X_only
9,YFM,9,378,4780,4726,946,0.178647,0.140392,0.139602,0.178647,0.603166,0.122903,0.141649,4.697693e-07,f1_macro,0.139602,0.019608,NaN,shuffle_training_X_only
10,YFM,10,420,4780,4716,944,0.218220,0.175456,0.178009,0.218220,0.631945,0.123083,0.140890,2.353205e-16,f1_macro,0.178009,0.019608,NaN,shuffle_training_X_only
11,YFM,11,462,4780,4715,943,0.198303,0.154426,0.151160,0.198303,0.598877,0.123022,0.141039,3.653323e-11,f1_macro,0.151160,0.019608,NaN,shuffle_training_X_only
12,YFM,12,504,4780,4722,945,0.197884,0.150999,0.147779,0.197884,0.610338,0.123122,0.140741,4.685448e-11,f1_macro,0.147779,0.019608,NaN,shuffle_training_X_only
13,YFM,13,546,4780,4724,945,0.173545,0.135023,0.133119,0.173545,0.576952,0.123122,0.140741,4.331816e-06,f1_macro,0.133119,0.019608,NaN,shuffle_training_X_only
14,YFM,14,588,4780,4720,944,0.184322,0.146900,0.146595,0.184322,0.602254,0.122859,0.140890,3.748061e-08,f1_macro,0.146595,0.019608,NaN,shuffle_training_X_only
15,YFM,15,630,4780,4718,944,0.182203,0.139703,0.135240,0.182203,0.609439,0.123088,0.141949,1.115519e-07,f1_macro,0.135240,0.019608,NaN,shuffle_training_X_only
16,YFM,16,672,4780,4722,945,0.173545,0.142493,0.144472,0.173545,0.600947,0.122864,0.140741,3.847964e-06,f1_macro,0.144472,0.019608,NaN,shuffle_training_X_only
17,YFM,17,714,4780,4722,945,0.193651,0.148544,0.145870,0.193651,0.625194,0.123120,0.140741,4.410447e-10,f1_macro,0.145870,0.019608,NaN,shuffle_training_X_only
18,YFM,18,756,4780,4722,945,0.184127,0.144122,0.139627,0.184127,0.605025,0.123120,0.140741,4.660138e-08,f1_macro,0.139627,0.019608,NaN,shuffle_training_X_only
19,YFM,19,798,4780,4718,944,0.184322,0.144981,0.143443,0.184322,0.603030,0.123086,0.140890,4.246830e-08,f1_macro,0.143443,0.019608,NaN,shuffle_training_X_only

aggregated YFM 2025-03-19 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFM/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-19/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFM,0,0,2258,2258,452,0.196903,0.143838,0.136364,0.196903,0.577605,0.12734,0.146018,1.984374e-05,f1_macro,0.136364,0.039216,0.160115,shuffle_training_X_only
1,YFM,1,42,2258,2258,452,0.188053,0.138451,0.136118,0.188053,0.580226,0.12734,0.146018,1.554137e-04,f1_macro,0.136118,0.019608,0.146534,shuffle_training_X_only
2,YFM,2,84,2258,2258,452,0.196903,0.143721,0.138032,0.196903,0.554431,0.12734,0.146018,1.984374e-05,f1_macro,0.138032,0.019608,0.159444,shuffle_training_X_only
3,YFM,3,126,2258,2258,452,0.214602,0.159663,0.155066,0.214602,0.591452,0.12734,0.146018,1.721432e-07,f1_macro,0.155066,0.019608,NaN,shuffle_training_X_only
4,YFM,4,168,2258,2258,452,0.214602,0.163266,0.164759,0.214602,0.587444,0.12734,0.146018,1.721432e-07,f1_macro,0.164759,0.019608,NaN,shuffle_training_X_only
5,YFM,5,210,2258,2258,452,0.223451,0.173485,0.171437,0.223451,0.606043,0.12734,0.146018,1.181243e-08,f1_macro,0.171437,0.019608,NaN,shuffle_training_X_only
6,YFM,6,252,2258,2258,452,0.194690,0.145354,0.141111,0.194690,0.571500,0.12734,0.146018,3.386931e-05,f1_macro,0.141111,0.019608,NaN,shuffle_training_X_only
7,YFM,7,294,2258,2258,452,0.212389,0.150286,0.138081,0.212389,0.597830,0.12734,0.146018,3.259489e-07,f1_macro,0.138081,0.019608,NaN,shuffle_training_X_only
8,YFM,8,336,2258,2258,452,0.216814,0.170960,0.172691,0.216814,0.589956,0.12734,0.146018,8.977315e-08,f1_macro,0.172691,0.019608,NaN,shuffle_training_X_only
9,YFM,9,378,2258,2258,452,0.219027,0.159327,0.153493,0.219027,0.574894,0.12734,0.146018,4.623301e-08,f1_macro,0.153493,0.019608,NaN,shuffle_training_X_only
10,YFM,10,420,2258,2258,452,0.205752,0.160017,0.158062,0.205752,0.590931,0.12734,0.146018,2.049726e-06,f1_macro,0.158062,0.019608,NaN,shuffle_training_X_only
11,YFM,11,462,2258,2258,452,0.221239,0.168485,0.167102,0.221239,0.597934,0.12734,0.146018,2.351468e-08,f1_macro,0.167102,0.019608,NaN,shuffle_training_X_only
12,YFM,12,504,2258,2258,452,0.225664,0.164091,0.157696,0.225664,0.601062,0.12734,0.146018,5.861165e-09,f1_macro,0.157696,0.019608,NaN,shuffle_training_X_only
13,YFM,13,546,2258,2258,452,0.201327,0.152374,0.147448,0.201327,0.569298,0.12734,0.146018,6.546819e-06,f1_macro,0.147448,0.019608,NaN,shuffle_training_X_only
14,YFM,14,588,2258,2258,452,0.192478,0.143502,0.140029,0.192478,0.572538,0.12734,0.146018,5.704283e-05,f1_macro,0.140029,0.019608,NaN,shuffle_training_X_only
15,YFM,15,630,2258,2258,452,0.183628,0.149360,0.154810,0.183628,0.574126,0.12734,0.146018,4.010681e-04,f1_macro,0.154810,0.019608,NaN,shuffle_training_X_only
16,YFM,16,672,2258,2258,452,0.183628,0.138232,0.134625,0.183628,0.578904,0.12734,0.146018,4.010681e-04,f1_macro,0.134625,0.019608,NaN,shuffle_training_X_only
17,YFM,17,714,2258,2258,452,0.188053,0.136650,0.131912,0.188053,0.552343,0.12734,0.146018,1.554137e-04,f1_macro,0.131912,0.039216,NaN,shuffle_training_X_only
18,YFM,18,756,2258,2258,452,0.192478,0.144630,0.139937,0.192478,0.582178,0.12734,0.146018,5.704283e-05,f1_macro,0.139937,0.019608,NaN,shuffle_training_X_only
19,YFM,19,798,2258,2258,452,0.201327,0.160909,0.170594,0.201327,0.588960,0.12734,0.146018,6.546819e-06,f1_macro,0.170594,0.019608,NaN,shuffle_training_X_only

aggregated YFN 2025-03-31 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFN/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-03-31/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFN,0,0,1021,1021,205,0.131707,0.111795,0.105060,0.131707,0.572843,0.114479,0.126829,0.248002,f1_macro,0.105060,0.274510,0.136645,shuffle_training_X_only
1,YFN,1,42,1021,1021,205,0.156098,0.142630,0.145550,0.156098,0.563141,0.114479,0.126829,0.043465,f1_macro,0.145550,0.019608,0.128182,shuffle_training_X_only
2,YFN,2,84,1021,1021,205,0.170732,0.141207,0.134778,0.170732,0.515596,0.114479,0.126829,0.010506,f1_macro,0.134778,0.039216,0.138965,shuffle_training_X_only
3,YFN,3,126,1021,1021,205,0.131707,0.110855,0.111401,0.131707,0.568658,0.114479,0.126829,0.248002,f1_macro,0.111401,0.274510,NaN,shuffle_training_X_only
4,YFN,4,168,1021,1021,205,0.156098,0.130750,0.127762,0.156098,0.494280,0.114479,0.126829,0.043465,f1_macro,0.127762,0.137255,NaN,shuffle_training_X_only
5,YFN,5,210,1021,1021,205,0.156098,0.131919,0.130693,0.156098,0.562795,0.114479,0.126829,0.043465,f1_macro,0.130693,0.058824,NaN,shuffle_training_X_only
6,YFN,6,252,1021,1021,205,0.165854,0.145543,0.145186,0.165854,0.499285,0.114479,0.126829,0.017394,f1_macro,0.145186,0.058824,NaN,shuffle_training_X_only
7,YFN,7,294,1021,1021,205,0.165854,0.142124,0.142905,0.165854,0.547942,0.114479,0.126829,0.017394,f1_macro,0.142905,0.019608,NaN,shuffle_training_X_only
8,YFN,8,336,1021,1021,205,0.146341,0.121515,0.121968,0.146341,0.543082,0.114479,0.126829,0.095861,f1_macro,0.121968,0.156863,NaN,shuffle_training_X_only
9,YFN,9,378,1021,1021,205,0.136585,0.116643,0.116351,0.136585,0.537373,0.114479,0.126829,0.186415,f1_macro,0.116351,0.196078,NaN,shuffle_training_X_only
10,YFN,10,420,1021,1021,205,0.131707,0.115662,0.113369,0.131707,0.541332,0.114479,0.126829,0.248002,f1_macro,0.113369,0.235294,NaN,shuffle_training_X_only
11,YFN,11,462,1021,1021,205,0.121951,0.109925,0.105813,0.121951,0.489461,0.114479,0.126829,0.400146,f1_macro,0.105813,0.352941,NaN,shuffle_training_X_only
12,YFN,12,504,1021,1021,205,0.151220,0.125823,0.118989,0.151220,0.549587,0.114479,0.126829,0.065571,f1_macro,0.118989,0.117647,NaN,shuffle_training_X_only
13,YFN,13,546,1021,1021,205,0.141463,0.118838,0.115165,0.141463,0.512542,0.114479,0.126829,0.135799,f1_macro,0.115165,0.352941,NaN,shuffle_training_X_only
14,YFN,14,588,1021,1021,205,0.156098,0.131765,0.130371,0.156098,0.549541,0.114479,0.126829,0.043465,f1_macro,0.130371,0.058824,NaN,shuffle_training_X_only
15,YFN,15,630,1021,1021,205,0.156098,0.132028,0.128850,0.156098,0.528645,0.114479,0.126829,0.043465,f1_macro,0.128850,0.039216,NaN,shuffle_training_X_only
16,YFN,16,672,1021,1021,205,0.131707,0.111504,0.107077,0.131707,0.496301,0.114479,0.126829,0.248002,f1_macro,0.107077,0.392157,NaN,shuffle_training_X_only
17,YFN,17,714,1021,1021,205,0.121951,0.107925,0.111403,0.121951,0.545913,0.114479,0.126829,0.400146,f1_macro,0.111403,0.274510,NaN,shuffle_training_X_only
18,YFN,18,756,1021,1021,205,0.141463,0.116729,0.113878,0.141463,0.541461,0.114479,0.126829,0.135799,f1_macro,0.113878,0.235294,NaN,shuffle_training_X_only
19,YFN,19,798,1021,1021,205,0.175610,0.152528,0.153933,0.175610,0.507155,0.114479,0.126829,0.006155,f1_macro,0.153933,0.019608,NaN,shuffle_training_X_only

aggregated YFN 2025-04-01 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFN/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-04-01/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFN,0,0,5944,5944,1189,0.191758,0.144109,0.134277,0.191758,0.571667,0.120825,0.139613,1.623062e-12,f1_macro,0.134277,0.019608,0.137212,shuffle_training_X_only
1,YFN,1,42,5944,5944,1189,0.189235,0.141993,0.132923,0.189235,0.571695,0.120825,0.139613,8.370508e-12,f1_macro,0.132923,0.019608,0.126699,shuffle_training_X_only
2,YFN,2,84,5944,5944,1189,0.186712,0.142701,0.135508,0.186712,0.566135,0.120825,0.139613,4.113767e-11,f1_macro,0.135508,0.019608,0.136030,shuffle_training_X_only
3,YFN,3,126,5944,5944,1189,0.195963,0.146125,0.136787,0.195963,0.555677,0.120825,0.139613,9.483333e-14,f1_macro,0.136787,0.019608,NaN,shuffle_training_X_only
4,YFN,4,168,5944,5944,1189,0.185029,0.139177,0.131436,0.185029,0.578293,0.120825,0.139613,1.157478e-10,f1_macro,0.131436,0.019608,NaN,shuffle_training_X_only
5,YFN,5,210,5944,5944,1189,0.181665,0.139085,0.133771,0.181665,0.557947,0.120825,0.139613,8.583884e-10,f1_macro,0.133771,0.019608,NaN,shuffle_training_X_only
6,YFN,6,252,5944,5944,1189,0.172414,0.132483,0.126481,0.172414,0.576547,0.120825,0.139613,1.343558e-07,f1_macro,0.126481,0.019608,NaN,shuffle_training_X_only
7,YFN,7,294,5944,5944,1189,0.172414,0.128893,0.121090,0.172414,0.564696,0.120825,0.139613,1.343558e-07,f1_macro,0.121090,0.019608,NaN,shuffle_training_X_only
8,YFN,8,336,5944,5944,1189,0.187553,0.139166,0.128669,0.187553,0.563647,0.120825,0.139613,2.432655e-11,f1_macro,0.128669,0.019608,NaN,shuffle_training_X_only
9,YFN,9,378,5944,5944,1189,0.194281,0.148988,0.143612,0.194281,0.560763,0.120825,0.139613,3.000355e-13,f1_macro,0.143612,0.019608,NaN,shuffle_training_X_only
10,YFN,10,420,5944,5944,1189,0.206897,0.155044,0.143522,0.206897,0.571555,0.120825,0.139613,3.208899e-17,f1_macro,0.143522,0.019608,NaN,shuffle_training_X_only
11,YFN,11,462,5944,5944,1189,0.178301,0.134521,0.126804,0.178301,0.558996,0.120825,0.139613,5.829677e-09,f1_macro,0.126804,0.019608,NaN,shuffle_training_X_only
12,YFN,12,504,5944,5944,1189,0.175778,0.132676,0.126266,0.175778,0.558440,0.120825,0.139613,2.313476e-08,f1_macro,0.126266,0.019608,NaN,shuffle_training_X_only
13,YFN,13,546,5944,5944,1189,0.178301,0.134543,0.125888,0.178301,0.542364,0.120825,0.139613,5.829677e-09,f1_macro,0.125888,0.019608,NaN,shuffle_training_X_only
14,YFN,14,588,5944,5944,1189,0.171573,0.130253,0.124988,0.171573,0.568652,0.120825,0.139613,2.056384e-07,f1_macro,0.124988,0.019608,NaN,shuffle_training_X_only
15,YFN,15,630,5944,5944,1189,0.170732,0.129375,0.122382,0.170732,0.564451,0.120825,0.139613,3.129522e-07,f1_macro,0.122382,0.019608,NaN,shuffle_training_X_only
16,YFN,16,672,5944,5944,1189,0.186712,0.143882,0.139228,0.186712,0.566048,0.120825,0.139613,4.113767e-11,f1_macro,0.139228,0.019608,NaN,shuffle_training_X_only
17,YFN,17,714,5944,5944,1189,0.181665,0.140632,0.137305,0.181665,0.560597,0.120825,0.139613,8.583884e-10,f1_macro,0.137305,0.019608,NaN,shuffle_training_X_only
18,YFN,18,756,5944,5944,1189,0.195963,0.150666,0.144670,0.195963,0.570309,0.120825,0.139613,9.483333e-14,f1_macro,0.144670,0.019608,NaN,shuffle_training_X_only
19,YFN,19,798,5944,5944,1189,0.190076,0.142304,0.132769,0.190076,0.568971,0.120825,0.139613,4.870751e-12,f1_macro,0.132769,0.019608,NaN,shuffle_training_X_only

aggregated YFN 2025-04-02 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFN/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-04-02/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFN,0,0,8819,8819,1764,0.176304,0.137229,0.126218,0.176304,0.578067,0.116938,0.13322,1.866806e-13,f1_macro,0.126218,0.019608,0.132025,shuffle_training_X_only
1,YFN,1,42,8819,8819,1764,0.170068,0.134898,0.129200,0.170068,0.571390,0.116938,0.13322,3.151918e-11,f1_macro,0.129200,0.019608,0.135001,shuffle_training_X_only
2,YFN,2,84,8819,8819,1764,0.165533,0.133276,0.128572,0.165533,0.571092,0.116938,0.13322,9.760371e-10,f1_macro,0.128572,0.019608,0.139153,shuffle_training_X_only
3,YFN,3,126,8819,8819,1764,0.163832,0.130431,0.124716,0.163832,0.573806,0.116938,0.13322,3.311803e-09,f1_macro,0.124716,0.019608,NaN,shuffle_training_X_only
4,YFN,4,168,8819,8819,1764,0.170068,0.132891,0.124211,0.170068,0.573197,0.116938,0.13322,3.151918e-11,f1_macro,0.124211,0.019608,NaN,shuffle_training_X_only
5,YFN,5,210,8819,8819,1764,0.177438,0.141961,0.137997,0.177438,0.577618,0.116938,0.13322,6.988163e-14,f1_macro,0.137997,0.019608,NaN,shuffle_training_X_only
6,YFN,6,252,8819,8819,1764,0.184807,0.147892,0.141085,0.184807,0.571811,0.116938,0.13322,8.139582e-17,f1_macro,0.141085,0.019608,NaN,shuffle_training_X_only
7,YFN,7,294,8819,8819,1764,0.178005,0.140828,0.134127,0.178005,0.566695,0.116938,0.13322,4.251207e-14,f1_macro,0.134127,0.019608,NaN,shuffle_training_X_only
8,YFN,8,336,8819,8819,1764,0.184240,0.147998,0.142965,0.184240,0.582722,0.116938,0.13322,1.399655e-16,f1_macro,0.142965,0.019608,NaN,shuffle_training_X_only
9,YFN,9,378,8819,8819,1764,0.163832,0.128779,0.122416,0.163832,0.558997,0.116938,0.13322,3.311803e-09,f1_macro,0.122416,0.019608,NaN,shuffle_training_X_only
10,YFN,10,420,8819,8819,1764,0.172902,0.138394,0.133056,0.172902,0.574294,0.116938,0.13322,3.245784e-12,f1_macro,0.133056,0.019608,NaN,shuffle_training_X_only
11,YFN,11,462,8819,8819,1764,0.174036,0.139360,0.134428,0.174036,0.575054,0.116938,0.13322,1.272351e-12,f1_macro,0.134428,0.019608,NaN,shuffle_training_X_only
12,YFN,12,504,8819,8819,1764,0.170635,0.137115,0.131840,0.170635,0.571866,0.116938,0.13322,2.016106e-11,f1_macro,0.131840,0.019608,NaN,shuffle_training_X_only
13,YFN,13,546,8819,8819,1764,0.179138,0.143889,0.139758,0.179138,0.574914,0.116938,0.13322,1.555476e-14,f1_macro,0.139758,0.019608,NaN,shuffle_training_X_only
14,YFN,14,588,8819,8819,1764,0.153628,0.123156,0.119008,0.153628,0.571624,0.116938,0.13322,2.346164e-06,f1_macro,0.119008,0.019608,NaN,shuffle_training_X_only
15,YFN,15,630,8819,8819,1764,0.167800,0.134486,0.129860,0.167800,0.571070,0.116938,0.13322,1.810342e-10,f1_macro,0.129860,0.019608,NaN,shuffle_training_X_only
16,YFN,16,672,8819,8819,1764,0.170068,0.136952,0.132133,0.170068,0.577005,0.116938,0.13322,3.151918e-11,f1_macro,0.132133,0.019608,NaN,shuffle_training_X_only
17,YFN,17,714,8819,8819,1764,0.187075,0.148954,0.143118,0.187075,0.579704,0.116938,0.13322,8.971842e-18,f1_macro,0.143118,0.019608,NaN,shuffle_training_X_only
18,YFN,18,756,8819,8819,1764,0.178571,0.141920,0.135921,0.178571,0.577788,0.116938,0.13322,2.576387e-14,f1_macro,0.135921,0.019608,NaN,shuffle_training_X_only
19,YFN,19,798,8819,8819,1764,0.175737,0.140222,0.135299,0.175737,0.576278,0.116938,0.13322,3.033732e-13,f1_macro,0.135299,0.019608,NaN,shuffle_training_X_only

aggregated YFN 2025-04-03 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFN/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-04-03/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFN,0,0,10036,10036,2008,0.213147,0.158397,0.148987,0.213147,0.613252,0.123159,0.138446,1.000157e-29,f1_macro,0.148987,0.019608,0.142536,shuffle_training_X_only
1,YFN,1,42,10036,10036,2008,0.198705,0.145732,0.135946,0.198705,0.598852,0.123159,0.138446,5.972788e-22,f1_macro,0.135946,0.019608,0.146116,shuffle_training_X_only
2,YFN,2,84,10036,10036,2008,0.190737,0.141190,0.132833,0.190737,0.577782,0.123159,0.138446,3.862680e-18,f1_macro,0.132833,0.019608,0.147774,shuffle_training_X_only
3,YFN,3,126,10036,10036,2008,0.194721,0.145735,0.138985,0.194721,0.586114,0.123159,0.138446,5.309822e-20,f1_macro,0.138985,0.019608,NaN,shuffle_training_X_only
4,YFN,4,168,10036,10036,2008,0.202689,0.156701,0.155085,0.202689,0.600820,0.123159,0.138446,5.513150e-24,f1_macro,0.155085,0.019608,NaN,shuffle_training_X_only
5,YFN,5,210,10036,10036,2008,0.198705,0.147795,0.139634,0.198705,0.593821,0.123159,0.138446,5.972788e-22,f1_macro,0.139634,0.019608,NaN,shuffle_training_X_only
6,YFN,6,252,10036,10036,2008,0.182271,0.133405,0.123203,0.182271,0.589960,0.123159,0.138446,1.771147e-14,f1_macro,0.123203,0.019608,NaN,shuffle_training_X_only
7,YFN,7,294,10036,10036,2008,0.187749,0.141776,0.135174,0.187749,0.581158,0.123159,0.138446,8.420423e-17,f1_macro,0.135174,0.019608,NaN,shuffle_training_X_only
8,YFN,8,336,10036,10036,2008,0.199203,0.148527,0.141407,0.199203,0.583072,0.123159,0.138446,3.361256e-22,f1_macro,0.141407,0.019608,NaN,shuffle_training_X_only
9,YFN,9,378,10036,10036,2008,0.192729,0.144448,0.137157,0.192729,0.603481,0.123159,0.138446,4.644606e-19,f1_macro,0.137157,0.019608,NaN,shuffle_training_X_only
10,YFN,10,420,10036,10036,2008,0.204681,0.149908,0.139957,0.204681,0.602114,0.123159,0.138446,4.922417e-25,f1_macro,0.139957,0.019608,NaN,shuffle_training_X_only
11,YFN,11,462,10036,10036,2008,0.207669,0.154059,0.144559,0.207669,0.589082,0.123159,0.138446,1.199390e-26,f1_macro,0.144559,0.019608,NaN,shuffle_training_X_only
12,YFN,12,504,10036,10036,2008,0.190239,0.142660,0.137198,0.190239,0.617082,0.123159,0.138446,6.507719e-18,f1_macro,0.137198,0.019608,NaN,shuffle_training_X_only
13,YFN,13,546,10036,10036,2008,0.210657,0.157645,0.150902,0.210657,0.605544,0.123159,0.138446,2.623615e-28,f1_macro,0.150902,0.019608,NaN,shuffle_training_X_only
14,YFN,14,588,10036,10036,2008,0.205677,0.154417,0.147944,0.205677,0.593151,0.123159,0.138446,1.444351e-25,f1_macro,0.147944,0.019608,NaN,shuffle_training_X_only
15,YFN,15,630,10036,10036,2008,0.198207,0.147184,0.139510,0.198207,0.605855,0.123159,0.138446,1.058061e-21,f1_macro,0.139510,0.019608,NaN,shuffle_training_X_only
16,YFN,16,672,10036,10036,2008,0.207171,0.155683,0.149529,0.207171,0.603672,0.123159,0.138446,2.244376e-26,f1_macro,0.149529,0.019608,NaN,shuffle_training_X_only
17,YFN,17,714,10036,10036,2008,0.205677,0.153681,0.144071,0.205677,0.587277,0.123159,0.138446,1.444351e-25,f1_macro,0.144071,0.019608,NaN,shuffle_training_X_only
18,YFN,18,756,10036,10036,2008,0.198207,0.148233,0.141279,0.198207,0.580447,0.123159,0.138446,1.058061e-21,f1_macro,0.141279,0.019608,NaN,shuffle_training_X_only
19,YFN,19,798,10036,10036,2008,0.212151,0.156287,0.146516,0.212151,0.590138,0.123159,0.138446,3.727771e-29,f1_macro,0.146516,0.019608,NaN,shuffle_training_X_only

aggregated YFN 2025-04-04 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFN/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-04-04/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFN,0,0,7223,7223,1445,0.177163,0.140278,0.133503,0.177163,0.580814,0.116759,0.132872,1.168588e-11,f1_macro,0.133503,0.019608,0.136824,shuffle_training_X_only
1,YFN,1,42,7223,7223,1445,0.182007,0.142881,0.134556,0.182007,0.568228,0.116759,0.132872,3.230526e-13,f1_macro,0.134556,0.019608,0.133465,shuffle_training_X_only
2,YFN,2,84,7223,7223,1445,0.172318,0.138945,0.134725,0.172318,0.563287,0.116759,0.132872,3.368107e-10,f1_macro,0.134725,0.019608,0.132171,shuffle_training_X_only
3,YFN,3,126,7223,7223,1445,0.152249,0.118573,0.111700,0.152249,0.556573,0.116759,0.132872,3.043793e-05,f1_macro,0.111700,0.039216,NaN,shuffle_training_X_only
4,YFN,4,168,7223,7223,1445,0.164706,0.131784,0.127716,0.164706,0.567191,0.116759,0.132872,4.144570e-08,f1_macro,0.127716,0.019608,NaN,shuffle_training_X_only
5,YFN,5,210,7223,7223,1445,0.161938,0.127825,0.122300,0.161938,0.564273,0.116759,0.132872,2.063336e-07,f1_macro,0.122300,0.019608,NaN,shuffle_training_X_only
6,YFN,6,252,7223,7223,1445,0.159170,0.125831,0.120649,0.159170,0.551633,0.116759,0.132872,9.495918e-07,f1_macro,0.120649,0.019608,NaN,shuffle_training_X_only
7,YFN,7,294,7223,7223,1445,0.170934,0.135275,0.128987,0.170934,0.566381,0.116759,0.132872,8.434762e-10,f1_macro,0.128987,0.019608,NaN,shuffle_training_X_only
8,YFN,8,336,7223,7223,1445,0.168166,0.134649,0.129828,0.168166,0.569698,0.116759,0.132872,4.996461e-09,f1_macro,0.129828,0.019608,NaN,shuffle_training_X_only
9,YFN,9,378,7223,7223,1445,0.171626,0.135511,0.130013,0.171626,0.568308,0.116759,0.132872,5.342660e-10,f1_macro,0.130013,0.019608,NaN,shuffle_training_X_only
10,YFN,10,420,7223,7223,1445,0.194464,0.157611,0.152759,0.194464,0.575696,0.116759,0.132872,1.151510e-17,f1_macro,0.152759,0.019608,NaN,shuffle_training_X_only
11,YFN,11,462,7223,7223,1445,0.189619,0.150516,0.143537,0.189619,0.580992,0.116759,0.132872,7.333453e-16,f1_macro,0.143537,0.019608,NaN,shuffle_training_X_only
12,YFN,12,504,7223,7223,1445,0.148789,0.118621,0.114986,0.148789,0.552178,0.116759,0.132872,1.425468e-04,f1_macro,0.114986,0.039216,NaN,shuffle_training_X_only
13,YFN,13,546,7223,7223,1445,0.161938,0.130657,0.126844,0.161938,0.562217,0.116759,0.132872,2.063336e-07,f1_macro,0.126844,0.019608,NaN,shuffle_training_X_only
14,YFN,14,588,7223,7223,1445,0.174394,0.141598,0.138805,0.174394,0.576295,0.116759,0.132872,8.203280e-11,f1_macro,0.138805,0.019608,NaN,shuffle_training_X_only
15,YFN,15,630,7223,7223,1445,0.168166,0.132234,0.125791,0.168166,0.579130,0.116759,0.132872,4.996461e-09,f1_macro,0.125791,0.019608,NaN,shuffle_training_X_only
16,YFN,16,672,7223,7223,1445,0.184775,0.149155,0.145133,0.184775,0.558808,0.116759,0.132872,3.759730e-14,f1_macro,0.145133,0.019608,NaN,shuffle_training_X_only
17,YFN,17,714,7223,7223,1445,0.160554,0.132072,0.131745,0.160554,0.565042,0.116759,0.132872,4.470341e-07,f1_macro,0.131745,0.019608,NaN,shuffle_training_X_only
18,YFN,18,756,7223,7223,1445,0.173702,0.140488,0.136557,0.173702,0.562732,0.116759,0.132872,1.319762e-10,f1_macro,0.136557,0.019608,NaN,shuffle_training_X_only
19,YFN,19,798,7223,7223,1445,0.173702,0.139544,0.135449,0.173702,0.570513,0.116759,0.132872,1.319762e-10,f1_macro,0.135449,0.019608,NaN,shuffle_training_X_only

aggregated YFN 2025-04-05 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFN/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-04-05/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFN,0,0,6365,6365,1273,0.184603,0.137665,0.127967,0.184603,0.582895,0.120999,0.139042,4.036304e-11,f1_macro,0.127967,0.019608,0.134786,shuffle_training_X_only
1,YFN,1,42,6365,6365,1273,0.177533,0.134067,0.123258,0.177533,0.590758,0.120999,0.139042,3.138497e-09,f1_macro,0.123258,0.019608,0.135509,shuffle_training_X_only
2,YFN,2,84,6365,6365,1273,0.192459,0.146342,0.138844,0.192459,0.566467,0.120999,0.139042,1.973886e-13,f1_macro,0.138844,0.019608,0.133248,shuffle_training_X_only
3,YFN,3,126,6365,6365,1273,0.172820,0.134427,0.131612,0.172820,0.573724,0.120999,0.139042,4.523486e-08,f1_macro,0.131612,0.019608,NaN,shuffle_training_X_only
4,YFN,4,168,6365,6365,1273,0.167321,0.126746,0.120000,0.167321,0.580682,0.120999,0.139042,7.986493e-07,f1_macro,0.120000,0.019608,NaN,shuffle_training_X_only
5,YFN,5,210,6365,6365,1273,0.161822,0.120534,0.112146,0.161822,0.557798,0.120999,0.139042,1.081672e-05,f1_macro,0.112146,0.019608,NaN,shuffle_training_X_only
6,YFN,6,252,6365,6365,1273,0.187745,0.142393,0.135343,0.187745,0.578319,0.120999,0.139042,5.103951e-12,f1_macro,0.135343,0.019608,NaN,shuffle_training_X_only
7,YFN,7,294,6365,6365,1273,0.186174,0.142160,0.137231,0.186174,0.568942,0.120999,0.139042,1.449913e-11,f1_macro,0.137231,0.019608,NaN,shuffle_training_X_only
8,YFN,8,336,6365,6365,1273,0.194030,0.147237,0.140410,0.194030,0.570206,0.120999,0.139042,6.414960e-14,f1_macro,0.140410,0.019608,NaN,shuffle_training_X_only
9,YFN,9,378,6365,6365,1273,0.164179,0.124454,0.119179,0.164179,0.564062,0.120999,0.139042,3.658485e-06,f1_macro,0.119179,0.019608,NaN,shuffle_training_X_only
10,YFN,10,420,6365,6365,1273,0.200314,0.156416,0.152828,0.200314,0.576433,0.120999,0.139042,5.882927e-16,f1_macro,0.152828,0.019608,NaN,shuffle_training_X_only
11,YFN,11,462,6365,6365,1273,0.201885,0.155136,0.149409,0.201885,0.588171,0.120999,0.139042,1.734398e-16,f1_macro,0.149409,0.019608,NaN,shuffle_training_X_only
12,YFN,12,504,6365,6365,1273,0.192459,0.147035,0.140845,0.192459,0.581217,0.120999,0.139042,1.973886e-13,f1_macro,0.140845,0.019608,NaN,shuffle_training_X_only
13,YFN,13,546,6365,6365,1273,0.168892,0.128552,0.123061,0.168892,0.549878,0.120999,0.139042,3.612091e-07,f1_macro,0.123061,0.019608,NaN,shuffle_training_X_only
14,YFN,14,588,6365,6365,1273,0.166536,0.130292,0.128451,0.166536,0.554116,0.120999,0.139042,1.177967e-06,f1_macro,0.128451,0.019608,NaN,shuffle_training_X_only
15,YFN,15,630,6365,6365,1273,0.175962,0.134144,0.129599,0.175962,0.557187,0.120999,0.139042,7.800255e-09,f1_macro,0.129599,0.019608,NaN,shuffle_training_X_only
16,YFN,16,672,6365,6365,1273,0.183818,0.141685,0.137402,0.183818,0.570754,0.120999,0.139042,6.683313e-11,f1_macro,0.137402,0.019608,NaN,shuffle_training_X_only
17,YFN,17,714,6365,6365,1273,0.167321,0.126366,0.120805,0.167321,0.553158,0.120999,0.139042,7.986493e-07,f1_macro,0.120805,0.019608,NaN,shuffle_training_X_only
18,YFN,18,756,6365,6365,1273,0.168107,0.127579,0.121813,0.168107,0.565822,0.120999,0.139042,5.385539e-07,f1_macro,0.121813,0.019608,NaN,shuffle_training_X_only
19,YFN,19,798,6365,6365,1273,0.189317,0.144371,0.136975,0.189317,0.565186,0.120999,0.139042,1.760864e-12,f1_macro,0.136975,0.019608,NaN,shuffle_training_X_only

aggregated YFN 2025-04-06 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFN/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-04-06/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFN,0,0,6501,6501,1301,0.186011,0.132016,0.121659,0.186011,0.564763,0.125592,0.14143,3.353403e-10,f1_macro,0.121659,0.019608,0.129771,shuffle_training_X_only
1,YFN,1,42,6501,6501,1301,0.173713,0.123339,0.113756,0.173713,0.553125,0.125592,0.14143,3.474692e-07,f1_macro,0.113756,0.019608,0.128311,shuffle_training_X_only
2,YFN,2,84,6501,6501,1301,0.185242,0.132825,0.125191,0.185242,0.566458,0.125592,0.14143,5.373857e-10,f1_macro,0.125191,0.019608,0.127341,shuffle_training_X_only
3,YFN,3,126,6501,6501,1301,0.195234,0.140661,0.133010,0.195234,0.581241,0.125592,0.14143,7.981839e-13,f1_macro,0.133010,0.019608,NaN,shuffle_training_X_only
4,YFN,4,168,6501,6501,1301,0.198309,0.142284,0.133684,0.198309,0.564854,0.125592,0.14143,9.133336e-14,f1_macro,0.133684,0.019608,NaN,shuffle_training_X_only
5,YFN,5,210,6501,6501,1301,0.168332,0.122973,0.118146,0.168332,0.550340,0.125592,0.14143,4.802429e-06,f1_macro,0.118146,0.039216,NaN,shuffle_training_X_only
6,YFN,6,252,6501,6501,1301,0.194466,0.142547,0.137332,0.194466,0.574651,0.125592,0.14143,1.356082e-12,f1_macro,0.137332,0.019608,NaN,shuffle_training_X_only
7,YFN,7,294,6501,6501,1301,0.176018,0.129434,0.124774,0.176018,0.563232,0.125592,0.14143,1.043379e-07,f1_macro,0.124774,0.019608,NaN,shuffle_training_X_only
8,YFN,8,336,6501,6501,1301,0.188317,0.134907,0.126643,0.188317,0.562289,0.125592,0.14143,7.911014e-11,f1_macro,0.126643,0.019608,NaN,shuffle_training_X_only
9,YFN,9,378,6501,6501,1301,0.192160,0.137716,0.129573,0.192160,0.558427,0.125592,0.14143,6.461052e-12,f1_macro,0.129573,0.019608,NaN,shuffle_training_X_only
10,YFN,10,420,6501,6501,1301,0.177556,0.127244,0.119192,0.177556,0.565212,0.125592,0.14143,4.560541e-08,f1_macro,0.119192,0.019608,NaN,shuffle_training_X_only
11,YFN,11,462,6501,6501,1301,0.192160,0.138688,0.130795,0.192160,0.567487,0.125592,0.14143,6.461052e-12,f1_macro,0.130795,0.019608,NaN,shuffle_training_X_only
12,YFN,12,504,6501,6501,1301,0.188317,0.138473,0.131853,0.188317,0.560798,0.125592,0.14143,7.911014e-11,f1_macro,0.131853,0.019608,NaN,shuffle_training_X_only
13,YFN,13,546,6501,6501,1301,0.192160,0.138450,0.130164,0.192160,0.558735,0.125592,0.14143,6.461052e-12,f1_macro,0.130164,0.019608,NaN,shuffle_training_X_only
14,YFN,14,588,6501,6501,1301,0.196772,0.142018,0.133674,0.196772,0.556671,0.125592,0.14143,2.725862e-13,f1_macro,0.133674,0.019608,NaN,shuffle_training_X_only
15,YFN,15,630,6501,6501,1301,0.196772,0.147341,0.143450,0.196772,0.555738,0.125592,0.14143,2.725862e-13,f1_macro,0.143450,0.019608,NaN,shuffle_training_X_only
16,YFN,16,672,6501,6501,1301,0.179093,0.128386,0.119029,0.179093,0.558257,0.125592,0.14143,1.953242e-08,f1_macro,0.119029,0.019608,NaN,shuffle_training_X_only
17,YFN,17,714,6501,6501,1301,0.176018,0.127125,0.119707,0.176018,0.553722,0.125592,0.14143,1.043379e-07,f1_macro,0.119707,0.019608,NaN,shuffle_training_X_only
18,YFN,18,756,6501,6501,1301,0.184473,0.130984,0.121454,0.184473,0.567760,0.125592,0.14143,8.569094e-10,f1_macro,0.121454,0.019608,NaN,shuffle_training_X_only
19,YFN,19,798,6501,6501,1301,0.192929,0.138168,0.129069,0.192929,0.561854,0.125592,0.14143,3.858260e-12,f1_macro,0.129069,0.019608,NaN,shuffle_training_X_only

aggregated YFP 2025-05-06 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFP/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-05-06/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFP,0,0,2232,2232,447,0.178971,0.140549,0.137643,0.178971,0.627166,0.122702,0.143177,3.651289e-04,f1_macro,0.137643,0.019608,0.144216,shuffle_training_X_only
1,YFP,1,42,2232,2232,447,0.208054,0.158658,0.151341,0.208054,0.600949,0.122702,0.143177,2.476947e-07,f1_macro,0.151341,0.019608,0.142891,shuffle_training_X_only
2,YFP,2,84,2232,2232,447,0.174497,0.135968,0.132490,0.174497,0.563713,0.122702,0.143177,9.114711e-04,f1_macro,0.132490,0.019608,0.145419,shuffle_training_X_only
3,YFP,3,126,2232,2232,447,0.165548,0.126318,0.124867,0.165548,0.547283,0.122702,0.143177,4.780453e-03,f1_macro,0.124867,0.019608,NaN,shuffle_training_X_only
4,YFP,4,168,2232,2232,447,0.217002,0.167572,0.163551,0.217002,0.625932,0.122702,0.143177,1.669448e-08,f1_macro,0.163551,0.019608,NaN,shuffle_training_X_only
5,YFP,5,210,2232,2232,447,0.201342,0.144750,0.133001,0.201342,0.610378,0.122702,0.143177,1.633247e-06,f1_macro,0.133001,0.019608,NaN,shuffle_training_X_only
6,YFP,6,252,2232,2232,447,0.167785,0.129212,0.124759,0.167785,0.582150,0.122702,0.143177,3.228322e-03,f1_macro,0.124759,0.039216,NaN,shuffle_training_X_only
7,YFP,7,294,2232,2232,447,0.201342,0.149028,0.134185,0.201342,0.586640,0.122702,0.143177,1.633247e-06,f1_macro,0.134185,0.019608,NaN,shuffle_training_X_only
8,YFP,8,336,2232,2232,447,0.234899,0.183887,0.185646,0.234899,0.617169,0.122702,0.143177,4.137565e-11,f1_macro,0.185646,0.019608,NaN,shuffle_training_X_only
9,YFP,9,378,2232,2232,447,0.192394,0.138881,0.129031,0.192394,0.581034,0.122702,0.143177,1.675725e-05,f1_macro,0.129031,0.039216,NaN,shuffle_training_X_only
10,YFP,10,420,2232,2232,447,0.176734,0.134949,0.129692,0.176734,0.582532,0.122702,0.143177,5.810131e-04,f1_macro,0.129692,0.019608,NaN,shuffle_training_X_only
11,YFP,11,462,2232,2232,447,0.199105,0.150571,0.145017,0.199105,0.595194,0.122702,0.143177,2.982602e-06,f1_macro,0.145017,0.019608,NaN,shuffle_training_X_only
12,YFP,12,504,2232,2232,447,0.210291,0.155606,0.147701,0.210291,0.623792,0.122702,0.143177,1.286741e-07,f1_macro,0.147701,0.019608,NaN,shuffle_training_X_only
13,YFP,13,546,2232,2232,447,0.161074,0.118939,0.114388,0.161074,0.579699,0.122702,0.143177,1.003232e-02,f1_macro,0.114388,0.039216,NaN,shuffle_training_X_only
14,YFP,14,588,2232,2232,447,0.192394,0.141263,0.131162,0.192394,0.577043,0.122702,0.143177,1.675725e-05,f1_macro,0.131162,0.019608,NaN,shuffle_training_X_only
15,YFP,15,630,2232,2232,447,0.194631,0.143195,0.135047,0.194631,0.613776,0.122702,0.143177,9.554500e-06,f1_macro,0.135047,0.019608,NaN,shuffle_training_X_only
16,YFP,16,672,2232,2232,447,0.183445,0.134906,0.127936,0.183445,0.580308,0.122702,0.143177,1.382171e-04,f1_macro,0.127936,0.019608,NaN,shuffle_training_X_only
17,YFP,17,714,2232,2232,447,0.156600,0.120812,0.116432,0.156600,0.591917,0.122702,0.143177,1.985053e-02,f1_macro,0.116432,0.019608,NaN,shuffle_training_X_only
18,YFP,18,756,2232,2232,447,0.187919,0.137789,0.130212,0.187919,0.608585,0.122702,0.143177,4.947448e-05,f1_macro,0.130212,0.019608,NaN,shuffle_training_X_only
19,YFP,19,798,2232,2232,447,0.172260,0.133562,0.130063,0.172260,0.552288,0.122702,0.143177,1.409557e-03,f1_macro,0.130063,0.039216,NaN,shuffle_training_X_only

aggregated YFP 2025-05-07 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFP/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-05-07/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFP,0,0,8127,8127,1626,0.204182,0.152071,0.145475,0.204182,0.599239,0.123567,0.144526,3.492320e-20,f1_macro,0.145475,0.019608,0.141937,shuffle_training_X_only
1,YFP,1,42,8127,8127,1626,0.204797,0.149469,0.140535,0.204797,0.580565,0.123567,0.144526,1.904821e-20,f1_macro,0.140535,0.019608,0.139962,shuffle_training_X_only
2,YFP,2,84,8127,8127,1626,0.194957,0.142629,0.135127,0.194957,0.575170,0.123567,0.144526,1.974690e-16,f1_macro,0.135127,0.019608,0.138021,shuffle_training_X_only
3,YFP,3,126,8127,8127,1626,0.206027,0.150499,0.142159,0.206027,0.594579,0.123567,0.144526,5.603803e-21,f1_macro,0.142159,0.019608,NaN,shuffle_training_X_only
4,YFP,4,168,8127,8127,1626,0.199877,0.147807,0.139573,0.199877,0.588481,0.123567,0.144526,2.189457e-18,f1_macro,0.139573,0.019608,NaN,shuffle_training_X_only
5,YFP,5,210,8127,8127,1626,0.207257,0.154733,0.147916,0.207257,0.581774,0.123567,0.144526,1.624294e-21,f1_macro,0.147916,0.019608,NaN,shuffle_training_X_only
6,YFP,6,252,8127,8127,1626,0.205412,0.146666,0.133363,0.205412,0.578566,0.123567,0.144526,1.035085e-20,f1_macro,0.133363,0.019608,NaN,shuffle_training_X_only
7,YFP,7,294,8127,8127,1626,0.196187,0.140969,0.131051,0.196187,0.582541,0.123567,0.144526,6.556618e-17,f1_macro,0.131051,0.019608,NaN,shuffle_training_X_only
8,YFP,8,336,8127,8127,1626,0.185732,0.136401,0.129365,0.185732,0.578024,0.123567,0.144526,4.690411e-13,f1_macro,0.129365,0.019608,NaN,shuffle_training_X_only
9,YFP,9,378,8127,8127,1626,0.207872,0.151563,0.142694,0.207872,0.588732,0.123567,0.144526,8.696533e-22,f1_macro,0.142694,0.019608,NaN,shuffle_training_X_only
10,YFP,10,420,8127,8127,1626,0.214022,0.161118,0.155400,0.214022,0.600295,0.123567,0.144526,1.375896e-24,f1_macro,0.155400,0.019608,NaN,shuffle_training_X_only
11,YFP,11,462,8127,8127,1626,0.201722,0.150449,0.144130,0.201722,0.578167,0.123567,0.144526,3.801043e-19,f1_macro,0.144130,0.019608,NaN,shuffle_training_X_only
12,YFP,12,504,8127,8127,1626,0.180812,0.132762,0.124746,0.180812,0.583786,0.123567,0.144526,2.057191e-11,f1_macro,0.124746,0.019608,NaN,shuffle_training_X_only
13,YFP,13,546,8127,8127,1626,0.213407,0.154242,0.143945,0.213407,0.587930,0.123567,0.144526,2.665505e-24,f1_macro,0.143945,0.019608,NaN,shuffle_training_X_only
14,YFP,14,588,8127,8127,1626,0.215252,0.159672,0.152478,0.215252,0.595849,0.123567,0.144526,3.626524e-25,f1_macro,0.152478,0.019608,NaN,shuffle_training_X_only
15,YFP,15,630,8127,8127,1626,0.218942,0.165500,0.160544,0.218942,0.584447,0.123567,0.144526,6.092034e-27,f1_macro,0.160544,0.019608,NaN,shuffle_training_X_only
16,YFP,16,672,8127,8127,1626,0.211562,0.152115,0.141972,0.211562,0.595703,0.123567,0.144526,1.896305e-23,f1_macro,0.141972,0.019608,NaN,shuffle_training_X_only
17,YFP,17,714,8127,8127,1626,0.194957,0.140815,0.130570,0.194957,0.590470,0.123567,0.144526,1.974690e-16,f1_macro,0.130570,0.019608,NaN,shuffle_training_X_only
18,YFP,18,756,8127,8127,1626,0.228782,0.167680,0.157002,0.228782,0.592510,0.123567,0.144526,6.049538e-32,f1_macro,0.157002,0.019608,NaN,shuffle_training_X_only
19,YFP,19,798,8127,8127,1626,0.199262,0.146364,0.138168,0.199262,0.596660,0.123567,0.144526,3.895183e-18,f1_macro,0.138168,0.019608,NaN,shuffle_training_X_only

aggregated YFP 2025-05-08 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFP/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-05-08/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFP,0,0,5869,5869,1174,0.206133,0.166180,0.161688,0.206133,0.593771,0.117293,0.134583,2.769213e-18,f1_macro,0.161688,0.019608,0.145615,shuffle_training_X_only
1,YFP,1,42,5869,5869,1174,0.170358,0.141642,0.140435,0.170358,0.587944,0.117293,0.134583,5.482943e-08,f1_macro,0.140435,0.019608,0.145266,shuffle_training_X_only
2,YFP,2,84,5869,5869,1174,0.195911,0.160879,0.160159,0.195911,0.593963,0.117293,0.134583,6.411194e-15,f1_macro,0.160159,0.019608,0.145917,shuffle_training_X_only
3,YFP,3,126,5869,5869,1174,0.210392,0.164653,0.154697,0.210392,0.589070,0.117293,0.134583,8.814202e-20,f1_macro,0.154697,0.019608,NaN,shuffle_training_X_only
4,YFP,4,168,5869,5869,1174,0.187394,0.147514,0.140694,0.187394,0.582107,0.117293,0.134583,2.278577e-12,f1_macro,0.140694,0.019608,NaN,shuffle_training_X_only
5,YFP,5,210,5869,5869,1174,0.199319,0.156106,0.145446,0.199319,0.576432,0.117293,0.134583,5.268922e-16,f1_macro,0.145446,0.019608,NaN,shuffle_training_X_only
6,YFP,6,252,5869,5869,1174,0.183135,0.143253,0.135880,0.183135,0.590943,0.117293,0.134583,3.502660e-11,f1_macro,0.135880,0.019608,NaN,shuffle_training_X_only
7,YFP,7,294,5869,5869,1174,0.192504,0.152770,0.145785,0.192504,0.591412,0.117293,0.134583,7.165991e-14,f1_macro,0.145785,0.019608,NaN,shuffle_training_X_only
8,YFP,8,336,5869,5869,1174,0.177172,0.144654,0.140461,0.177172,0.592066,0.117293,0.134583,1.271483e-09,f1_macro,0.140461,0.019608,NaN,shuffle_training_X_only
9,YFP,9,378,5869,5869,1174,0.183135,0.146509,0.140641,0.183135,0.586347,0.117293,0.134583,3.502660e-11,f1_macro,0.140641,0.019608,NaN,shuffle_training_X_only
10,YFP,10,420,5869,5869,1174,0.202726,0.159706,0.152847,0.202726,0.613920,0.117293,0.134583,3.981574e-17,f1_macro,0.152847,0.019608,NaN,shuffle_training_X_only
11,YFP,11,462,5869,5869,1174,0.160136,0.125888,0.121159,0.160136,0.583062,0.117293,0.134583,7.701765e-06,f1_macro,0.121159,0.019608,NaN,shuffle_training_X_only
12,YFP,12,504,5869,5869,1174,0.202726,0.159262,0.151150,0.202726,0.583773,0.117293,0.134583,3.981574e-17,f1_macro,0.151150,0.019608,NaN,shuffle_training_X_only
13,YFP,13,546,5869,5869,1174,0.179727,0.144502,0.139342,0.179727,0.602211,0.117293,0.134583,2.821069e-10,f1_macro,0.139342,0.019608,NaN,shuffle_training_X_only
14,YFP,14,588,5869,5869,1174,0.184838,0.143877,0.136596,0.184838,0.592289,0.117293,0.134583,1.193681e-11,f1_macro,0.136596,0.019608,NaN,shuffle_training_X_only
15,YFP,15,630,5869,5869,1174,0.171210,0.136742,0.131515,0.171210,0.583545,0.117293,0.134583,3.494929e-08,f1_macro,0.131515,0.019608,NaN,shuffle_training_X_only
16,YFP,16,672,5869,5869,1174,0.197615,0.157060,0.150554,0.197615,0.603359,0.117293,0.134583,1.857433e-15,f1_macro,0.150554,0.019608,NaN,shuffle_training_X_only
17,YFP,17,714,5869,5869,1174,0.162692,0.129242,0.124467,0.162692,0.587421,0.117293,0.134583,2.424068e-06,f1_macro,0.124467,0.019608,NaN,shuffle_training_X_only
18,YFP,18,756,5869,5869,1174,0.197615,0.158412,0.154028,0.197615,0.595635,0.117293,0.134583,1.857433e-15,f1_macro,0.154028,0.019608,NaN,shuffle_training_X_only
19,YFP,19,798,5869,5869,1174,0.174617,0.137038,0.129158,0.174617,0.595782,0.117293,0.134583,5.445318e-09,f1_macro,0.129158,0.019608,NaN,shuffle_training_X_only

aggregated YFP 2025-05-09 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFP/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-05-09/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFP,0,0,8206,8206,1642,0.157125,0.129864,0.127432,0.157125,0.572037,0.113641,0.130938,7.202235e-08,f1_macro,0.127432,0.019608,0.139938,shuffle_training_X_only
1,YFP,1,42,8206,8206,1642,0.162607,0.129365,0.120320,0.162607,0.571753,0.113641,0.130938,1.879896e-09,f1_macro,0.120320,0.019608,0.133561,shuffle_training_X_only
2,YFP,2,84,8206,8206,1642,0.165652,0.135554,0.131153,0.165652,0.573835,0.113641,0.130938,2.129425e-10,f1_macro,0.131153,0.019608,0.134038,shuffle_training_X_only
3,YFP,3,126,8206,8206,1642,0.171742,0.143491,0.140335,0.171742,0.576813,0.113641,0.130938,1.982963e-12,f1_macro,0.140335,0.019608,NaN,shuffle_training_X_only
4,YFP,4,168,8206,8206,1642,0.161998,0.132089,0.126372,0.161998,0.563920,0.113641,0.130938,2.868580e-09,f1_macro,0.126372,0.019608,NaN,shuffle_training_X_only
5,YFP,5,210,8206,8206,1642,0.185749,0.151834,0.145891,0.185749,0.579610,0.113641,0.130938,8.769877e-18,f1_macro,0.145891,0.019608,NaN,shuffle_training_X_only
6,YFP,6,252,8206,8206,1642,0.149817,0.121070,0.115114,0.149817,0.564962,0.113641,0.130938,5.310097e-06,f1_macro,0.115114,0.058824,NaN,shuffle_training_X_only
7,YFP,7,294,8206,8206,1642,0.155907,0.127183,0.121227,0.155907,0.565897,0.113641,0.130938,1.542519e-07,f1_macro,0.121227,0.019608,NaN,shuffle_training_X_only
8,YFP,8,336,8206,8206,1642,0.174178,0.142691,0.137228,0.174178,0.574941,0.113641,0.130938,2.714953e-13,f1_macro,0.137228,0.019608,NaN,shuffle_training_X_only
9,YFP,9,378,8206,8206,1642,0.178441,0.148611,0.144471,0.178441,0.580648,0.113641,0.130938,7.134571e-15,f1_macro,0.144471,0.019608,NaN,shuffle_training_X_only
10,YFP,10,420,8206,8206,1642,0.158343,0.131853,0.127840,0.158343,0.571638,0.113641,0.130938,3.303639e-08,f1_macro,0.127840,0.019608,NaN,shuffle_training_X_only
11,YFP,11,462,8206,8206,1642,0.160780,0.134395,0.131622,0.160780,0.569407,0.113641,0.130938,6.592582e-09,f1_macro,0.131622,0.019608,NaN,shuffle_training_X_only
12,YFP,12,504,8206,8206,1642,0.166261,0.139011,0.134786,0.166261,0.581553,0.113641,0.130938,1.359813e-10,f1_macro,0.134786,0.019608,NaN,shuffle_training_X_only
13,YFP,13,546,8206,8206,1642,0.154689,0.125038,0.119148,0.154689,0.571917,0.113641,0.130938,3.245232e-07,f1_macro,0.119148,0.019608,NaN,shuffle_training_X_only
14,YFP,14,588,8206,8206,1642,0.177832,0.146276,0.141050,0.177832,0.576708,0.113641,0.130938,1.214747e-14,f1_macro,0.141050,0.019608,NaN,shuffle_training_X_only
15,YFP,15,630,8206,8206,1642,0.168088,0.134623,0.125361,0.168088,0.575039,0.113641,0.130938,3.451383e-11,f1_macro,0.125361,0.019608,NaN,shuffle_training_X_only
16,YFP,16,672,8206,8206,1642,0.167479,0.135020,0.126531,0.167479,0.583242,0.113641,0.130938,5.474443e-11,f1_macro,0.126531,0.019608,NaN,shuffle_training_X_only
17,YFP,17,714,8206,8206,1642,0.165652,0.134186,0.127762,0.165652,0.564279,0.113641,0.130938,2.129425e-10,f1_macro,0.127762,0.019608,NaN,shuffle_training_X_only
18,YFP,18,756,8206,8206,1642,0.160171,0.134570,0.132929,0.160171,0.569174,0.113641,0.130938,9.928913e-09,f1_macro,0.132929,0.019608,NaN,shuffle_training_X_only
19,YFP,19,798,8206,8206,1642,0.172351,0.140858,0.135459,0.172351,0.582013,0.113641,0.130938,1.213790e-12,f1_macro,0.135459,0.019608,NaN,shuffle_training_X_only

aggregated YFP 2025-05-10 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFP/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-05-10/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFP,0,0,5422,5422,1085,0.187097,0.148854,0.148730,0.187097,0.575134,0.120214,0.140092,1.454064e-10,f1_macro,0.148730,0.019608,0.133436,shuffle_training_X_only
1,YFP,1,42,5422,5422,1085,0.184332,0.137796,0.126951,0.184332,0.566855,0.120214,0.140092,6.977346e-10,f1_macro,0.126951,0.019608,0.131814,shuffle_training_X_only
2,YFP,2,84,5422,5422,1085,0.167742,0.132319,0.128909,0.167742,0.558373,0.120214,0.140092,2.711592e-06,f1_macro,0.128909,0.019608,0.134994,shuffle_training_X_only
3,YFP,3,126,5422,5422,1085,0.181567,0.139898,0.134030,0.181567,0.571266,0.120214,0.140092,3.173257e-09,f1_macro,0.134030,0.019608,NaN,shuffle_training_X_only
4,YFP,4,168,5422,5422,1085,0.174194,0.133282,0.126259,0.174194,0.569760,0.120214,0.140092,1.380642e-07,f1_macro,0.126259,0.019608,NaN,shuffle_training_X_only
5,YFP,5,210,5422,5422,1085,0.187097,0.147360,0.144933,0.187097,0.571435,0.120214,0.140092,1.454064e-10,f1_macro,0.144933,0.019608,NaN,shuffle_training_X_only
6,YFP,6,252,5422,5422,1085,0.176037,0.134271,0.127538,0.176037,0.577928,0.120214,0.140092,5.576391e-08,f1_macro,0.127538,0.019608,NaN,shuffle_training_X_only
7,YFP,7,294,5422,5422,1085,0.194470,0.153477,0.150937,0.194470,0.570975,0.120214,0.140092,1.714415e-12,f1_macro,0.150937,0.019608,NaN,shuffle_training_X_only
8,YFP,8,336,5422,5422,1085,0.160369,0.123155,0.118112,0.160369,0.570604,0.120214,0.140092,5.578369e-05,f1_macro,0.118112,0.019608,NaN,shuffle_training_X_only
9,YFP,9,378,5422,5422,1085,0.176959,0.136709,0.132899,0.176959,0.555534,0.120214,0.140092,3.511470e-08,f1_macro,0.132899,0.019608,NaN,shuffle_training_X_only
10,YFP,10,420,5422,5422,1085,0.186175,0.142847,0.137157,0.186175,0.569319,0.120214,0.140092,2.467137e-10,f1_macro,0.137157,0.019608,NaN,shuffle_training_X_only
11,YFP,11,462,5422,5422,1085,0.175115,0.134518,0.130229,0.175115,0.573829,0.120214,0.140092,8.801434e-08,f1_macro,0.130229,0.019608,NaN,shuffle_training_X_only
12,YFP,12,504,5422,5422,1085,0.200000,0.159787,0.160327,0.200000,0.594717,0.120214,0.140092,4.814889e-14,f1_macro,0.160327,0.019608,NaN,shuffle_training_X_only
13,YFP,13,546,5422,5422,1085,0.160369,0.127283,0.124867,0.160369,0.559244,0.120214,0.140092,5.578369e-05,f1_macro,0.124867,0.019608,NaN,shuffle_training_X_only
14,YFP,14,588,5422,5422,1085,0.183410,0.141589,0.136374,0.183410,0.569114,0.120214,0.140092,1.162950e-09,f1_macro,0.136374,0.019608,NaN,shuffle_training_X_only
15,YFP,15,630,5422,5422,1085,0.189862,0.153661,0.151900,0.189862,0.577001,0.120214,0.140092,2.873481e-11,f1_macro,0.151900,0.019608,NaN,shuffle_training_X_only
16,YFP,16,672,5422,5422,1085,0.173272,0.139203,0.138805,0.173272,0.568945,0.120214,0.140092,2.152423e-07,f1_macro,0.138805,0.019608,NaN,shuffle_training_X_only
17,YFP,17,714,5422,5422,1085,0.182488,0.139915,0.134459,0.182488,0.578762,0.120214,0.140092,1.926795e-09,f1_macro,0.134459,0.019608,NaN,shuffle_training_X_only
18,YFP,18,756,5422,5422,1085,0.193548,0.150671,0.146356,0.193548,0.586742,0.120214,0.140092,3.047922e-12,f1_macro,0.146356,0.019608,NaN,shuffle_training_X_only
19,YFP,19,798,5422,5422,1085,0.190783,0.151135,0.146661,0.190783,0.572542,0.120214,0.140092,1.654227e-11,f1_macro,0.146661,0.019608,NaN,shuffle_training_X_only

aggregated YFP 2025-05-11 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFP/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-05-11/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFP,0,0,5771,5771,1155,0.172294,0.131629,0.126309,0.172294,0.588024,0.12143,0.141991,2.995632e-07,f1_macro,0.126309,0.019608,0.131447,shuffle_training_X_only
1,YFP,1,42,5771,5771,1155,0.167965,0.127151,0.122687,0.167965,0.579122,0.12143,0.141991,2.301703e-06,f1_macro,0.122687,0.019608,0.126341,shuffle_training_X_only
2,YFP,2,84,5771,5771,1155,0.179221,0.135578,0.130213,0.179221,0.581576,0.12143,0.141991,8.474038e-09,f1_macro,0.130213,0.019608,0.131601,shuffle_training_X_only
3,YFP,3,126,5771,5771,1155,0.174892,0.133451,0.129247,0.174892,0.571975,0.12143,0.141991,8.215905e-08,f1_macro,0.129247,0.019608,NaN,shuffle_training_X_only
4,YFP,4,168,5771,5771,1155,0.170563,0.129178,0.124806,0.170563,0.564391,0.12143,0.141991,6.892461e-07,f1_macro,0.124806,0.019608,NaN,shuffle_training_X_only
5,YFP,5,210,5771,5771,1155,0.174026,0.131071,0.126096,0.174026,0.556315,0.12143,0.141991,1.271912e-07,f1_macro,0.126096,0.019608,NaN,shuffle_training_X_only
6,YFP,6,252,5771,5771,1155,0.168831,0.125419,0.117089,0.168831,0.567049,0.12143,0.141991,1.549012e-06,f1_macro,0.117089,0.019608,NaN,shuffle_training_X_only
7,YFP,7,294,5771,5771,1155,0.184416,0.139227,0.133661,0.184416,0.586346,0.12143,0.141991,4.598072e-10,f1_macro,0.133661,0.019608,NaN,shuffle_training_X_only
8,YFP,8,336,5771,5771,1155,0.177489,0.136896,0.135982,0.177489,0.566598,0.12143,0.141991,2.138936e-08,f1_macro,0.135982,0.019608,NaN,shuffle_training_X_only
9,YFP,9,378,5771,5771,1155,0.161039,0.120578,0.114853,0.161039,0.569094,0.12143,0.141991,4.413115e-05,f1_macro,0.114853,0.019608,NaN,shuffle_training_X_only
10,YFP,10,420,5771,5771,1155,0.184416,0.140514,0.134619,0.184416,0.575182,0.12143,0.141991,4.598072e-10,f1_macro,0.134619,0.019608,NaN,shuffle_training_X_only
11,YFP,11,462,5771,5771,1155,0.170563,0.127450,0.120797,0.170563,0.577744,0.12143,0.141991,6.892461e-07,f1_macro,0.120797,0.019608,NaN,shuffle_training_X_only
12,YFP,12,504,5771,5771,1155,0.175758,0.138044,0.137239,0.175758,0.571863,0.12143,0.141991,5.276428e-08,f1_macro,0.137239,0.019608,NaN,shuffle_training_X_only
13,YFP,13,546,5771,5771,1155,0.172294,0.129701,0.123387,0.172294,0.574375,0.12143,0.141991,2.995632e-07,f1_macro,0.123387,0.019608,NaN,shuffle_training_X_only
14,YFP,14,588,5771,5771,1155,0.179221,0.132270,0.123451,0.179221,0.574935,0.12143,0.141991,8.474038e-09,f1_macro,0.123451,0.019608,NaN,shuffle_training_X_only
15,YFP,15,630,5771,5771,1155,0.168831,0.125505,0.120316,0.168831,0.572613,0.12143,0.141991,1.549012e-06,f1_macro,0.120316,0.019608,NaN,shuffle_training_X_only
16,YFP,16,672,5771,5771,1155,0.175758,0.138338,0.136427,0.175758,0.568305,0.12143,0.141991,5.276428e-08,f1_macro,0.136427,0.019608,NaN,shuffle_training_X_only
17,YFP,17,714,5771,5771,1155,0.166234,0.128680,0.127218,0.166234,0.574476,0.12143,0.141991,4.992410e-06,f1_macro,0.127218,0.019608,NaN,shuffle_training_X_only
18,YFP,18,756,5771,5771,1155,0.167965,0.128379,0.124374,0.167965,0.569845,0.12143,0.141991,2.301703e-06,f1_macro,0.124374,0.019608,NaN,shuffle_training_X_only
19,YFP,19,798,5771,5771,1155,0.175758,0.133739,0.129717,0.175758,0.572649,0.12143,0.141991,5.276428e-08,f1_macro,0.129717,0.019608,NaN,shuffle_training_X_only

aggregated YFP 2025-05-12 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFP/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-05-12/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFP,0,0,13821,13821,2765,0.180108,0.142619,0.134559,0.180108,0.578031,0.11602,0.133816,4.651685e-23,f1_macro,0.134559,0.019608,0.134194,shuffle_training_X_only
1,YFP,1,42,13821,13821,2765,0.171790,0.134236,0.124043,0.171790,0.569297,0.11602,0.133816,3.753064e-18,f1_macro,0.124043,0.019608,0.133781,shuffle_training_X_only
2,YFP,2,84,13821,13821,2765,0.190597,0.150258,0.139213,0.190597,0.591515,0.11602,0.133816,4.899977e-30,f1_macro,0.139213,0.019608,0.130851,shuffle_training_X_only
3,YFP,3,126,13821,13821,2765,0.184448,0.146008,0.138703,0.184448,0.570883,0.11602,0.133816,7.683574e-26,f1_macro,0.138703,0.019608,NaN,shuffle_training_X_only
4,YFP,4,168,13821,13821,2765,0.168174,0.132973,0.124127,0.168174,0.563288,0.11602,0.133816,3.384005e-16,f1_macro,0.124127,0.019608,NaN,shuffle_training_X_only
5,YFP,5,210,13821,13821,2765,0.190235,0.153183,0.148276,0.190235,0.584593,0.11602,0.133816,8.812932e-30,f1_macro,0.148276,0.019608,NaN,shuffle_training_X_only
6,YFP,6,252,13821,13821,2765,0.183725,0.145284,0.136375,0.183725,0.581800,0.11602,0.133816,2.288972e-25,f1_macro,0.136375,0.019608,NaN,shuffle_training_X_only
7,YFP,7,294,13821,13821,2765,0.176130,0.138471,0.130828,0.176130,0.573344,0.11602,0.133816,1.215863e-20,f1_macro,0.130828,0.019608,NaN,shuffle_training_X_only
8,YFP,8,336,13821,13821,2765,0.175769,0.140361,0.134084,0.175769,0.575381,0.11602,0.133816,1.987273e-20,f1_macro,0.134084,0.019608,NaN,shuffle_training_X_only
9,YFP,9,378,13821,13821,2765,0.184087,0.147645,0.141696,0.184087,0.580199,0.11602,0.133816,1.327759e-25,f1_macro,0.141696,0.019608,NaN,shuffle_training_X_only
10,YFP,10,420,13821,13821,2765,0.189512,0.149046,0.139020,0.189512,0.577354,0.11602,0.133816,2.831004e-29,f1_macro,0.139020,0.019608,NaN,shuffle_training_X_only
11,YFP,11,462,13821,13821,2765,0.188427,0.147099,0.136279,0.188427,0.578618,0.11602,0.133816,1.601651e-28,f1_macro,0.136279,0.019608,NaN,shuffle_training_X_only
12,YFP,12,504,13821,13821,2765,0.184087,0.142305,0.131125,0.184087,0.578522,0.11602,0.133816,1.327759e-25,f1_macro,0.131125,0.019608,NaN,shuffle_training_X_only
13,YFP,13,546,13821,13821,2765,0.185172,0.147566,0.139822,0.185172,0.577620,0.11602,0.133816,2.554776e-26,f1_macro,0.139822,0.019608,NaN,shuffle_training_X_only
14,YFP,14,588,13821,13821,2765,0.178300,0.143944,0.138283,0.178300,0.580857,0.11602,0.133816,6.057101e-22,f1_macro,0.138283,0.019608,NaN,shuffle_training_X_only
15,YFP,15,630,13821,13821,2765,0.175769,0.138053,0.130754,0.175769,0.578703,0.11602,0.133816,1.987273e-20,f1_macro,0.130754,0.019608,NaN,shuffle_training_X_only
16,YFP,16,672,13821,13821,2765,0.175045,0.135497,0.125550,0.175045,0.569177,0.11602,0.133816,5.269770e-20,f1_macro,0.125550,0.019608,NaN,shuffle_training_X_only
17,YFP,17,714,13821,13821,2765,0.185172,0.149865,0.144899,0.185172,0.581241,0.11602,0.133816,2.554776e-26,f1_macro,0.144899,0.019608,NaN,shuffle_training_X_only
18,YFP,18,756,13821,13821,2765,0.175045,0.136044,0.126269,0.175045,0.571422,0.11602,0.133816,5.269770e-20,f1_macro,0.126269,0.019608,NaN,shuffle_training_X_only
19,YFP,19,798,13821,13821,2765,0.182278,0.143582,0.134611,0.182278,0.569952,0.11602,0.133816,1.974001e-24,f1_macro,0.134611,0.019608,NaN,shuffle_training_X_only

aggregated YFP 2025-05-13 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFP/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-05-13/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFP,0,0,4453,4453,891,0.145903,0.110630,0.101983,0.145903,0.550815,0.119001,0.13468,8.891587e-03,f1_macro,0.101983,0.313725,0.137616,shuffle_training_X_only
1,YFP,1,42,4453,4453,891,0.191919,0.146464,0.136395,0.191919,0.574486,0.119001,0.13468,2.560490e-10,f1_macro,0.136395,0.019608,0.132271,shuffle_training_X_only
2,YFP,2,84,4453,4453,891,0.159371,0.124440,0.120783,0.159371,0.563232,0.119001,0.13468,2.099796e-04,f1_macro,0.120783,0.019608,0.124466,shuffle_training_X_only
3,YFP,3,126,4453,4453,891,0.175084,0.134981,0.128964,0.175084,0.558684,0.119001,0.13468,6.409275e-07,f1_macro,0.128964,0.019608,NaN,shuffle_training_X_only
4,YFP,4,168,4453,4453,891,0.167228,0.134764,0.133791,0.167228,0.550124,0.119001,0.13468,1.399301e-05,f1_macro,0.133791,0.019608,NaN,shuffle_training_X_only
5,YFP,5,210,4453,4453,891,0.168350,0.130217,0.124066,0.168350,0.573739,0.119001,0.13468,9.214777e-06,f1_macro,0.124066,0.019608,NaN,shuffle_training_X_only
6,YFP,6,252,4453,4453,891,0.172840,0.129755,0.120129,0.172840,0.554609,0.119001,0.13468,1.606147e-06,f1_macro,0.120129,0.019608,NaN,shuffle_training_X_only
7,YFP,7,294,4453,4453,891,0.159371,0.124996,0.120263,0.159371,0.542433,0.119001,0.13468,2.099796e-04,f1_macro,0.120263,0.019608,NaN,shuffle_training_X_only
8,YFP,8,336,4453,4453,891,0.160494,0.122178,0.114876,0.160494,0.551768,0.119001,0.13468,1.459691e-04,f1_macro,0.114876,0.019608,NaN,shuffle_training_X_only
9,YFP,9,378,4453,4453,891,0.162738,0.124146,0.117121,0.162738,0.565627,0.119001,0.13468,6.890670e-05,f1_macro,0.117121,0.019608,NaN,shuffle_training_X_only
10,YFP,10,420,4453,4453,891,0.169473,0.129489,0.123576,0.169473,0.563766,0.119001,0.13468,6.022087e-06,f1_macro,0.123576,0.019608,NaN,shuffle_training_X_only
11,YFP,11,462,4453,4453,891,0.189675,0.146229,0.138773,0.189675,0.574908,0.119001,0.13468,7.981455e-10,f1_macro,0.138773,0.019608,NaN,shuffle_training_X_only
12,YFP,12,504,4453,4453,891,0.163861,0.131555,0.130446,0.163861,0.545785,0.119001,0.13468,4.679512e-05,f1_macro,0.130446,0.019608,NaN,shuffle_training_X_only
13,YFP,13,546,4453,4453,891,0.203143,0.162920,0.161139,0.203143,0.570320,0.119001,0.13468,5.726074e-13,f1_macro,0.161139,0.019608,NaN,shuffle_training_X_only
14,YFP,14,588,4453,4453,891,0.159371,0.129396,0.128685,0.159371,0.576605,0.119001,0.13468,2.099796e-04,f1_macro,0.128685,0.019608,NaN,shuffle_training_X_only
15,YFP,15,630,4453,4453,891,0.178451,0.137675,0.131898,0.178451,0.563018,0.119001,0.13468,1.527872e-07,f1_macro,0.131898,0.019608,NaN,shuffle_training_X_only
16,YFP,16,672,4453,4453,891,0.194164,0.149133,0.140494,0.194164,0.568475,0.119001,0.13468,7.986039e-11,f1_macro,0.140494,0.019608,NaN,shuffle_training_X_only
17,YFP,17,714,4453,4453,891,0.177329,0.136604,0.128879,0.177329,0.567300,0.119001,0.13468,2.482441e-07,f1_macro,0.128879,0.019608,NaN,shuffle_training_X_only
18,YFP,18,756,4453,4453,891,0.162738,0.125385,0.120324,0.162738,0.556524,0.119001,0.13468,6.890670e-05,f1_macro,0.120324,0.019608,NaN,shuffle_training_X_only
19,YFP,19,798,4453,4453,891,0.175084,0.138848,0.136824,0.175084,0.566377,0.119001,0.13468,6.409275e-07,f1_macro,0.136824,0.019608,NaN,shuffle_training_X_only

aggregated YFP 2025-05-14 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFP/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-05-14/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFP,0,0,11571,11571,2315,0.193089,0.156098,0.149378,0.193089,0.590627,0.115515,0.131317,2.487186e-27,f1_macro,0.149378,0.019608,0.147542,shuffle_training_X_only
1,YFP,1,42,11571,11571,2315,0.184881,0.148077,0.139605,0.184881,0.584637,0.115515,0.131317,1.617405e-22,f1_macro,0.139605,0.019608,0.151038,shuffle_training_X_only
2,YFP,2,84,11571,11571,2315,0.193089,0.155924,0.149978,0.193089,0.599134,0.115515,0.131317,2.487186e-27,f1_macro,0.149978,0.019608,0.148646,shuffle_training_X_only
3,YFP,3,126,11571,11571,2315,0.189201,0.151446,0.144774,0.189201,0.592712,0.115515,0.131317,5.371216e-25,f1_macro,0.144774,0.019608,NaN,shuffle_training_X_only
4,YFP,4,168,11571,11571,2315,0.190065,0.155277,0.149696,0.190065,0.594156,0.115515,0.131317,1.658603e-25,f1_macro,0.149696,0.019608,NaN,shuffle_training_X_only
5,YFP,5,210,11571,11571,2315,0.197840,0.160707,0.155137,0.197840,0.593314,0.115515,0.131317,2.579831e-30,f1_macro,0.155137,0.019608,NaN,shuffle_training_X_only
6,YFP,6,252,11571,11571,2315,0.186609,0.151006,0.143922,0.186609,0.587025,0.115515,0.131317,1.705947e-23,f1_macro,0.143922,0.019608,NaN,shuffle_training_X_only
7,YFP,7,294,11571,11571,2315,0.181857,0.150028,0.147072,0.181857,0.591417,0.115515,0.131317,7.428091e-21,f1_macro,0.147072,0.019608,NaN,shuffle_training_X_only
8,YFP,8,336,11571,11571,2315,0.194816,0.158202,0.153404,0.194816,0.589887,0.115515,0.131317,2.123893e-28,f1_macro,0.153404,0.019608,NaN,shuffle_training_X_only
9,YFP,9,378,11571,11571,2315,0.191793,0.155798,0.149997,0.191793,0.587241,0.115515,0.131317,1.529779e-26,f1_macro,0.149997,0.019608,NaN,shuffle_training_X_only
10,YFP,10,420,11571,11571,2315,0.180130,0.146272,0.141605,0.180130,0.582291,0.115515,0.131317,6.212829e-20,f1_macro,0.141605,0.019608,NaN,shuffle_training_X_only
11,YFP,11,462,11571,11571,2315,0.191361,0.154983,0.148362,0.191361,0.597145,0.115515,0.131317,2.787462e-26,f1_macro,0.148362,0.019608,NaN,shuffle_training_X_only
12,YFP,12,504,11571,11571,2315,0.182721,0.148227,0.142932,0.182721,0.596541,0.115515,0.131317,2.524613e-21,f1_macro,0.142932,0.019608,NaN,shuffle_training_X_only
13,YFP,13,546,11571,11571,2315,0.188337,0.150271,0.140123,0.188337,0.589994,0.115515,0.131317,1.720140e-24,f1_macro,0.140123,0.019608,NaN,shuffle_training_X_only
14,YFP,14,588,11571,11571,2315,0.176674,0.143008,0.136569,0.176674,0.592967,0.115515,0.131317,3.782879e-18,f1_macro,0.136569,0.019608,NaN,shuffle_training_X_only
15,YFP,15,630,11571,11571,2315,0.185313,0.151179,0.144995,0.185313,0.597111,0.115515,0.131317,9.256466e-23,f1_macro,0.144995,0.019608,NaN,shuffle_training_X_only
16,YFP,16,672,11571,11571,2315,0.191793,0.154642,0.147078,0.191793,0.598673,0.115515,0.131317,1.529779e-26,f1_macro,0.147078,0.019608,NaN,shuffle_training_X_only
17,YFP,17,714,11571,11571,2315,0.187473,0.152290,0.146664,0.187473,0.595370,0.115515,0.131317,5.447536e-24,f1_macro,0.146664,0.019608,NaN,shuffle_training_X_only
18,YFP,18,756,11571,11571,2315,0.176242,0.143707,0.138495,0.176242,0.582050,0.115515,0.131317,6.240141e-18,f1_macro,0.138495,0.019608,NaN,shuffle_training_X_only
19,YFP,19,798,11571,11571,2315,0.186609,0.153125,0.148313,0.186609,0.596559,0.115515,0.131317,1.705947e-23,f1_macro,0.148313,0.019608,NaN,shuffle_training_X_only

aggregated YFP 2025-05-15 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFP/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-05-15/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFP,0,0,6807,6041,1209,0.160463,0.135483,0.132214,0.160463,0.562054,0.112355,0.128205,3.072263e-07,f1_macro,0.132214,0.019608,0.128035,shuffle_training_X_only
1,YFP,1,42,6807,6033,1207,0.178956,0.146127,0.136969,0.178956,0.563964,0.112457,0.129246,6.106735e-12,f1_macro,0.136969,0.019608,0.142833,shuffle_training_X_only
2,YFP,2,84,6807,6010,1202,0.160566,0.131551,0.124107,0.160566,0.556670,0.112338,0.128952,3.112014e-07,f1_macro,0.124107,0.019608,0.133352,shuffle_training_X_only
3,YFP,3,126,6807,6047,1210,0.166116,0.138136,0.132853,0.166116,0.572077,0.112390,0.129752,1.480253e-08,f1_macro,0.132853,0.019608,NaN,shuffle_training_X_only
4,YFP,4,168,6807,6046,1210,0.165289,0.138444,0.134598,0.165289,0.559297,0.112391,0.129752,2.351439e-08,f1_macro,0.134598,0.019608,NaN,shuffle_training_X_only
5,YFP,5,210,6807,6030,1206,0.172471,0.143962,0.138703,0.172471,0.562943,0.112291,0.129353,3.474400e-10,f1_macro,0.138703,0.019608,NaN,shuffle_training_X_only
6,YFP,6,252,6807,6040,1208,0.168046,0.139559,0.132298,0.168046,0.566718,0.112501,0.130795,5.461610e-09,f1_macro,0.132298,0.019608,NaN,shuffle_training_X_only
7,YFP,7,294,6807,6011,1203,0.163757,0.137444,0.130980,0.163757,0.575635,0.112217,0.129676,5.311281e-08,f1_macro,0.130980,0.019608,NaN,shuffle_training_X_only
8,YFP,8,336,6807,6033,1207,0.159072,0.132505,0.125522,0.159072,0.554376,0.112460,0.128418,6.759268e-07,f1_macro,0.125522,0.019608,NaN,shuffle_training_X_only
9,YFP,9,378,6807,6031,1207,0.178128,0.148543,0.142598,0.178128,0.559566,0.112324,0.130075,9.493520e-12,f1_macro,0.142598,0.019608,NaN,shuffle_training_X_only
10,YFP,10,420,6807,6025,1205,0.161826,0.135632,0.130371,0.161826,0.561216,0.112267,0.129461,1.499994e-07,f1_macro,0.130371,0.019608,NaN,shuffle_training_X_only
11,YFP,11,462,6807,6042,1209,0.181141,0.149498,0.142160,0.181141,0.560880,0.112507,0.129859,1.398579e-12,f1_macro,0.142160,0.019608,NaN,shuffle_training_X_only
12,YFP,12,504,6807,6022,1205,0.168465,0.141252,0.136646,0.168465,0.552254,0.112273,0.129461,3.822090e-09,f1_macro,0.136646,0.019608,NaN,shuffle_training_X_only
13,YFP,13,546,6807,6034,1207,0.163215,0.138476,0.135570,0.163215,0.553767,0.112507,0.129246,8.146704e-08,f1_macro,0.135570,0.019608,NaN,shuffle_training_X_only
14,YFP,14,588,6807,6029,1206,0.165008,0.139973,0.135420,0.165008,0.567597,0.112295,0.129353,2.715080e-08,f1_macro,0.135420,0.019608,NaN,shuffle_training_X_only
15,YFP,15,630,6807,6029,1206,0.178275,0.149485,0.143135,0.178275,0.574439,0.112281,0.128524,8.479605e-12,f1_macro,0.143135,0.019608,NaN,shuffle_training_X_only
16,YFP,16,672,6807,6049,1210,0.165289,0.138965,0.134386,0.165289,0.565659,0.112393,0.129752,2.353555e-08,f1_macro,0.134386,0.019608,NaN,shuffle_training_X_only
17,YFP,17,714,6807,6027,1206,0.160862,0.131756,0.122343,0.160862,0.552154,0.112435,0.128524,2.712850e-07,f1_macro,0.122343,0.019608,NaN,shuffle_training_X_only
18,YFP,18,756,6807,6042,1209,0.156328,0.130638,0.125581,0.156328,0.556077,0.112370,0.129859,2.411235e-06,f1_macro,0.125581,0.019608,NaN,shuffle_training_X_only
19,YFP,19,798,6807,6032,1207,0.192212,0.157554,0.149073,0.192212,0.571433,0.112309,0.129246,3.874832e-16,f1_macro,0.149073,0.019608,NaN,shuffle_training_X_only

aggregated YFP 2025-05-16 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFP/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-05-16/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFP,0,0,6006,6006,1202,0.178037,0.138984,0.134200,0.178037,0.580813,0.118732,0.135607,1.355591e-09,f1_macro,0.134200,0.019608,0.147233,shuffle_training_X_only
1,YFP,1,42,6006,6006,1202,0.207155,0.158732,0.148530,0.207155,0.603461,0.118732,0.135607,2.161990e-18,f1_macro,0.148530,0.019608,0.140493,shuffle_training_X_only
2,YFP,2,84,6006,6006,1202,0.184692,0.144434,0.139182,0.184692,0.575513,0.118732,0.135607,2.342136e-11,f1_macro,0.139182,0.019608,0.143452,shuffle_training_X_only
3,YFP,3,126,6006,6006,1202,0.198003,0.155401,0.149015,0.198003,0.590783,0.118732,0.135607,2.503190e-15,f1_macro,0.149015,0.019608,NaN,shuffle_training_X_only
4,YFP,4,168,6006,6006,1202,0.184692,0.144967,0.138776,0.184692,0.565006,0.118732,0.135607,2.342136e-11,f1_macro,0.138776,0.019608,NaN,shuffle_training_X_only
5,YFP,5,210,6006,6006,1202,0.186356,0.145301,0.137271,0.186356,0.587008,0.118732,0.135607,8.043183e-12,f1_macro,0.137271,0.019608,NaN,shuffle_training_X_only
6,YFP,6,252,6006,6006,1202,0.182196,0.142733,0.137710,0.182196,0.570918,0.118732,0.135607,1.117662e-10,f1_macro,0.137710,0.019608,NaN,shuffle_training_X_only
7,YFP,7,294,6006,6006,1202,0.176373,0.134493,0.126583,0.176373,0.584952,0.118732,0.135607,3.539308e-09,f1_macro,0.126583,0.019608,NaN,shuffle_training_X_only
8,YFP,8,336,6006,6006,1202,0.198003,0.155817,0.150455,0.198003,0.573898,0.118732,0.135607,2.503190e-15,f1_macro,0.150455,0.019608,NaN,shuffle_training_X_only
9,YFP,9,378,6006,6006,1202,0.195507,0.151001,0.140325,0.195507,0.578952,0.118732,0.135607,1.539776e-14,f1_macro,0.140325,0.019608,NaN,shuffle_training_X_only
10,YFP,10,420,6006,6006,1202,0.168885,0.131684,0.125843,0.168885,0.570109,0.118732,0.135607,2.014651e-07,f1_macro,0.125843,0.019608,NaN,shuffle_training_X_only
11,YFP,11,462,6006,6006,1202,0.192180,0.151975,0.147520,0.192180,0.590764,0.118732,0.135607,1.613711e-13,f1_macro,0.147520,0.019608,NaN,shuffle_training_X_only
12,YFP,12,504,6006,6006,1202,0.188852,0.151238,0.146084,0.188852,0.580957,0.118732,0.135607,1.554936e-12,f1_macro,0.146084,0.019608,NaN,shuffle_training_X_only
13,YFP,13,546,6006,6006,1202,0.196339,0.154492,0.148536,0.196339,0.599255,0.118732,0.135607,8.447239e-15,f1_macro,0.148536,0.019608,NaN,shuffle_training_X_only
14,YFP,14,588,6006,6006,1202,0.193844,0.150320,0.141294,0.193844,0.576624,0.118732,0.135607,5.037038e-14,f1_macro,0.141294,0.019608,NaN,shuffle_training_X_only
15,YFP,15,630,6006,6006,1202,0.180532,0.143127,0.138315,0.180532,0.577600,0.118732,0.135607,3.083010e-10,f1_macro,0.138315,0.019608,NaN,shuffle_training_X_only
16,YFP,16,672,6006,6006,1202,0.187188,0.142903,0.132294,0.187188,0.588793,0.118732,0.135607,4.675640e-12,f1_macro,0.132294,0.019608,NaN,shuffle_training_X_only
17,YFP,17,714,6006,6006,1202,0.176373,0.137415,0.131104,0.176373,0.576681,0.118732,0.135607,3.539308e-09,f1_macro,0.131104,0.019608,NaN,shuffle_training_X_only
18,YFP,18,756,6006,6006,1202,0.197171,0.149470,0.139427,0.197171,0.571610,0.118732,0.135607,4.610253e-15,f1_macro,0.139427,0.019608,NaN,shuffle_training_X_only
19,YFP,19,798,6006,6006,1202,0.184692,0.144952,0.138370,0.184692,0.581691,0.118732,0.135607,2.342136e-11,f1_macro,0.138370,0.019608,NaN,shuffle_training_X_only

aggregated YFQ 2025-06-14 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFQ/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-06-14/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFQ,0,0,6150,4701,941,0.217853,0.163644,0.156680,0.217853,0.599335,0.123426,0.151966,4.426743e-16,f1_macro,0.156680,0.019608,0.166106,shuffle_training_X_only
1,YFQ,1,42,6150,4629,926,0.235421,0.181608,0.176363,0.235421,0.632733,0.123157,0.153348,3.422088e-21,f1_macro,0.176363,0.019608,0.166528,shuffle_training_X_only
2,YFQ,2,84,6150,4665,933,0.243301,0.186101,0.178721,0.243301,0.635724,0.123189,0.155413,6.412270e-24,f1_macro,0.178721,0.019608,0.162171,shuffle_training_X_only
3,YFQ,3,126,6150,4654,931,0.238453,0.183756,0.178756,0.238453,0.629527,0.123433,0.156821,3.706401e-22,f1_macro,0.178756,0.019608,NaN,shuffle_training_X_only
4,YFQ,4,168,6150,4663,933,0.221865,0.168160,0.160135,0.221865,0.625794,0.123194,0.154341,3.477775e-17,f1_macro,0.160135,0.019608,NaN,shuffle_training_X_only
5,YFQ,5,210,6150,4650,930,0.233333,0.179167,0.172172,0.233333,0.614484,0.123096,0.153763,1.223780e-20,f1_macro,0.172172,0.019608,NaN,shuffle_training_X_only
6,YFQ,6,252,6150,4660,932,0.224249,0.168631,0.159225,0.224249,0.599521,0.123241,0.157725,7.570203e-18,f1_macro,0.159225,0.019608,NaN,shuffle_training_X_only
7,YFQ,7,294,6150,4654,931,0.237379,0.182954,0.174874,0.237379,0.618149,0.123177,0.155747,6.417145e-22,f1_macro,0.174874,0.019608,NaN,shuffle_training_X_only
8,YFQ,8,336,6150,4664,933,0.212219,0.162360,0.158339,0.212219,0.620320,0.123288,0.156484,1.820576e-14,f1_macro,0.158339,0.019608,NaN,shuffle_training_X_only
9,YFQ,9,378,6150,4630,926,0.225702,0.177652,0.174759,0.225702,0.605051,0.122910,0.153348,2.672543e-18,f1_macro,0.174759,0.019608,NaN,shuffle_training_X_only
10,YFQ,10,420,6150,4662,933,0.232583,0.181379,0.176497,0.232583,0.609783,0.123247,0.155413,2.116936e-20,f1_macro,0.176497,0.019608,NaN,shuffle_training_X_only
11,YFQ,11,462,6150,4649,930,0.241935,0.185938,0.183766,0.241935,0.590122,0.123161,0.155914,2.105845e-23,f1_macro,0.183766,0.019608,NaN,shuffle_training_X_only
12,YFQ,12,504,6150,4664,933,0.218650,0.163033,0.152298,0.218650,0.621268,0.123242,0.155413,3.010484e-16,f1_macro,0.152298,0.019608,NaN,shuffle_training_X_only
13,YFQ,13,546,6150,4695,939,0.210863,0.158527,0.148531,0.210863,0.606285,0.123380,0.152290,3.722671e-14,f1_macro,0.148531,0.019608,NaN,shuffle_training_X_only
14,YFQ,14,588,6150,4663,933,0.233655,0.174577,0.166225,0.233655,0.618954,0.123228,0.153269,9.554820e-21,f1_macro,0.166225,0.019608,NaN,shuffle_training_X_only
15,YFQ,15,630,6150,4688,938,0.231343,0.178824,0.175459,0.231343,0.632408,0.123581,0.153518,5.654029e-20,f1_macro,0.175459,0.019608,NaN,shuffle_training_X_only
16,YFQ,16,672,6150,4658,932,0.222103,0.166306,0.157373,0.222103,0.602427,0.123195,0.154506,3.084720e-17,f1_macro,0.157373,0.019608,NaN,shuffle_training_X_only
17,YFQ,17,714,6150,4666,934,0.226981,0.177385,0.175345,0.226981,0.584687,0.123296,0.156317,1.123493e-18,f1_macro,0.175345,0.019608,NaN,shuffle_training_X_only
18,YFQ,18,756,6150,4636,928,0.230603,0.174596,0.164555,0.230603,0.628877,0.123079,0.156250,9.371420e-20,f1_macro,0.164555,0.019608,NaN,shuffle_training_X_only
19,YFQ,19,798,6150,4659,932,0.214592,0.163382,0.157212,0.214592,0.617098,0.123195,0.155579,4.000881e-15,f1_macro,0.157212,0.019608,NaN,shuffle_training_X_only

aggregated YFQ 2025-06-15 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFQ/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-06-15/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFQ,0,0,5824,5824,1165,0.212017,0.169321,0.163501,0.212017,0.626252,0.118288,0.134764,9.168033e-20,f1_macro,0.163501,0.019608,0.165889,shuffle_training_X_only
1,YFQ,1,42,5824,5824,1165,0.218026,0.176648,0.173053,0.218026,0.641854,0.118288,0.134764,5.936088e-22,f1_macro,0.173053,0.019608,0.162837,shuffle_training_X_only
2,YFQ,2,84,5824,5824,1165,0.210300,0.168182,0.160703,0.210300,0.626184,0.118288,0.134764,3.697669e-19,f1_macro,0.160703,0.019608,0.163251,shuffle_training_X_only
3,YFQ,3,126,5824,5824,1165,0.223176,0.178760,0.173716,0.223176,0.616461,0.118288,0.134764,6.503157e-24,f1_macro,0.173716,0.019608,NaN,shuffle_training_X_only
4,YFQ,4,168,5824,5824,1165,0.222318,0.182007,0.179775,0.222318,0.612680,0.118288,0.134764,1.397010e-23,f1_macro,0.179775,0.019608,NaN,shuffle_training_X_only
5,YFQ,5,210,5824,5824,1165,0.210300,0.166883,0.161049,0.210300,0.627031,0.118288,0.134764,3.697669e-19,f1_macro,0.161049,0.019608,NaN,shuffle_training_X_only
6,YFQ,6,252,5824,5824,1165,0.185408,0.150063,0.148334,0.185408,0.608384,0.118288,0.134764,2.134671e-11,f1_macro,0.148334,0.019608,NaN,shuffle_training_X_only
7,YFQ,7,294,5824,5824,1165,0.229185,0.189326,0.184671,0.229185,0.614417,0.118288,0.134764,2.687761e-26,f1_macro,0.184671,0.019608,NaN,shuffle_training_X_only
8,YFQ,8,336,5824,5824,1165,0.193133,0.155419,0.151846,0.193133,0.609727,0.118288,0.134764,1.346931e-13,f1_macro,0.151846,0.019608,NaN,shuffle_training_X_only
9,YFQ,9,378,5824,5824,1165,0.210300,0.169717,0.164571,0.210300,0.607498,0.118288,0.134764,3.697669e-19,f1_macro,0.164571,0.019608,NaN,shuffle_training_X_only
10,YFQ,10,420,5824,5824,1165,0.216309,0.175216,0.169637,0.216309,0.625106,0.118288,0.134764,2.568900e-21,f1_macro,0.169637,0.019608,NaN,shuffle_training_X_only
11,YFQ,11,462,5824,5824,1165,0.190558,0.156944,0.153276,0.190558,0.606391,0.118288,0.134764,7.656395e-13,f1_macro,0.153276,0.019608,NaN,shuffle_training_X_only
12,YFQ,12,504,5824,5824,1165,0.204292,0.168053,0.167497,0.204292,0.635045,0.118288,0.134764,4.146619e-17,f1_macro,0.167497,0.019608,NaN,shuffle_training_X_only
13,YFQ,13,546,5824,5824,1165,0.196567,0.157512,0.153577,0.196567,0.603222,0.118288,0.134764,1.231191e-14,f1_macro,0.153577,0.019608,NaN,shuffle_training_X_only
14,YFQ,14,588,5824,5824,1165,0.200858,0.159689,0.153837,0.200858,0.621055,0.118288,0.134764,5.488940e-16,f1_macro,0.153837,0.019608,NaN,shuffle_training_X_only
15,YFQ,15,630,5824,5824,1165,0.212876,0.171461,0.167675,0.212876,0.614808,0.118288,0.134764,4.530508e-20,f1_macro,0.167675,0.019608,NaN,shuffle_training_X_only
16,YFQ,16,672,5824,5824,1165,0.230901,0.191027,0.189957,0.230901,0.621811,0.118288,0.134764,5.363557e-27,f1_macro,0.189957,0.019608,NaN,shuffle_training_X_only
17,YFQ,17,714,5824,5824,1165,0.200000,0.161486,0.158784,0.200000,0.611423,0.118288,0.134764,1.033350e-15,f1_macro,0.158784,0.019608,NaN,shuffle_training_X_only
18,YFQ,18,756,5824,5824,1165,0.213734,0.170453,0.165726,0.213734,0.615318,0.118288,0.134764,2.227529e-20,f1_macro,0.165726,0.019608,NaN,shuffle_training_X_only
19,YFQ,19,798,5824,5824,1165,0.200000,0.163573,0.162405,0.200000,0.631564,0.118288,0.134764,1.033350e-15,f1_macro,0.162405,0.019608,NaN,shuffle_training_X_only

aggregated YFQ 2025-06-16 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFQ/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-06-16/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFQ,0,0,7428,6775,1355,0.222140,0.169488,0.162080,0.222140,0.626856,0.122806,0.143173,1.733085e-24,f1_macro,0.162080,0.019608,0.178741,shuffle_training_X_only
1,YFQ,1,42,7428,6791,1359,0.223694,0.167273,0.158996,0.223694,0.625740,0.122922,0.143488,3.749839e-25,f1_macro,0.158996,0.019608,0.168348,shuffle_training_X_only
2,YFQ,2,84,7428,6806,1362,0.218796,0.173156,0.171099,0.218796,0.624299,0.123001,0.143906,4.230169e-23,f1_macro,0.171099,0.019608,0.166487,shuffle_training_X_only
3,YFQ,3,126,7428,6796,1360,0.217647,0.166134,0.162161,0.217647,0.624599,0.122944,0.143382,1.255621e-22,f1_macro,0.162161,0.019608,NaN,shuffle_training_X_only
4,YFQ,4,168,7428,6789,1358,0.221649,0.168662,0.162987,0.221649,0.626831,0.122889,0.143594,2.762760e-24,f1_macro,0.162987,0.019608,NaN,shuffle_training_X_only
5,YFQ,5,210,7428,6766,1354,0.228951,0.171777,0.163956,0.228951,0.650572,0.122781,0.143279,1.937895e-27,f1_macro,0.163956,0.019608,NaN,shuffle_training_X_only
6,YFQ,6,252,7428,6793,1359,0.220751,0.160234,0.147196,0.220751,0.634944,0.122929,0.144224,6.665756e-24,f1_macro,0.147196,0.019608,NaN,shuffle_training_X_only
7,YFQ,7,294,7428,6756,1352,0.231509,0.171633,0.160939,0.231509,0.635652,0.122704,0.143491,1.355888e-28,f1_macro,0.160939,0.019608,NaN,shuffle_training_X_only
8,YFQ,8,336,7428,6809,1362,0.245228,0.187792,0.182821,0.245228,0.650195,0.122997,0.143172,3.647587e-35,f1_macro,0.182821,0.019608,NaN,shuffle_training_X_only
9,YFQ,9,378,7428,6777,1356,0.213864,0.161413,0.154477,0.213864,0.633183,0.122835,0.143805,4.169626e-21,f1_macro,0.154477,0.019608,NaN,shuffle_training_X_only
10,YFQ,10,420,7428,6784,1357,0.218865,0.162459,0.151368,0.218865,0.634093,0.122856,0.142962,3.977019e-23,f1_macro,0.151368,0.019608,NaN,shuffle_training_X_only
11,YFQ,11,462,7428,6768,1354,0.231167,0.171803,0.159295,0.231167,0.635856,0.122783,0.143279,1.969761e-28,f1_macro,0.159295,0.019608,NaN,shuffle_training_X_only
12,YFQ,12,504,7428,6770,1354,0.242245,0.184363,0.178180,0.242245,0.638308,0.122781,0.143279,1.209900e-33,f1_macro,0.178180,0.019608,NaN,shuffle_training_X_only
13,YFQ,13,546,7428,6783,1357,0.227708,0.169408,0.158094,0.227708,0.630533,0.122866,0.144436,6.784959e-27,f1_macro,0.158094,0.019608,NaN,shuffle_training_X_only
14,YFQ,14,588,7428,6795,1359,0.231052,0.171156,0.160922,0.231052,0.649233,0.122920,0.144224,2.138097e-28,f1_macro,0.160922,0.019608,NaN,shuffle_training_X_only
15,YFQ,15,630,7428,6792,1359,0.220751,0.165928,0.158208,0.220751,0.629942,0.122917,0.143488,6.567863e-24,f1_macro,0.158208,0.019608,NaN,shuffle_training_X_only
16,YFQ,16,672,7428,6786,1358,0.229013,0.178032,0.173641,0.229013,0.630538,0.122888,0.143594,1.765166e-27,f1_macro,0.173641,0.019608,NaN,shuffle_training_X_only
17,YFQ,17,714,7428,6792,1359,0.232524,0.175007,0.167047,0.232524,0.625401,0.122913,0.142752,4.522703e-29,f1_macro,0.167047,0.019608,NaN,shuffle_training_X_only
18,YFQ,18,756,7428,6797,1360,0.227941,0.169586,0.161202,0.227941,0.636444,0.122940,0.143382,5.199919e-27,f1_macro,0.161202,0.019608,NaN,shuffle_training_X_only
19,YFQ,19,798,7428,6809,1362,0.240088,0.180544,0.174370,0.240088,0.626389,0.122998,0.143172,1.221011e-32,f1_macro,0.174370,0.019608,NaN,shuffle_training_X_only

aggregated YFQ 2025-06-17 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFQ/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-06-17/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFQ,0,0,2890,2890,578,0.186851,0.152054,0.148605,0.186851,0.616916,0.114827,0.133218,2.911238e-07,f1_macro,0.148605,0.019608,0.147859,shuffle_training_X_only
1,YFQ,1,42,2890,2890,578,0.171280,0.138840,0.133701,0.171280,0.596153,0.114827,0.133218,3.711817e-05,f1_macro,0.133701,0.019608,0.150621,shuffle_training_X_only
2,YFQ,2,84,2890,2890,578,0.223183,0.187552,0.185312,0.223183,0.614218,0.114827,0.133218,1.220657e-13,f1_macro,0.185312,0.019608,0.147679,shuffle_training_X_only
3,YFQ,3,126,2890,2890,578,0.185121,0.153397,0.151594,0.185121,0.610541,0.114827,0.133218,5.216614e-07,f1_macro,0.151594,0.019608,NaN,shuffle_training_X_only
4,YFQ,4,168,2890,2890,578,0.178201,0.143764,0.140037,0.178201,0.581730,0.114827,0.133218,4.814869e-06,f1_macro,0.140037,0.039216,NaN,shuffle_training_X_only
5,YFQ,5,210,2890,2890,578,0.186851,0.153261,0.151551,0.186851,0.582280,0.114827,0.133218,2.911238e-07,f1_macro,0.151551,0.019608,NaN,shuffle_training_X_only
6,YFQ,6,252,2890,2890,578,0.207612,0.170827,0.166349,0.207612,0.609638,0.114827,0.133218,1.151576e-10,f1_macro,0.166349,0.019608,NaN,shuffle_training_X_only
7,YFQ,7,294,2890,2890,578,0.211073,0.168381,0.159915,0.211073,0.624859,0.114827,0.133218,2.696339e-11,f1_macro,0.159915,0.019608,NaN,shuffle_training_X_only
8,YFQ,8,336,2890,2890,578,0.193772,0.153993,0.145180,0.193772,0.608526,0.114827,0.133218,2.532761e-08,f1_macro,0.145180,0.019608,NaN,shuffle_training_X_only
9,YFQ,9,378,2890,2890,578,0.157439,0.120111,0.108136,0.157439,0.584095,0.114827,0.133218,1.264774e-03,f1_macro,0.108136,0.098039,NaN,shuffle_training_X_only
10,YFQ,10,420,2890,2890,578,0.198962,0.166747,0.167865,0.198962,0.599749,0.114827,0.133218,3.625501e-09,f1_macro,0.167865,0.019608,NaN,shuffle_training_X_only
11,YFQ,11,462,2890,2890,578,0.202422,0.169970,0.168309,0.202422,0.586454,0.114827,0.133218,9.411699e-10,f1_macro,0.168309,0.019608,NaN,shuffle_training_X_only
12,YFQ,12,504,2890,2890,578,0.197232,0.163621,0.161813,0.197232,0.603495,0.114827,0.133218,7.004523e-09,f1_macro,0.161813,0.019608,NaN,shuffle_training_X_only
13,YFQ,13,546,2890,2890,578,0.197232,0.155951,0.145583,0.197232,0.601107,0.114827,0.133218,7.004523e-09,f1_macro,0.145583,0.019608,NaN,shuffle_training_X_only
14,YFQ,14,588,2890,2890,578,0.217993,0.177729,0.170998,0.217993,0.620632,0.114827,0.133218,1.309597e-12,f1_macro,0.170998,0.019608,NaN,shuffle_training_X_only
15,YFQ,15,630,2890,2890,578,0.195502,0.159664,0.155616,0.195502,0.608378,0.114827,0.133218,1.339047e-08,f1_macro,0.155616,0.019608,NaN,shuffle_training_X_only
16,YFQ,16,672,2890,2890,578,0.211073,0.166327,0.157503,0.211073,0.617076,0.114827,0.133218,2.696339e-11,f1_macro,0.157503,0.019608,NaN,shuffle_training_X_only
17,YFQ,17,714,2890,2890,578,0.164360,0.135993,0.132379,0.164360,0.581190,0.114827,0.133218,2.380320e-04,f1_macro,0.132379,0.019608,NaN,shuffle_training_X_only
18,YFQ,18,756,2890,2890,578,0.192042,0.150850,0.140935,0.192042,0.608850,0.114827,0.133218,4.739667e-08,f1_macro,0.140935,0.019608,NaN,shuffle_training_X_only
19,YFQ,19,798,2890,2890,578,0.166090,0.129013,0.120197,0.166090,0.586409,0.114827,0.133218,1.522173e-04,f1_macro,0.120197,0.039216,NaN,shuffle_training_X_only

aggregated YFQ 2025-06-18 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFQ/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-06-18/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFQ,0,0,6212,6212,1243,0.235720,0.172559,0.164472,0.235720,0.625378,0.126043,0.143202,2.303654e-26,f1_macro,0.164472,0.019608,0.170402,shuffle_training_X_only
1,YFQ,1,42,6212,6212,1243,0.241352,0.180215,0.173278,0.241352,0.630285,0.126043,0.143202,9.763899e-29,f1_macro,0.173278,0.019608,0.172278,shuffle_training_X_only
2,YFQ,2,84,6212,6212,1243,0.235720,0.172951,0.165273,0.235720,0.635398,0.126043,0.143202,2.303654e-26,f1_macro,0.165273,0.019608,0.169769,shuffle_training_X_only
3,YFQ,3,126,6212,6212,1243,0.205149,0.153366,0.148181,0.205149,0.624126,0.126043,0.143202,3.646669e-15,f1_macro,0.148181,0.019608,NaN,shuffle_training_X_only
4,YFQ,4,168,6212,6212,1243,0.222043,0.162144,0.153313,0.222043,0.613855,0.126043,0.143202,5.374927e-21,f1_macro,0.153313,0.019608,NaN,shuffle_training_X_only
5,YFQ,5,210,6212,6212,1243,0.242156,0.179410,0.173528,0.242156,0.640475,0.126043,0.143202,4.396021e-29,f1_macro,0.173528,0.019608,NaN,shuffle_training_X_only
6,YFQ,6,252,6212,6212,1243,0.233307,0.172262,0.165709,0.233307,0.640218,0.126043,0.143202,2.241943e-25,f1_macro,0.165709,0.019608,NaN,shuffle_training_X_only
7,YFQ,7,294,6212,6212,1243,0.250201,0.186505,0.180763,0.250201,0.625008,0.126043,0.143202,1.186741e-32,f1_macro,0.180763,0.019608,NaN,shuffle_training_X_only
8,YFQ,8,336,6212,6212,1243,0.251006,0.185565,0.179995,0.251006,0.644855,0.126043,0.143202,5.096416e-33,f1_macro,0.179995,0.019608,NaN,shuffle_training_X_only
9,YFQ,9,378,6212,6212,1243,0.236525,0.177862,0.174713,0.236525,0.626127,0.126043,0.143202,1.069475e-26,f1_macro,0.174713,0.019608,NaN,shuffle_training_X_only
10,YFQ,10,420,6212,6212,1243,0.219630,0.160585,0.153859,0.219630,0.603095,0.126043,0.143202,4.153569e-20,f1_macro,0.153859,0.019608,NaN,shuffle_training_X_only
11,YFQ,11,462,6212,6212,1243,0.241352,0.174975,0.165629,0.241352,0.616154,0.126043,0.143202,9.763899e-29,f1_macro,0.165629,0.019608,NaN,shuffle_training_X_only
12,YFQ,12,504,6212,6212,1243,0.225261,0.166262,0.161200,0.225261,0.621529,0.126043,0.143202,3.298989e-22,f1_macro,0.161200,0.019608,NaN,shuffle_training_X_only
13,YFQ,13,546,6212,6212,1243,0.224457,0.168272,0.164059,0.224457,0.618221,0.126043,0.143202,6.673545e-22,f1_macro,0.164059,0.019608,NaN,shuffle_training_X_only
14,YFQ,14,588,6212,6212,1243,0.229284,0.167289,0.159512,0.229284,0.628663,0.126043,0.143202,9.097744e-24,f1_macro,0.159512,0.019608,NaN,shuffle_training_X_only
15,YFQ,15,630,6212,6212,1243,0.231698,0.175003,0.171797,0.231698,0.616794,0.126043,0.143202,9.994838e-25,f1_macro,0.171797,0.019608,NaN,shuffle_training_X_only
16,YFQ,16,672,6212,6212,1243,0.240547,0.177025,0.169803,0.240547,0.639888,0.126043,0.143202,2.159220e-28,f1_macro,0.169803,0.019608,NaN,shuffle_training_X_only
17,YFQ,17,714,6212,6212,1243,0.218825,0.156093,0.144922,0.218825,0.622936,0.126043,0.143202,8.136216e-20,f1_macro,0.144922,0.019608,NaN,shuffle_training_X_only
18,YFQ,18,756,6212,6212,1243,0.226066,0.167719,0.162149,0.226066,0.627004,0.126043,0.143202,1.623408e-22,f1_macro,0.162149,0.019608,NaN,shuffle_training_X_only
19,YFQ,19,798,6212,6212,1243,0.230893,0.171378,0.165609,0.230893,0.626880,0.126043,0.143202,2.096245e-24,f1_macro,0.165609,0.019608,NaN,shuffle_training_X_only

aggregated YFQ 2025-06-19 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFQ/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-06-19/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFQ,0,0,1381,1381,277,0.191336,0.146081,0.129606,0.191336,0.567250,0.116918,0.133574,2.209707e-04,f1_macro,0.129606,0.058824,0.173823,shuffle_training_X_only
1,YFQ,1,42,1381,1381,277,0.220217,0.182793,0.185043,0.220217,0.597704,0.116918,0.133574,8.337602e-07,f1_macro,0.185043,0.019608,0.165585,shuffle_training_X_only
2,YFQ,2,84,1381,1381,277,0.184116,0.171235,0.173303,0.184116,0.596995,0.116918,0.133574,7.203842e-04,f1_macro,0.173303,0.019608,0.180706,shuffle_training_X_only
3,YFQ,3,126,1381,1381,277,0.162455,0.126581,0.117192,0.162455,0.546688,0.116918,0.133574,1.457123e-02,f1_macro,0.117192,0.137255,NaN,shuffle_training_X_only
4,YFQ,4,168,1381,1381,277,0.202166,0.160078,0.153290,0.202166,0.574849,0.116918,0.133574,3.190935e-05,f1_macro,0.153290,0.019608,NaN,shuffle_training_X_only
5,YFQ,5,210,1381,1381,277,0.212996,0.160652,0.146611,0.212996,0.636322,0.116918,0.133574,3.810573e-06,f1_macro,0.146611,0.019608,NaN,shuffle_training_X_only
6,YFQ,6,252,1381,1381,277,0.194946,0.154196,0.144484,0.194946,0.590548,0.116918,0.133574,1.184443e-04,f1_macro,0.144484,0.019608,NaN,shuffle_training_X_only
7,YFQ,7,294,1381,1381,277,0.209386,0.169465,0.162821,0.209386,0.608424,0.116918,0.133574,7.900456e-06,f1_macro,0.162821,0.019608,NaN,shuffle_training_X_only
8,YFQ,8,336,1381,1381,277,0.216606,0.171342,0.160919,0.216606,0.613532,0.116918,0.133574,1.800632e-06,f1_macro,0.160919,0.019608,NaN,shuffle_training_X_only
9,YFQ,9,378,1381,1381,277,0.209386,0.161239,0.145054,0.209386,0.563716,0.116918,0.133574,7.900456e-06,f1_macro,0.145054,0.019608,NaN,shuffle_training_X_only
10,YFQ,10,420,1381,1381,277,0.162455,0.127511,0.117017,0.162455,0.606731,0.116918,0.133574,1.457123e-02,f1_macro,0.117017,0.098039,NaN,shuffle_training_X_only
11,YFQ,11,462,1381,1381,277,0.158845,0.128117,0.121933,0.158845,0.581996,0.116918,0.133574,2.219145e-02,f1_macro,0.121933,0.039216,NaN,shuffle_training_X_only
12,YFQ,12,504,1381,1381,277,0.220217,0.173592,0.161610,0.220217,0.612544,0.116918,0.133574,8.337602e-07,f1_macro,0.161610,0.019608,NaN,shuffle_training_X_only
13,YFQ,13,546,1381,1381,277,0.137184,0.106470,0.099092,0.137184,0.610822,0.116918,0.133574,1.687931e-01,f1_macro,0.099092,0.196078,NaN,shuffle_training_X_only
14,YFQ,14,588,1381,1381,277,0.220217,0.169347,0.155495,0.220217,0.598841,0.116918,0.133574,8.337602e-07,f1_macro,0.155495,0.019608,NaN,shuffle_training_X_only
15,YFQ,15,630,1381,1381,277,0.216606,0.170650,0.160351,0.216606,0.620044,0.116918,0.133574,1.800632e-06,f1_macro,0.160351,0.019608,NaN,shuffle_training_X_only
16,YFQ,16,672,1381,1381,277,0.187726,0.149720,0.138272,0.187726,0.626261,0.116918,0.133574,4.033809e-04,f1_macro,0.138272,0.019608,NaN,shuffle_training_X_only
17,YFQ,17,714,1381,1381,277,0.180505,0.142670,0.135248,0.180505,0.609987,0.116918,0.133574,1.258317e-03,f1_macro,0.135248,0.058824,NaN,shuffle_training_X_only
18,YFQ,18,756,1381,1381,277,0.198556,0.154299,0.145378,0.198556,0.611119,0.116918,0.133574,6.213621e-05,f1_macro,0.145378,0.039216,NaN,shuffle_training_X_only
19,YFQ,19,798,1381,1381,277,0.191336,0.147964,0.138620,0.191336,0.583251,0.116918,0.133574,2.209707e-04,f1_macro,0.138620,0.019608,NaN,shuffle_training_X_only

skipping YFR 2025-06-30: not all resamples finished
aggregated YFR 2025-07-01 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFR/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-07-01/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFR,0,0,3735,3735,747,0.207497,0.167746,0.160989,0.207497,0.603664,0.115878,0.128514,5.774337e-13,f1_macro,0.160989,0.019608,0.163961,shuffle_training_X_only
1,YFR,1,42,3735,3735,747,0.211513,0.170327,0.162100,0.211513,0.594328,0.115878,0.128514,6.780313e-14,f1_macro,0.162100,0.019608,0.161929,shuffle_training_X_only
2,YFR,2,84,3735,3735,747,0.219545,0.175183,0.165012,0.219545,0.610436,0.115878,0.128514,7.566605e-16,f1_macro,0.165012,0.019608,0.158814,shuffle_training_X_only
3,YFR,3,126,3735,3735,747,0.176707,0.140677,0.131308,0.176707,0.570613,0.115878,0.128514,6.734386e-07,f1_macro,0.131308,0.019608,NaN,shuffle_training_X_only
4,YFR,4,168,3735,3735,747,0.198126,0.160022,0.153770,0.198126,0.601958,0.115878,0.128514,6.461457e-11,f1_macro,0.153770,0.019608,NaN,shuffle_training_X_only
5,YFR,5,210,3735,3735,747,0.219545,0.176086,0.166788,0.219545,0.603721,0.115878,0.128514,7.566605e-16,f1_macro,0.166788,0.019608,NaN,shuffle_training_X_only
6,YFR,6,252,3735,3735,747,0.195448,0.156920,0.148580,0.195448,0.616266,0.115878,0.128514,2.311291e-10,f1_macro,0.148580,0.019608,NaN,shuffle_training_X_only
7,YFR,7,294,3735,3735,747,0.204819,0.168418,0.163311,0.204819,0.595671,0.115878,0.128514,2.314196e-12,f1_macro,0.163311,0.019608,NaN,shuffle_training_X_only
8,YFR,8,336,3735,3735,747,0.178046,0.140374,0.133040,0.178046,0.593971,0.115878,0.128514,4.028937e-07,f1_macro,0.133040,0.019608,NaN,shuffle_training_X_only
9,YFR,9,378,3735,3735,747,0.187416,0.152642,0.146032,0.187416,0.583240,0.115878,0.128514,8.661281e-09,f1_macro,0.146032,0.019608,NaN,shuffle_training_X_only
10,YFR,10,420,3735,3735,747,0.170013,0.135948,0.129561,0.170013,0.599690,0.115878,0.128514,7.691272e-06,f1_macro,0.129561,0.019608,NaN,shuffle_training_X_only
11,YFR,11,462,3735,3735,747,0.235609,0.186889,0.174355,0.235609,0.600871,0.115878,0.128514,4.139969e-20,f1_macro,0.174355,0.019608,NaN,shuffle_training_X_only
12,YFR,12,504,3735,3735,747,0.207497,0.164387,0.156158,0.207497,0.611694,0.115878,0.128514,5.774337e-13,f1_macro,0.156158,0.019608,NaN,shuffle_training_X_only
13,YFR,13,546,3735,3735,747,0.212851,0.171193,0.161872,0.212851,0.592154,0.115878,0.128514,3.268251e-14,f1_macro,0.161872,0.019608,NaN,shuffle_training_X_only
14,YFR,14,588,3735,3735,747,0.194110,0.155336,0.146921,0.194110,0.608008,0.115878,0.128514,4.317469e-10,f1_macro,0.146921,0.019608,NaN,shuffle_training_X_only
15,YFR,15,630,3735,3735,747,0.198126,0.159184,0.151280,0.198126,0.594464,0.115878,0.128514,6.461457e-11,f1_macro,0.151280,0.019608,NaN,shuffle_training_X_only
16,YFR,16,672,3735,3735,747,0.165997,0.132273,0.125544,0.165997,0.575626,0.115878,0.128514,2.976595e-05,f1_macro,0.125544,0.019608,NaN,shuffle_training_X_only
17,YFR,17,714,3735,3735,747,0.202142,0.162579,0.152166,0.202142,0.606321,0.115878,0.128514,8.981399e-12,f1_macro,0.152166,0.019608,NaN,shuffle_training_X_only
18,YFR,18,756,3735,3735,747,0.214190,0.173079,0.165967,0.214190,0.606787,0.115878,0.128514,1.563075e-14,f1_macro,0.165967,0.019608,NaN,shuffle_training_X_only
19,YFR,19,798,3735,3735,747,0.212851,0.172405,0.166745,0.212851,0.609136,0.115878,0.128514,3.268251e-14,f1_macro,0.166745,0.019608,NaN,shuffle_training_X_only

aggregated YFR 2025-07-02 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFR/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-07-02/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFR,0,0,9516,9516,1904,0.231618,0.186676,0.184677,0.231618,0.644834,0.122675,0.138655,1.335627e-39,f1_macro,0.184677,0.019608,0.185464,shuffle_training_X_only
1,YFR,1,42,9516,9516,1904,0.238445,0.184147,0.175464,0.238445,0.624661,0.122675,0.138655,4.606591e-44,f1_macro,0.175464,0.019608,0.183765,shuffle_training_X_only
2,YFR,2,84,9516,9516,1904,0.226366,0.181545,0.178396,0.226366,0.632924,0.122675,0.138655,2.582638e-36,f1_macro,0.178396,0.019608,0.187953,shuffle_training_X_only
3,YFR,3,126,9516,9516,1904,0.236345,0.185825,0.178450,0.236345,0.653315,0.122675,0.138655,1.145661e-42,f1_macro,0.178450,0.019608,NaN,shuffle_training_X_only
4,YFR,4,168,9516,9516,1904,0.241597,0.191377,0.186716,0.241597,0.641189,0.122675,0.138655,3.407617e-46,f1_macro,0.186716,0.019608,NaN,shuffle_training_X_only
5,YFR,5,210,9516,9516,1904,0.237395,0.184351,0.175438,0.237395,0.657527,0.122675,0.138655,2.310585e-43,f1_macro,0.175438,0.019608,NaN,shuffle_training_X_only
6,YFR,6,252,9516,9516,1904,0.244748,0.193231,0.186523,0.244748,0.646511,0.122675,0.138655,2.274943e-48,f1_macro,0.186523,0.019608,NaN,shuffle_training_X_only
7,YFR,7,294,9516,9516,1904,0.234769,0.183806,0.176712,0.234769,0.634416,0.122675,0.138655,1.237756e-41,f1_macro,0.176712,0.019608,NaN,shuffle_training_X_only
8,YFR,8,336,9516,9516,1904,0.249475,0.198530,0.193375,0.249475,0.641139,0.122675,0.138655,1.025750e-51,f1_macro,0.193375,0.019608,NaN,shuffle_training_X_only
9,YFR,9,378,9516,9516,1904,0.223214,0.177782,0.173271,0.223214,0.629766,0.122675,0.138655,2.098780e-34,f1_macro,0.173271,0.019608,NaN,shuffle_training_X_only
10,YFR,10,420,9516,9516,1904,0.232668,0.180312,0.170751,0.232668,0.645429,0.122675,0.138655,2.838394e-40,f1_macro,0.170751,0.019608,NaN,shuffle_training_X_only
11,YFR,11,462,9516,9516,1904,0.231092,0.178833,0.168406,0.231092,0.643844,0.122675,0.138655,2.884585e-39,f1_macro,0.168406,0.019608,NaN,shuffle_training_X_only
12,YFR,12,504,9516,9516,1904,0.250000,0.201437,0.198389,0.250000,0.651529,0.122675,0.138655,4.297248e-52,f1_macro,0.198389,0.019608,NaN,shuffle_training_X_only
13,YFR,13,546,9516,9516,1904,0.246849,0.195992,0.192266,0.246849,0.650562,0.122675,0.138655,7.622316e-50,f1_macro,0.192266,0.019608,NaN,shuffle_training_X_only
14,YFR,14,588,9516,9516,1904,0.223739,0.174398,0.165923,0.223739,0.632866,0.122675,0.138655,1.016016e-34,f1_macro,0.165923,0.019608,NaN,shuffle_training_X_only
15,YFR,15,630,9516,9516,1904,0.227941,0.182136,0.177844,0.227941,0.641683,0.122675,0.138655,2.751897e-37,f1_macro,0.177844,0.019608,NaN,shuffle_training_X_only
16,YFR,16,672,9516,9516,1904,0.233718,0.187578,0.184010,0.233718,0.626894,0.122675,0.138655,5.961893e-41,f1_macro,0.184010,0.019608,NaN,shuffle_training_X_only
17,YFR,17,714,9516,9516,1904,0.243172,0.191224,0.182995,0.243172,0.635789,0.122675,0.138655,2.820043e-47,f1_macro,0.182995,0.019608,NaN,shuffle_training_X_only
18,YFR,18,756,9516,9516,1904,0.247374,0.198961,0.192431,0.247374,0.642323,0.122675,0.138655,3.238258e-50,f1_macro,0.192431,0.019608,NaN,shuffle_training_X_only
19,YFR,19,798,9516,9516,1904,0.237920,0.191083,0.187739,0.237920,0.651797,0.122675,0.138655,1.033180e-43,f1_macro,0.187739,0.019608,NaN,shuffle_training_X_only

aggregated YFR 2025-07-03 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFR/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-07-03/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFR,0,0,2857,2857,572,0.243007,0.197073,0.193673,0.243007,0.663487,0.124676,0.134615,7.319949e-15,f1_macro,0.193673,0.019608,0.176560,shuffle_training_X_only
1,YFR,1,42,2857,2857,572,0.229021,0.175121,0.163843,0.229021,0.630657,0.124676,0.134615,3.892830e-12,f1_macro,0.163843,0.019608,0.178721,shuffle_training_X_only
2,YFR,2,84,2857,2857,572,0.246503,0.190967,0.182742,0.246503,0.632320,0.124676,0.134615,1.387418e-15,f1_macro,0.182742,0.019608,0.197694,shuffle_training_X_only
3,YFR,3,126,2857,2857,572,0.225524,0.178048,0.168337,0.225524,0.647094,0.124676,0.134615,1.698590e-11,f1_macro,0.168337,0.019608,NaN,shuffle_training_X_only
4,YFR,4,168,2857,2857,572,0.263986,0.197848,0.184058,0.263986,0.644388,0.124676,0.134615,1.961363e-19,f1_macro,0.184058,0.019608,NaN,shuffle_training_X_only
5,YFR,5,210,2857,2857,572,0.211538,0.158306,0.147974,0.211538,0.628215,0.124676,0.134615,4.150405e-09,f1_macro,0.147974,0.019608,NaN,shuffle_training_X_only
6,YFR,6,252,2857,2857,572,0.215035,0.166747,0.159607,0.215035,0.624978,0.124676,0.134615,1.114605e-09,f1_macro,0.159607,0.019608,NaN,shuffle_training_X_only
7,YFR,7,294,2857,2857,572,0.258741,0.210971,0.211320,0.258741,0.660824,0.124676,0.134615,3.080397e-18,f1_macro,0.211320,0.019608,NaN,shuffle_training_X_only
8,YFR,8,336,2857,2857,572,0.248252,0.195125,0.188559,0.248252,0.648496,0.124676,0.134615,5.956997e-16,f1_macro,0.188559,0.019608,NaN,shuffle_training_X_only
9,YFR,9,378,2857,2857,572,0.236014,0.180510,0.172901,0.236014,0.651665,0.124676,0.134615,1.821260e-13,f1_macro,0.172901,0.019608,NaN,shuffle_training_X_only
10,YFR,10,420,2857,2857,572,0.223776,0.170644,0.158779,0.223776,0.619890,0.124676,0.134615,3.496628e-11,f1_macro,0.158779,0.019608,NaN,shuffle_training_X_only
11,YFR,11,462,2857,2857,572,0.241259,0.180190,0.165177,0.241259,0.628807,0.124676,0.134615,1.658033e-14,f1_macro,0.165177,0.019608,NaN,shuffle_training_X_only
12,YFR,12,504,2857,2857,572,0.225524,0.173764,0.161086,0.225524,0.621788,0.124676,0.134615,1.698590e-11,f1_macro,0.161086,0.019608,NaN,shuffle_training_X_only
13,YFR,13,546,2857,2857,572,0.237762,0.184474,0.177291,0.237762,0.649131,0.124676,0.134615,8.270725e-14,f1_macro,0.177291,0.019608,NaN,shuffle_training_X_only
14,YFR,14,588,2857,2857,572,0.232517,0.174084,0.161163,0.232517,0.633362,0.124676,0.134615,8.583035e-13,f1_macro,0.161163,0.019608,NaN,shuffle_training_X_only
15,YFR,15,630,2857,2857,572,0.229021,0.171293,0.155170,0.229021,0.648481,0.124676,0.134615,3.892830e-12,f1_macro,0.155170,0.019608,NaN,shuffle_training_X_only
16,YFR,16,672,2857,2857,572,0.239510,0.187401,0.177867,0.239510,0.636959,0.124676,0.134615,3.720585e-14,f1_macro,0.177867,0.019608,NaN,shuffle_training_X_only
17,YFR,17,714,2857,2857,572,0.225524,0.172136,0.161096,0.225524,0.634370,0.124676,0.134615,1.698590e-11,f1_macro,0.161096,0.019608,NaN,shuffle_training_X_only
18,YFR,18,756,2857,2857,572,0.218531,0.163888,0.149363,0.218531,0.641228,0.124676,0.134615,2.875300e-10,f1_macro,0.149363,0.019608,NaN,shuffle_training_X_only
19,YFR,19,798,2857,2857,572,0.256993,0.195319,0.180808,0.256993,0.644807,0.124676,0.134615,7.577313e-18,f1_macro,0.180808,0.019608,NaN,shuffle_training_X_only

aggregated YFR 2025-07-04 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFR/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-07-04/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFR,0,0,5722,5722,1145,0.233188,0.174937,0.160233,0.233188,0.609575,0.123233,0.135371,7.136200e-25,f1_macro,0.160233,0.019608,0.166438,shuffle_training_X_only
1,YFR,1,42,5722,5722,1145,0.241048,0.182330,0.171384,0.241048,0.643153,0.123233,0.135371,5.388680e-28,f1_macro,0.171384,0.019608,0.177202,shuffle_training_X_only
2,YFR,2,84,5722,5722,1145,0.235808,0.177789,0.166489,0.235808,0.618843,0.123233,0.135371,6.784265e-26,f1_macro,0.166489,0.019608,0.171432,shuffle_training_X_only
3,YFR,3,126,5722,5722,1145,0.215721,0.161938,0.152274,0.215721,0.592153,0.123233,0.135371,1.503516e-18,f1_macro,0.152274,0.019608,NaN,shuffle_training_X_only
4,YFR,4,168,5722,5722,1145,0.228821,0.172559,0.164525,0.228821,0.588548,0.123233,0.135371,3.271269e-23,f1_macro,0.164525,0.019608,NaN,shuffle_training_X_only
5,YFR,5,210,5722,5722,1145,0.220961,0.166779,0.158448,0.220961,0.613235,0.123233,0.135371,2.347973e-20,f1_macro,0.158448,0.019608,NaN,shuffle_training_X_only
6,YFR,6,252,5722,5722,1145,0.244541,0.187999,0.179811,0.244541,0.603696,0.123233,0.135371,1.951396e-29,f1_macro,0.179811,0.019608,NaN,shuffle_training_X_only
7,YFR,7,294,5722,5722,1145,0.241048,0.184137,0.178460,0.241048,0.623505,0.123233,0.135371,5.388680e-28,f1_macro,0.178460,0.019608,NaN,shuffle_training_X_only
8,YFR,8,336,5722,5722,1145,0.261135,0.197634,0.187277,0.261135,0.618646,0.123233,0.135371,1.012668e-36,f1_macro,0.187277,0.019608,NaN,shuffle_training_X_only
9,YFR,9,378,5722,5722,1145,0.238428,0.181629,0.173758,0.238428,0.609939,0.123233,0.135371,6.177268e-27,f1_macro,0.173758,0.019608,NaN,shuffle_training_X_only
10,YFR,10,420,5722,5722,1145,0.227948,0.172722,0.162560,0.227948,0.606706,0.123233,0.135371,6.928120e-23,f1_macro,0.162560,0.019608,NaN,shuffle_training_X_only
11,YFR,11,462,5722,5722,1145,0.247162,0.186188,0.174742,0.247162,0.627080,0.123233,0.135371,1.542127e-30,f1_macro,0.174742,0.019608,NaN,shuffle_training_X_only
12,YFR,12,504,5722,5722,1145,0.223581,0.175402,0.171196,0.223581,0.612597,0.123233,0.135371,2.741967e-21,f1_macro,0.171196,0.019608,NaN,shuffle_training_X_only
13,YFR,13,546,5722,5722,1145,0.258515,0.194988,0.180053,0.258515,0.627592,0.123233,0.135371,1.596895e-35,f1_macro,0.180053,0.019608,NaN,shuffle_training_X_only
14,YFR,14,588,5722,5722,1145,0.239301,0.181402,0.171126,0.239301,0.620436,0.123233,0.135371,2.752661e-27,f1_macro,0.171126,0.019608,NaN,shuffle_training_X_only
15,YFR,15,630,5722,5722,1145,0.234061,0.177000,0.166684,0.234061,0.624512,0.123233,0.135371,3.272677e-25,f1_macro,0.166684,0.019608,NaN,shuffle_training_X_only
16,YFR,16,672,5722,5722,1145,0.222707,0.167462,0.156081,0.222707,0.596421,0.123233,0.135371,5.637719e-21,f1_macro,0.156081,0.019608,NaN,shuffle_training_X_only
17,YFR,17,714,5722,5722,1145,0.237555,0.178653,0.167154,0.237555,0.606027,0.123233,0.135371,1.379662e-26,f1_macro,0.167154,0.019608,NaN,shuffle_training_X_only
18,YFR,18,756,5722,5722,1145,0.218341,0.167265,0.160308,0.218341,0.615715,0.123233,0.135371,1.922030e-19,f1_macro,0.160308,0.019608,NaN,shuffle_training_X_only
19,YFR,19,798,5722,5722,1145,0.253275,0.191020,0.180843,0.253275,0.619421,0.123233,0.135371,3.513753e-33,f1_macro,0.180843,0.019608,NaN,shuffle_training_X_only

aggregated YFR 2025-07-05 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFR/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-07-05/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFR,0,0,5544,5544,1109,0.185753,0.142817,0.134365,0.185753,0.607340,0.120606,0.138864,2.662032e-10,f1_macro,0.134365,0.019608,0.152118,shuffle_training_X_only
1,YFR,1,42,5544,5544,1109,0.190261,0.150147,0.146065,0.190261,0.596009,0.120606,0.138864,1.847105e-11,f1_macro,0.146065,0.019608,0.154616,shuffle_training_X_only
2,YFR,2,84,5544,5544,1109,0.211001,0.161326,0.151250,0.211001,0.610215,0.120606,0.138864,1.418825e-17,f1_macro,0.151250,0.019608,0.155986,shuffle_training_X_only
3,YFR,3,126,5544,5544,1109,0.201082,0.155716,0.148713,0.201082,0.596195,0.120606,0.138864,1.715179e-14,f1_macro,0.148713,0.019608,NaN,shuffle_training_X_only
4,YFR,4,168,5544,5544,1109,0.209197,0.160609,0.151815,0.209197,0.606392,0.120606,0.138864,5.413333e-17,f1_macro,0.151815,0.019608,NaN,shuffle_training_X_only
5,YFR,5,210,5544,5544,1109,0.203787,0.157464,0.146271,0.203787,0.607914,0.120606,0.138864,2.642184e-15,f1_macro,0.146271,0.019608,NaN,shuffle_training_X_only
6,YFR,6,252,5544,5544,1109,0.211001,0.162542,0.154923,0.211001,0.610126,0.120606,0.138864,1.418825e-17,f1_macro,0.154923,0.019608,NaN,shuffle_training_X_only
7,YFR,7,294,5544,5544,1109,0.200180,0.153846,0.145043,0.200180,0.600295,0.120606,0.138864,3.164596e-14,f1_macro,0.145043,0.019608,NaN,shuffle_training_X_only
8,YFR,8,336,5544,5544,1109,0.221821,0.172357,0.162836,0.221821,0.594221,0.120606,0.138864,2.951455e-21,f1_macro,0.162836,0.019608,NaN,shuffle_training_X_only
9,YFR,9,378,5544,5544,1109,0.213706,0.163389,0.152160,0.213706,0.593668,0.120606,0.138864,1.829262e-18,f1_macro,0.152160,0.019608,NaN,shuffle_training_X_only
10,YFR,10,420,5544,5544,1109,0.200180,0.155051,0.147644,0.200180,0.595254,0.120606,0.138864,3.164596e-14,f1_macro,0.147644,0.019608,NaN,shuffle_training_X_only
11,YFR,11,462,5544,5544,1109,0.211903,0.164219,0.153519,0.211903,0.587023,0.120606,0.138864,7.205839e-18,f1_macro,0.153519,0.019608,NaN,shuffle_training_X_only
12,YFR,12,504,5544,5544,1109,0.207394,0.162604,0.157057,0.207394,0.586887,0.120606,0.138864,2.021554e-16,f1_macro,0.157057,0.019608,NaN,shuffle_training_X_only
13,YFR,13,546,5544,5544,1109,0.185753,0.143520,0.135888,0.185753,0.604215,0.120606,0.138864,2.662032e-10,f1_macro,0.135888,0.019608,NaN,shuffle_training_X_only
14,YFR,14,588,5544,5544,1109,0.229035,0.178646,0.171028,0.229035,0.608884,0.120606,0.138864,6.848930e-24,f1_macro,0.171028,0.019608,NaN,shuffle_training_X_only
15,YFR,15,630,5544,5544,1109,0.197475,0.152686,0.144752,0.197475,0.603071,0.120606,0.138864,1.922757e-13,f1_macro,0.144752,0.019608,NaN,shuffle_training_X_only
16,YFR,16,672,5544,5544,1109,0.215509,0.164790,0.153754,0.215509,0.589850,0.120606,0.138864,4.546576e-19,f1_macro,0.153754,0.019608,NaN,shuffle_training_X_only
17,YFR,17,714,5544,5544,1109,0.208296,0.163396,0.157374,0.208296,0.592204,0.120606,0.138864,1.048921e-16,f1_macro,0.157374,0.019608,NaN,shuffle_training_X_only
18,YFR,18,756,5544,5544,1109,0.204689,0.160436,0.154242,0.204689,0.601584,0.120606,0.138864,1.400978e-15,f1_macro,0.154242,0.019608,NaN,shuffle_training_X_only
19,YFR,19,798,5544,5544,1109,0.203787,0.161578,0.155625,0.203787,0.589787,0.120606,0.138864,2.642184e-15,f1_macro,0.155625,0.019608,NaN,shuffle_training_X_only

aggregated YFR 2025-07-06 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFR/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-07-06/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFR,0,0,13424,13424,2685,0.179516,0.151243,0.141222,0.179516,0.588095,0.110393,0.123277,1.864439e-26,f1_macro,0.141222,0.019608,0.142347,shuffle_training_X_only
1,YFR,1,42,13424,13424,2685,0.182495,0.153289,0.142757,0.182495,0.595121,0.110393,0.123277,1.784615e-28,f1_macro,0.142757,0.019608,0.147716,shuffle_training_X_only
2,YFR,2,84,13424,13424,2685,0.179888,0.151439,0.140821,0.179888,0.578650,0.110393,0.123277,1.051864e-26,f1_macro,0.140821,0.019608,0.141431,shuffle_training_X_only
3,YFR,3,126,13424,13424,2685,0.170577,0.144132,0.136063,0.170577,0.580542,0.110393,0.123277,8.066366e-21,f1_macro,0.136063,0.019608,NaN,shuffle_training_X_only
4,YFR,4,168,13424,13424,2685,0.176536,0.150243,0.142640,0.176536,0.592196,0.110393,0.123277,1.659524e-24,f1_macro,0.142640,0.019608,NaN,shuffle_training_X_only
5,YFR,5,210,13424,13424,2685,0.173557,0.149263,0.143613,0.173557,0.593598,0.110393,0.123277,1.255998e-22,f1_macro,0.143613,0.019608,NaN,shuffle_training_X_only
6,YFR,6,252,13424,13424,2685,0.176164,0.151566,0.146037,0.176164,0.579066,0.110393,0.123277,2.875601e-24,f1_macro,0.146037,0.019608,NaN,shuffle_training_X_only
7,YFR,7,294,13424,13424,2685,0.178399,0.152473,0.146156,0.178399,0.578814,0.110393,0.123277,1.022786e-25,f1_macro,0.146156,0.019608,NaN,shuffle_training_X_only
8,YFR,8,336,13424,13424,2685,0.174302,0.150217,0.145342,0.174302,0.591474,0.110393,0.123277,4.324026e-23,f1_macro,0.145342,0.019608,NaN,shuffle_training_X_only
9,YFR,9,378,13424,13424,2685,0.180633,0.154592,0.147836,0.180633,0.583061,0.110393,0.123277,3.322988e-27,f1_macro,0.147836,0.019608,NaN,shuffle_training_X_only
10,YFR,10,420,13424,13424,2685,0.186965,0.157738,0.149279,0.186965,0.577946,0.110393,0.123277,1.242863e-31,f1_macro,0.149279,0.019608,NaN,shuffle_training_X_only
11,YFR,11,462,13424,13424,2685,0.183613,0.154182,0.144886,0.183613,0.580917,0.110393,0.123277,2.996775e-29,f1_macro,0.144886,0.019608,NaN,shuffle_training_X_only
12,YFR,12,504,13424,13424,2685,0.174302,0.146579,0.136704,0.174302,0.585482,0.110393,0.123277,4.324026e-23,f1_macro,0.136704,0.019608,NaN,shuffle_training_X_only
13,YFR,13,546,13424,13424,2685,0.165736,0.139799,0.131068,0.165736,0.584713,0.110393,0.123277,4.894531e-18,f1_macro,0.131068,0.019608,NaN,shuffle_training_X_only
14,YFR,14,588,13424,13424,2685,0.180261,0.153523,0.146738,0.180261,0.590602,0.110393,0.123277,5.919515e-27,f1_macro,0.146738,0.019608,NaN,shuffle_training_X_only
15,YFR,15,630,13424,13424,2685,0.178399,0.152165,0.145510,0.178399,0.577031,0.110393,0.123277,1.022786e-25,f1_macro,0.145510,0.019608,NaN,shuffle_training_X_only
16,YFR,16,672,13424,13424,2685,0.177654,0.149318,0.139510,0.177654,0.591026,0.110393,0.123277,3.141607e-25,f1_macro,0.139510,0.019608,NaN,shuffle_training_X_only
17,YFR,17,714,13424,13424,2685,0.175791,0.146985,0.136434,0.175791,0.585480,0.110393,0.123277,4.970176e-24,f1_macro,0.136434,0.019608,NaN,shuffle_training_X_only
18,YFR,18,756,13424,13424,2685,0.177654,0.149928,0.140913,0.177654,0.586251,0.110393,0.123277,3.141607e-25,f1_macro,0.140913,0.019608,NaN,shuffle_training_X_only
19,YFR,19,798,13424,13424,2685,0.175791,0.148738,0.140757,0.175791,0.586497,0.110393,0.123277,4.970176e-24,f1_macro,0.140757,0.019608,NaN,shuffle_training_X_only

aggregated YFR 2025-07-07 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFR/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-07-07/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFR,0,0,1749,1749,350,0.180000,0.136750,0.126826,0.180000,0.567230,0.118645,0.137143,5.235467e-04,f1_macro,0.126826,0.019608,0.130776,shuffle_training_X_only
1,YFR,1,42,1749,1749,350,0.194286,0.145250,0.131679,0.194286,0.564150,0.118645,0.137143,3.106006e-05,f1_macro,0.131679,0.019608,0.147335,shuffle_training_X_only
2,YFR,2,84,1749,1749,350,0.177143,0.148793,0.151401,0.177143,0.555221,0.118645,0.137143,8.733696e-04,f1_macro,0.151401,0.019608,0.149159,shuffle_training_X_only
3,YFR,3,126,1749,1749,350,0.177143,0.133167,0.120682,0.177143,0.573974,0.118645,0.137143,8.733696e-04,f1_macro,0.120682,0.117647,NaN,shuffle_training_X_only
4,YFR,4,168,1749,1749,350,0.165714,0.124833,0.113281,0.165714,0.565798,0.118645,0.137143,5.638907e-03,f1_macro,0.113281,0.078431,NaN,shuffle_training_X_only
5,YFR,5,210,1749,1749,350,0.197143,0.147750,0.134953,0.197143,0.550954,0.118645,0.137143,1.675579e-05,f1_macro,0.134953,0.019608,NaN,shuffle_training_X_only
6,YFR,6,252,1749,1749,350,0.182857,0.135417,0.119328,0.182857,0.578594,0.118645,0.137143,3.082693e-04,f1_macro,0.119328,0.039216,NaN,shuffle_training_X_only
7,YFR,7,294,1749,1749,350,0.182857,0.139667,0.128852,0.182857,0.543068,0.118645,0.137143,3.082693e-04,f1_macro,0.128852,0.019608,NaN,shuffle_training_X_only
8,YFR,8,336,1749,1749,350,0.151429,0.118379,0.115659,0.151429,0.539732,0.118645,0.137143,3.821164e-02,f1_macro,0.115659,0.039216,NaN,shuffle_training_X_only
9,YFR,9,378,1749,1749,350,0.182857,0.137333,0.125994,0.182857,0.579616,0.118645,0.137143,3.082693e-04,f1_macro,0.125994,0.019608,NaN,shuffle_training_X_only
10,YFR,10,420,1749,1749,350,0.200000,0.149417,0.135615,0.200000,0.572412,0.118645,0.137143,8.885985e-06,f1_macro,0.135615,0.019608,NaN,shuffle_training_X_only
11,YFR,11,462,1749,1749,350,0.217143,0.160833,0.146299,0.217143,0.564845,0.118645,0.137143,1.391168e-07,f1_macro,0.146299,0.019608,NaN,shuffle_training_X_only
12,YFR,12,504,1749,1749,350,0.160000,0.116667,0.103290,0.160000,0.554754,0.118645,0.137143,1.282512e-02,f1_macro,0.103290,0.352941,NaN,shuffle_training_X_only
13,YFR,13,546,1749,1749,350,0.182857,0.135833,0.122334,0.182857,0.571492,0.118645,0.137143,3.082693e-04,f1_macro,0.122334,0.039216,NaN,shuffle_training_X_only
14,YFR,14,588,1749,1749,350,0.174286,0.130667,0.119554,0.174286,0.549456,0.118645,0.137143,1.430868e-03,f1_macro,0.119554,0.039216,NaN,shuffle_training_X_only
15,YFR,15,630,1749,1749,350,0.205714,0.153583,0.138515,0.205714,0.569367,0.118645,0.137143,2.375521e-06,f1_macro,0.138515,0.019608,NaN,shuffle_training_X_only
16,YFR,16,672,1749,1749,350,0.180000,0.132917,0.121166,0.180000,0.574345,0.118645,0.137143,5.235467e-04,f1_macro,0.121166,0.078431,NaN,shuffle_training_X_only
17,YFR,17,714,1749,1749,350,0.197143,0.149000,0.138895,0.197143,0.588414,0.118645,0.137143,1.675579e-05,f1_macro,0.138895,0.019608,NaN,shuffle_training_X_only
18,YFR,18,756,1749,1749,350,0.185714,0.137083,0.120957,0.185714,0.561939,0.118645,0.137143,1.783127e-04,f1_macro,0.120957,0.078431,NaN,shuffle_training_X_only
19,YFR,19,798,1749,1749,350,0.154286,0.114833,0.102706,0.154286,0.548345,0.118645,0.137143,2.706151e-02,f1_macro,0.102706,0.333333,NaN,shuffle_training_X_only

aggregated YFT 2025-07-28 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFT/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-07-28/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFT,0,0,2794,2794,559,0.193202,0.153246,0.155815,0.193202,0.585224,0.123422,0.141324,1.698138e-06,f1_macro,0.155815,0.019608,0.144684,shuffle_training_X_only
1,YFT,1,42,2794,2794,559,0.207513,0.163956,0.164549,0.207513,0.591200,0.123422,0.141324,1.482388e-08,f1_macro,0.164549,0.019608,0.147177,shuffle_training_X_only
2,YFT,2,84,2794,2794,559,0.203936,0.153015,0.147165,0.203936,0.601539,0.123422,0.141324,5.171423e-08,f1_macro,0.147165,0.019608,0.157442,shuffle_training_X_only
3,YFT,3,126,2794,2794,559,0.168157,0.126162,0.121735,0.168157,0.602799,0.123422,0.141324,1.234546e-03,f1_macro,0.121735,0.019608,NaN,shuffle_training_X_only
4,YFT,4,168,2794,2794,559,0.175313,0.131045,0.125639,0.175313,0.592193,0.123422,0.141324,2.361905e-04,f1_macro,0.125639,0.039216,NaN,shuffle_training_X_only
5,YFT,5,210,2794,2794,559,0.250447,0.194398,0.191664,0.250447,0.597091,0.123422,0.141324,1.928771e-16,f1_macro,0.191664,0.019608,NaN,shuffle_training_X_only
6,YFT,6,252,2794,2794,559,0.205725,0.157539,0.152192,0.205725,0.613190,0.123422,0.141324,2.783441e-08,f1_macro,0.152192,0.019608,NaN,shuffle_training_X_only
7,YFT,7,294,2794,2794,559,0.178891,0.136361,0.131806,0.178891,0.607883,0.123422,0.141324,9.637102e-05,f1_macro,0.131806,0.019608,NaN,shuffle_training_X_only
8,YFT,8,336,2794,2794,559,0.187835,0.142690,0.137838,0.187835,0.623468,0.123422,0.141324,8.397594e-06,f1_macro,0.137838,0.019608,NaN,shuffle_training_X_only
9,YFT,9,378,2794,2794,559,0.221825,0.171655,0.169743,0.221825,0.594808,0.123422,0.141324,6.599727e-11,f1_macro,0.169743,0.019608,NaN,shuffle_training_X_only
10,YFT,10,420,2794,2794,559,0.198569,0.149278,0.143051,0.198569,0.581851,0.123422,0.141324,3.110989e-07,f1_macro,0.143051,0.019608,NaN,shuffle_training_X_only
11,YFT,11,462,2794,2794,559,0.221825,0.171361,0.166815,0.221825,0.608208,0.123422,0.141324,6.599727e-11,f1_macro,0.166815,0.019608,NaN,shuffle_training_X_only
12,YFT,12,504,2794,2794,559,0.202147,0.153050,0.148772,0.202147,0.614842,0.123422,0.141324,9.506526e-08,f1_macro,0.148772,0.019608,NaN,shuffle_training_X_only
13,YFT,13,546,2794,2794,559,0.184258,0.142999,0.140735,0.184258,0.603207,0.123422,0.141324,2.305553e-05,f1_macro,0.140735,0.019608,NaN,shuffle_training_X_only
14,YFT,14,588,2794,2794,559,0.173524,0.127172,0.120006,0.173524,0.592374,0.123422,0.141324,3.634187e-04,f1_macro,0.120006,0.019608,NaN,shuffle_training_X_only
15,YFT,15,630,2794,2794,559,0.221825,0.177834,0.181285,0.221825,0.619577,0.123422,0.141324,6.599727e-11,f1_macro,0.181285,0.019608,NaN,shuffle_training_X_only
16,YFT,16,672,2794,2794,559,0.194991,0.148167,0.145097,0.194991,0.595089,0.123422,0.141324,9.750200e-07,f1_macro,0.145097,0.019608,NaN,shuffle_training_X_only
17,YFT,17,714,2794,2794,559,0.216458,0.165370,0.163095,0.216458,0.593388,0.123422,0.141324,5.430191e-10,f1_macro,0.163095,0.019608,NaN,shuffle_training_X_only
18,YFT,18,756,2794,2794,559,0.223614,0.170147,0.166933,0.223614,0.619006,0.123422,0.141324,3.203551e-11,f1_macro,0.166933,0.019608,NaN,shuffle_training_X_only
19,YFT,19,798,2794,2794,559,0.194991,0.148170,0.143961,0.194991,0.579467,0.123422,0.141324,9.750200e-07,f1_macro,0.143961,0.019608,NaN,shuffle_training_X_only

aggregated YFT 2025-07-29 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFT/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-07-29/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFT,0,0,10757,9759,1952,0.214139,0.166231,0.164916,0.214139,0.608870,0.123691,0.143955,3.974233e-29,f1_macro,0.164916,0.019608,0.147961,shuffle_training_X_only
1,YFT,1,42,10757,9772,1955,0.221483,0.163615,0.152832,0.221483,0.603672,0.123757,0.144246,2.224739e-33,f1_macro,0.152832,0.019608,0.147484,shuffle_training_X_only
2,YFT,2,84,10757,9773,1955,0.197442,0.149616,0.143122,0.197442,0.610908,0.123752,0.144246,1.844008e-20,f1_macro,0.143122,0.019608,0.149646,shuffle_training_X_only
3,YFT,3,126,10757,9775,1955,0.203069,0.152119,0.146312,0.203069,0.595205,0.123744,0.143734,3.172680e-23,f1_macro,0.146312,0.019608,NaN,shuffle_training_X_only
4,YFT,4,168,10757,9776,1956,0.203988,0.153061,0.147668,0.203988,0.605447,0.123673,0.143661,9.529526e-24,f1_macro,0.147668,0.019608,NaN,shuffle_training_X_only
5,YFT,5,210,10757,9770,1954,0.193449,0.148774,0.147321,0.193449,0.608606,0.123732,0.143808,1.319666e-18,f1_macro,0.147321,0.019608,NaN,shuffle_training_X_only
6,YFT,6,252,10757,9739,1948,0.204825,0.160693,0.158018,0.204825,0.611225,0.123641,0.144764,4.169329e-24,f1_macro,0.158018,0.019608,NaN,shuffle_training_X_only
7,YFT,7,294,10757,9775,1955,0.191816,0.146881,0.145266,0.191816,0.599486,0.123739,0.143734,7.095854e-18,f1_macro,0.145266,0.019608,NaN,shuffle_training_X_only
8,YFT,8,336,10757,9761,1953,0.207373,0.151376,0.141354,0.207373,0.604128,0.123710,0.143881,1.910603e-25,f1_macro,0.141354,0.019608,NaN,shuffle_training_X_only
9,YFT,9,378,10757,9767,1954,0.220573,0.161648,0.152103,0.220573,0.593993,0.123728,0.144319,7.637123e-33,f1_macro,0.152103,0.019608,NaN,shuffle_training_X_only
10,YFT,10,420,10757,9761,1953,0.188428,0.142730,0.138310,0.188428,0.589597,0.123707,0.143369,2.129711e-16,f1_macro,0.138310,0.019608,NaN,shuffle_training_X_only
11,YFT,11,462,10757,9748,1950,0.205128,0.156777,0.152809,0.205128,0.604154,0.123666,0.143590,2.868328e-24,f1_macro,0.152809,0.019608,NaN,shuffle_training_X_only
12,YFT,12,504,10757,9779,1956,0.197342,0.148486,0.143824,0.197342,0.597963,0.123760,0.143661,2.036749e-20,f1_macro,0.143824,0.019608,NaN,shuffle_training_X_only
13,YFT,13,546,10757,9765,1953,0.198669,0.145087,0.135430,0.198669,0.606835,0.123633,0.143881,4.245880e-21,f1_macro,0.135430,0.019608,NaN,shuffle_training_X_only
14,YFT,14,588,10757,9784,1957,0.209504,0.159807,0.155163,0.209504,0.620149,0.123772,0.143587,1.372936e-26,f1_macro,0.155163,0.019608,NaN,shuffle_training_X_only
15,YFT,15,630,10757,9789,1958,0.186415,0.139531,0.133261,0.186415,0.594063,0.123803,0.144025,1.546375e-15,f1_macro,0.133261,0.019608,NaN,shuffle_training_X_only
16,YFT,16,672,10757,9743,1949,0.206260,0.157865,0.153002,0.206260,0.610631,0.123657,0.144690,7.540480e-25,f1_macro,0.153002,0.019608,NaN,shuffle_training_X_only
17,YFT,17,714,10757,9756,1952,0.201844,0.150239,0.142561,0.201844,0.594324,0.123613,0.144467,1.168225e-22,f1_macro,0.142561,0.019608,NaN,shuffle_training_X_only
18,YFT,18,756,10757,9772,1955,0.203069,0.152565,0.147101,0.203069,0.605573,0.123748,0.143734,3.191881e-23,f1_macro,0.147101,0.019608,NaN,shuffle_training_X_only
19,YFT,19,798,10757,9769,1954,0.206755,0.154087,0.146098,0.206755,0.608357,0.123727,0.143808,4.025776e-25,f1_macro,0.146098,0.019608,NaN,shuffle_training_X_only

aggregated YFT 2025-07-30 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFT/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-07-30/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFT,0,0,18706,15005,3001,0.194269,0.149753,0.142547,0.194269,0.598740,0.119689,0.139620,8.949242e-32,f1_macro,0.142547,0.019608,0.158119,shuffle_training_X_only
1,YFT,1,42,18706,15029,3006,0.216900,0.166012,0.157196,0.216900,0.612802,0.119730,0.139388,7.351972e-51,f1_macro,0.157196,0.019608,0.150775,shuffle_training_X_only
2,YFT,2,84,18706,14989,2998,0.209139,0.163143,0.157599,0.209139,0.608365,0.119642,0.139093,7.528698e-44,f1_macro,0.157599,0.019608,0.152236,shuffle_training_X_only
3,YFT,3,126,18706,14974,2995,0.204674,0.160752,0.156018,0.204674,0.608420,0.119612,0.138230,4.904939e-40,f1_macro,0.156018,0.019608,NaN,shuffle_training_X_only
4,YFT,4,168,18706,14950,2990,0.202007,0.162223,0.158997,0.202007,0.601623,0.119543,0.138796,7.554404e-38,f1_macro,0.158997,0.019608,NaN,shuffle_training_X_only
5,YFT,5,210,18706,14963,2993,0.189776,0.149418,0.145002,0.189776,0.597541,0.119523,0.138991,1.471288e-28,f1_macro,0.145002,0.019608,NaN,shuffle_training_X_only
6,YFT,6,252,18706,14948,2990,0.196656,0.154499,0.148849,0.196656,0.605190,0.119490,0.139130,1.152155e-33,f1_macro,0.148849,0.019608,NaN,shuffle_training_X_only
7,YFT,7,294,18706,14947,2990,0.202676,0.155509,0.148054,0.202676,0.613073,0.119484,0.138796,1.869989e-38,f1_macro,0.148054,0.019608,NaN,shuffle_training_X_only
8,YFT,8,336,18706,14957,2992,0.199866,0.159298,0.156855,0.199866,0.607762,0.119524,0.139372,3.611836e-36,f1_macro,0.156855,0.019608,NaN,shuffle_training_X_only
9,YFT,9,378,18706,14967,2994,0.196059,0.152679,0.147258,0.196059,0.604766,0.119593,0.139613,3.764993e-33,f1_macro,0.147258,0.019608,NaN,shuffle_training_X_only
10,YFT,10,420,18706,14999,3000,0.192667,0.153515,0.150877,0.192667,0.600163,0.119664,0.138333,1.352365e-30,f1_macro,0.150877,0.019608,NaN,shuffle_training_X_only
11,YFT,11,462,18706,14974,2995,0.196327,0.155234,0.151851,0.196327,0.605029,0.119612,0.138898,2.387427e-33,f1_macro,0.151851,0.019608,NaN,shuffle_training_X_only
12,YFT,12,504,18706,14949,2990,0.195987,0.153646,0.148917,0.195987,0.599505,0.119557,0.138796,4.357180e-33,f1_macro,0.148917,0.019608,NaN,shuffle_training_X_only
13,YFT,13,546,18706,14962,2993,0.194788,0.157108,0.155709,0.194788,0.608961,0.119588,0.138657,3.527251e-32,f1_macro,0.155709,0.019608,NaN,shuffle_training_X_only
14,YFT,14,588,18706,14925,2985,0.197320,0.153185,0.147139,0.197320,0.611606,0.119498,0.139028,4.069802e-34,f1_macro,0.147139,0.019608,NaN,shuffle_training_X_only
15,YFT,15,630,18706,14955,2991,0.197927,0.155106,0.150152,0.197927,0.602272,0.119552,0.138415,1.334246e-34,f1_macro,0.150152,0.019608,NaN,shuffle_training_X_only
16,YFT,16,672,18706,14948,2990,0.205017,0.162512,0.158230,0.205017,0.613688,0.119555,0.138796,2.557478e-40,f1_macro,0.158230,0.019608,NaN,shuffle_training_X_only
17,YFT,17,714,18706,14977,2996,0.196929,0.158499,0.157199,0.196929,0.601732,0.119621,0.139519,8.173934e-34,f1_macro,0.157199,0.019608,NaN,shuffle_training_X_only
18,YFT,18,756,18706,14906,2982,0.204561,0.160977,0.156613,0.204561,0.606999,0.119461,0.139168,6.188424e-40,f1_macro,0.156613,0.019608,NaN,shuffle_training_X_only
19,YFT,19,798,18706,14992,2999,0.188396,0.145994,0.139660,0.188396,0.595737,0.119653,0.139046,1.601392e-27,f1_macro,0.139660,0.019608,NaN,shuffle_training_X_only

aggregated YFT 2025-07-31 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFT/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-07-31/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFT,0,0,11069,11069,2214,0.194219,0.150767,0.146492,0.194219,0.588472,0.120938,0.136405,4.686335e-23,f1_macro,0.146492,0.019608,0.148495,shuffle_training_X_only
1,YFT,1,42,11069,11069,2214,0.196929,0.154380,0.150309,0.196929,0.590969,0.120938,0.136405,1.497549e-24,f1_macro,0.150309,0.019608,0.148797,shuffle_training_X_only
2,YFT,2,84,11069,11069,2214,0.196477,0.154903,0.152045,0.196477,0.588713,0.120938,0.136405,2.677328e-24,f1_macro,0.152045,0.019608,0.152111,shuffle_training_X_only
3,YFT,3,126,11069,11069,2214,0.186089,0.142233,0.135707,0.186089,0.584818,0.120938,0.136405,7.723434e-19,f1_macro,0.135707,0.019608,NaN,shuffle_training_X_only
4,YFT,4,168,11069,11069,2214,0.186992,0.144211,0.139330,0.186992,0.613178,0.120938,0.136405,2.750785e-19,f1_macro,0.139330,0.019608,NaN,shuffle_training_X_only
5,YFT,5,210,11069,11069,2214,0.192412,0.149944,0.145312,0.192412,0.587558,0.120938,0.136405,4.395941e-22,f1_macro,0.145312,0.019608,NaN,shuffle_training_X_only
6,YFT,6,252,11069,11069,2214,0.185637,0.144970,0.140497,0.185637,0.590933,0.120938,0.136405,1.288467e-18,f1_macro,0.140497,0.019608,NaN,shuffle_training_X_only
7,YFT,7,294,11069,11069,2214,0.189702,0.148169,0.143723,0.189702,0.602826,0.120938,0.136405,1.158582e-20,f1_macro,0.143723,0.019608,NaN,shuffle_training_X_only
8,YFT,8,336,11069,11069,2214,0.195574,0.152432,0.146157,0.195574,0.589955,0.120938,0.136405,8.485054e-24,f1_macro,0.146157,0.019608,NaN,shuffle_training_X_only
9,YFT,9,378,11069,11069,2214,0.198284,0.153753,0.147533,0.198284,0.603756,0.120938,0.136405,2.576714e-25,f1_macro,0.147533,0.019608,NaN,shuffle_training_X_only
10,YFT,10,420,11069,11069,2214,0.203252,0.163509,0.162865,0.203252,0.598182,0.120938,0.136405,3.273195e-28,f1_macro,0.162865,0.019608,NaN,shuffle_training_X_only
11,YFT,11,462,11069,11069,2214,0.197380,0.151446,0.144590,0.197380,0.602392,0.120938,0.136405,8.352827e-25,f1_macro,0.144590,0.019608,NaN,shuffle_training_X_only
12,YFT,12,504,11069,11069,2214,0.206865,0.162257,0.155913,0.206865,0.607555,0.120938,0.136405,2.076799e-30,f1_macro,0.155913,0.019608,NaN,shuffle_training_X_only
13,YFT,13,546,11069,11069,2214,0.185185,0.146322,0.142651,0.185185,0.595551,0.120938,0.136405,2.143174e-18,f1_macro,0.142651,0.019608,NaN,shuffle_training_X_only
14,YFT,14,588,11069,11069,2214,0.193315,0.147869,0.139487,0.193315,0.586018,0.120938,0.136405,1.443539e-22,f1_macro,0.139487,0.019608,NaN,shuffle_training_X_only
15,YFT,15,630,11069,11069,2214,0.182927,0.140797,0.135247,0.182927,0.579991,0.120938,0.136405,2.610462e-17,f1_macro,0.135247,0.019608,NaN,shuffle_training_X_only
16,YFT,16,672,11069,11069,2214,0.196025,0.153793,0.149101,0.196025,0.594789,0.120938,0.136405,4.773022e-24,f1_macro,0.149101,0.019608,NaN,shuffle_training_X_only
17,YFT,17,714,11069,11069,2214,0.189702,0.146724,0.140466,0.189702,0.594191,0.120938,0.136405,1.158582e-20,f1_macro,0.140466,0.019608,NaN,shuffle_training_X_only
18,YFT,18,756,11069,11069,2214,0.186089,0.147848,0.145978,0.186089,0.598714,0.120938,0.136405,7.723434e-19,f1_macro,0.145978,0.019608,NaN,shuffle_training_X_only
19,YFT,19,798,11069,11069,2214,0.183830,0.142182,0.135500,0.183830,0.589085,0.120938,0.136405,9.689786e-18,f1_macro,0.135500,0.019608,NaN,shuffle_training_X_only

aggregated YFT 2025-08-01 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFT/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-08-01/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFT,0,0,12763,12763,2553,0.215433,0.162938,0.154274,0.215433,0.622281,0.121495,0.137877,1.401388e-40,f1_macro,0.154274,0.019608,0.150287,shuffle_training_X_only
1,YFT,1,42,12763,12763,2553,0.207599,0.159052,0.153105,0.207599,0.609212,0.121495,0.137877,8.474131e-35,f1_macro,0.153105,0.019608,0.153890,shuffle_training_X_only
2,YFT,2,84,12763,12763,2553,0.213474,0.163565,0.156841,0.213474,0.617466,0.121495,0.137877,4.264206e-39,f1_macro,0.156841,0.019608,0.157953,shuffle_training_X_only
3,YFT,3,126,12763,12763,2553,0.201723,0.154749,0.149300,0.201723,0.606788,0.121495,0.137877,9.895904e-31,f1_macro,0.149300,0.019608,NaN,shuffle_training_X_only
4,YFT,4,168,12763,12763,2553,0.220525,0.171338,0.166075,0.220525,0.611270,0.121495,0.137877,1.490903e-44,f1_macro,0.166075,0.019608,NaN,shuffle_training_X_only
5,YFT,5,210,12763,12763,2553,0.200940,0.156309,0.151844,0.200940,0.613638,0.121495,0.137877,3.311868e-30,f1_macro,0.151844,0.019608,NaN,shuffle_training_X_only
6,YFT,6,252,12763,12763,2553,0.213083,0.164166,0.159141,0.213083,0.611922,0.121495,0.137877,8.384571e-39,f1_macro,0.159141,0.019608,NaN,shuffle_training_X_only
7,YFT,7,294,12763,12763,2553,0.196240,0.152598,0.148077,0.196240,0.605473,0.121495,0.137877,3.794561e-27,f1_macro,0.148077,0.019608,NaN,shuffle_training_X_only
8,YFT,8,336,12763,12763,2553,0.211124,0.164077,0.161121,0.211124,0.623097,0.121495,0.137877,2.379884e-37,f1_macro,0.161121,0.019608,NaN,shuffle_training_X_only
9,YFT,9,378,12763,12763,2553,0.205640,0.159650,0.155370,0.205640,0.605001,0.121495,0.137877,2.040638e-33,f1_macro,0.155370,0.019608,NaN,shuffle_training_X_only
10,YFT,10,420,12763,12763,2553,0.213474,0.161637,0.153280,0.213474,0.604062,0.121495,0.137877,4.264206e-39,f1_macro,0.153280,0.019608,NaN,shuffle_training_X_only
11,YFT,11,462,12763,12763,2553,0.200157,0.153169,0.147699,0.200157,0.603138,0.121495,0.137877,1.097717e-29,f1_macro,0.147699,0.019608,NaN,shuffle_training_X_only
12,YFT,12,504,12763,12763,2553,0.211516,0.165273,0.161317,0.211516,0.608901,0.121495,0.137877,1.224514e-37,f1_macro,0.161317,0.019608,NaN,shuffle_training_X_only
13,YFT,13,546,12763,12763,2553,0.210341,0.158091,0.149602,0.210341,0.606637,0.121495,0.137877,8.926823e-37,f1_macro,0.149602,0.019608,NaN,shuffle_training_X_only
14,YFT,14,588,12763,12763,2553,0.189973,0.149698,0.147409,0.189973,0.612220,0.121495,0.137877,2.619805e-23,f1_macro,0.147409,0.019608,NaN,shuffle_training_X_only
15,YFT,15,630,12763,12763,2553,0.197807,0.152919,0.147296,0.197807,0.608714,0.121495,0.137877,3.770713e-28,f1_macro,0.147296,0.019608,NaN,shuffle_training_X_only
16,YFT,16,672,12763,12763,2553,0.205249,0.157799,0.151875,0.205249,0.606167,0.121495,0.137877,3.828305e-33,f1_macro,0.151875,0.019608,NaN,shuffle_training_X_only
17,YFT,17,714,12763,12763,2553,0.198982,0.153765,0.147914,0.198982,0.601575,0.121495,0.137877,6.504519e-29,f1_macro,0.147914,0.019608,NaN,shuffle_training_X_only
18,YFT,18,756,12763,12763,2553,0.202115,0.153725,0.145148,0.202115,0.613909,0.121495,0.137877,5.389832e-31,f1_macro,0.145148,0.019608,NaN,shuffle_training_X_only
19,YFT,19,798,12763,12763,2553,0.215433,0.166745,0.160281,0.215433,0.616174,0.121495,0.137877,1.401388e-40,f1_macro,0.160281,0.019608,NaN,shuffle_training_X_only

aggregated YFT 2025-08-02 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFT/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-08-02/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFT,0,0,16169,15031,3007,0.198537,0.156758,0.148132,0.198537,0.602186,0.117554,0.135351,2.908229e-37,f1_macro,0.148132,0.019608,0.155170,shuffle_training_X_only
1,YFT,1,42,16169,15026,3006,0.209248,0.164756,0.156198,0.209248,0.608959,0.117493,0.136061,1.685231e-46,f1_macro,0.156198,0.019608,0.154627,shuffle_training_X_only
2,YFT,2,84,16169,15047,3010,0.209302,0.167128,0.161384,0.209302,0.604476,0.117587,0.135216,1.688637e-46,f1_macro,0.161384,0.019608,0.157902,shuffle_training_X_only
3,YFT,3,126,16169,15028,3006,0.211244,0.172182,0.169269,0.211244,0.601795,0.117493,0.135396,2.593140e-48,f1_macro,0.169269,0.019608,NaN,shuffle_training_X_only
4,YFT,4,168,16169,15056,3012,0.207835,0.166125,0.159403,0.207835,0.618078,0.117610,0.135458,3.450814e-45,f1_macro,0.159403,0.019608,NaN,shuffle_training_X_only
5,YFT,5,210,16169,15017,3004,0.213382,0.171558,0.166476,0.213382,0.603552,0.117473,0.135819,2.793878e-50,f1_macro,0.166476,0.019608,NaN,shuffle_training_X_only
6,YFT,6,252,16169,15004,3001,0.202932,0.163160,0.158028,0.202932,0.603336,0.117490,0.135955,6.540651e-41,f1_macro,0.158028,0.019608,NaN,shuffle_training_X_only
7,YFT,7,294,16169,15011,3003,0.200799,0.162701,0.158542,0.200799,0.600505,0.117512,0.136197,4.038663e-39,f1_macro,0.158542,0.019608,NaN,shuffle_training_X_only
8,YFT,8,336,16169,15038,3008,0.210439,0.170469,0.164958,0.210439,0.604592,0.117565,0.135971,1.596564e-47,f1_macro,0.164958,0.019608,NaN,shuffle_training_X_only
9,YFT,9,378,16169,15034,3007,0.196541,0.153914,0.144888,0.196541,0.606491,0.117557,0.135683,1.187912e-35,f1_macro,0.144888,0.019608,NaN,shuffle_training_X_only
10,YFT,10,420,16169,14997,3000,0.197333,0.158569,0.153204,0.197333,0.605176,0.117478,0.135667,2.757970e-36,f1_macro,0.153204,0.019608,NaN,shuffle_training_X_only
11,YFT,11,462,16169,15071,3015,0.194030,0.154635,0.148509,0.194030,0.601231,0.117595,0.135987,1.009455e-33,f1_macro,0.148509,0.019608,NaN,shuffle_training_X_only
12,YFT,12,504,16169,15016,3004,0.203395,0.160642,0.152739,0.203395,0.614425,0.117473,0.135819,2.314001e-41,f1_macro,0.152739,0.019608,NaN,shuffle_training_X_only
13,YFT,13,546,16169,15010,3002,0.204197,0.163773,0.158726,0.204197,0.610292,0.117455,0.136243,4.832924e-42,f1_macro,0.158726,0.019608,NaN,shuffle_training_X_only
14,YFT,14,588,16169,15050,3010,0.207309,0.164361,0.157477,0.207309,0.603581,0.117583,0.135548,1.007162e-44,f1_macro,0.157477,0.019608,NaN,shuffle_training_X_only
15,YFT,15,630,16169,15037,3008,0.209774,0.166939,0.159886,0.209774,0.613861,0.117563,0.135638,6.362781e-47,f1_macro,0.159886,0.019608,NaN,shuffle_training_X_only
16,YFT,16,672,16169,15003,3001,0.197601,0.156240,0.148507,0.197601,0.615092,0.117440,0.135621,1.497052e-36,f1_macro,0.148507,0.019608,NaN,shuffle_training_X_only
17,YFT,17,714,16169,15017,3004,0.189081,0.150236,0.144428,0.189081,0.595681,0.117527,0.136818,6.246415e-30,f1_macro,0.144428,0.019608,NaN,shuffle_training_X_only
18,YFT,18,756,16169,15045,3009,0.211698,0.169772,0.163686,0.211698,0.603244,0.117524,0.135593,9.721781e-49,f1_macro,0.163686,0.019608,NaN,shuffle_training_X_only
19,YFT,19,798,16169,15048,3010,0.201329,0.159819,0.152648,0.201329,0.602510,0.117584,0.135880,1.422861e-39,f1_macro,0.152648,0.019608,NaN,shuffle_training_X_only

aggregated YFT 2025-08-03 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFT/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-08-03/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFT,0,0,18429,15945,3189,0.193478,0.153505,0.147878,0.193478,0.598053,0.116797,0.134211,6.352079e-36,f1_macro,0.147878,0.019608,0.154369,shuffle_training_X_only
1,YFT,1,42,18429,15931,3187,0.207405,0.163720,0.155674,0.207405,0.614593,0.116737,0.133668,2.357156e-48,f1_macro,0.155674,0.019608,0.147507,shuffle_training_X_only
2,YFT,2,84,18429,15932,3187,0.205522,0.162913,0.156204,0.205522,0.609293,0.116735,0.133668,1.385233e-46,f1_macro,0.156204,0.019608,0.144090,shuffle_training_X_only
3,YFT,3,126,18429,15932,3187,0.189520,0.152100,0.147294,0.189520,0.602321,0.116735,0.133668,9.391775e-33,f1_macro,0.147294,0.019608,NaN,shuffle_training_X_only
4,YFT,4,168,18429,15965,3193,0.189164,0.154319,0.151735,0.189164,0.603291,0.116832,0.134043,1.961627e-32,f1_macro,0.151735,0.019608,NaN,shuffle_training_X_only
5,YFT,5,210,18429,15932,3187,0.185755,0.148306,0.143297,0.185755,0.605425,0.116735,0.133982,7.929369e-30,f1_macro,0.143297,0.019608,NaN,shuffle_training_X_only
6,YFT,6,252,18429,15937,3188,0.202949,0.159888,0.152151,0.202949,0.616222,0.116748,0.134567,3.285413e-44,f1_macro,0.152151,0.019608,NaN,shuffle_training_X_only
7,YFT,7,294,18429,15961,3193,0.210147,0.167494,0.160850,0.210147,0.607876,0.116796,0.133730,5.262154e-51,f1_macro,0.160850,0.019608,NaN,shuffle_training_X_only
8,YFT,8,336,18429,15988,3198,0.207942,0.167776,0.163790,0.207942,0.608887,0.116885,0.133521,7.619013e-49,f1_macro,0.163790,0.019608,NaN,shuffle_training_X_only
9,YFT,9,378,18429,15946,3190,0.198746,0.159464,0.154049,0.198746,0.597978,0.116808,0.133856,2.059824e-40,f1_macro,0.154049,0.019608,NaN,shuffle_training_X_only
10,YFT,10,420,18429,15937,3188,0.197302,0.157337,0.151228,0.197302,0.605709,0.116746,0.133940,3.345441e-39,f1_macro,0.151228,0.019608,NaN,shuffle_training_X_only
11,YFT,11,462,18429,15954,3191,0.195863,0.156812,0.151559,0.195863,0.598021,0.116824,0.135381,6.393216e-38,f1_macro,0.151559,0.019608,NaN,shuffle_training_X_only
12,YFT,12,504,18429,15999,3200,0.219375,0.172479,0.163105,0.219375,0.621295,0.116874,0.135000,2.370250e-60,f1_macro,0.163105,0.019608,NaN,shuffle_training_X_only
13,YFT,13,546,18429,15963,3193,0.197307,0.156773,0.149581,0.197307,0.612859,0.116752,0.133730,2.937083e-39,f1_macro,0.149581,0.019608,NaN,shuffle_training_X_only
14,YFT,14,588,18429,15932,3187,0.187324,0.150944,0.146810,0.187324,0.607018,0.116733,0.133668,4.944222e-31,f1_macro,0.146810,0.019608,NaN,shuffle_training_X_only
15,YFT,15,630,18429,15913,3183,0.191643,0.153259,0.147145,0.191643,0.609256,0.116734,0.133522,2.024242e-34,f1_macro,0.147145,0.019608,NaN,shuffle_training_X_only
16,YFT,16,672,18429,15931,3187,0.199874,0.159404,0.153361,0.199874,0.599639,0.116775,0.133982,2.094689e-41,f1_macro,0.153361,0.019608,NaN,shuffle_training_X_only
17,YFT,17,714,18429,15899,3180,0.198428,0.160142,0.155631,0.198428,0.597452,0.116707,0.133962,3.984836e-40,f1_macro,0.155631,0.019608,NaN,shuffle_training_X_only
18,YFT,18,756,18429,15932,3187,0.191403,0.154018,0.149468,0.191403,0.602876,0.116776,0.134296,3.188088e-34,f1_macro,0.149468,0.019608,NaN,shuffle_training_X_only
19,YFT,19,798,18429,15985,3197,0.198311,0.158434,0.153115,0.198311,0.600114,0.116882,0.134188,4.917228e-40,f1_macro,0.153115,0.019608,NaN,shuffle_training_X_only

aggregated YFT 2025-08-04 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFT/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-08-04/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFT,0,0,2115,2115,423,0.208038,0.172914,0.176171,0.208038,0.585455,0.11765,0.132388,8.224288e-08,f1_macro,0.176171,0.019608,0.158056,shuffle_training_X_only
1,YFT,1,42,2115,2115,423,0.160757,0.132111,0.127865,0.160757,0.544902,0.11765,0.132388,5.020116e-03,f1_macro,0.127865,0.019608,0.142318,shuffle_training_X_only
2,YFT,2,84,2115,2115,423,0.167849,0.138041,0.136235,0.167849,0.594349,0.11765,0.132388,1.411097e-03,f1_macro,0.136235,0.019608,0.150024,shuffle_training_X_only
3,YFT,3,126,2115,2115,423,0.179669,0.152424,0.149771,0.179669,0.586743,0.11765,0.132388,1.249555e-04,f1_macro,0.149771,0.019608,NaN,shuffle_training_X_only
4,YFT,4,168,2115,2115,423,0.167849,0.134721,0.133898,0.167849,0.553614,0.11765,0.132388,1.411097e-03,f1_macro,0.133898,0.019608,NaN,shuffle_training_X_only
5,YFT,5,210,2115,2115,423,0.179669,0.148944,0.148474,0.179669,0.566483,0.11765,0.132388,1.249555e-04,f1_macro,0.148474,0.019608,NaN,shuffle_training_X_only
6,YFT,6,252,2115,2115,423,0.158392,0.128036,0.123201,0.158392,0.567909,0.11765,0.132388,7.426381e-03,f1_macro,0.123201,0.019608,NaN,shuffle_training_X_only
7,YFT,7,294,2115,2115,423,0.156028,0.139846,0.146867,0.156028,0.582753,0.11765,0.132388,1.081325e-02,f1_macro,0.146867,0.019608,NaN,shuffle_training_X_only
8,YFT,8,336,2115,2115,423,0.196217,0.158971,0.156096,0.196217,0.577445,0.11765,0.132388,2.239032e-06,f1_macro,0.156096,0.019608,NaN,shuffle_training_X_only
9,YFT,9,378,2115,2115,423,0.172577,0.148188,0.153492,0.172577,0.551735,0.11765,0.132388,5.602219e-04,f1_macro,0.153492,0.019608,NaN,shuffle_training_X_only
10,YFT,10,420,2115,2115,423,0.177305,0.148266,0.148329,0.177305,0.582625,0.11765,0.132388,2.091898e-04,f1_macro,0.148329,0.019608,NaN,shuffle_training_X_only
11,YFT,11,462,2115,2115,423,0.198582,0.166810,0.168332,0.198582,0.597809,0.11765,0.132388,1.189387e-06,f1_macro,0.168332,0.019608,NaN,shuffle_training_X_only
12,YFT,12,504,2115,2115,423,0.127660,0.102716,0.099535,0.127660,0.572090,0.11765,0.132388,2.821207e-01,f1_macro,0.099535,0.352941,NaN,shuffle_training_X_only
13,YFT,13,546,2115,2115,423,0.184397,0.161169,0.165681,0.184397,0.589768,0.11765,0.132388,4.262405e-05,f1_macro,0.165681,0.019608,NaN,shuffle_training_X_only
14,YFT,14,588,2115,2115,423,0.141844,0.119892,0.122192,0.141844,0.600698,0.11765,0.132388,7.364635e-02,f1_macro,0.122192,0.019608,NaN,shuffle_training_X_only
15,YFT,15,630,2115,2115,423,0.186761,0.149419,0.147166,0.186761,0.559233,0.11765,0.132388,2.434606e-05,f1_macro,0.147166,0.019608,NaN,shuffle_training_X_only
16,YFT,16,672,2115,2115,423,0.184397,0.150275,0.145088,0.184397,0.561133,0.11765,0.132388,4.262405e-05,f1_macro,0.145088,0.019608,NaN,shuffle_training_X_only
17,YFT,17,714,2115,2115,423,0.184397,0.149021,0.146110,0.184397,0.563140,0.11765,0.132388,4.262405e-05,f1_macro,0.146110,0.019608,NaN,shuffle_training_X_only
18,YFT,18,756,2115,2115,423,0.182033,0.147144,0.139963,0.182033,0.563052,0.11765,0.132388,7.352671e-05,f1_macro,0.139963,0.019608,NaN,shuffle_training_X_only
19,YFT,19,798,2115,2115,423,0.167849,0.142923,0.146979,0.167849,0.570477,0.11765,0.132388,1.411097e-03,f1_macro,0.146979,0.019608,NaN,shuffle_training_X_only

aggregated YFU 2025-12-08 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFU/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-12-08/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFU,0,0,279,279,56,0.196429,0.161376,0.144159,0.196429,NaN,0.127551,0.142857,0.094167,f1_macro,0.144159,0.137255,0.174088,shuffle_training_X_only
1,YFU,1,42,279,279,56,0.160714,0.154762,0.163878,0.160714,NaN,0.127551,0.142857,0.281462,f1_macro,0.163878,0.117647,0.171434,shuffle_training_X_only
2,YFU,2,84,279,279,56,0.107143,0.089286,0.071429,0.107143,NaN,0.127551,0.142857,0.735084,f1_macro,0.071429,0.862745,0.195065,shuffle_training_X_only
3,YFU,3,126,279,279,56,0.178571,0.147487,0.146264,0.178571,NaN,0.127551,0.142857,0.170448,f1_macro,0.146264,0.196078,NaN,shuffle_training_X_only
4,YFU,4,168,279,279,56,0.196429,0.166005,0.144373,0.196429,NaN,0.127551,0.142857,0.094167,f1_macro,0.144373,0.156863,NaN,shuffle_training_X_only
5,YFU,5,210,279,279,56,0.232143,0.197751,0.176335,0.232143,NaN,0.127551,0.142857,0.021962,f1_macro,0.176335,0.058824,NaN,shuffle_training_X_only
6,YFU,6,252,279,279,56,0.160714,0.137566,0.133455,0.160714,NaN,0.127551,0.142857,0.281462,f1_macro,0.133455,0.215686,NaN,shuffle_training_X_only
7,YFU,7,294,279,279,56,0.089286,0.071429,0.060214,0.089286,NaN,0.127551,0.142857,0.857604,f1_macro,0.060214,0.941176,NaN,shuffle_training_X_only
8,YFU,8,336,279,279,56,0.142857,0.134259,0.127646,0.142857,NaN,0.127551,0.142857,0.423836,f1_macro,0.127646,0.313725,NaN,shuffle_training_X_only
9,YFU,9,378,279,279,56,0.214286,0.175265,0.159503,0.214286,NaN,0.127551,0.142857,0.047531,f1_macro,0.159503,0.078431,NaN,shuffle_training_X_only
10,YFU,10,420,279,279,56,0.196429,0.177910,0.189683,0.196429,NaN,0.127551,0.142857,0.094167,f1_macro,0.189683,0.039216,NaN,shuffle_training_X_only
11,YFU,11,462,279,279,56,0.160714,0.133598,0.126608,0.160714,NaN,0.127551,0.142857,0.281462,f1_macro,0.126608,0.352941,NaN,shuffle_training_X_only
12,YFU,12,504,279,279,56,0.214286,0.200397,0.204603,0.214286,NaN,0.127551,0.142857,0.047531,f1_macro,0.204603,0.019608,NaN,shuffle_training_X_only
13,YFU,13,546,279,279,56,0.214286,0.175265,0.166630,0.214286,NaN,0.127551,0.142857,0.047531,f1_macro,0.166630,0.058824,NaN,shuffle_training_X_only
14,YFU,14,588,279,279,56,0.142857,0.117063,0.110468,0.142857,NaN,0.127551,0.142857,0.423836,f1_macro,0.110468,0.490196,NaN,shuffle_training_X_only
15,YFU,15,630,279,279,56,0.125000,0.099206,0.089506,0.125000,NaN,0.127551,0.142857,0.582831,f1_macro,0.089506,0.666667,NaN,shuffle_training_X_only
16,YFU,16,672,279,279,56,0.142857,0.119709,0.120194,0.142857,NaN,0.127551,0.142857,0.423836,f1_macro,0.120194,0.372549,NaN,shuffle_training_X_only
17,YFU,17,714,279,279,56,0.232143,0.193783,0.191386,0.232143,NaN,0.127551,0.142857,0.021962,f1_macro,0.191386,0.019608,NaN,shuffle_training_X_only
18,YFU,18,756,279,279,56,0.178571,0.149471,0.145189,0.178571,NaN,0.127551,0.142857,0.170448,f1_macro,0.145189,0.176471,NaN,shuffle_training_X_only
19,YFU,19,798,279,279,56,0.178571,0.170635,0.170194,0.178571,NaN,0.127551,0.142857,0.170448,f1_macro,0.170194,0.019608,NaN,shuffle_training_X_only

aggregated YFU 2025-12-09 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFU/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-12-09/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFU,0,0,1219,1219,244,0.180328,0.141098,0.129988,0.180328,0.564301,0.119256,0.135246,0.003471,f1_macro,0.129988,0.058824,0.124612,shuffle_training_X_only
1,YFU,1,42,1219,1219,244,0.168033,0.129735,0.126875,0.168033,0.526523,0.119256,0.135246,0.015143,f1_macro,0.126875,0.156863,0.139380,shuffle_training_X_only
2,YFU,2,84,1219,1219,244,0.172131,0.138485,0.134902,0.172131,0.529896,0.119256,0.135246,0.009506,f1_macro,0.134902,0.019608,0.147777,shuffle_training_X_only
3,YFU,3,126,1219,1219,244,0.188525,0.148144,0.138940,0.188525,0.585627,0.119256,0.135246,0.001147,f1_macro,0.138940,0.039216,NaN,shuffle_training_X_only
4,YFU,4,168,1219,1219,244,0.176230,0.136648,0.132226,0.176230,0.537201,0.119256,0.135246,0.005818,f1_macro,0.132226,0.058824,NaN,shuffle_training_X_only
5,YFU,5,210,1219,1219,244,0.131148,0.100473,0.097578,0.131148,0.547815,0.119256,0.135246,0.310765,f1_macro,0.097578,0.509804,NaN,shuffle_training_X_only
6,YFU,6,252,1219,1219,244,0.209016,0.158902,0.145952,0.209016,0.532739,0.119256,0.135246,0.000047,f1_macro,0.145952,0.019608,NaN,shuffle_training_X_only
7,YFU,7,294,1219,1219,244,0.139344,0.109413,0.105661,0.139344,0.527708,0.119256,0.135246,0.190502,f1_macro,0.105661,0.254902,NaN,shuffle_training_X_only
8,YFU,8,336,1219,1219,244,0.184426,0.145871,0.139814,0.184426,0.565987,0.119256,0.135246,0.002020,f1_macro,0.139814,0.019608,NaN,shuffle_training_X_only
9,YFU,9,378,1219,1219,244,0.168033,0.144236,0.150342,0.168033,0.522303,0.119256,0.135246,0.015143,f1_macro,0.150342,0.019608,NaN,shuffle_training_X_only
10,YFU,10,420,1219,1219,244,0.131148,0.105246,0.103746,0.131148,0.572153,0.119256,0.135246,0.310765,f1_macro,0.103746,0.254902,NaN,shuffle_training_X_only
11,YFU,11,462,1219,1219,244,0.184426,0.145208,0.141811,0.184426,0.556115,0.119256,0.135246,0.002020,f1_macro,0.141811,0.019608,NaN,shuffle_training_X_only
12,YFU,12,504,1219,1219,244,0.147541,0.114015,0.107253,0.147541,0.526284,0.119256,0.135246,0.105297,f1_macro,0.107253,0.215686,NaN,shuffle_training_X_only
13,YFU,13,546,1219,1219,244,0.151639,0.119924,0.114594,0.151639,0.558257,0.119256,0.135246,0.075274,f1_macro,0.114594,0.078431,NaN,shuffle_training_X_only
14,YFU,14,588,1219,1219,244,0.176230,0.135227,0.123755,0.176230,0.511157,0.119256,0.135246,0.005818,f1_macro,0.123755,0.039216,NaN,shuffle_training_X_only
15,YFU,15,630,1219,1219,244,0.143443,0.111364,0.105646,0.143443,0.485337,0.119256,0.135246,0.143490,f1_macro,0.105646,0.352941,NaN,shuffle_training_X_only
16,YFU,16,672,1219,1219,244,0.192623,0.152879,0.149051,0.192623,0.553389,0.119256,0.135246,0.000635,f1_macro,0.149051,0.039216,NaN,shuffle_training_X_only
17,YFU,17,714,1219,1219,244,0.172131,0.135265,0.124589,0.172131,0.560418,0.119256,0.135246,0.009506,f1_macro,0.124589,0.058824,NaN,shuffle_training_X_only
18,YFU,18,756,1219,1219,244,0.135246,0.103598,0.099156,0.135246,0.536055,0.119256,0.135246,0.246449,f1_macro,0.099156,0.313725,NaN,shuffle_training_X_only
19,YFU,19,798,1219,1219,244,0.159836,0.121307,0.113493,0.159836,0.536344,0.119256,0.135246,0.035564,f1_macro,0.113493,0.078431,NaN,shuffle_training_X_only

aggregated YFU 2025-12-10 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFU/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-12-10/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFU,0,0,1183,1183,237,0.147679,0.128546,0.128220,0.147679,0.578584,0.116452,0.130802,0.084341,f1_macro,0.128220,0.039216,0.147530,shuffle_training_X_only
1,YFU,1,42,1183,1183,237,0.143460,0.118220,0.112305,0.143460,0.562063,0.116452,0.130802,0.117823,f1_macro,0.112305,0.176471,0.138538,shuffle_training_X_only
2,YFU,2,84,1183,1183,237,0.198312,0.161031,0.155805,0.198312,0.584964,0.116452,0.130802,0.000189,f1_macro,0.155805,0.019608,0.130637,shuffle_training_X_only
3,YFU,3,126,1183,1183,237,0.177215,0.144676,0.136542,0.177215,0.537253,0.116452,0.130802,0.003803,f1_macro,0.136542,0.019608,NaN,shuffle_training_X_only
4,YFU,4,168,1183,1183,237,0.202532,0.166534,0.163100,0.202532,0.574145,0.116452,0.130802,0.000096,f1_macro,0.163100,0.019608,NaN,shuffle_training_X_only
5,YFU,5,210,1183,1183,237,0.143460,0.119143,0.115979,0.143460,0.557635,0.116452,0.130802,0.117823,f1_macro,0.115979,0.098039,NaN,shuffle_training_X_only
6,YFU,6,252,1183,1183,237,0.194093,0.162325,0.155525,0.194093,0.577060,0.116452,0.130802,0.000363,f1_macro,0.155525,0.019608,NaN,shuffle_training_X_only
7,YFU,7,294,1183,1183,237,0.177215,0.146494,0.143525,0.177215,0.597930,0.116452,0.130802,0.003803,f1_macro,0.143525,0.039216,NaN,shuffle_training_X_only
8,YFU,8,336,1183,1183,237,0.143460,0.116658,0.111627,0.143460,0.525474,0.116452,0.130802,0.117823,f1_macro,0.111627,0.313725,NaN,shuffle_training_X_only
9,YFU,9,378,1183,1183,237,0.135021,0.111065,0.109518,0.135021,0.509465,0.116452,0.130802,0.211872,f1_macro,0.109518,0.215686,NaN,shuffle_training_X_only
10,YFU,10,420,1183,1183,237,0.113924,0.092025,0.086317,0.113924,0.508556,0.116452,0.130802,0.578337,f1_macro,0.086317,0.627451,NaN,shuffle_training_X_only
11,YFU,11,462,1183,1183,237,0.151899,0.122589,0.116315,0.151899,0.524643,0.116452,0.130802,0.058746,f1_macro,0.116315,0.137255,NaN,shuffle_training_X_only
12,YFU,12,504,1183,1183,237,0.181435,0.147591,0.142834,0.181435,0.571518,0.116452,0.130802,0.002197,f1_macro,0.142834,0.019608,NaN,shuffle_training_X_only
13,YFU,13,546,1183,1183,237,0.147679,0.118477,0.112708,0.147679,0.527917,0.116452,0.130802,0.084341,f1_macro,0.112708,0.215686,NaN,shuffle_training_X_only
14,YFU,14,588,1183,1183,237,0.168776,0.138504,0.131093,0.168776,0.575246,0.116452,0.130802,0.010541,f1_macro,0.131093,0.039216,NaN,shuffle_training_X_only
15,YFU,15,630,1183,1183,237,0.202532,0.167852,0.163574,0.202532,0.578153,0.116452,0.130802,0.000096,f1_macro,0.163574,0.019608,NaN,shuffle_training_X_only
16,YFU,16,672,1183,1183,237,0.206751,0.166442,0.161581,0.206751,0.576093,0.116452,0.130802,0.000048,f1_macro,0.161581,0.019608,NaN,shuffle_training_X_only
17,YFU,17,714,1183,1183,237,0.135021,0.107084,0.102765,0.135021,0.569462,0.116452,0.130802,0.211872,f1_macro,0.102765,0.470588,NaN,shuffle_training_X_only
18,YFU,18,756,1183,1183,237,0.168776,0.137983,0.134799,0.168776,0.589737,0.116452,0.130802,0.010541,f1_macro,0.134799,0.039216,NaN,shuffle_training_X_only
19,YFU,19,798,1183,1183,237,0.122363,0.100299,0.098991,0.122363,0.546092,0.116452,0.130802,0.417849,f1_macro,0.098991,0.431373,NaN,shuffle_training_X_only

aggregated YFU 2025-12-11 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFU/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-12-11/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFU,0,0,7756,6494,1299,0.206313,0.161436,0.150617,0.206313,0.603697,0.117054,0.140878,3.140454e-20,f1_macro,0.150617,0.019608,0.154849,shuffle_training_X_only
1,YFU,1,42,7756,6478,1296,0.207562,0.168934,0.165313,0.207562,0.611119,0.116967,0.139660,1.037742e-20,f1_macro,0.165313,0.019608,0.157034,shuffle_training_X_only
2,YFU,2,84,7756,6471,1295,0.201544,0.158251,0.148807,0.201544,0.605150,0.116921,0.138996,1.884866e-18,f1_macro,0.148807,0.019608,0.154829,shuffle_training_X_only
3,YFU,3,126,7756,6455,1291,0.187452,0.148243,0.141720,0.187452,0.606413,0.116810,0.138652,1.223568e-13,f1_macro,0.141720,0.019608,NaN,shuffle_training_X_only
4,YFU,4,168,7756,6482,1297,0.202005,0.160188,0.152286,0.202005,0.610476,0.116975,0.139553,1.275699e-18,f1_macro,0.152286,0.019608,NaN,shuffle_training_X_only
5,YFU,5,210,7756,6451,1291,0.198296,0.159321,0.152164,0.198296,0.612960,0.116810,0.138652,2.794808e-17,f1_macro,0.152164,0.019608,NaN,shuffle_training_X_only
6,YFU,6,252,7756,6458,1292,0.215944,0.174384,0.166983,0.215944,0.626172,0.116831,0.137771,4.450290e-24,f1_macro,0.166983,0.019608,NaN,shuffle_training_X_only
7,YFU,7,294,7756,6459,1292,0.185759,0.147288,0.139124,0.185759,0.604332,0.116863,0.140867,4.263404e-13,f1_macro,0.139124,0.019608,NaN,shuffle_training_X_only
8,YFU,8,336,7756,6482,1297,0.215883,0.173555,0.165782,0.215883,0.613700,0.117013,0.141866,4.862331e-24,f1_macro,0.165782,0.019608,NaN,shuffle_training_X_only
9,YFU,9,378,7756,6428,1286,0.188180,0.151279,0.146058,0.188180,0.606490,0.116919,0.141524,8.826098e-14,f1_macro,0.146058,0.019608,NaN,shuffle_training_X_only
10,YFU,10,420,7756,6477,1296,0.194444,0.153677,0.146991,0.194444,0.622281,0.116936,0.138117,6.111140e-16,f1_macro,0.146991,0.019608,NaN,shuffle_training_X_only
11,YFU,11,462,7756,6483,1297,0.196608,0.154977,0.146074,0.196608,0.610011,0.117005,0.141095,1.139640e-16,f1_macro,0.146074,0.019608,NaN,shuffle_training_X_only
12,YFU,12,504,7756,6469,1294,0.197836,0.157806,0.150538,0.197836,0.615600,0.116887,0.139104,4.052836e-17,f1_macro,0.150538,0.019608,NaN,shuffle_training_X_only
13,YFU,13,546,7756,6494,1299,0.216320,0.175284,0.169465,0.216320,0.605384,0.117223,0.140108,3.845493e-24,f1_macro,0.169465,0.019608,NaN,shuffle_training_X_only
14,YFU,14,588,7756,6472,1295,0.220849,0.177836,0.170920,0.220849,0.611912,0.116921,0.138996,3.719839e-26,f1_macro,0.170920,0.019608,NaN,shuffle_training_X_only
15,YFU,15,630,7756,6470,1294,0.210201,0.166193,0.156479,0.210201,0.614530,0.116937,0.141422,9.957583e-22,f1_macro,0.156479,0.019608,NaN,shuffle_training_X_only
16,YFU,16,672,7756,6460,1292,0.198142,0.158120,0.152236,0.198142,0.621420,0.116911,0.142415,3.420338e-17,f1_macro,0.152236,0.019608,NaN,shuffle_training_X_only
17,YFU,17,714,7756,6490,1298,0.187211,0.149029,0.141477,0.187211,0.607686,0.117074,0.138675,1.591611e-13,f1_macro,0.141477,0.019608,NaN,shuffle_training_X_only
18,YFU,18,756,7756,6435,1287,0.201243,0.164028,0.158936,0.201243,0.608930,0.116740,0.139860,2.539160e-18,f1_macro,0.158936,0.019608,NaN,shuffle_training_X_only
19,YFU,19,798,7756,6463,1293,0.185615,0.148462,0.143384,0.185615,0.613356,0.117081,0.139985,5.594038e-13,f1_macro,0.143384,0.019608,NaN,shuffle_training_X_only

aggregated YFU 2025-12-12 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFU/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-12-12/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFU,0,0,6663,6663,1333,0.222806,0.170116,0.166634,0.222806,0.606492,0.126308,0.146287,1.478839e-22,f1_macro,0.166634,0.019608,0.156197,shuffle_training_X_only
1,YFU,1,42,6663,6663,1333,0.220555,0.165142,0.160676,0.220555,0.623520,0.126308,0.146287,1.149889e-21,f1_macro,0.160676,0.019608,0.155491,shuffle_training_X_only
2,YFU,2,84,6663,6663,1333,0.210053,0.157079,0.149322,0.210053,0.593016,0.126308,0.146287,9.836354e-18,f1_macro,0.149322,0.019608,0.164636,shuffle_training_X_only
3,YFU,3,126,6663,6663,1333,0.215304,0.161102,0.155407,0.215304,0.605614,0.126308,0.146287,1.183967e-19,f1_macro,0.155407,0.019608,NaN,shuffle_training_X_only
4,YFU,4,168,6663,6663,1333,0.200300,0.150776,0.147966,0.200300,0.628399,0.126308,0.146287,2.018525e-14,f1_macro,0.147966,0.019608,NaN,shuffle_training_X_only
5,YFU,5,210,6663,6663,1333,0.195049,0.147945,0.143122,0.195049,0.614175,0.126308,0.146287,8.902369e-13,f1_macro,0.143122,0.019608,NaN,shuffle_training_X_only
6,YFU,6,252,6663,6663,1333,0.216054,0.158831,0.152695,0.216054,0.636597,0.126308,0.146287,6.187045e-20,f1_macro,0.152695,0.019608,NaN,shuffle_training_X_only
7,YFU,7,294,6663,6663,1333,0.223556,0.168985,0.167535,0.223556,0.605874,0.126308,0.146287,7.400927e-23,f1_macro,0.167535,0.019608,NaN,shuffle_training_X_only
8,YFU,8,336,6663,6663,1333,0.219055,0.166691,0.161219,0.219055,0.611046,0.126308,0.146287,4.417021e-21,f1_macro,0.161219,0.019608,NaN,shuffle_training_X_only
9,YFU,9,378,6663,6663,1333,0.228807,0.176963,0.173496,0.228807,0.623942,0.126308,0.146287,5.165876e-25,f1_macro,0.173496,0.019608,NaN,shuffle_training_X_only
10,YFU,10,420,6663,6663,1333,0.223556,0.176635,0.173914,0.223556,0.606504,0.126308,0.146287,7.400927e-23,f1_macro,0.173914,0.019608,NaN,shuffle_training_X_only
11,YFU,11,462,6663,6663,1333,0.213053,0.167627,0.167606,0.213053,0.609323,0.126308,0.146287,8.081275e-19,f1_macro,0.167606,0.019608,NaN,shuffle_training_X_only
12,YFU,12,504,6663,6663,1333,0.217554,0.164153,0.155826,0.217554,0.618601,0.126308,0.146287,1.667568e-20,f1_macro,0.155826,0.019608,NaN,shuffle_training_X_only
13,YFU,13,546,6663,6663,1333,0.210803,0.157592,0.151242,0.210803,0.623070,0.126308,0.146287,5.301322e-18,f1_macro,0.151242,0.019608,NaN,shuffle_training_X_only
14,YFU,14,588,6663,6663,1333,0.222806,0.169335,0.163899,0.222806,0.627105,0.126308,0.146287,1.478839e-22,f1_macro,0.163899,0.019608,NaN,shuffle_training_X_only
15,YFU,15,630,6663,6663,1333,0.228057,0.174149,0.171003,0.228057,0.619172,0.126308,0.146287,1.063347e-24,f1_macro,0.171003,0.019608,NaN,shuffle_training_X_only
16,YFU,16,672,6663,6663,1333,0.225056,0.172391,0.169882,0.225056,0.618308,0.126308,0.146287,1.830025e-23,f1_macro,0.169882,0.019608,NaN,shuffle_training_X_only
17,YFU,17,714,6663,6663,1333,0.217554,0.162799,0.159222,0.217554,0.617304,0.126308,0.146287,1.667568e-20,f1_macro,0.159222,0.019608,NaN,shuffle_training_X_only
18,YFU,18,756,6663,6663,1333,0.209302,0.154522,0.149080,0.209302,0.602676,0.126308,0.146287,1.816982e-17,f1_macro,0.149080,0.019608,NaN,shuffle_training_X_only
19,YFU,19,798,6663,6663,1333,0.217554,0.166873,0.165174,0.217554,0.614538,0.126308,0.146287,1.667568e-20,f1_macro,0.165174,0.019608,NaN,shuffle_training_X_only

aggregated YFU 2025-12-13 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFU/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-12-13/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFU,0,0,15507,15507,3102,0.207930,0.154242,0.140206,0.207930,0.598382,0.121674,0.138943,5.850250e-42,f1_macro,0.140206,0.019608,0.142184,shuffle_training_X_only
1,YFU,1,42,15507,15507,3102,0.207930,0.153525,0.140427,0.207930,0.588244,0.121674,0.138943,5.850250e-42,f1_macro,0.140427,0.019608,0.145745,shuffle_training_X_only
2,YFU,2,84,15507,15507,3102,0.196970,0.147744,0.137652,0.196970,0.600841,0.121674,0.138943,5.645947e-33,f1_macro,0.137652,0.019608,0.147398,shuffle_training_X_only
3,YFU,3,126,15507,15507,3102,0.211154,0.161653,0.153641,0.211154,0.598742,0.121674,0.138943,8.652561e-45,f1_macro,0.153641,0.019608,NaN,shuffle_training_X_only
4,YFU,4,168,15507,15507,3102,0.195035,0.146528,0.137659,0.195035,0.595379,0.121674,0.138943,1.710071e-31,f1_macro,0.137659,0.019608,NaN,shuffle_training_X_only
5,YFU,5,210,15507,15507,3102,0.205674,0.154811,0.145071,0.205674,0.592408,0.121674,0.138943,4.988756e-40,f1_macro,0.145071,0.019608,NaN,shuffle_training_X_only
6,YFU,6,252,15507,15507,3102,0.205674,0.157209,0.149236,0.205674,0.589286,0.121674,0.138943,4.988756e-40,f1_macro,0.149236,0.019608,NaN,shuffle_training_X_only
7,YFU,7,294,15507,15507,3102,0.207608,0.154876,0.143173,0.207608,0.606844,0.121674,0.138943,1.110573e-41,f1_macro,0.143173,0.019608,NaN,shuffle_training_X_only
8,YFU,8,336,15507,15507,3102,0.203740,0.154634,0.145739,0.203740,0.595249,0.121674,0.138943,2.088298e-38,f1_macro,0.145739,0.019608,NaN,shuffle_training_X_only
9,YFU,9,378,15507,15507,3102,0.204707,0.153062,0.142385,0.204707,0.592559,0.121674,0.138943,3.256386e-39,f1_macro,0.142385,0.019608,NaN,shuffle_training_X_only
10,YFU,10,420,15507,15507,3102,0.206641,0.157411,0.149782,0.206641,0.593568,0.121674,0.138943,7.509093e-41,f1_macro,0.149782,0.019608,NaN,shuffle_training_X_only
11,YFU,11,462,15507,15507,3102,0.202450,0.152098,0.142371,0.202450,0.585304,0.121674,0.138943,2.420279e-37,f1_macro,0.142371,0.019608,NaN,shuffle_training_X_only
12,YFU,12,504,15507,15507,3102,0.210509,0.161867,0.155728,0.210509,0.604327,0.121674,0.138943,3.234921e-44,f1_macro,0.155728,0.019608,NaN,shuffle_training_X_only
13,YFU,13,546,15507,15507,3102,0.205351,0.156809,0.149451,0.205351,0.591744,0.121674,0.138943,9.341701e-40,f1_macro,0.149451,0.019608,NaN,shuffle_training_X_only
14,YFU,14,588,15507,15507,3102,0.203095,0.153515,0.144876,0.203095,0.604509,0.121674,0.138943,7.137511e-38,f1_macro,0.144876,0.019608,NaN,shuffle_training_X_only
15,YFU,15,630,15507,15507,3102,0.213088,0.158623,0.146088,0.213088,0.606281,0.121674,0.138943,1.581119e-46,f1_macro,0.146088,0.019608,NaN,shuffle_training_X_only
16,YFU,16,672,15507,15507,3102,0.215345,0.159017,0.145810,0.215345,0.597619,0.121674,0.138943,1.359346e-48,f1_macro,0.145810,0.019608,NaN,shuffle_training_X_only
17,YFU,17,714,15507,15507,3102,0.204707,0.154889,0.146459,0.204707,0.585037,0.121674,0.138943,3.256386e-39,f1_macro,0.146459,0.019608,NaN,shuffle_training_X_only
18,YFU,18,756,15507,15507,3102,0.200193,0.152318,0.144883,0.200193,0.598100,0.121674,0.138943,1.632339e-35,f1_macro,0.144883,0.019608,NaN,shuffle_training_X_only
19,YFU,19,798,15507,15507,3102,0.209865,0.157072,0.146774,0.209865,0.596693,0.121674,0.138943,1.200144e-43,f1_macro,0.146774,0.019608,NaN,shuffle_training_X_only

aggregated YFU 2025-12-14 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFU/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-12-14/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFU,0,0,7201,7201,1441,0.214434,0.165401,0.159017,0.214434,0.607963,0.125393,0.14018,3.239461e-21,f1_macro,0.159017,0.019608,0.153595,shuffle_training_X_only
1,YFU,1,42,7201,7201,1441,0.213046,0.162646,0.157368,0.213046,0.592637,0.125393,0.14018,1.177872e-20,f1_macro,0.157368,0.019608,0.154105,shuffle_training_X_only
2,YFU,2,84,7201,7201,1441,0.192228,0.148696,0.143368,0.192228,0.593312,0.125393,0.14018,4.080938e-13,f1_macro,0.143368,0.019608,0.148945,shuffle_training_X_only
3,YFU,3,126,7201,7201,1441,0.206107,0.158051,0.154147,0.206107,0.601315,0.125393,0.14018,5.849983e-18,f1_macro,0.154147,0.019608,NaN,shuffle_training_X_only
4,YFU,4,168,7201,7201,1441,0.219292,0.165199,0.157704,0.219292,0.605647,0.125393,0.14018,3.110627e-23,f1_macro,0.157704,0.019608,NaN,shuffle_training_X_only
5,YFU,5,210,7201,7201,1441,0.207495,0.154987,0.148541,0.207495,0.594619,0.125393,0.14018,1.747132e-18,f1_macro,0.148541,0.019608,NaN,shuffle_training_X_only
6,YFU,6,252,7201,7201,1441,0.203331,0.155488,0.150665,0.203331,0.600675,0.125393,0.14018,6.237495e-17,f1_macro,0.150665,0.019608,NaN,shuffle_training_X_only
7,YFU,7,294,7201,7201,1441,0.198473,0.153861,0.152652,0.198473,0.603954,0.125393,0.14018,3.335106e-15,f1_macro,0.152652,0.019608,NaN,shuffle_training_X_only
8,YFU,8,336,7201,7201,1441,0.207495,0.158611,0.150904,0.207495,0.604943,0.125393,0.14018,1.747132e-18,f1_macro,0.150904,0.019608,NaN,shuffle_training_X_only
9,YFU,9,378,7201,7201,1441,0.206801,0.158967,0.153170,0.206801,0.608004,0.125393,0.14018,3.203651e-18,f1_macro,0.153170,0.019608,NaN,shuffle_training_X_only
10,YFU,10,420,7201,7201,1441,0.199861,0.147737,0.139337,0.199861,0.591642,0.125393,0.14018,1.092964e-15,f1_macro,0.139337,0.019608,NaN,shuffle_training_X_only
11,YFU,11,462,7201,7201,1441,0.204025,0.150005,0.138684,0.204025,0.598600,0.125393,0.14018,3.473617e-17,f1_macro,0.138684,0.019608,NaN,shuffle_training_X_only
12,YFU,12,504,7201,7201,1441,0.215128,0.162687,0.156603,0.215128,0.606065,0.125393,0.14018,1.688530e-21,f1_macro,0.156603,0.019608,NaN,shuffle_training_X_only
13,YFU,13,546,7201,7201,1441,0.201249,0.152020,0.146213,0.201249,0.581056,0.125393,0.14018,3.521225e-16,f1_macro,0.146213,0.019608,NaN,shuffle_training_X_only
14,YFU,14,588,7201,7201,1441,0.200555,0.150535,0.144636,0.200555,0.588653,0.125393,0.14018,6.216896e-16,f1_macro,0.144636,0.019608,NaN,shuffle_training_X_only
15,YFU,15,630,7201,7201,1441,0.208883,0.156501,0.149179,0.208883,0.590279,0.125393,0.14018,5.131845e-19,f1_macro,0.149179,0.019608,NaN,shuffle_training_X_only
16,YFU,16,672,7201,7201,1441,0.195003,0.144089,0.136251,0.195003,0.596755,0.125393,0.14018,5.031867e-14,f1_macro,0.136251,0.019608,NaN,shuffle_training_X_only
17,YFU,17,714,7201,7201,1441,0.192228,0.142637,0.134917,0.192228,0.601849,0.125393,0.14018,4.080938e-13,f1_macro,0.134917,0.019608,NaN,shuffle_training_X_only
18,YFU,18,756,7201,7201,1441,0.204719,0.155662,0.149459,0.204719,0.606006,0.125393,0.14018,1.926314e-17,f1_macro,0.149459,0.019608,NaN,shuffle_training_X_only
19,YFU,19,798,7201,7201,1441,0.229008,0.171882,0.164071,0.229008,0.615592,0.125393,0.14018,1.596185e-27,f1_macro,0.164071,0.019608,NaN,shuffle_training_X_only

aggregated YFU 2025-12-15 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFU/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-12-15/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFU,0,0,11200,11200,2240,0.200446,0.156451,0.145192,0.200446,0.605016,0.117612,0.134375,2.301457e-29,f1_macro,0.145192,0.019608,0.152872,shuffle_training_X_only
1,YFU,1,42,11200,11200,2240,0.215179,0.169868,0.158310,0.215179,0.613203,0.117612,0.134375,4.075686e-39,f1_macro,0.158310,0.019608,0.153027,shuffle_training_X_only
2,YFU,2,84,11200,11200,2240,0.201786,0.160598,0.153122,0.201786,0.608757,0.117605,0.134375,3.334601e-30,f1_macro,0.153122,0.019608,0.154472,shuffle_training_X_only
3,YFU,3,126,11200,11200,2240,0.208036,0.163497,0.152383,0.208036,0.610087,0.117605,0.134375,3.100634e-34,f1_macro,0.152383,0.019608,NaN,shuffle_training_X_only
4,YFU,4,168,11200,11200,2240,0.207589,0.162866,0.152984,0.207589,0.603751,0.117605,0.134375,6.124466e-34,f1_macro,0.152984,0.019608,NaN,shuffle_training_X_only
5,YFU,5,210,11200,11200,2240,0.204911,0.162165,0.154219,0.204911,0.608871,0.117612,0.134375,3.481237e-32,f1_macro,0.154219,0.019608,NaN,shuffle_training_X_only
6,YFU,6,252,11200,11200,2240,0.208482,0.165540,0.156657,0.208482,0.610416,0.117605,0.134375,1.565544e-34,f1_macro,0.156657,0.019608,NaN,shuffle_training_X_only
7,YFU,7,294,11200,11200,2240,0.184821,0.146078,0.138071,0.184821,0.590084,0.117605,0.134375,1.869723e-20,f1_macro,0.138071,0.019608,NaN,shuffle_training_X_only
8,YFU,8,336,11200,11200,2240,0.206250,0.160835,0.150311,0.206250,0.599805,0.117612,0.134375,4.704992e-33,f1_macro,0.150311,0.019608,NaN,shuffle_training_X_only
9,YFU,9,378,11200,11200,2240,0.204911,0.161718,0.150733,0.204911,0.607136,0.117612,0.134375,3.481237e-32,f1_macro,0.150733,0.019608,NaN,shuffle_training_X_only
10,YFU,10,420,11200,11200,2240,0.204911,0.161420,0.150304,0.204911,0.603498,0.117605,0.134375,3.436832e-32,f1_macro,0.150304,0.019608,NaN,shuffle_training_X_only
11,YFU,11,462,11200,11200,2240,0.203571,0.159460,0.147562,0.203571,0.607019,0.117612,0.134375,2.513554e-31,f1_macro,0.147562,0.019608,NaN,shuffle_training_X_only
12,YFU,12,504,11200,11200,2240,0.212946,0.166893,0.155707,0.212946,0.618907,0.117605,0.134375,1.455421e-37,f1_macro,0.155707,0.019608,NaN,shuffle_training_X_only
13,YFU,13,546,11200,11200,2240,0.206250,0.162733,0.152958,0.206250,0.601611,0.117605,0.134375,4.644072e-33,f1_macro,0.152958,0.019608,NaN,shuffle_training_X_only
14,YFU,14,588,11200,11200,2240,0.205357,0.161496,0.151385,0.205357,0.599526,0.117612,0.134375,1.791374e-32,f1_macro,0.151385,0.019608,NaN,shuffle_training_X_only
15,YFU,15,630,11200,11200,2240,0.209821,0.167520,0.160964,0.209821,0.607422,0.117612,0.134375,2.010057e-35,f1_macro,0.160964,0.019608,NaN,shuffle_training_X_only
16,YFU,16,672,11200,11200,2240,0.203125,0.158273,0.147803,0.203125,0.598360,0.117605,0.134375,4.771358e-31,f1_macro,0.147803,0.019608,NaN,shuffle_training_X_only
17,YFU,17,714,11200,11200,2240,0.206696,0.162698,0.153311,0.206696,0.607976,0.117605,0.134375,2.370250e-33,f1_macro,0.153311,0.019608,NaN,shuffle_training_X_only
18,YFU,18,756,11200,11200,2240,0.196875,0.153765,0.143557,0.196875,0.607895,0.117605,0.134375,3.364638e-27,f1_macro,0.143557,0.019608,NaN,shuffle_training_X_only
19,YFU,19,798,11200,11200,2240,0.223661,0.178795,0.170553,0.223661,0.600458,0.117612,0.134375,2.680862e-45,f1_macro,0.170553,0.019608,NaN,shuffle_training_X_only

aggregated YFU 2025-12-16 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFU/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-12-16/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFU,0,0,10215,9609,1922,0.185744,0.150798,0.142797,0.185744,0.580777,0.115199,0.132674,1.378840e-19,f1_macro,0.142797,0.019608,0.148261,shuffle_training_X_only
1,YFU,1,42,10215,9577,1916,0.190501,0.151925,0.139575,0.190501,0.597750,0.115096,0.132046,6.734040e-22,f1_macro,0.139575,0.019608,0.146988,shuffle_training_X_only
2,YFU,2,84,10215,9592,1919,0.194372,0.157973,0.146097,0.194372,0.578818,0.115150,0.132361,7.292066e-24,f1_macro,0.146097,0.019608,0.148562,shuffle_training_X_only
3,YFU,3,126,10215,9611,1923,0.183567,0.150247,0.141152,0.183567,0.585497,0.115219,0.133125,1.438098e-18,f1_macro,0.141152,0.019608,NaN,shuffle_training_X_only
4,YFU,4,168,10215,9607,1922,0.188866,0.153846,0.145833,0.188866,0.598077,0.115144,0.132674,4.016183e-21,f1_macro,0.145833,0.019608,NaN,shuffle_training_X_only
5,YFU,5,210,10215,9595,1919,0.176655,0.144374,0.137109,0.176655,0.580958,0.115090,0.131839,1.493966e-15,f1_macro,0.137109,0.019608,NaN,shuffle_training_X_only
6,YFU,6,252,10215,9621,1925,0.183377,0.149712,0.141854,0.183377,0.580770,0.115201,0.133506,1.653272e-18,f1_macro,0.141854,0.019608,NaN,shuffle_training_X_only
7,YFU,7,294,10215,9612,1923,0.195008,0.159044,0.150467,0.195008,0.592269,0.115218,0.133125,3.389513e-24,f1_macro,0.150467,0.019608,NaN,shuffle_training_X_only
8,YFU,8,336,10215,9618,1924,0.189189,0.153333,0.144708,0.189189,0.579485,0.115233,0.132536,3.013271e-21,f1_macro,0.144708,0.019608,NaN,shuffle_training_X_only
9,YFU,9,378,10215,9617,1924,0.181913,0.149341,0.142202,0.181913,0.582282,0.115175,0.132017,7.590859e-18,f1_macro,0.142202,0.019608,NaN,shuffle_training_X_only
10,YFU,10,420,10215,9633,1927,0.181111,0.146417,0.140317,0.181111,0.591289,0.115290,0.133887,1.905091e-17,f1_macro,0.140317,0.019608,NaN,shuffle_training_X_only
11,YFU,11,462,10215,9608,1922,0.190427,0.153371,0.143466,0.190427,0.589652,0.115197,0.132154,7.334334e-22,f1_macro,0.143466,0.019608,NaN,shuffle_training_X_only
12,YFU,12,504,10215,9609,1922,0.199272,0.160174,0.149082,0.199272,0.604860,0.115203,0.132674,1.811160e-26,f1_macro,0.149082,0.019608,NaN,shuffle_training_X_only
13,YFU,13,546,10215,9614,1923,0.196568,0.159452,0.151713,0.196568,0.591495,0.115218,0.132605,5.118883e-25,f1_macro,0.151713,0.019608,NaN,shuffle_training_X_only
14,YFU,14,588,10215,9605,1921,0.186361,0.148841,0.139740,0.186361,0.583545,0.115182,0.132223,7.012472e-20,f1_macro,0.139740,0.019608,NaN,shuffle_training_X_only
15,YFU,15,630,10215,9628,1926,0.186397,0.154459,0.149659,0.186397,0.586793,0.115271,0.132918,6.831842e-20,f1_macro,0.149659,0.019608,NaN,shuffle_training_X_only
16,YFU,16,672,10215,9606,1922,0.209157,0.170198,0.161680,0.209157,0.591239,0.115148,0.133715,3.826323e-32,f1_macro,0.161680,0.019608,NaN,shuffle_training_X_only
17,YFU,17,714,10215,9595,1919,0.176133,0.141761,0.134439,0.176133,0.584031,0.115151,0.132882,2.657902e-15,f1_macro,0.134439,0.019608,NaN,shuffle_training_X_only
18,YFU,18,756,10215,9622,1925,0.186494,0.151605,0.144102,0.186494,0.586406,0.115197,0.133506,5.675470e-20,f1_macro,0.144102,0.019608,NaN,shuffle_training_X_only
19,YFU,19,798,10215,9614,1923,0.197088,0.162193,0.155604,0.197088,0.600660,0.115161,0.132605,2.476436e-25,f1_macro,0.155604,0.019608,NaN,shuffle_training_X_only

aggregated YFU 2025-12-17 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFU/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-12-17/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFU,0,0,7278,7278,1456,0.230082,0.169125,0.163249,0.230082,0.591009,0.126532,0.143544,1.319842e-27,f1_macro,0.163249,0.019608,0.149186,shuffle_training_X_only
1,YFU,1,42,7278,7278,1456,0.232830,0.168194,0.156425,0.232830,0.593868,0.126532,0.143544,6.938602e-29,f1_macro,0.156425,0.019608,0.146891,shuffle_training_X_only
2,YFU,2,84,7278,7278,1456,0.208791,0.148734,0.134959,0.208791,0.593970,0.126532,0.143544,1.298252e-18,f1_macro,0.134959,0.019608,0.138661,shuffle_training_X_only
3,YFU,3,126,7278,7278,1456,0.208791,0.150517,0.141142,0.208791,0.589526,0.126532,0.143544,1.298252e-18,f1_macro,0.141142,0.019608,NaN,shuffle_training_X_only
4,YFU,4,168,7278,7278,1456,0.204670,0.147179,0.136713,0.204670,0.584277,0.126532,0.143544,4.569746e-17,f1_macro,0.136713,0.019608,NaN,shuffle_training_X_only
5,YFU,5,210,7278,7278,1456,0.216346,0.157264,0.148944,0.216346,0.568310,0.126532,0.143544,1.295039e-21,f1_macro,0.148944,0.019608,NaN,shuffle_training_X_only
6,YFU,6,252,7278,7278,1456,0.215659,0.153519,0.140775,0.215659,0.579300,0.126532,0.143544,2.476677e-21,f1_macro,0.140775,0.019608,NaN,shuffle_training_X_only
7,YFU,7,294,7278,7278,1456,0.227335,0.163325,0.154047,0.227335,0.586374,0.126532,0.143544,2.361001e-26,f1_macro,0.154047,0.019608,NaN,shuffle_training_X_only
8,YFU,8,336,7278,7278,1456,0.204670,0.147576,0.138938,0.204670,0.572558,0.126532,0.143544,4.569746e-17,f1_macro,0.138938,0.019608,NaN,shuffle_training_X_only
9,YFU,9,378,7278,7278,1456,0.204670,0.146459,0.135779,0.204670,0.588342,0.126532,0.143544,4.569746e-17,f1_macro,0.135779,0.019608,NaN,shuffle_training_X_only
10,YFU,10,420,7278,7278,1456,0.219780,0.159039,0.148119,0.219780,0.581305,0.126532,0.143544,4.768312e-23,f1_macro,0.148119,0.019608,NaN,shuffle_training_X_only
11,YFU,11,462,7278,7278,1456,0.219780,0.159505,0.149654,0.219780,0.580656,0.126532,0.143544,4.768312e-23,f1_macro,0.149654,0.019608,NaN,shuffle_training_X_only
12,YFU,12,504,7278,7278,1456,0.207418,0.151211,0.144291,0.207418,0.578865,0.126532,0.143544,4.325432e-18,f1_macro,0.144291,0.019608,NaN,shuffle_training_X_only
13,YFU,13,546,7278,7278,1456,0.222527,0.159113,0.147427,0.222527,0.589061,0.126532,0.143544,3.164219e-24,f1_macro,0.147427,0.019608,NaN,shuffle_training_X_only
14,YFU,14,588,7278,7278,1456,0.216346,0.157762,0.148234,0.216346,0.600091,0.126532,0.143544,1.295039e-21,f1_macro,0.148234,0.019608,NaN,shuffle_training_X_only
15,YFU,15,630,7278,7278,1456,0.225962,0.164194,0.154579,0.225962,0.588562,0.126532,0.143544,9.756930e-26,f1_macro,0.154579,0.019608,NaN,shuffle_training_X_only
16,YFU,16,672,7278,7278,1456,0.218407,0.155913,0.142843,0.218407,0.585548,0.126532,0.143544,1.807649e-22,f1_macro,0.142843,0.019608,NaN,shuffle_training_X_only
17,YFU,17,714,7278,7278,1456,0.195742,0.142225,0.136372,0.195742,0.591393,0.126532,0.143544,6.120751e-14,f1_macro,0.136372,0.019608,NaN,shuffle_training_X_only
18,YFU,18,756,7278,7278,1456,0.202610,0.147116,0.139247,0.202610,0.584944,0.126532,0.143544,2.563705e-16,f1_macro,0.139247,0.019608,NaN,shuffle_training_X_only
19,YFU,19,798,7278,7278,1456,0.228709,0.167812,0.159305,0.228709,0.603404,0.126532,0.143544,5.625443e-27,f1_macro,0.159305,0.019608,NaN,shuffle_training_X_only

aggregated YFU 2025-12-18 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFU/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2025-12-18/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFU,0,0,3425,3425,685,0.176642,0.136900,0.134222,0.176642,0.604584,0.122319,0.137226,2.377267e-05,f1_macro,0.134222,0.019608,0.152798,shuffle_training_X_only
1,YFU,1,42,3425,3425,685,0.188321,0.145881,0.144722,0.188321,0.591481,0.122319,0.137226,4.768944e-07,f1_macro,0.144722,0.019608,0.153712,shuffle_training_X_only
2,YFU,2,84,3425,3425,685,0.207299,0.158009,0.150733,0.207299,0.598400,0.122319,0.137226,2.400214e-10,f1_macro,0.150733,0.019608,0.154241,shuffle_training_X_only
3,YFU,3,126,3425,3425,685,0.202920,0.159546,0.157144,0.202920,0.590736,0.122319,0.137226,1.581410e-09,f1_macro,0.157144,0.019608,NaN,shuffle_training_X_only
4,YFU,4,168,3425,3425,685,0.192701,0.147039,0.140608,0.192701,0.616541,0.122319,0.137226,9.453637e-08,f1_macro,0.140608,0.019608,NaN,shuffle_training_X_only
5,YFU,5,210,3425,3425,685,0.204380,0.158103,0.153526,0.204380,0.609484,0.122319,0.137226,8.509317e-10,f1_macro,0.153526,0.019608,NaN,shuffle_training_X_only
6,YFU,6,252,3425,3425,685,0.208759,0.164911,0.160511,0.208759,0.595881,0.122319,0.137226,1.258313e-10,f1_macro,0.160511,0.019608,NaN,shuffle_training_X_only
7,YFU,7,294,3425,3425,685,0.204380,0.159830,0.156243,0.204380,0.617809,0.122319,0.137226,8.509317e-10,f1_macro,0.156243,0.019608,NaN,shuffle_training_X_only
8,YFU,8,336,3425,3425,685,0.185401,0.138831,0.131219,0.185401,0.602314,0.122319,0.137226,1.339962e-06,f1_macro,0.131219,0.019608,NaN,shuffle_training_X_only
9,YFU,9,378,3425,3425,685,0.186861,0.149975,0.149945,0.186861,0.607342,0.122319,0.137226,8.030772e-07,f1_macro,0.149945,0.019608,NaN,shuffle_training_X_only
10,YFU,10,420,3425,3425,685,0.208759,0.162608,0.159156,0.208759,0.590037,0.122319,0.137226,1.258313e-10,f1_macro,0.159156,0.019608,NaN,shuffle_training_X_only
11,YFU,11,462,3425,3425,685,0.185401,0.139695,0.132987,0.185401,0.588801,0.122319,0.137226,1.339962e-06,f1_macro,0.132987,0.019608,NaN,shuffle_training_X_only
12,YFU,12,504,3425,3425,685,0.217518,0.166494,0.157541,0.217518,0.595936,0.122319,0.137226,2.183302e-12,f1_macro,0.157541,0.019608,NaN,shuffle_training_X_only
13,YFU,13,546,3425,3425,685,0.194161,0.152991,0.148595,0.194161,0.601261,0.122319,0.137226,5.413093e-08,f1_macro,0.148595,0.019608,NaN,shuffle_training_X_only
14,YFU,14,588,3425,3425,685,0.195620,0.150431,0.145070,0.195620,0.610370,0.122319,0.137226,3.071726e-08,f1_macro,0.145070,0.019608,NaN,shuffle_training_X_only
15,YFU,15,630,3425,3425,685,0.195620,0.149629,0.143336,0.195620,0.597999,0.122319,0.137226,3.071726e-08,f1_macro,0.143336,0.019608,NaN,shuffle_training_X_only
16,YFU,16,672,3425,3425,685,0.191241,0.144306,0.135342,0.191241,0.603433,0.122319,0.137226,1.636157e-07,f1_macro,0.135342,0.019608,NaN,shuffle_training_X_only
17,YFU,17,714,3425,3425,685,0.208759,0.160258,0.154788,0.208759,0.623073,0.122319,0.137226,1.258313e-10,f1_macro,0.154788,0.019608,NaN,shuffle_training_X_only
18,YFU,18,756,3425,3425,685,0.185401,0.139960,0.133313,0.185401,0.603090,0.122319,0.137226,1.339962e-06,f1_macro,0.133313,0.019608,NaN,shuffle_training_X_only
19,YFU,19,798,3425,3425,685,0.175182,0.138633,0.137138,0.175182,0.586402,0.122319,0.137226,3.714507e-05,f1_macro,0.137138,0.019608,NaN,shuffle_training_X_only

aggregated YFV 2026-02-17 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFV/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2026-02-17/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFV,0,0,4092,4092,819,0.188034,0.146544,0.140719,0.188034,0.582475,0.118959,0.136752,7.596109e-09,f1_macro,0.140719,0.019608,0.150503,shuffle_training_X_only
1,YFV,1,42,4092,4092,819,0.197802,0.151069,0.140920,0.197802,0.565649,0.118959,0.136752,7.161350e-11,f1_macro,0.140920,0.019608,0.144855,shuffle_training_X_only
2,YFV,2,84,4092,4092,819,0.192918,0.145801,0.135258,0.192918,0.572105,0.118959,0.136752,7.839090e-10,f1_macro,0.135258,0.019608,0.148396,shuffle_training_X_only
3,YFV,3,126,4092,4092,819,0.183150,0.145740,0.142302,0.183150,0.574824,0.118959,0.136752,6.502810e-08,f1_macro,0.142302,0.019608,NaN,shuffle_training_X_only
4,YFV,4,168,4092,4092,819,0.190476,0.148739,0.140973,0.190476,0.573918,0.118959,0.136752,2.477995e-09,f1_macro,0.140973,0.019608,NaN,shuffle_training_X_only
5,YFV,5,210,4092,4092,819,0.195360,0.154995,0.150909,0.195360,0.580399,0.118959,0.136752,2.405442e-10,f1_macro,0.150909,0.019608,NaN,shuffle_training_X_only
6,YFV,6,252,4092,4092,819,0.222222,0.178336,0.173406,0.222222,0.588849,0.118959,0.136752,7.819053e-17,f1_macro,0.173406,0.019608,NaN,shuffle_training_X_only
7,YFV,7,294,4092,4092,819,0.203907,0.160948,0.156317,0.203907,0.586618,0.118959,0.136752,3.039062e-12,f1_macro,0.156317,0.019608,NaN,shuffle_training_X_only
8,YFV,8,336,4092,4092,819,0.179487,0.139044,0.132898,0.179487,0.563552,0.118959,0.136752,2.996624e-07,f1_macro,0.132898,0.019608,NaN,shuffle_training_X_only
9,YFV,9,378,4092,4092,819,0.177045,0.136871,0.130759,0.177045,0.594955,0.118959,0.136752,7.974491e-07,f1_macro,0.130759,0.019608,NaN,shuffle_training_X_only
10,YFV,10,420,4092,4092,819,0.206349,0.163188,0.157332,0.206349,0.596889,0.118959,0.136752,8.154615e-13,f1_macro,0.157332,0.019608,NaN,shuffle_training_X_only
11,YFV,11,462,4092,4092,819,0.191697,0.155441,0.154937,0.191697,0.592012,0.118959,0.136752,1.399086e-09,f1_macro,0.154937,0.019608,NaN,shuffle_training_X_only
12,YFV,12,504,4092,4092,819,0.179487,0.144714,0.142061,0.179487,0.562145,0.118959,0.136752,2.996624e-07,f1_macro,0.142061,0.019608,NaN,shuffle_training_X_only
13,YFV,13,546,4092,4092,819,0.188034,0.144893,0.138564,0.188034,0.590646,0.118959,0.136752,7.596109e-09,f1_macro,0.138564,0.019608,NaN,shuffle_training_X_only
14,YFV,14,588,4092,4092,819,0.188034,0.147922,0.141362,0.188034,0.599792,0.118959,0.136752,7.596109e-09,f1_macro,0.141362,0.019608,NaN,shuffle_training_X_only
15,YFV,15,630,4092,4092,819,0.212454,0.164224,0.153564,0.212454,0.584814,0.118959,0.136752,2.678214e-14,f1_macro,0.153564,0.019608,NaN,shuffle_training_X_only
16,YFV,16,672,4092,4092,819,0.178266,0.140302,0.135949,0.178266,0.592609,0.118959,0.136752,4.908009e-07,f1_macro,0.135949,0.019608,NaN,shuffle_training_X_only
17,YFV,17,714,4092,4092,819,0.210012,0.165263,0.159571,0.210012,0.594216,0.118959,0.136752,1.073183e-13,f1_macro,0.159571,0.019608,NaN,shuffle_training_X_only
18,YFV,18,756,4092,4092,819,0.172161,0.135980,0.131584,0.172161,0.577165,0.118959,0.136752,5.126891e-06,f1_macro,0.131584,0.019608,NaN,shuffle_training_X_only
19,YFV,19,798,4092,4092,819,0.196581,0.152653,0.145990,0.196581,0.580686,0.118959,0.136752,1.317436e-10,f1_macro,0.145990,0.019608,NaN,shuffle_training_X_only

aggregated YFV 2026-02-18 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFV/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2026-02-18/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFV,0,0,2860,2860,572,0.187063,0.144961,0.132776,0.187063,0.593522,0.11717,0.134615,8.087763e-07,f1_macro,0.132776,0.019608,0.144571,shuffle_training_X_only
1,YFV,1,42,2860,2860,572,0.166084,0.134241,0.129104,0.166084,0.569852,0.11717,0.134615,3.282484e-04,f1_macro,0.129104,0.019608,0.141671,shuffle_training_X_only
2,YFV,2,84,2860,2860,572,0.174825,0.138629,0.132530,0.174825,0.584564,0.11717,0.134615,3.281510e-05,f1_macro,0.132530,0.019608,0.126898,shuffle_training_X_only
3,YFV,3,126,2860,2860,572,0.178322,0.143606,0.136649,0.178322,0.566946,0.11717,0.134615,1.205122e-05,f1_macro,0.136649,0.019608,NaN,shuffle_training_X_only
4,YFV,4,168,2860,2860,572,0.190559,0.155191,0.149921,0.190559,0.584190,0.11717,0.134615,2.540237e-07,f1_macro,0.149921,0.019608,NaN,shuffle_training_X_only
5,YFV,5,210,2860,2860,572,0.162587,0.129060,0.123835,0.162587,0.563400,0.11717,0.134615,7.598228e-04,f1_macro,0.123835,0.019608,NaN,shuffle_training_X_only
6,YFV,6,252,2860,2860,572,0.153846,0.123310,0.120487,0.153846,0.567508,0.11717,0.134615,5.028310e-03,f1_macro,0.120487,0.019608,NaN,shuffle_training_X_only
7,YFV,7,294,2860,2860,572,0.150350,0.117191,0.110224,0.150350,0.554755,0.11717,0.134615,9.840931e-03,f1_macro,0.110224,0.098039,NaN,shuffle_training_X_only
8,YFV,8,336,2860,2860,572,0.166084,0.133603,0.130120,0.166084,0.591751,0.11717,0.134615,3.282484e-04,f1_macro,0.130120,0.019608,NaN,shuffle_training_X_only
9,YFV,9,378,2860,2860,572,0.173077,0.142791,0.138579,0.173077,0.588734,0.11717,0.134615,5.322924e-05,f1_macro,0.138579,0.019608,NaN,shuffle_training_X_only
10,YFV,10,420,2860,2860,572,0.169580,0.136891,0.133310,0.169580,0.565231,0.11717,0.134615,1.352945e-04,f1_macro,0.133310,0.019608,NaN,shuffle_training_X_only
11,YFV,11,462,2860,2860,572,0.180070,0.145085,0.141859,0.180070,0.573942,0.11717,0.134615,7.179908e-06,f1_macro,0.141859,0.019608,NaN,shuffle_training_X_only
12,YFV,12,504,2860,2860,572,0.166084,0.136835,0.135715,0.166084,0.567380,0.11717,0.134615,3.282484e-04,f1_macro,0.135715,0.019608,NaN,shuffle_training_X_only
13,YFV,13,546,2860,2860,572,0.202797,0.158944,0.150204,0.202797,0.594153,0.11717,0.134615,3.139672e-09,f1_macro,0.150204,0.019608,NaN,shuffle_training_X_only
14,YFV,14,588,2860,2860,572,0.157343,0.125491,0.121150,0.157343,0.582477,0.11717,0.134615,2.447798e-03,f1_macro,0.121150,0.039216,NaN,shuffle_training_X_only
15,YFV,15,630,2860,2860,572,0.194056,0.153866,0.145996,0.194056,0.615290,0.11717,0.134615,7.638319e-08,f1_macro,0.145996,0.019608,NaN,shuffle_training_X_only
16,YFV,16,672,2860,2860,572,0.166084,0.132623,0.125884,0.166084,0.601762,0.11717,0.134615,3.282484e-04,f1_macro,0.125884,0.019608,NaN,shuffle_training_X_only
17,YFV,17,714,2860,2860,572,0.204545,0.163201,0.155672,0.204545,0.588684,0.11717,0.134615,1.606596e-09,f1_macro,0.155672,0.019608,NaN,shuffle_training_X_only
18,YFV,18,756,2860,2860,572,0.148601,0.124822,0.124061,0.148601,0.554706,0.11717,0.134615,1.351811e-02,f1_macro,0.124061,0.039216,NaN,shuffle_training_X_only
19,YFV,19,798,2860,2860,572,0.190559,0.156180,0.151776,0.190559,0.600142,0.11717,0.134615,2.540237e-07,f1_macro,0.151776,0.019608,NaN,shuffle_training_X_only

aggregated YFV 2026-02-19 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFV/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2026-02-19/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFV,0,0,7284,5205,1041,0.198847,0.152796,0.152990,0.198847,0.569169,0.127943,0.155620,8.827948e-11,f1_macro,0.152990,0.019608,0.142922,shuffle_training_X_only
1,YFV,1,42,7284,5194,1039,0.216554,0.152781,0.144094,0.216554,0.592658,0.127937,0.155919,1.801120e-15,f1_macro,0.144094,0.019608,0.140041,shuffle_training_X_only
2,YFV,2,84,7284,5204,1041,0.196926,0.148968,0.147085,0.196926,0.581760,0.128079,0.157541,2.786125e-10,f1_macro,0.147085,0.019608,0.145257,shuffle_training_X_only
3,YFV,3,126,7284,5238,1048,0.202290,0.151249,0.149898,0.202290,0.605492,0.128161,0.157443,1.246806e-11,f1_macro,0.149898,0.019608,NaN,shuffle_training_X_only
4,YFV,4,168,7284,5229,1046,0.196941,0.143188,0.135343,0.196941,0.568043,0.128241,0.156788,2.792482e-10,f1_macro,0.135343,0.019608,NaN,shuffle_training_X_only
5,YFV,5,210,7284,5204,1041,0.194044,0.145505,0.141956,0.194044,0.586444,0.128044,0.158501,1.273484e-09,f1_macro,0.141956,0.019608,NaN,shuffle_training_X_only
6,YFV,6,252,7284,5186,1038,0.202312,0.150608,0.146291,0.202312,0.594579,0.128047,0.158960,1.415057e-11,f1_macro,0.146291,0.019608,NaN,shuffle_training_X_only
7,YFV,7,294,7284,5201,1041,0.211335,0.155372,0.151019,0.211335,0.581828,0.127943,0.155620,5.105309e-14,f1_macro,0.151019,0.019608,NaN,shuffle_training_X_only
8,YFV,8,336,7284,5207,1042,0.203455,0.152391,0.149798,0.203455,0.581363,0.128061,0.157390,6.721539e-12,f1_macro,0.149798,0.019608,NaN,shuffle_training_X_only
9,YFV,9,378,7284,5194,1039,0.201155,0.145787,0.141422,0.201155,0.576156,0.127902,0.154957,2.431745e-11,f1_macro,0.141422,0.019608,NaN,shuffle_training_X_only
10,YFV,10,420,7284,5222,1045,0.193301,0.137144,0.127984,0.193301,0.576836,0.128174,0.157895,1.900651e-09,f1_macro,0.127984,0.019608,NaN,shuffle_training_X_only
11,YFV,11,462,7284,5191,1039,0.195380,0.145719,0.142238,0.195380,0.573654,0.127956,0.155919,6.147321e-10,f1_macro,0.142238,0.019608,NaN,shuffle_training_X_only
12,YFV,12,504,7284,5213,1043,0.203260,0.153222,0.152082,0.203260,0.591837,0.128142,0.158198,7.805116e-12,f1_macro,0.152082,0.019608,NaN,shuffle_training_X_only
13,YFV,13,546,7284,5214,1043,0.204219,0.146629,0.138845,0.204219,0.578941,0.127993,0.156280,3.988579e-12,f1_macro,0.138845,0.019608,NaN,shuffle_training_X_only
14,YFV,14,588,7284,5210,1042,0.209213,0.155278,0.152502,0.209213,0.591110,0.127973,0.156430,1.934958e-13,f1_macro,0.152502,0.019608,NaN,shuffle_training_X_only
15,YFV,15,630,7284,5217,1044,0.199234,0.148278,0.145931,0.199234,0.589648,0.128057,0.156130,7.230576e-11,f1_macro,0.145931,0.019608,NaN,shuffle_training_X_only
16,YFV,16,672,7284,5225,1045,0.203828,0.150082,0.145627,0.203828,0.578673,0.128112,0.157895,5.228907e-12,f1_macro,0.145627,0.019608,NaN,shuffle_training_X_only
17,YFV,17,714,7284,5191,1039,0.193455,0.139265,0.132646,0.193455,0.586971,0.127913,0.156882,1.654780e-09,f1_macro,0.132646,0.019608,NaN,shuffle_training_X_only
18,YFV,18,756,7284,5208,1042,0.197697,0.148331,0.144510,0.197697,0.595246,0.128059,0.155470,1.769142e-10,f1_macro,0.144510,0.019608,NaN,shuffle_training_X_only
19,YFV,19,798,7284,5212,1043,0.211889,0.152860,0.145794,0.211889,0.589288,0.127921,0.154362,3.337602e-14,f1_macro,0.145794,0.019608,NaN,shuffle_training_X_only

aggregated YFV 2026-02-20 -> /mnt/labworlds/Hayden/Hayden_Lab/speech_247/vad_new/YFV/standard_decoding_analysis/scat_xgboost_sampled_norm_filtered_per_day/2026-02-20/scat_sampled_all_resamples.csv

,patient,resample_idx,seed,n_sampled_raw,n_sampled_final,n_test,acc,balanced_accuracy,f1_macro,f1_micro,auc_macro_ovr,baseline_proportional_acc,baseline_majority_acc,binomial_p_vs_proportional,perm_metric,observed_perm_metric,perm_pvalue,cv_best_score,perm_null
0,YFV,0,0,9234,7830,1566,0.236271,0.170019,0.155493,0.236271,0.630881,0.123723,0.150064,1.221263e-34,f1_macro,0.155493,0.019608,0.163232,shuffle_training_X_only
1,YFV,1,42,9234,7824,1565,0.222364,0.162874,0.155534,0.222364,0.644866,0.123604,0.149521,1.311618e-27,f1_macro,0.155534,0.019608,0.164978,shuffle_training_X_only
2,YFV,2,84,9234,7809,1562,0.227273,0.167967,0.159414,0.227273,0.619159,0.123491,0.150448,4.761547e-30,f1_macro,0.159414,0.019608,0.157512,shuffle_training_X_only
3,YFV,3,126,9234,7788,1558,0.208601,0.154564,0.147870,0.208601,0.627365,0.123370,0.148909,2.289500e-21,f1_macro,0.147870,0.019608,NaN,shuffle_training_X_only
4,YFV,4,168,9234,7789,1558,0.222080,0.162485,0.153212,0.222080,0.623442,0.123483,0.147625,1.970896e-27,f1_macro,0.153212,0.019608,NaN,shuffle_training_X_only
5,YFV,5,210,9234,7850,1570,0.214650,0.162623,0.158896,0.214650,0.622272,0.123861,0.150955,6.426299e-24,f1_macro,0.158896,0.019608,NaN,shuffle_training_X_only
6,YFV,6,252,9234,7798,1560,0.207051,0.154325,0.148137,0.207051,0.636376,0.123565,0.148077,1.250726e-20,f1_macro,0.148137,0.019608,NaN,shuffle_training_X_only
7,YFV,7,294,9234,7816,1564,0.210997,0.161787,0.157753,0.210997,0.627000,0.123540,0.148977,2.169185e-22,f1_macro,0.157753,0.019608,NaN,shuffle_training_X_only
8,YFV,8,336,9234,7792,1559,0.234766,0.174756,0.165791,0.234766,0.624739,0.123564,0.148172,8.330592e-34,f1_macro,0.165791,0.019608,NaN,shuffle_training_X_only
9,YFV,9,378,9234,7827,1566,0.211367,0.159576,0.155905,0.211367,0.618965,0.123608,0.150702,1.533986e-22,f1_macro,0.155905,0.019608,NaN,shuffle_training_X_only
10,YFV,10,420,9234,7841,1569,0.237094,0.184736,0.185008,0.237094,0.636239,0.123647,0.149140,3.356471e-35,f1_macro,0.185008,0.019608,NaN,shuffle_training_X_only
11,YFV,11,462,9234,7806,1562,0.245198,0.181198,0.172020,0.245198,0.624621,0.123460,0.148528,1.116883e-39,f1_macro,0.172020,0.019608,NaN,shuffle_training_X_only
12,YFV,12,504,9234,7805,1561,0.209481,0.156619,0.150541,0.209481,0.617007,0.123459,0.147982,9.796278e-22,f1_macro,0.150541,0.019608,NaN,shuffle_training_X_only
13,YFV,13,546,9234,7781,1557,0.224149,0.167338,0.158955,0.224149,0.632370,0.123328,0.146435,1.620972e-28,f1_macro,0.158955,0.019608,NaN,shuffle_training_X_only
14,YFV,14,588,9234,7793,1559,0.214881,0.165063,0.161528,0.214881,0.615411,0.123415,0.147530,3.999339e-24,f1_macro,0.161528,0.019608,NaN,shuffle_training_X_only
15,YFV,15,630,9234,7821,1565,0.223642,0.171453,0.168321,0.223642,0.625564,0.123687,0.148882,3.538536e-28,f1_macro,0.168321,0.019608,NaN,shuffle_training_X_only
16,YFV,16,672,9234,7844,1569,0.196941,0.149759,0.145961,0.196941,0.616794,0.123652,0.147228,1.262884e-16,f1_macro,0.145961,0.019608,NaN,shuffle_training_X_only
17,YFV,17,714,9234,7831,1567,0.211232,0.165025,0.163808,0.211232,0.615847,0.123590,0.148054,1.665316e-22,f1_macro,0.163808,0.019608,NaN,shuffle_training_X_only
18,YFV,18,756,9234,7813,1563,0.230326,0.179310,0.180157,0.230326,0.623843,0.123498,0.148433,1.294732e-31,f1_macro,0.180157,0.019608,NaN,shuffle_training_X_only
19,YFV,19,798,9234,7799,1560,0.236538,0.178991,0.173861,0.236538,0.622314,0.123701,0.149359,1.130083e-34,f1_macro,0.173861,0.019608,NaN,shuffle_training_X_only